Repository dbt-labs/dbt-core, pull requests merged in 2018-06, with the labels that each got.

#797 Allow for more complex version comparison (redux)
  dbt/version.py
  test/unit/test_version.py
Labels: code review

#807 Bump/psycopg2 2.7.5
  requirements.txt
  setup.py
Labels: dependencies

#780 fix __all__ setting for submodules (#777)
  dbt/adapters/bigquery/__init__.py
  dbt/adapters/default/__init__.py
  dbt/adapters/postgres/__init__.py
  dbt/adapters/redshift/__init__.py
  dbt/adapters/snowflake/__init__.py
  dbt/api/__init__.py
Labels: bug
