Repository dbt-labs/dbt-core, pull requests merged in 2021-12, with the labels that each got.

#4376 Make the stdout logger actually go to stdout
  core/dbt/events/functions.py
Labels: cla:yes

#4381 move event code up a level
  core/dbt/events/functions.py
Labels: cla:yes

#4380 Add windows OS error suppressing for temp dir cleanups
  test/integration/015_cli_invocation_tests/test_cli_invocation.py
Labels: cla:yes, test windows

#4366 Tiny touchups for deps, clean
  core/dbt/config/runtime.py
  core/dbt/task/clean.py
Labels: cla:yes

#4379 [#4354] Different output for console and file logs
  core/dbt/events/functions.py
  core/dbt/main.py
Labels: cla:yes

#4387 [Backport] #4293
  core/dbt/config/runtime.py
  core/dbt/task/clean.py
Labels: cla:yes

#4393 [Backport] Fix release process (#4385)
  .github/workflows/release.yml
Labels: cla:yes

#4394 allow log_format to be set in profile configs
  core/dbt/contracts/project.py
Labels: cla:yes

#4396 change json override strategy
  core/dbt/adapters/base/impl.py
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  test/unit/test_events.py
Labels: cla:yes, test all

#4397 [Backport] move event code up a level
  core/dbt/events/functions.py
Labels: cla:yes

#4398 [Backport] Add windows OS error supressing for temp dir cleanups
  test/integration/015_cli_invocation_tests/test_cli_invocation.py
Labels: cla:yes

#4399 [Backport] Different output for console and file logs
  core/dbt/events/functions.py
  core/dbt/main.py
Labels: cla:yes

#4400 [Backport] use rfc3339 format for log time stamps
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
Labels: cla:yes

#4406 loglines are not always created by events
  core/dbt/events/functions.py
Labels: cla:yes

#4402 update file name
  core/dbt/logger.py
Labels: cla:yes

#4388 A few final logging touch-ups
  core/dbt/deprecations.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  core/dbt/parser/schemas.py
  core/dbt/task/deps.py
  core/dbt/task/printer.py
  core/dbt/task/runnable.py
  core/dbt/task/serve.py
  core/dbt/ui.py
  test/integration/012_deprecation_tests/test_deprecations.py
  test/unit/test_events.py
Labels: cla:yes

#4405 Rollover + backup for `dbt.log`
  core/dbt/events/functions.py
Labels: cla:yes

#4401 [Backport] allow log_format to be set in profile configs
  core/dbt/contracts/project.py
Labels: cla:yes

#4403 [Backport] change json override strategy
  core/dbt/adapters/base/impl.py
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  test/unit/test_events.py
Labels: cla:yes

#4407 [backport] #4402
  core/dbt/logger.py
Labels: cla:yes

#4411 user configurable event buffer size
  core/dbt/events/functions.py
  core/dbt/flags.py
  test/unit/test_events.py
Labels: cla:yes

#4408 [Backport] #4388 + #4405
  core/dbt/deprecations.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  core/dbt/parser/schemas.py
  core/dbt/task/deps.py
  core/dbt/task/printer.py
  core/dbt/task/runnable.py
  core/dbt/task/serve.py
  core/dbt/ui.py
  test/integration/012_deprecation_tests/test_deprecations.py
  test/unit/test_events.py
Labels: cla:yes

#4395 Logging README
  core/dbt/events/README.md
Labels: cla:yes

#4412 [Backport] user configurable event buffer size
  core/dbt/events/functions.py
  core/dbt/flags.py
  test/unit/test_events.py
Labels: cla:yes

#4413 [Backport] Logging README
  core/dbt/events/README.md
Labels: cla:yes

#4410 use reference keys instead of relations
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/cache.py
  core/dbt/adapters/reference_keys.py
  core/dbt/adapters/sql/impl.py
  core/dbt/events/types.py
  core/dbt/task/deps.py
  test/unit/test_events.py
Labels: cla:yes

#4414 [Backport] use reference keys instead of relations
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/cache.py
  core/dbt/adapters/reference_keys.py
  core/dbt/adapters/sql/impl.py
  core/dbt/events/types.py
  core/dbt/task/deps.py
  test/unit/test_events.py
Labels: cla:yes

#4378 add node type codes to more events + more hook log data
  core/dbt/adapters/sql/connections.py
  core/dbt/events/types.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
Labels: cla:yes

#4415 [Backport] add node type codes to more events + more hook log data (#4378)
  core/dbt/adapters/sql/connections.py
  core/dbt/events/types.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
Labels: cla:yes

#4416 Add `--event-buffer-size` flag, recreate `EVENT_HISTORY` once configured
  core/dbt/events/functions.py
  core/dbt/main.py
Labels: cla:yes

#4417 Make `node_info.materialized` optional
  core/dbt/events/base_types.py
Labels: cla:yes

#4418 Info vs debug text formatting
  core/dbt/events/functions.py
Labels: cla:yes

#4419 [Backport] Add flag to main.py. Reinstantiate after flags (#4416)
  core/dbt/events/functions.py
  core/dbt/main.py
Labels: cla:yes

#4420 [Backport] Sources aren't materialized (#4417)
  core/dbt/events/base_types.py
Labels: cla:yes

#4421 [Backport] Info vs debug text formatting (#4418)
  core/dbt/events/functions.py
Labels: cla:yes

#4424 Stringify generic exceptions
  core/dbt/events/types.py
  core/dbt/task/base.py
  test/unit/test_events.py
Labels: cla:yes

#4425 [Backport] stringify generic exceptions (#4424)
  core/dbt/events/types.py
  core/dbt/task/base.py
  test/unit/test_events.py
Labels: cla:yes

#4327 add new interop tests for black-box json log schema testing
  .github/workflows/structured-logging-schema-check.yml
  test/integration/030_statement_test/test_statements.py
  test/interop/log_parsing/Cargo.lock
  test/interop/log_parsing/Cargo.toml
  test/interop/log_parsing/src/main.rs
Labels: cla:yes

#4427 relax version specifier for dbt-extractor
  docker/requirements/requirements.txt
Labels: cla:yes

#4428 [Backport] #4327
  .github/workflows/structured-logging-schema-check.yml
  test/integration/030_statement_test/test_statements.py
  test/interop/log_parsing/Cargo.lock
  test/interop/log_parsing/Cargo.toml
  test/interop/log_parsing/src/main.rs
Labels: cla:yes

#4389 Changelog entries for rc3 -> final
  CHANGELOG.md
Labels: cla:yes

#4429 [Backport] #4427
  docker/requirements/requirements.txt
Labels: cla:yes

#4430 [Backport] #4389 - update changelog
  CHANGELOG.md
Labels: cla:yes

#4432 [Backport] Bumping version to 1.0.0 (#4431)
  .bumpversion.cfg
  core/dbt/version.py
  core/scripts/create_adapter_plugins.py
  core/setup.py
  docker/requirements/requirements.txt
  plugins/postgres/dbt/adapters/postgres/__version__.py
  plugins/postgres/setup.py
  setup.py
Labels: cla:yes

#4434 point latest version check to dbt-core package
  core/dbt/version.py
Labels: cla:yes

#4435 [backport] point latest version check to dbt-core package (#4434)
  core/dbt/version.py
Labels: cla:yes

#4460 [Backport] 4442
  CHANGELOG.md
  core/dbt/include/global_project/docs/overview.md
Labels: cla:yes

#4356 updating contributing.md based on suggestions from updates to adapter…
  CONTRIBUTING.md
Labels: cla:yes

#4463 made change to test of str
  CHANGELOG.md
  core/dbt/adapters/sql/connections.py
Labels: cla:yes

#4478 [BACKPORT] made change to test of str (#4463)
  CHANGELOG.md
  core/dbt/adapters/sql/connections.py
Labels: cla:yes

#4482 updated DepsStartPackageInstall event to use package name
  CHANGELOG.md
  core/dbt/events/types.py
  core/dbt/task/deps.py
  test/unit/test_events.py
Labels: cla:yes

#4485 [BACKPORT] #4482
  CHANGELOG.md
  core/dbt/events/types.py
  core/dbt/task/deps.py
  test/unit/test_events.py
Labels: cla:yes

#4465 [#4464] Check specifically for generic node type for some partial parsing actions
  core/dbt/contracts/graph/parsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  test/integration/068_partial_parsing_tests/test-files/my_test.sql
  test/integration/068_partial_parsing_tests/test-files/test-macro.sql
  test/integration/068_partial_parsing_tests/test-files/test-macro2.sql
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
  test/integration/068_partial_parsing_tests/test_pp_docs.py
  test/integration/068_partial_parsing_tests/test_pp_metrics.py
  test/integration/068_partial_parsing_tests/test_pp_vars.py
Labels: cla:yes

#4494 [Backport] Various partial parsing fixes
  core/dbt/contracts/graph/parsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  test/integration/068_partial_parsing_tests/test-files/my_test.sql
  test/integration/068_partial_parsing_tests/test-files/test-macro.sql
  test/integration/068_partial_parsing_tests/test-files/test-macro2.sql
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
  test/integration/068_partial_parsing_tests/test_pp_docs.py
  test/integration/068_partial_parsing_tests/test_pp_metrics.py
  test/integration/068_partial_parsing_tests/test_pp_vars.py
Labels: cla:yes

#4484 compile new index file for docs
  CHANGELOG.md
  core/dbt/include/index.html
Labels: cla:yes

#4483 Simplify Log Destinations
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/test_types.py
  core/dbt/events/types.py
  test/unit/test_events.py
Labels: cla:yes

#4501 update log message to use adapter name
  CHANGELOG.md
  core/dbt/task/runnable.py
Labels: cla:yes

#4497 Improve checking of schema version for pre-1.0.0 manifests
  CHANGELOG.md
  core/dbt/contracts/state.py
  core/dbt/contracts/util.py
  test/integration/062_defer_state_test/previous_state/manifest.json
  test/integration/062_defer_state_test/test_modified_state.py
Labels: cla:yes

#4502 [BACKPORT] 4501
  CHANGELOG.md
  core/dbt/task/runnable.py
Labels: cla:yes

#4503 Backport #4470 improve error message for invalid schemas
  CHANGELOG.md
  core/dbt/contracts/state.py
  core/dbt/contracts/util.py
  test/integration/062_defer_state_test/previous_state/manifest.json
  test/integration/062_defer_state_test/test_modified_state.py
Labels: cla:yes

#4507 scrub message of secrets
  CHANGELOG.md
  core/dbt/clients/git.py
  core/dbt/exceptions.py
Labels: cla:yes

#4510 [BACKPORT] #4507
  CHANGELOG.md
  core/dbt/clients/git.py
  core/dbt/exceptions.py
Labels: cla:yes

#4512 Fix bool coercion to 0/1
  CHANGELOG.md
  core/dbt/clients/agate_helper.py
  test/unit/test_agate_helper.py
  test/unit/utils.py
Labels: cla:yes

#4524 [#4523] Fix error with env_var in hook
  CHANGELOG.md
  core/dbt/context/providers.py
  test/integration/014_hook_tests/test_run_hooks.py
Labels: cla:yes

#4526 [#4523] Fix error with env_var in hook
  CHANGELOG.md
  core/dbt/context/providers.py
  test/integration/014_hook_tests/test_run_hooks.py
Labels: cla:yes

#4518 [Backport] Bumping version to 1.0.1rc1 (#4517)
  .bumpversion.cfg
  CHANGELOG.md
  core/dbt/version.py
  core/scripts/create_adapter_plugins.py
  core/setup.py
  docker/requirements/requirements.txt
  plugins/postgres/dbt/adapters/postgres/__version__.py
  plugins/postgres/setup.py
  setup.py
Labels: cla:yes

#4487 New Dockerfile
  .bumpversion.cfg
  CHANGELOG.md
  Dockerfile.test
  docker-compose.yml
  docker/Dockerfile
  docker/README.md
  docker/requirements/requirements.txt
  docker/test.sh
Labels: cla:yes

#4308 Add Structured Logging ADR
  docs/arch/adr-002-structured-logging-arch.md
Labels: cla:yes

#4496 removed unused code in unit tests
  CHANGELOG.md
  test/unit/test_parse_manifest.py
Labels: cla:yes
