Repository dbt-labs/dbt-core, pull requests merged in 2021-11, with the labels that each got.

#4166 contracts call sites
  core/dbt/contracts/connection.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/results.py
  core/dbt/events/types.py
Labels: cla:yes

#4180 Dataclass compatibility
  core/dbt/events/types.py
Labels: cla:yes

#4169 config call sites
  core/dbt/config/profile.py
  core/dbt/config/runtime.py
  core/dbt/config/utils.py
  core/dbt/events/types.py
Labels: cla:yes

#4177 parser call sites
  core/dbt/events/types.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/macros.py
  core/dbt/parser/manifest.py
  core/dbt/parser/models.py
  core/dbt/parser/partial.py
Labels: cla:yes

#4143 Add extra graph edges for `build` only
  CHANGELOG.md
  core/dbt/compilation.py
  core/dbt/task/build.py
  test/integration/062_defer_state_test/test_run_results_state.py
Labels: cla:yes

#4160 Add test edges for improper subsets, too
  CHANGELOG.md
  core/dbt/compilation.py
  test/integration/069_build_test/models-simple-blocking/model_a.sql
  test/integration/069_build_test/models-simple-blocking/model_b.sql
  test/integration/069_build_test/models-simple-blocking/schema.yml
  test/integration/069_build_test/test_build.py
Labels: cla:yes

#4186 [Backport] #4155, #4143, #4160
  CHANGELOG.md
  core/dbt/compilation.py
  core/dbt/graph/graph.py
  core/dbt/task/build.py
  test/integration/069_build_test/models-simple-blocking/model_a.sql
  test/integration/069_build_test/models-simple-blocking/model_b.sql
  test/integration/069_build_test/models-simple-blocking/schema.yml
  test/integration/069_build_test/test_build.py
Labels: cla:yes

#4183 task call sites part 1
  core/dbt/events/types.py
  core/dbt/task/base.py
  core/dbt/task/clean.py
  core/dbt/task/compile.py
  core/dbt/task/debug.py
  core/dbt/task/deps.py
  core/dbt/task/freshness.py
  core/dbt/task/generate.py
  core/dbt/task/run.py
  core/dbt/task/run_operation.py
Labels: cla:yes

#4192 Change Bigquery google-api-core max version dependency
  CHANGELOG.md
  plugins/bigquery/setup.py
Labels: cla:yes

#4190 Show Exception should trigger a stack trace
  core/dbt/events/types.py
Labels: cla:yes

#4191 Bumping artifact versions for v1
  CHANGELOG.md
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/results.py
  test/integration/029_docs_generate_tests/test_docs_generate.py
  test/integration/042_sources_test/test_sources.py
  test/unit/test_manifest.py
Labels: cla:yes

#4197 Add get_where_subquery to test namespace
  CHANGELOG.md
  core/dbt/context/providers.py
  core/dbt/include/global_project/macros/etc/where_subquery.sql
  test/integration/008_schema_tests_test/test-context-where-subq-macros/custom_generic_test.sql
  test/integration/008_schema_tests_test/test-context-where-subq-models/model_a.sql
  test/integration/008_schema_tests_test/test-context-where-subq-models/schema.yml
  test/integration/008_schema_tests_test/test_schema_v2_tests.py
Labels: cla:yes

#4207 [Backport] #4206
  CHANGELOG.md
  core/dbt/context/providers.py
  core/dbt/include/global_project/macros/etc/where_subquery.sql
  test/integration/008_schema_tests_test/test-context-where-subq-macros/custom_generic_test.sql
  test/integration/008_schema_tests_test/test-context-where-subq-models/model_a.sql
  test/integration/008_schema_tests_test/test-context-where-subq-models/schema.yml
  test/integration/008_schema_tests_test/test_schema_v2_tests.py
Labels: cla:yes

#4203 scrub the secrets
  core/dbt/events/functions.py
Labels: cla:yes

#4199 deps call sites
  core/dbt/deps/base.py
  core/dbt/deps/git.py
  core/dbt/deps/local.py
  core/dbt/events/types.py
Labels: cla:yes

#4202 call sites in core/dbt (excluding main.py)
  core/dbt/compilation.py
  core/dbt/events/format.py
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/task/debug.py
  core/dbt/task/printer.py
  core/dbt/task/test.py
  core/dbt/tracking.py
  core/dbt/utils.py
Labels: cla:yes

#4124 Add error surfacing for git cloning errors
  CHANGELOG.md
  core/dbt/clients/git.py
Labels: cla:yes, ok to test

#4214 `incorporate_indirect_nodes` should pass if not needed
  CHANGELOG.md
  core/dbt/graph/selector.py
Labels: cla:yes

#4216 unit call sites call sites
  test/unit/test_graph.py
  test/unit/test_postgres_adapter.py
Labels: cla:yes

#4209 test/integration call sites
  core/dbt/events/test_types.py
  test/integration/base.py
Labels: cla:yes

#4217 missed call site contracts
  core/dbt/contracts/project.py
Labels: cla:yes

#4210 lazy logging in event module
  core/dbt/events/functions.py
Labels: cla:yes

#4219 Deal with callsites in Main
  core/dbt/events/types.py
  core/dbt/main.py
Labels: cla:yes

#4170 Use common columns for incremental schema changes
  CHANGELOG.md
  core/dbt/include/global_project/macros/materializations/incremental/incremental.sql
  core/dbt/include/global_project/macros/materializations/incremental/on_schema_change.sql
  test/integration/070_incremental_schema_tests/models/incremental_append_new_columns_remove_one.sql
  test/integration/070_incremental_schema_tests/models/incremental_append_new_columns_remove_one_target.sql
  test/integration/070_incremental_schema_tests/test_incremental_schema.py
Labels: cla:yes, ok to test

#4104 Parser no longer takes greedy. Accepts indirect selection, a bool.
  CHANGELOG.md
  core/dbt/flags.py
  core/dbt/graph/cli.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_spec.py
  core/dbt/main.py
  test/integration/066_test_selection_tests/test_selection_expansion.py
Labels: cla:yes

#4133 Raise error on `pip install dbt`
  .github/workflows/main.yml
  CHANGELOG.md
  core/README.md
  core/setup.py
  plugins/postgres/setup.py
  scripts/build-dist.sh
  setup.py
Labels: cla:yes

#4225 Fix/dbt deps retry none answer
  CHANGELOG.md
  core/dbt/clients/registry.py
  core/dbt/utils.py
  test/unit/test_core_dbt_utils.py
Labels: cla:yes, ok to test

#4218 Clears adapters before registering to fix dbt-server cacheing behavior
  CHANGELOG.md
  core/dbt/lib.py
Labels: cla:yes

#4162 [#3885] Partially parse when environment variables in schema files change
  CHANGELOG.md
  core/dbt/clients/jinja.py
  core/dbt/config/renderer.py
  core/dbt/context/base.py
  core/dbt/context/configured.py
  core/dbt/context/docs.py
  core/dbt/context/providers.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/compiled.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/exceptions.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/partial.py
  core/dbt/parser/schema_renderer.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  core/dbt/utils.py
  test/integration/008_schema_tests_test/test_schema_v2_tests.py
  test/integration/029_docs_generate_tests/test_docs_generate.py
  test/integration/039_config_test/test_configs_in_schema_files.py
  test/integration/060_persist_docs_tests/seeds/seed.csv
  test/integration/068_partial_parsing_tests/test-files/env_var-sources.yml
  test/integration/068_partial_parsing_tests/test-files/env_var_macro.sql
  test/integration/068_partial_parsing_tests/test-files/env_var_macros.yml
  test/integration/068_partial_parsing_tests/test-files/env_var_model_one.sql
  test/integration/068_partial_parsing_tests/test-files/env_var_model_test.yml
  test/integration/068_partial_parsing_tests/test-files/env_var_schema.yml
  test/integration/068_partial_parsing_tests/test-files/env_var_schema2.yml
  test/integration/068_partial_parsing_tests/test-files/env_var_schema3.yml
  test/integration/068_partial_parsing_tests/test-files/model_color.sql
  test/integration/068_partial_parsing_tests/test-files/test_color.sql
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
  test/integration/068_partial_parsing_tests/test_pp_vars.py
  test/unit/test_utils.py
  test/unit/test_yaml_renderer.py
Labels: cla:yes

#4212 [#3885] Skip partial parsing if project env vars change
  CHANGELOG.md
  core/dbt/config/profile.py
  core/dbt/config/project.py
  core/dbt/config/renderer.py
  core/dbt/config/runtime.py
  core/dbt/context/base.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/deps/resolver.py
  core/dbt/parser/manifest.py
  core/dbt/task/base.py
  core/dbt/task/debug.py
  core/dbt/task/deps.py
  test/integration/068_partial_parsing_tests/test_pp_vars.py
  test/unit/test_config.py
  test/unit/test_graph.py
  test/unit/utils.py
Labels: cla:yes

#4237 Raise parsing error instead of compilation when extracting test args
  core/dbt/exceptions.py
  core/dbt/parser/generic_test_builders.py
  test/integration/042_sources_test/test_sources.py
Labels: cla:yes

#4236 Issue message instead of exception when patch does not have a matching node
  core/dbt/parser/schemas.py
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
Labels: cla:yes

#4239 fancy print timestamp removal
  core/dbt/events/format.py
Labels: cla:yes

#4235 [#4071] Add metrics feature
  CHANGELOG.md
  core/dbt/compilation.py
  core/dbt/context/providers.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/compiled.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/graph/cli.py
  core/dbt/graph/queue.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/node_types.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  core/dbt/task/list.py
  test/integration/029_docs_generate_tests/test_docs_generate.py
  test/integration/068_partial_parsing_tests/test-files/my_metric.yml
  test/integration/068_partial_parsing_tests/test-files/people.sql
  test/integration/068_partial_parsing_tests/test-files/people_metrics.yml
  test/integration/068_partial_parsing_tests/test-files/people_metrics2.yml
  test/integration/068_partial_parsing_tests/test_pp_metrics.py
  test/unit/test_compiler.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
Labels: cla:yes

#4223 Rm py36 support
  .github/scripts/integration-test-matrix.js
  .github/workflows/main.yml
  CHANGELOG.md
  core/setup.py
  plugins/postgres/setup.py
  setup.py
  tox.ini
Labels: cla:yes

#4189 Struct log for adapter call sites
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/cache.py
  core/dbt/adapters/factory.py
  core/dbt/adapters/sql/connections.py
  core/dbt/adapters/sql/impl.py
  core/dbt/events/stubs.py
  core/dbt/events/types.py
  test/integration/051_query_comments_test/test_query_comments.py
Labels: cla:yes

#4240 Wrap get_batch_size() in return()
  core/dbt/include/global_project/macros/materializations/seeds/helpers.sql
Labels: cla:yes

#4231 std logger for structured logging
  core/dbt/events/README.md
  core/dbt/events/__init__.py
  core/dbt/events/adapter_endpoint.py
  core/dbt/events/functions.py
  core/dbt/events/test_types.py
  core/dbt/events/types.py
  core/dbt/logger.py
  core/dbt/main.py
Labels: cla:yes

#4241 Update docs
  CHANGELOG.md
  core/dbt/include/index.html
Labels: cla:yes

#4244 Improve error message raised by `pip install dbt`
  setup.py
Labels: cla:yes

#4250 test_postgres_profile_env_vars: change user env var instead of pass
  test/integration/068_partial_parsing_tests/test_pp_vars.py
Labels: cla:yes, test postgres, test windows, test macos

#4257 configure event logger for integration tests
  core/dbt/events/functions.py
  test/integration/001_simple_copy_test/test_simple_copy.py
  test/integration/051_query_comments_test/test_query_comments.py
  test/integration/base.py
Labels: cla:yes

#4255 Env var shim to enable legacy logger
  core/dbt/events/functions.py
  core/dbt/flags.py
  core/dbt/logger.py
Labels: cla:yes

#4249 Dbt init with provided project name
  CHANGELOG.md
  core/dbt/main.py
  core/dbt/task/init.py
  test/integration/040_init_test/test_init.py
Labels: cla:yes, ok to test

#4263 Update dbt-postgres readme
  plugins/postgres/README.md
Labels: cla:yes

#4275 Remove duplicate logging during integration tests
  core/dbt/events/functions.py
Labels: cla:yes

#4270 Feature/3997 profiles test selection flag
  CHANGELOG.md
  core/dbt/contracts/project.py
  core/dbt/flags.py
  core/dbt/graph/cli.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_spec.py
  core/dbt/main.py
  test/unit/test_flags.py
Labels: cla:yes

#4285 Avoid errors when missing column in yaml doc
  CHANGELOG.md
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  test/integration/060_persist_docs_tests/models-column-missing/missing_column.sql
  test/integration/060_persist_docs_tests/models-column-missing/schema.yaml
  test/integration/060_persist_docs_tests/test_persist_docs.py
Labels: cla:yes, ok to test

#4266 Minor Cleanup of Structured Logging Module
  core/dbt/events/adapter_endpoint.py
  core/dbt/events/base_types.py
  core/dbt/events/format.py
  core/dbt/events/functions.py
  core/dbt/events/history.py
  core/dbt/events/stubs.py
  core/dbt/events/types.py
  test/unit/test_events.py
Labels: cla:yes

#4296 Alow snapshot defer
  CHANGELOG.md
  core/dbt/main.py
  core/dbt/task/snapshot.py
  test/integration/062_defer_state_test/test_defer_state.py
Labels: cla:yes, ok to test

#4291 Clean up project config rename deprecation warnings
  CHANGELOG.md
  core/dbt/config/project.py
  core/dbt/deprecations.py
  core/dbt/events/functions.py
  core/dbt/ui.py
  test/integration/012_deprecation_tests/test_deprecations.py
Labels: cla:yes

#4302 Fix: default log formatting
  core/dbt/events/functions.py
Labels: cla:yes

#4297 [#4272] Move validator keyword argument in jinja 'config.get' to after default
  CHANGELOG.md
  core/dbt/context/providers.py
  test/integration/039_config_test/models-get/any_model.sql
  test/integration/039_config_test/test_configs.py
Labels: cla:yes

#4287 [#4252] Serialization error when missing quotes in metrics model ref() call
  CHANGELOG.md
  core/dbt/context/providers.py
  test/integration/075_metrics_tests/invalid-models/people.sql
  test/integration/075_metrics_tests/invalid-models/people_metrics.yml
  test/integration/075_metrics_tests/models/people.sql
  test/integration/075_metrics_tests/models/people_metrics.yml
  test/integration/075_metrics_tests/test_metrics.py
Labels: cla:yes

#4303 adjust level length for text only
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
Labels: cla:yes

#4295 Get prerelease packages when specifically requested
  CHANGELOG.md
  core/dbt/deps/registry.py
  test/unit/test_deps.py
Labels: cla:yes

#4292 Fix metrics count in compile stats
  CHANGELOG.md
  core/dbt/compilation.py
Labels: cla:yes

#4299 [#4298] Fix 'created_at' in ParsedMetric to allow recalculating metrics depends_on refs
  CHANGELOG.md
  core/dbt/contracts/graph/parsed.py
  test/integration/068_partial_parsing_tests/test_pp_metrics.py
Labels: cla:yes

#4305 Fix adapter failures due to string formatting issues
  core/dbt/events/types.py
  test/unit/test_events.py
Labels: cla:yes

#4200 Add supported dbt tasks
  CHANGELOG.md
  core/dbt/lib.py
Labels: cla:yes

#4307 Fix flags import
  core/dbt/lib.py
Labels: cla:yes

#4311 SecretContext for secret env vars, profiles + packages only
  CHANGELOG.md
  core/dbt/config/renderer.py
  core/dbt/context/base.py
  core/dbt/context/configured.py
  core/dbt/context/providers.py
  core/dbt/context/secret.py
  core/dbt/exceptions.py
  test/integration/013_context_var_tests/models-with-secret-bad/context.sql
  test/integration/013_context_var_tests/models/context.sql
  test/integration/013_context_var_tests/test_context_vars.py
Labels: cla:yes

#4289 version logging
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
Labels: cla:yes

#4301 structured logging: add data attributes to json log output
  CHANGELOG.md
  core/dbt/events/functions.py
Labels: cla:yes

#4319 Add codes to all log events (re-work of PR #4268)
  CHANGELOG.md
  core/dbt/clients/system.py
  core/dbt/events/base_types.py
  core/dbt/events/test_types.py
  core/dbt/events/types.py
Labels: cla:yes

#4328 [#4254] Change some CompilationExceptions to ParsingExceptions in the parser
  CHANGELOG.md
  core/dbt/parser/base.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/macros.py
  core/dbt/parser/read_files.py
  core/dbt/parser/search.py
  core/dbt/parser/snapshots.py
  test/integration/004_simple_snapshot_test/test_simple_snapshot.py
  test/integration/008_schema_tests_test/test_schema_v2_tests.py
Labels: cla:yes

#4322 [#4253] Support partial parsing of env_vars in metrics definitions
  CHANGELOG.md
  core/dbt/parser/partial.py
  test/integration/068_partial_parsing_tests/test-files/env_var_metrics.yml
  test/integration/068_partial_parsing_tests/test_pp_vars.py
Labels: cla:yes

#4332 Fix static parser tracking logic
  CHANGELOG.md
  core/dbt/parser/models.py
Labels: cla:yes

#4340 [#4337] Always create an invocation_id, even when not tracking
  core/dbt/context/base.py
  core/dbt/contracts/util.py
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/parser/manifest.py
  core/dbt/task/run.py
  core/dbt/tracking.py
  test/unit/test_manifest.py
  test/unit/test_tracking.py
Labels: cla:yes

#4338 Mc knight 42/test event codes
  core/dbt/events/types.py
  test/unit/test_events.py
Labels: cla:yes

#4331 adds additional augmented assignment statements (#4315)
  CHANGELOG.md
  core/dbt/dataclass_schema.py
  core/dbt/graph/selector_spec.py
  core/dbt/parser/manifest.py
  test/integration/047_dbt_ls_test/test_ls.py
  test/unit/test_macro_calls.py
Labels: cla:yes

#4076 Adjust logic when finding approx matches for model or test matching
  CHANGELOG.md
  core/dbt/adapters/base/relation.py
Labels: cla:yes, ok to test

#4349 fix typo in UnparsedSourceDefinition.__post_serialize_
  CHANGELOG.md
  core/dbt/contracts/graph/unparsed.py
Labels: cla:yes, ok to test

#4345 Use `cls` in classmethod
  core/dbt/parser/manifest.py
Labels: cla:yes

#4351 Provide function to set the invocation_id
  core/dbt/events/functions.py
Labels: cla:yes

#4288 Adding release workflow
  .github/workflows/release.yml
Labels: cla:yes

#4341 Logging: restore previous (small) behaviors
  CHANGELOG.md
  core/dbt/events/functions.py
  core/dbt/events/types.py
  core/dbt/main.py
  core/dbt/task/base.py
  core/dbt/task/list.py
Labels: cla:yes

#4353 add thread_name to structured logging
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
Labels: cla:yes

#4355 Serialize exception for structured json log
  core/dbt/events/types.py
  core/dbt/task/runnable.py
Labels: cla:yes, test all

#4359 set invocation id when generating psuedo config
  core/dbt/lib.py
Labels: cla:yes

#4326 make json serialization overridable for events
  core/dbt/adapters/sql/connections.py
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/stubs.py
  core/dbt/events/types.py
  core/dbt/main.py
  core/dbt/task/runnable.py
  core/dbt/tracking.py
  test/unit/test_events.py
Labels: cla:yes, test all

#4358 Event buffer for structlog
  core/dbt/events/functions.py
  core/dbt/events/history.py
  core/dbt/events/test_types.py
  core/dbt/events/types.py
  test/unit/test_events.py
Labels: cla:yes

#4360 Events with graph_func include actual output of graph_func
  core/dbt/events/types.py
Labels: cla:yes

#4336 add node_info to relevant logs
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/results.py
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/stubs.py
  core/dbt/events/types.py
  core/dbt/task/base.py
  core/dbt/task/freshness.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  core/dbt/task/snapshot.py
  core/dbt/task/test.py
  test/unit/test_events.py
Labels: cla:yes, test all

#4361 better dataclass field handling
  core/dbt/adapters/cache.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
Labels: cla:yes, test all

#4369 only log events in cache.py when --log-cache-events is set
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  core/dbt/flags.py
Labels: cla:yes, test all

#4371 [backport] only log events in cache.py when --log-cache-events is set
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  core/dbt/flags.py
Labels: cla:yes

#4368 Make the stdout logger actually go to stdout
  core/dbt/events/functions.py
Labels: cla:yes
