Repository dbt-labs/dbt-core, pull requests merged in 2022-05, with the labels that each got.

#5149 remove reference to unused `ok to test` label
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#5203 Adding Skip Changelog label to Version Bump action
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#5194 update label check for dependabot action
  .github/workflows/dependency-changelog.yml
Labels: cla:yes, Skip Changelog

#5199 Convert 013_context_vars_tests to context_methods. Move existing cli_vars into context_methods
  core/dbt/main.py
  test/integration/013_context_var_tests/bad-generate-macros/generate_names.sql
  test/integration/013_context_var_tests/dependency-models/inside/model.sql
  test/integration/013_context_var_tests/dependency-seeds/root_model_expected.csv
  test/integration/013_context_var_tests/emit-warning-models/warnings.sql
  test/integration/013_context_var_tests/first_dependency/dbt_project.yml
  test/integration/013_context_var_tests/first_dependency/models/nested/first_dep_model.sql
  test/integration/013_context_var_tests/first_dependency/seeds/first_dep_expected.csv
  test/integration/013_context_var_tests/models-with-secret-bad/context.sql
  test/integration/013_context_var_tests/models/context.sql
  test/integration/013_context_var_tests/test_context_members.py
  test/integration/013_context_var_tests/test_context_vars.py
  test/integration/013_context_var_tests/tests/from_yaml.sql
  test/integration/013_context_var_tests/tests/to_yaml.sql
  test/integration/013_context_var_tests/trivial-models/model.sql
  tests/functional/context_methods/first_dependency.py
  tests/functional/context_methods/test_cli_var_override.py
  tests/functional/context_methods/test_cli_vars.py
  tests/functional/context_methods/test_env_vars.py
  tests/functional/context_methods/test_secret_env_vars.py
  tests/functional/context_methods/test_var_dependency.py
  tests/functional/context_methods/test_var_in_generate_name.py
  tests/functional/context_methods/test_yaml_functions.py
  tests/functional/invalid_model_tests/test_model_warning.py
Labels: cla:yes, Skip Changelog

#5207 seed: Add new macro get_csv_sql
  .changes/unreleased/Features-20220503-142934.yaml
  core/dbt/include/global_project/macros/materializations/seeds/helpers.sql
  core/dbt/include/global_project/macros/materializations/seeds/seed.sql
Labels: cla:yes

#5184 Allow the target name to be set in profile_template.yml
  .changes/unreleased/Features-20220428-065644.yaml
  CONTRIBUTING.md
  core/dbt/task/init.py
  plugins/postgres/setup.py
  test/integration/040_init_tests/test_init.py
Labels: cla:yes, Team:Execution

#5198 propseal for modification to drop_test_schema
  .changes/unreleased/Fixes-20220429-160742.yaml
  core/dbt/adapters/sql/impl.py
Labels: cla:yes

#5212 Convert materialization tests to new test framework
  test/integration/017_runtime_materialization_tests/create_incremental__dbt_tmp.sql
  test/integration/017_runtime_materialization_tests/create_view__dbt_backup.sql
  test/integration/017_runtime_materialization_tests/create_view__dbt_tmp.sql
  test/integration/017_runtime_materialization_tests/invalidate_incremental.sql
  test/integration/017_runtime_materialization_tests/models/incremental.sql
  test/integration/017_runtime_materialization_tests/models/materialized.sql
  test/integration/017_runtime_materialization_tests/models/view.sql
  test/integration/017_runtime_materialization_tests/seeds/seed.csv
  test/integration/017_runtime_materialization_tests/test_runtime_materialization.py
  test/integration/017_runtime_materialization_tests/update.sql
  test/integration/053_custom_materialization_tests/models/model.sql
  test/integration/053_custom_materialization_tests/override-view-adapter-dep/dbt_project.yml
  test/integration/053_custom_materialization_tests/override-view-adapter-dep/macros/override_view.sql
  test/integration/053_custom_materialization_tests/override-view-adapter-macros/override_view.sql
  test/integration/053_custom_materialization_tests/override-view-adapter-pass-dep/dbt_project.yml
  test/integration/053_custom_materialization_tests/override-view-adapter-pass-dep/macros/override_view.sql
  test/integration/053_custom_materialization_tests/override-view-default-dep/dbt_project.yml
  test/integration/053_custom_materialization_tests/override-view-default-dep/macros/default_view.sql
  test/integration/053_custom_materialization_tests/override-view-return-no-relation/dbt_project.yml
  test/integration/053_custom_materialization_tests/override-view-return-no-relation/macros/override_view.sql
  test/integration/053_custom_materialization_tests/test_custom_materialization.py
  tests/functional/materializations/conftest.py
  tests/functional/materializations/test_custom_materialization.py
  tests/functional/materializations/test_runtime_materialization.py
Labels: cla:yes, Skip Changelog

#5216 Revert inaccurate mypy change
  core/dbt/version.py
  test/integration/040_init_tests/test_init.py
Labels: cla:yes, Skip Changelog

#5111 [Backport 1.1.latest] Flexibilize MarkupSafe pinned version (#5039)
  .changes/unreleased/Fixes-20220413-151735.yaml
  core/setup.py
Labels: cla:yes

#5218 Bumping hologram version
  .changes/unreleased/Dependencies-20220506-160907.yaml
  core/setup.py
Labels: dependencies, cla:yes

#5223 Fix: column comparison logic for check-strategy snapshots
  .changes/unreleased/Fixes-20220509-130021.yaml
  core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql
  tests/functional/simple_snapshot/test_changing_check_cols_snapshot.py
Labels: cla:yes

#5232 Fix snapshot_check_all_get_existing_columns: use adapter.get_columns_in_relation
  .changes/unreleased/Fixes-20220511-123238.yaml
  core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql
Labels: cla:yes, Team:Adapters

#5107 Feature: Add set/zip function to contexts
  .changes/unreleased/Features-20220423-231756.yaml
  core/dbt/context/base.py
  test/unit/test_context.py
  tests/functional/context_methods/test_builtin_functions.py
Labels: cla:yes, Team:Language

#5241 Add support for File Selectors and add file selectors to the default method selector list
  .changes/unreleased/Features-20220512-215748.yaml
  core/dbt/graph/selector_methods.py
  core/dbt/graph/selector_spec.py
  test/unit/test_graph_selector_methods.py
Labels: cla:yes, Team:Execution

#5224 Fix macro modified from previous state with pkg
  .changes/unreleased/Fixes-20220509-131312.yaml
  core/dbt/graph/selector_methods.py
  test/unit/test_graph_selector_methods.py
Labels: cla:yes

#5246 Add "dbt: A Core Story" to `docs/roadmap`
  docs/roadmap/2022-05-dbt-a-core-story.md
Labels: cla:yes, Skip Changelog

#5272 Tweak test to avoid set ordering problem
  .changes/unreleased/Under the Hood-20220518-145522.yaml
  tests/functional/context_methods/test_builtin_functions.py
Labels: cla:yes

#4998 Creating ADR for versioning and branching strategy
  docs/arch/adr-003-versioning-branching-strategy.md
  docs/arch/images/ReleasingBranchStrategy.png
Labels: cla:yes, Skip Changelog

#4921 Truncate relation names when appending a suffix
  .changes/unreleased/Fixes-20220322-173753.yaml
  core/dbt/include/global_project/macros/adapters/relation.sql
  core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql
  core/dbt/include/global_project/macros/materializations/models/table/table.sql
  core/dbt/include/global_project/macros/materializations/models/view/view.sql
  core/dbt/include/global_project/macros/materializations/snapshots/helpers.sql
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  tests/functional/materializations/test_runtime_materialization.py
Labels: cla:yes, Team:Adapters

#5270 CT-159 Remove docs file from manifest when deleting doc node
  .changes/unreleased/Fixes-20220518-134610.yaml
  core/dbt/parser/partial.py
  test/integration/068_partial_parsing_tests/test-files/my_macro-docs.sql
  test/integration/068_partial_parsing_tests/test-files/schema-docs.yml
  test/integration/068_partial_parsing_tests/test-files/schema-docs2.yml
  test/integration/068_partial_parsing_tests/test_pp_docs.py
  tests/functional/partial_parsing/test_pp_docs.py
Labels: cla:yes, backport 1.1.latest

#5269 Switch the Makefile to use the default installed Python version instead of py38 for local testing
  .changes/unreleased/Under the Hood-20220518-095144.yaml
  Makefile
Labels: cla:yes

#5230 Ct-581 grants as configs
  .changes/unreleased/Features-20220510-204949.yaml
  Makefile
  core/dbt/context/context_config.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/parser/base.py
  core/dbt/tests/fixtures/project.py
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_manifest.py
  test/unit/test_model_config.py
  test/unit/test_parser.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_grant_configs.py
  tests/functional/list/test_list.py
Labels: cla:yes

#5280 [1.0.latest] Lowering networkx dependency
  .changes/unreleased/Dependencies-20220520-120920.yaml
  core/setup.py
Labels: dependencies, cla:yes, test all

#5306 Add notes on invoking Python methods in adapter macros
  core/dbt/adapters/base/impl.py
Labels: cla:yes, Skip Changelog
