Repository dbt-labs/dbt-core, pull requests merged in 2022-10, with the labels that each got.

#5961 Remove 015_cli_invocation_tests directory
  test/integration/015_cli_invocation_tests/local_dependency/dbt_project.yml
  test/integration/015_cli_invocation_tests/local_dependency/macros/my_test_macro.sql
  test/integration/015_cli_invocation_tests/models/subdir1/subdir2/model.sql
  test/integration/015_cli_invocation_tests/models/subdir1/subdir2/schema.yml
  test/integration/015_cli_invocation_tests/seed.sql
  test/integration/015_cli_invocation_tests/seed_custom.sql
  test/integration/015_cli_invocation_tests/test_cli_invocation.py
Labels: cla:yes, Skip Changelog

#5993 [Backport 1.2.latest] Update Version Bump to include Homebrew in PATH (#5963)
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#6004 convert 025 to new framework, add metrics dupe test
  core/dbt/tests/fixtures/project.py
  test/integration/025_duplicate_model_tests/local_dependency/dbt_project.yml
  test/integration/025_duplicate_model_tests/local_dependency/models/table_model.sql
  test/integration/025_duplicate_model_tests/macros-bad-same/macros.sql
  test/integration/025_duplicate_model_tests/macros-bad-separate/one.sql
  test/integration/025_duplicate_model_tests/macros-bad-separate/two.sql
  test/integration/025_duplicate_model_tests/models-1/model-enabled-1/model.sql
  test/integration/025_duplicate_model_tests/models-1/model-enabled-2/model.sql
  test/integration/025_duplicate_model_tests/models-2/model-disabled/model.sql
  test/integration/025_duplicate_model_tests/models-2/model-enabled/model.sql
  test/integration/025_duplicate_model_tests/models-3/table_model.sql
  test/integration/025_duplicate_model_tests/models-4/table_model.sql
  test/integration/025_duplicate_model_tests/models-5/subdir1/model_alt.sql
  test/integration/025_duplicate_model_tests/models-5/subdir2/model_alt.sql
  test/integration/025_duplicate_model_tests/models-5/subdir3/model_alt.sql
  test/integration/025_duplicate_model_tests/models-exposure-dupes/schema.yml
  test/integration/025_duplicate_model_tests/models-naming-dupes/schema.yml
  test/integration/025_duplicate_model_tests/models-source-dupes/schema.yml
  test/integration/025_duplicate_model_tests/seed.sql
  test/integration/025_duplicate_model_tests/test_duplicate_exposure.py
  test/integration/025_duplicate_model_tests/test_duplicate_macro.py
  test/integration/025_duplicate_model_tests/test_duplicate_model.py
  test/integration/025_duplicate_model_tests/test_duplicate_resource.py
  test/integration/025_duplicate_model_tests/test_duplicate_source.py
  tests/functional/duplicates/test_duplicate_exposure.py
  tests/functional/duplicates/test_duplicate_macro.py
  tests/functional/duplicates/test_duplicate_metric.py
  tests/functional/duplicates/test_duplicate_model.py
  tests/functional/duplicates/test_duplicate_resource.py
  tests/functional/duplicates/test_duplicate_source.py
Labels: cla:yes, Skip Changelog

#5975 CT-1150: Include flat_graph in manifest.deepcopy(), tests
  .changes/unreleased/Under the Hood-20220929-134406.yaml
  core/dbt/contracts/graph/manifest.py
  test/unit/test_manifest.py
Labels: cla:yes

#6006 Convert 019_analysis_tests
  core/dbt/tests/fixtures/project.py
  test/integration/019_analysis_tests/analyses/my_analysis.sql
  test/integration/019_analysis_tests/analyses/raw_stuff.sql
  test/integration/019_analysis_tests/analyses/schema.yml
  test/integration/019_analysis_tests/models/.gitkeep
  test/integration/019_analysis_tests/models/my_model.sql
  test/integration/019_analysis_tests/test_analyses.py
  tests/functional/analysis/test_analyses.py
  tests/functional/duplicates/test_duplicate_analysis.py
Labels: cla:yes, Skip Changelog

#5684 Andy/fix init comment
  .changes/unreleased/Docs-20220908-154157.yaml
  core/dbt/include/starter_project/dbt_project.yml
  test/integration/040_init_tests/test_init.py
Labels: cla:yes, Team:Adapters, ready_for_review

#5991 add -f for seeds
  .changes/unreleased/Features-20221003-110705.yaml
  core/dbt/main.py
Labels: cla:yes, ready_for_review, support_rotation

#6024 Consolidate exception
  .changes/unreleased/Under the Hood-20221007-094627.yaml
  core/dbt/context/providers.py
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
Labels: cla:yes

#5812 Add friendlier error messages when packages yml is malformed
  .changes/unreleased/Features-20220912-125935.yaml
  core/dbt/contracts/project.py
  test/unit/test_deps.py
Labels: cla:yes, Team:Language, ready_for_review

#6045 Adding 1.3.latest branch to testing matrix
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#5983 Make `mypy` pass from the command line
  .changes/unreleased/Under the Hood-20221005-120310.yaml
  mypy.ini
  pyproject.toml
Labels: cla:yes, ready_for_review, support_rotation

#5971 [CT-1271] Test Query Comment conversion
  test/integration/051_query_comments_tests/models/x.sql
  test/integration/051_query_comments_tests/test_query_comments.py
  tests/adapter/dbt/tests/adapter/query_comment/fixtures.py
  tests/adapter/dbt/tests/adapter/query_comment/test_query_comment.py
Labels: cla:yes, Skip Changelog

#6038 Validate enabled config is a bool for sources, exposures and metrics
  .changes/unreleased/Fixes-20221010-113218.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  tests/functional/configs/fixtures.py
  tests/functional/configs/test_disabled_model.py
  tests/functional/exposures/fixtures.py
  tests/functional/exposures/test_exposure_configs.py
  tests/functional/exposures/test_exposures.py
  tests/functional/metrics/fixture_metrics.py
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metric_configs.py
  tests/functional/metrics/test_metric_deferral.py
  tests/functional/metrics/test_metric_helper_functions.py
  tests/functional/metrics/test_metrics.py
  tests/functional/sources/common_source_setup.py
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_simple_source.py
  tests/functional/sources/test_source_configs.py
  tests/functional/sources/test_source_fresher_state.py
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes

#6042 fix: check length of args of python model function before accessing it
  .changes/unreleased/Fixes-20221011-160715.yaml
  core/dbt/parser/models.py
  test/unit/test_parser.py
Labels: cla:yes

#6049 fix: check length of args of python model function before accessing i…
  .changes/unreleased/Fixes-20221011-160715.yaml
  core/dbt/parser/models.py
  test/unit/test_parser.py
Labels: cla:yes

#6022 Generate API docs
  .changes/unreleased/Docs-20221007-090656.yaml
  core/dbt/docs/Makefile
  core/dbt/docs/make.bat
  core/dbt/docs/source/_ext/dbt_click.py
  core/dbt/docs/source/conf.py
  core/dbt/docs/source/index.rst
  dev-requirements.txt
Labels: cla:yes

#5780 Ct 1049/migrate 016 macro tests
  test/integration/016_macro_tests/deprecated-adapter-macro-models/model.sql
  test/integration/016_macro_tests/deprecated-adapter-macro/model.sql
  test/integration/016_macro_tests/fail-missing-macro-models/model.sql
  test/integration/016_macro_tests/macros/my_macros.sql
  test/integration/016_macro_tests/models/.gitkeep
  test/integration/016_macro_tests/models/dep_macro.sql
  test/integration/016_macro_tests/models/local_macro.sql
  test/integration/016_macro_tests/models/ref_macro.sql
  test/integration/016_macro_tests/no-default-macros/my_macros.sql
  test/integration/016_macro_tests/override-get-columns-models/model.sql
  test/integration/016_macro_tests/override-postgres-get-columns-macros/macros.sql
  test/integration/016_macro_tests/package_macro_overrides/macros/macros.sql
  test/integration/016_macro_tests/test_macros.py
  tests/functional/macros/data/seed.sql
  tests/functional/macros/fixtures.py
  tests/functional/macros/package_macro_overrides/dbt_project.yml
  tests/functional/macros/package_macro_overrides/macros/macros.sql
  tests/functional/macros/test_macros.py
Labels: cla:yes, Skip Changelog

#5930 Allowing partitions in external table to be a list
  .changes/unreleased/Features-20220925-211651.yaml
  core/dbt/contracts/graph/unparsed.py
Labels: cla:yes, ready_for_review

#6054 migrate 034 integration test to functional
  test/integration/034_changing_relation_type_tests/models/model.sql
  test/integration/034_changing_relation_type_tests/test_changing_relation_type.py
  tests/adapter/dbt/tests/adapter/relations/test_changing_relation_type.py
Labels: cla:yes, Skip Changelog

#5999 Allow custom metadata to be attached to every log
  core/dbt/constants.py
  core/dbt/context/providers.py
  core/dbt/contracts/util.py
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/lib.py
  core/dbt/tests/util.py
  test/unit/test_context.py
  test/unit/test_manifest.py
  tests/functional/context_methods/test_custom_env_vars.py
  tests/unit/test_proto_events.py
Labels: cla:yes, Skip Changelog

#5954 Initial structured logging changes
  .changes/unreleased/Features-20220817-154857.yaml
  .github/workflows/structured-logging-schema-check.yml
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/cache.py
  core/dbt/adapters/factory.py
  core/dbt/adapters/reference_keys.py
  core/dbt/adapters/sql/connections.py
  core/dbt/adapters/sql/impl.py
  core/dbt/clients/registry.py
  core/dbt/constants.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/results.py
  core/dbt/contracts/util.py
  core/dbt/events/README.md
  core/dbt/events/adapter_endpoint.py
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/proto_types.py
  core/dbt/events/serialization.py
  core/dbt/events/test_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/lib.py
  core/dbt/main.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/task/base.py
  core/dbt/task/deps.py
  core/dbt/task/freshness.py
  core/dbt/task/generate.py
  core/dbt/task/init.py
  core/dbt/task/parse.py
  core/dbt/task/run.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  core/dbt/task/sql.py
  core/dbt/task/test.py
  core/dbt/tests/util.py
  core/dbt/tracking.py
  core/dbt/utils.py
  core/setup.py
  dev-requirements.txt
  test/unit/test_context.py
  test/unit/test_events.py
  test/unit/test_manifest.py
  tests/functional/context_methods/test_builtin_functions.py
  tests/functional/context_methods/test_custom_env_vars.py
  tests/unit/test_events.py
  tests/unit/test_proto_events.py
  third-party-stubs/mashumaro/__init__.pyi
  tox.ini
Labels: cla:yes

#6025 CT-625: Fail with clear message for invalid materialized vals
  .changes/unreleased/Under the Hood-20221013-181912.yaml
  core/dbt/contracts/graph/model_config.py
  tests/functional/configs/fixtures.py
  tests/functional/configs/test_configs.py
Labels: cla:yes

#6082 f-string cleanup #6068
  .changes/unreleased/Under the Hood-20221017-155844.yaml
  core/dbt/config/project.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/exceptions.py
  core/dbt/graph/selector.py
  core/dbt/parser/base.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/sources.py
  core/dbt/task/runnable.py
Labels: cla:yes, Hackathon

#6086 Updated string formatting on non-f-strings.
  .changes/unreleased/Under the Hood-20221017-151511.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/clients/_jinja_blocks.py
  core/dbt/config/project.py
  core/dbt/context/base.py
  core/dbt/contracts/connection.py
  core/dbt/contracts/results.py
  core/dbt/graph/graph.py
  core/dbt/logger.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  core/dbt/task/base.py
  core/dbt/task/compile.py
  core/dbt/task/freshness.py
  core/dbt/task/runnable.py
  core/dbt/utils.py
  tests/functional/artifacts/expected_manifest.py
Labels: cla:yes, Hackathon

#6095 Add unit tests per Colin's idea
  tests/unit/test_events.py
Labels: cla:yes, Skip Changelog

#6084 [CT-1221] Add 'michelleark' to changie's core_team list
  .changie.yaml
Labels: cla:yes, Skip Changelog

#6094 convert 027 cycle test
  test/integration/027_cycle_tests/complex_cycle_models/model_a.sql
  test/integration/027_cycle_tests/complex_cycle_models/model_b.sql
  test/integration/027_cycle_tests/complex_cycle_models/model_c.sql
  test/integration/027_cycle_tests/complex_cycle_models/model_d.sql
  test/integration/027_cycle_tests/complex_cycle_models/model_e.sql
  test/integration/027_cycle_tests/complex_cycle_models/readme
  test/integration/027_cycle_tests/simple_cycle_models/model_a.sql
  test/integration/027_cycle_tests/simple_cycle_models/model_b.sql
  test/integration/027_cycle_tests/test_cycles.py
  tests/functional/cycles/test_cycles.py
Labels: cla:yes, Skip Changelog

#6134 [BUGFIX] Force `tox` to update `pip` (fixes `psycopg2-binary @ 2.9.5`)
  tox.ini
Labels: cla:yes, Skip Changelog

#6137 Fix CI issue with tox
  .changes/unreleased/Fixes-20221016-173742.yaml
  .changes/unreleased/Under the Hood-20221017-151511.yaml
  .changes/unreleased/Under the Hood-20221017-155844.yaml
  .changie.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/clients/_jinja_blocks.py
  core/dbt/config/project.py
  core/dbt/context/base.py
  core/dbt/context/providers.py
  core/dbt/contracts/connection.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/results.py
  core/dbt/events/adapter_endpoint.py
  core/dbt/events/base_types.py
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/graph/graph.py
  core/dbt/graph/selector.py
  core/dbt/logger.py
  core/dbt/parser/base.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  core/dbt/task/base.py
  core/dbt/task/compile.py
  core/dbt/task/freshness.py
  core/dbt/task/runnable.py
  core/dbt/utils.py
  test/integration/027_cycle_tests/complex_cycle_models/model_a.sql
  test/integration/027_cycle_tests/complex_cycle_models/model_b.sql
  test/integration/027_cycle_tests/complex_cycle_models/model_c.sql
  test/integration/027_cycle_tests/complex_cycle_models/model_d.sql
  test/integration/027_cycle_tests/complex_cycle_models/model_e.sql
  test/integration/027_cycle_tests/complex_cycle_models/readme
  test/integration/027_cycle_tests/simple_cycle_models/model_a.sql
  test/integration/027_cycle_tests/simple_cycle_models/model_b.sql
  test/integration/027_cycle_tests/test_cycles.py
  test/integration/071_commented_yaml_regression_3568_tests/models/schema.yml
  test/integration/071_commented_yaml_regression_3568_tests/test_all_comment_yml_files.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/cycles/test_cycles.py
  tests/functional/schema_tests/fixtures.py
  tests/functional/schema_tests/test_schema_v2_tests.py
  tests/unit/test_events.py
  tox.ini
Labels: cla:yes, Skip Changelog

#6088 Logging works with Click
  .changes/unreleased/Under the Hood-20221017-170500.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/clients/system.py
  core/dbt/events/functions.py
  core/dbt/main.py
  core/dbt/tests/fixtures/project.py
  test/integration/base.py
  test/unit/test_system_client.py
Labels: cla:yes

#6109 Ct 1167/030 statement tests conversion
  test/integration/030_statement_tests/models/statement_actual.sql
  test/integration/030_statement_tests/seed/statement_expected.csv
  test/integration/030_statement_tests/test_statements.py
  tests/functional/statements/fixtures.py
  tests/functional/statements/test_statements.py
Labels: cla:yes, Skip Changelog

#6120 switch out to use internal action for triage labels
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#6157 More ergonomic profile name handling
  core/dbt/config/runtime.py
Labels: cla:yes, Skip Changelog, backport 1.2.latest

#6161 point to correct workflow
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#6163 revert triage-label action to community action
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#6064 Convert messages to struct logs
  core/dbt/adapters/base/impl.py
  core/dbt/config/runtime.py
  core/dbt/constants.py
  core/dbt/context/providers.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/deps/git.py
  core/dbt/events/functions.py
  core/dbt/events/helpers.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/graph/selector.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  core/dbt/task/list.py
  core/dbt/task/printer.py
  core/dbt/task/runnable.py
  test/unit/test_config.py
  test/unit/test_graph_selector_methods.py
  tests/unit/test_events.py
Labels: cla:yes, Skip Changelog
