Repository dbt-labs/dbt-core, pull requests merged in 2022-03, with the labels that each got.

#4792 Fix stdout piped colored output on MacOS and Linux
  CHANGELOG.md
  core/dbt/events/functions.py
  core/dbt/logger.py
Labels: cla:yes

#4803 simplify and cleanup gha workflow
  .github/scripts/integration-test-matrix.js
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/release-docker.yml
  .github/workflows/structured-logging-schema-check.yml
  Makefile
  README.md
  core/README.md
  plugins/postgres/README.md
  pytest.ini
  tox.ini
Labels: cla:yes

#4815 Convert tests in dbt-adapter-tests to use new pytest framework
  core/dbt/contracts/graph/model_config.py
  core/dbt/tests/adapter.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  pytest.ini
  tests/fixtures/jaffle_shop.py
  tests/functional/adapter/__init__.py
  tests/functional/adapter/files.py
  tests/functional/adapter/test_base.py
  tests/functional/adapter/test_data_test_ephemerals.py
  tests/functional/adapter/test_data_tests.py
  tests/functional/adapter/test_empty.py
  tests/functional/adapter/test_ephemeral.py
  tests/functional/adapter/test_incremental.py
  tests/functional/adapter/test_schema_tests.py
  tests/functional/adapter/test_snapshot_check_cols.py
  tests/functional/adapter/test_snapshot_timestamp.py
  tests/functional/basic/test_jaffle_shop.py
Labels: cla:yes

#4820 Fix macro modified from previous state
  CHANGELOG.md
  core/dbt/graph/selector_methods.py
  test/unit/test_graph_selector_methods.py
Labels: cla:yes

#4835 Switch to using class scope fixtures
  core/dbt/tests/fixtures/project.py
  tests/fixtures/jaffle_shop.py
  tests/functional/adapter/test_base.py
  tests/functional/adapter/test_data_test_ephemerals.py
  tests/functional/adapter/test_data_tests.py
  tests/functional/adapter/test_ephemeral.py
  tests/functional/adapter/test_incremental.py
  tests/functional/adapter/test_schema_tests.py
  tests/functional/adapter/test_snapshot_check_cols.py
  tests/functional/adapter/test_snapshot_timestamp.py
  tests/functional/basic/test_basic.py
  tests/functional/basic/test_copy_uppercase.py
  tests/functional/basic/test_invalid_reference.py
  tests/functional/basic/test_mixed_case_db.py
  tests/functional/basic/test_simple_copy.py
  tests/functional/basic/test_simple_reference.py
  tests/functional/basic/test_varchar_widening.py
  tests/functional/graph_selection/fixtures.py
  tests/functional/graph_selection/test_graph_selection.py
  tests/functional/graph_selection/test_intersection_syntax.py
  tests/functional/graph_selection/test_schema_test_graph_selection.py
  tests/functional/graph_selection/test_tag_selection.py
  tests/functional/simple_seed/test_seed.py
Labels: cla:yes

#4743 Automate changelog
  .changes/0.0.0.md
  .changes/1.0.1.md
  .changes/README.md
  .changes/header.tpl.md
  .changes/unreleased/.gitkeep
  .changes/unreleased/Under the Hood-20220218-161319.yaml
  .changie.yaml
  .github/pull_request_template.md
  .github/workflows/changelog-check.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: cla:yes

#4841 Small updates to clarify change destinations
  .changes/1.0.99.md
  .changes/unreleased/Docs-20220307-203105.yaml
  .changes/unreleased/Fixes-20220307-203022.yaml
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#4834 [Backport] CT-231
  CHANGELOG.md
  core/dbt/graph/selector_methods.py
  test/unit/test_graph_selector_methods.py
Labels: cla:yes

#4847 manually add performance baseline for 1.0.3
  performance/baselines/1.0.3/parse___2000_models.json
Labels: cla:yes

#4817 [Backport] task init: support older click v7.0 (#4681)
  CHANGELOG.md
  core/dbt/task/init.py
  core/setup.py
Labels: cla:yes

#4777 [CT-271] [Feature] not_null test selects column instead of *
  .changes/unreleased/Features-20220309-163817.yaml
  core/dbt/include/global_project/macros/generic_test_sql/not_null.sql
Labels: cla:yes, Team:Execution

#4838 Er/ct 303 004 simple snapshot
  test/integration/004_simple_snapshot_tests/add_column_to_source_bq.sql
  test/integration/004_simple_snapshot_tests/macros-custom-snapshot/custom.sql
  test/integration/004_simple_snapshot_tests/models-collision/snapshot_actual.sql
  test/integration/004_simple_snapshot_tests/models-slow/gen.sql
  test/integration/004_simple_snapshot_tests/models/.gitkeep
  test/integration/004_simple_snapshot_tests/models/ref_snapshot.sql
  test/integration/004_simple_snapshot_tests/models/schema.yml
  test/integration/004_simple_snapshot_tests/seed.sql
  test/integration/004_simple_snapshot_tests/seed_longtext.sql
  test/integration/004_simple_snapshot_tests/seeds/seed.csv
  test/integration/004_simple_snapshot_tests/seeds/seed_newcol.csv
  test/integration/004_simple_snapshot_tests/snapshots-check-col-noconfig/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-check-col/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-check/check_cols_cycle.sql
  test/integration/004_simple_snapshot_tests/snapshots-checkall/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-invalid/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-longtext/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-pg-custom-invalid/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-pg-custom-namespaced/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-pg-custom/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-pg/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-select-noconfig/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-select/snapshot.sql
  test/integration/004_simple_snapshot_tests/snapshots-slow/snapshot.sql
  test/integration/004_simple_snapshot_tests/test-check-snapshots-expected/check_snapshots_test_current.sql
  test/integration/004_simple_snapshot_tests/test-snapshots-changing-strategy/test_snapshot.sql
  test/integration/004_simple_snapshot_tests/test-snapshots-slow/test_timestamps.sql
  test/integration/004_simple_snapshot_tests/test_simple_snapshot.py
  test/integration/004_simple_snapshot_tests/test_snapshot_check_cols.py
  tests/functional/simple_snapshot/data/invalidate_postgres.sql
  tests/functional/simple_snapshot/data/seed_pg.sql
  tests/functional/simple_snapshot/data/shared_macros.sql
  tests/functional/simple_snapshot/data/update.sql
  tests/functional/simple_snapshot/fixtures.py
  tests/functional/simple_snapshot/test_basic_snapshot.py
  tests/functional/simple_snapshot/test_changing_strategy_snapshot.py
  tests/functional/simple_snapshot/test_check_cols_snapshot.py
  tests/functional/simple_snapshot/test_cross_schema_snapshot.py
  tests/functional/simple_snapshot/test_hard_delete_snapshot.py
  tests/functional/simple_snapshot/test_invalid_namespace_snapshot.py
  tests/functional/simple_snapshot/test_long_text_snapshot.py
  tests/functional/simple_snapshot/test_missing_strategy_snapshot.py
  tests/functional/simple_snapshot/test_renamed_source_snapshot.py
  tests/functional/simple_snapshot/test_select_exclude_snapshot.py
  tests/functional/simple_snapshot/test_slow_query_snapshot.py
Labels: cla:yes, Skip Changelog

#4857 Small changie fixes
  .changes/header.tpl.md
  .changes/unreleased/Under the Hood-20220311-101851.yaml
  .github/workflows/changelog-check.yml
  CHANGELOG.md
Labels: cla:yes, backport 1.0.latest

#4866 python 3.10 support
  .changes/unreleased/Under the Hood-20220315-155436.yaml
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/main.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  test/integration/base.py
  tox.ini
Labels: cla:yes

#4869 get_response type hint is AdapterResponse only.
  .changes/unreleased/Breaking Changes-20220316-031311.yaml
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/protocol.py
  core/dbt/adapters/sql/connections.py
Labels: cla:yes

#4816 Add bugged version tag value to finds.
  core/dbt/exceptions.py
  core/dbt/parser/schemas.py
Labels: cla:yes

#4878 Use cli_vars instead of context to create package and selector renderers
  .changes/unreleased/Fixes-20220316-155420.yaml
  core/dbt/config/renderer.py
Labels: cla:yes, backport 1.0.latest

#4890 [HOTFIX] update dbt-extractor dependency
  .changes/unreleased/Fixes-20220317-132418.yaml
  core/setup.py
Labels: cla:yes

#4896 remove missing setup.py file (holdover from pip install dbt
  .bumpversion.cfg
  .changes/unreleased/Fixes-20220317-163051.yaml
Labels: cla:yes

#4846 Set up adapter testing framework for use by adapter test repos
  .changes/unreleased/Features-20220309-142645.yaml
  core/dbt/adapters/sql/impl.py
  core/dbt/tests/__init__.py
  core/dbt/tests/adapter.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  editable-requirements.txt
  tests/adapter/README.md
  tests/adapter/dbt/tests/adapter/basic/__init__.py
  tests/adapter/dbt/tests/adapter/basic/files.py
  tests/adapter/dbt/tests/adapter/basic/test_base.py
  tests/adapter/dbt/tests/adapter/basic/test_empty.py
  tests/adapter/dbt/tests/adapter/basic/test_ephemeral.py
  tests/adapter/dbt/tests/adapter/basic/test_generic_tests.py
  tests/adapter/dbt/tests/adapter/basic/test_incremental.py
  tests/adapter/dbt/tests/adapter/basic/test_singular_tests.py
  tests/adapter/dbt/tests/adapter/basic/test_singular_tests_ephemeral.py
  tests/adapter/dbt/tests/adapter/basic/test_snapshot_check_cols.py
  tests/adapter/dbt/tests/adapter/basic/test_snapshot_timestamp.py
  tests/adapter/setup.py
  tests/functional/adapter/test_base.py
  tests/functional/adapter/test_data_test_ephemerals.py
  tests/functional/adapter/test_data_tests.py
  tests/functional/adapter/test_empty.py
  tests/functional/adapter/test_ephemeral.py
  tests/functional/adapter/test_incremental.py
  tests/functional/adapter/test_schema_tests.py
  tests/functional/adapter/test_snapshot_check_cols.py
  tests/functional/adapter/test_snapshot_timestamp.py
  tests/functional/graph_selection/test_tag_selection.py
  tox.ini
Labels: cla:yes

#4900 Bump setup.py file to 1.0.4
  setup.py
Labels: cla:yes

#4903 added permissions settings for docker release workflow
  .changes/unreleased/Fixes-20220318-095846.yaml
  .github/workflows/release-docker.yml
Labels: cla:yes

#4892 [Backport] [HOTFIX] update dbt-extractor dependency
  .changes/unreleased/Fixes-20220317-132418.yaml
  core/setup.py
Labels: cla:yes

#4917 changie - convert changelogs to yaml files and make quality of life improvements
  .changes/1.0.99.md
  .changes/README.md
  .changes/unreleased/Features-20220321-135949.yaml
  .changes/unreleased/Features-20220321-140046.yaml
  .changes/unreleased/Features-20220321-140139.yaml
  .changes/unreleased/Features-20220321-140306.yaml
  .changes/unreleased/Fixes-20220321-140521.yaml
  .changes/unreleased/Fixes-20220321-140720.yaml
  .changes/unreleased/Fixes-20220321-140833.yaml
  .changes/unreleased/Fixes-20220321-140921.yaml
  .changes/unreleased/Fixes-20220321-141007.yaml
  .changes/unreleased/Under the Hood-20220321-141158.yaml
  .changes/unreleased/Under the Hood-20220321-141300.yaml
  .changes/unreleased/Under the Hood-20220321-141338.yaml
  .changes/unreleased/Under the Hood-20220321-141451.yaml
  .changes/unreleased/Under the Hood-20220321-141523.yaml
  .changes/unreleased/Under the Hood-20220321-141610.yaml
  .changes/unreleased/Under the Hood-20220321-141707.yaml
  .changes/unreleased/Under the Hood-20220321-141747.yaml
  .changes/unreleased/Under the Hood-20220321-142055.yaml
  .changie.yaml
  .github/workflows/changelog-check.yml
  CHANGELOG.md
Labels: cla:yes

#4920 Updating backport workflow to use forked action
  .github/workflows/backport.yml
Labels: cla:yes, Skip Changelog

#4858 update of macro for postgres/redshift use of unique_key as a list
  .changes/unreleased/Features-20220314-112341.yaml
  core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql
  test/integration/076_incremental_unique_id_test/models/duplicated_unary_unique_key_list.sql
  test/integration/076_incremental_unique_id_test/models/empty_str_unique_key.sql
  test/integration/076_incremental_unique_id_test/models/empty_unique_key_list.sql
  test/integration/076_incremental_unique_id_test/models/expected/one_str__overwrite.sql
  test/integration/076_incremental_unique_id_test/models/expected/unique_key_list__inplace_overwrite.sql
  test/integration/076_incremental_unique_id_test/models/no_unique_key.sql
  test/integration/076_incremental_unique_id_test/models/nontyped_trinary_unique_key_list.sql
  test/integration/076_incremental_unique_id_test/models/not_found_unique_key.sql
  test/integration/076_incremental_unique_id_test/models/not_found_unique_key_list.sql
  test/integration/076_incremental_unique_id_test/models/str_unique_key.sql
  test/integration/076_incremental_unique_id_test/models/trinary_unique_key_list.sql
  test/integration/076_incremental_unique_id_test/models/unary_unique_key_list.sql
  test/integration/076_incremental_unique_id_test/seeds/add_new_rows.sql
  test/integration/076_incremental_unique_id_test/seeds/duplicate_insert.sql
  test/integration/076_incremental_unique_id_test/seeds/seed.csv
  test/integration/076_incremental_unique_id_test/test_incremental_unique_id.py
Labels: cla:yes

#4744 Add space before justification periods
  .changes/unreleased/Features-20220322-144822.yaml
  core/dbt/events/format.py
Labels: cla:yes

#4932 updated bumpversion
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#4912 add compliation and cache tracking
  .changes/unreleased/Under the Hood-20220321-142854.yaml
  core/dbt/task/runnable.py
  core/dbt/tracking.py
Labels: cla:yes

#4934 remove capping version of typing extensions
  core/setup.py
Labels: dependencies, cla:yes, install, backport 1.0.latest, Skip Changelog

#4941 v1.0.4 changelog with one entry
  .changes/1.0.4.md
  .changes/1.0.5-rc1.md
  .changes/1.0.5/Fixes-20220317-132418.yaml
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#4937 Update v0.21 changelog: confusing note about breaking change to Snowflake transactions
  CHANGELOG.md
Labels: cla:yes

#4944 Cosmetic changelog/changie fixups
  .changes/1.1.0-b1.md
  .changes/1.1.0/Breaking Changes-20220316-031311.yaml
  .changie.yaml
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#4935 Convert source tests
  test/integration/042_sources_tests/error_models/model.sql
  test/integration/042_sources_tests/error_models/schema.yml
  test/integration/042_sources_tests/filtered_models/schema.yml
  test/integration/042_sources_tests/macros/macro.sql
  test/integration/042_sources_tests/malformed_models/descendant_model.sql
  test/integration/042_sources_tests/malformed_models/schema.yml
  test/integration/042_sources_tests/malformed_schema_tests/model.sql
  test/integration/042_sources_tests/malformed_schema_tests/schema.yml
  test/integration/042_sources_tests/models/descendant_model.sql
  test/integration/042_sources_tests/models/ephemeral_model.sql
  test/integration/042_sources_tests/models/multi_source_model.sql
  test/integration/042_sources_tests/models/nonsource_descendant.sql
  test/integration/042_sources_tests/models/schema.yml
  test/integration/042_sources_tests/models/view_model.sql
  test/integration/042_sources_tests/override_freshness_models/schema.yml
  test/integration/042_sources_tests/seeds/expected_multi_source.csv
  test/integration/042_sources_tests/seeds/other_source_table.csv
  test/integration/042_sources_tests/seeds/other_table.csv
  test/integration/042_sources_tests/test_sources.py
  test/integration/059_source_overrides_tests/dupe-models/schema1.yml
  test/integration/059_source_overrides_tests/dupe-models/schema2.yml
  test/integration/059_source_overrides_tests/local_dependency/dbt_project.yml
  test/integration/059_source_overrides_tests/local_dependency/models/my_model.sql
  test/integration/059_source_overrides_tests/local_dependency/models/schema.yml
  test/integration/059_source_overrides_tests/local_dependency/seeds/keep/never_fresh.csv
  test/integration/059_source_overrides_tests/local_dependency/seeds/keep/snapshot_freshness_base.csv
  test/integration/059_source_overrides_tests/local_dependency/seeds/my_other_seed.csv
  test/integration/059_source_overrides_tests/local_dependency/seeds/my_seed.csv
  test/integration/059_source_overrides_tests/models/schema.yml
  test/integration/059_source_overrides_tests/seeds/expected_result.csv
  test/integration/059_source_overrides_tests/seeds/my_real_other_seed.csv
  test/integration/059_source_overrides_tests/seeds/my_real_seed.csv
  test/integration/059_source_overrides_tests/test_source_overrides.py
  tests/functional/source_overrides/fixtures.py
  tests/functional/source_overrides/test_simple_source_override.py
  tests/functional/source_overrides/test_source_overrides_duplicate_model.py
  tests/functional/sources/common_source_setup.py
  tests/functional/sources/data/seed.sql
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_simple_source.py
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes, Skip Changelog

#4898 Custom names for generic tests
  .changes/unreleased/Features-20220318-085756.yaml
  core/dbt/exceptions.py
  core/dbt/parser/generic_test_builders.py
  test/integration/025_duplicate_model_tests/test_duplicate_exposure.py
  test/integration/025_duplicate_model_tests/test_duplicate_model.py
  test/integration/025_duplicate_model_tests/test_duplicate_source.py
  tests/functional/schema_tests/fixtures.py
  tests/functional/schema_tests/test_schema_v2_tests.py
Labels: cla:yes, Team:Language

#4948 Create a dbt.tests.adapter release when releasing dbt and postgres
  .bumpversion.cfg
  .changes/unreleased/Under the Hood-20220329-112448.yaml
  .pre-commit-config.yaml
  scripts/build-dist.sh
  tests/adapter/dbt/tests/adapter/__version__.py
  tests/adapter/setup.py
  third-party-stubs/logbook/ticketing.pyi
Labels: cla:yes
