Repository dbt-labs/dbt-core, pull requests merged in 2022-12, with the labels that each got.

#6342 Exposures support metrics
  .changes/unreleased/Features-20221130-112913.yaml
  core/dbt/context/providers.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v8.json
  test/unit/test_contracts_graph_parsed.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/exposures/fixtures.py
  tests/functional/exposures/test_exposure_configs.py
  tests/functional/exposures/test_exposures.py
Labels: cla:yes

#6251 clarify error log for number of allowed models in a Python file
  .changes/unreleased/Fixes-20221115-081021.yaml
  core/dbt/parser/models.py
Labels: cla:yes, Team:Language, ready_for_review

#6314 reformatting of test after some spike investigation
  tests/adapter/dbt/tests/adapter/aliases/test_aliases.py
Labels: cla:yes, Skip Changelog

#6362 Update main workflow for 1.0.latest branch
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#6363 Reverting back to older ubuntu image
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#6266 Set Flags from UserConfig
  .changes/unreleased/Features-20221129-183239.yaml
  core/dbt/cli/flags.py
  tests/unit/test_cli_flags.py
Labels: cla:yes

#6370 [Backport 1.3.latest] Reverting back to older ubuntu image
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#6081 [fix] Fix the partial parse write path
  .changes/unreleased/Fixes-20221202-164859.yaml
  core/dbt/parser/manifest.py
Labels: cla:yes, Team:Language, ready_for_review, Hackathon

#6371 Update `core/dbt/README.md` to match current
  .changes/unreleased/Docs-20221202-150523.yaml
  core/dbt/README.md
Labels: cla:yes, ready_for_review

#6325 CT 1477 enrich logging events with data similar to legacy logger
  .changes/unreleased/Features-20220817-154857.yaml
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/sql/connections.py
  core/dbt/compilation.py
  core/dbt/context/base.py
  core/dbt/contracts/connection.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/results.py
  core/dbt/events/adapter_endpoint.py
  core/dbt/events/contextvars.py
  core/dbt/events/functions.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/lib.py
  core/dbt/logger.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/macros.py
  core/dbt/task/base.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  tests/functional/logging/test_logging.py
  tests/unit/test_events.py
  tox.ini
Labels: cla:yes, logging, Skip Changelog

#6380 Pin ubuntu at 20.04 for some workflows
  .changes/unreleased/Under the Hood-20221205-092217.yaml
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes

#6390 Prevent docs gen workflow on forks
  .changes/unreleased/Under the Hood-20221206-094015.yaml
  .github/workflows/generate-cli-api-docs.yml
Labels: cla:yes

#6291 CT-1405: Refactor event logging code
  .changes/unreleased/Under the Hood-20221118-145717.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/contracts/project.py
  core/dbt/events/base_types.py
  core/dbt/events/eventmgr.py
  core/dbt/events/functions.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/flags.py
  core/dbt/main.py
  core/dbt/task/base.py
  core/dbt/task/list.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  test/integration/base.py
  test/unit/test_context.py
  test/unit/test_flags.py
  test/unit/test_manifest.py
  tests/functional/context_methods/test_builtin_functions.py
  tests/unit/test_events.py
Labels: cla:yes

#6385 Adding Semantic Structure: The First Draft
  core/dbt/compilation.py
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/context/context_config.py
  core/dbt/context/providers.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/compiled.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.py
  core/dbt/graph/cli.py
  core/dbt/graph/queue.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/node_types.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  core/dbt/task/list.py
  testing-project/postgres/.gitignore
  testing-project/postgres/README.md
  testing-project/postgres/analyses/.gitkeep
  testing-project/postgres/dbt_project.yml
  testing-project/postgres/macros/.gitkeep
  testing-project/postgres/models/combined__orders_customers.sql
  testing-project/postgres/models/dim_customers.sql
  testing-project/postgres/models/dim_customers.yml
  testing-project/postgres/models/entities/customers.yml
  testing-project/postgres/models/entities/orders.yml
  testing-project/postgres/models/fact_orders.sql
  testing-project/postgres/models/fact_orders.yml
  testing-project/postgres/seeds/.gitkeep
  testing-project/postgres/seeds/dim_customers_source.csv
  testing-project/postgres/seeds/fact_orders_source.csv
  testing-project/postgres/snapshots/.gitkeep
  testing-project/postgres/tests/.gitkeep
Labels: cla:yes

#6395 Fix intermittent database connection failure in Windows CI test
  .changes/unreleased/Under the Hood-20221206-113053.yaml
  core/dbt/tests/fixtures/project.py
Labels: cla:yes

#6384 CT 1604 remove compiled classes
  .changes/unreleased/Under the Hood-20221205-164948.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/base/query_headers.py
  core/dbt/adapters/base/relation.py
  core/dbt/adapters/protocol.py
  core/dbt/clients/jinja.py
  core/dbt/compilation.py
  core/dbt/context/base.py
  core/dbt/context/docs.py
  core/dbt/context/macro_resolver.py
  core/dbt/context/macros.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/compiled.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/metrics.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/results.py
  core/dbt/contracts/sql.py
  core/dbt/graph/queue.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/README.md
  core/dbt/parser/analysis.py
  core/dbt/parser/base.py
  core/dbt/parser/docs.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/hooks.py
  core/dbt/parser/macros.py
  core/dbt/parser/manifest.py
  core/dbt/parser/models.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  core/dbt/parser/seeds.py
  core/dbt/parser/singular_test.py
  core/dbt/parser/snapshots.py
  core/dbt/parser/sources.py
  core/dbt/parser/sql.py
  core/dbt/task/freshness.py
  core/dbt/task/generate.py
  core/dbt/task/list.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/dbt/task/test.py
  test/unit/test_compiler.py
  test/unit/test_context.py
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_docs_blocks.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_macro_resolver.py
  test/unit/test_manifest.py
  test/unit/test_parser.py
  test/unit/test_partial_parsing.py
  test/unit/utils.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/exit_codes/test_exit_codes.py
  tests/unit/test_events.py
Labels: cla:yes

#6405 Adjust tox passenv to be multiline
  tox.ini
Labels: cla:yes, Skip Changelog

#4689 Feature/dbt deps tarball
  .changes/unreleased/Features-20221107-105018.yaml
  core/dbt/contracts/project.py
  core/dbt/deps/README.md
  core/dbt/deps/base.py
  core/dbt/deps/registry.py
  core/dbt/deps/resolver.py
  core/dbt/deps/tarball.py
  core/dbt/task/deps.py
  test/unit/test_deps.py
Labels: cla:yes, Team:Language, ready_for_review

#6407 [Backport 1.2.latest] tox fix
  tox.ini
Labels: cla:yes, Skip Changelog

#6406 [Backport 1.3.latest] tox fix
  tox.ini
Labels: cla:yes, Skip Changelog

#6317 Fix dbt.config.get default values (python-model)
  .changes/unreleased/Fixes-20221124-163419.yaml
  core/dbt/include/global_project/macros/python_model/python.sql
  core/dbt/parser/models.py
  test/unit/test_parser.py
Labels: cla:yes, Team:Language, ready_for_review

#6410 Disable `test_postgres_package_redirect_fail` in 1.1.latest
  test/integration/012_deprecation_tests/test_deprecations.py
Labels: cla:yes, Skip Changelog

#6396 `dbt run` works with Click
  .changes/unreleased/Under the Hood-20221206-151759.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/config/runtime.py
  core/dbt/config/utils.py
  core/dbt/graph/cli.py
  core/dbt/task/base.py
  core/dbt/task/debug.py
  core/dbt/task/deps.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  test/unit/test_config.py
  test/unit/test_graph.py
  test/unit/test_graph_selection.py
  test/unit/test_linker.py
  test/unit/test_parser.py
  test/unit/utils.py
Labels: cla:yes

#6326 Add support for Python 3.11
  .changes/unreleased/Features-20221206-150704.yaml
  .github/workflows/main.yml
  CONTRIBUTING.md
  Dockerfile.test
  core/dbt/adapters/base/relation.py
  core/dbt/contracts/project.py
  core/dbt/events/eventmgr.py
  core/dbt/events/types.py
  core/dbt/helper_types.py
  core/setup.py
  plugins/postgres/setup.py
  tests/unit/test_version.py
  tox.ini
Labels: cla:yes

#6430 Adjust tox passenv to be multiline (#6405)
  .changes/unreleased/Under the Hood-20221212-110859.yaml
  tox.ini
Labels: cla:yes

#6423 Update docker README
  docker/README.md
Labels: cla:yes

#6427 CT 1644 node cleanup
  .changes/unreleased/Under the Hood-20221211-214240.yaml
  core/dbt/adapters/base/relation.py
  core/dbt/adapters/protocol.py
  core/dbt/compilation.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/util.py
  core/dbt/events/types.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/node_types.py
  core/dbt/parser/base.py
  core/dbt/parser/docs.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  core/dbt/parser/seeds.py
  core/dbt/parser/snapshots.py
  schemas/dbt/manifest/v8.json
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
  test/unit/test_node_types.py
  test/unit/test_parser.py
  tests/functional/artifacts/data/state/v8/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/partial_parsing/test_pp_docs.py
Labels: cla:yes

#6439 Add Optional back on "database" field of HasRelationMetadata
  core/dbt/contracts/graph/nodes.py
Labels: cla:yes, Skip Changelog

#6443 CT-1685: Restore certain aspects of legacy logging behavior important…
  .changes/unreleased/Under the Hood-20221213-214106.yaml
  core/dbt/events/eventmgr.py
  core/dbt/events/functions.py
Labels: cla:yes

#6447 Paw/ct 1652 restore default logging
  .changes/unreleased/Fixes-20221214-155307.yaml
  core/dbt/events/functions.py
Labels: cla:yes

#5702 Feature/support incremental predicates
  .changes/unreleased/Features-20220823-085727.yaml
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql
  core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql
  core/dbt/include/global_project/macros/materializations/models/incremental/strategies.sql
  tests/adapter/dbt/tests/adapter/incremental/test_incremental_predicates.py
Labels: cla:yes, Team:Adapters, test all, ready_for_review

#6450 Updating 1.4.0b1 changelog
  .changes/1.4.0-b1.md
  .changes/1.4.0/Features-20220823-085727.yaml
  .changes/1.4.0/Fixes-20221213-112620.yaml
  .changes/1.4.0/Fixes-20221214-155307.yaml
  .changes/1.4.0/Under the Hood-20221213-214106.yaml
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#6446 multiline passenv
  tox.ini
Labels: cla:yes, test all, Skip Changelog

#6369 Make clean task work with click
  .changes/unreleased/Under the Hood-20221202-123046.yaml
  core/dbt/cli/main.py
  core/dbt/task/clean.py
Labels: cla:yes

#6387 Functional test framework working with Click, dbtRunner
  .changes/unreleased/Under the Hood-20221214-112048.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  tests/unit/test_dbt_runner.py
  tox.ini
Labels: cla:yes

#6452 Fix dependency changelog kind
  .changes/1.4.0-b1.md
  .changes/1.4.0/Dependency-20221205-002118.yaml
  CHANGELOG.md
Labels: cla:yes

#6037 Fix typo in util.py
  .changes/unreleased/Fixes-20221117-220320.yaml
  core/dbt/tests/util.py
Labels: cla:yes, Team:Language, ready_for_review

#6465 add back validator_error_message
  core/dbt/exceptions.py
Labels: cla:yes, Skip Changelog

#6462 Treat dense text blobs as binary for `git grep`
  .changes/unreleased/Under the Hood-20221219-193435.yaml
  .gitattributes
Labels: cla:yes, ready_for_review
