Repository dbt-labs/dbt-core, pull requests merged in 2022-09, with the labels that each got.

#5754 Fix label selection syntax and trigger
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#5762 Move docs in from Jinja.
  CONTRIBUTING.md
  core/dbt/adapters/base/README.md
  core/dbt/clients/README.md
  core/dbt/context/README.md
  core/dbt/include/README.md
  core/dbt/parser/README.md
Labels: cla:yes, Skip Changelog

#5767 Add 1.2.latest branch to scheduled test matrix
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#5772 Convert experimental parser tests
  test/integration/072_experimental_parser_tests/basic/model_a.sql
  test/integration/072_experimental_parser_tests/basic/schema.yml
  test/integration/072_experimental_parser_tests/config_macro/macros/config.sql
  test/integration/072_experimental_parser_tests/config_macro/models/model_a.sql
  test/integration/072_experimental_parser_tests/config_macro/schema.yml
  test/integration/072_experimental_parser_tests/ref_macro/macros/ref.sql
  test/integration/072_experimental_parser_tests/ref_macro/models/model_a.sql
  test/integration/072_experimental_parser_tests/ref_macro/schema.yml
  test/integration/072_experimental_parser_tests/source_macro/macros/source.sql
  test/integration/072_experimental_parser_tests/source_macro/models/model_a.sql
  test/integration/072_experimental_parser_tests/source_macro/schema.yml
  test/integration/072_experimental_parser_tests/test_all_experimental_parser.py
  tests/functional/experimental_parser/test_all_experimental_parser.py
Labels: cla:yes, Skip Changelog

#5760 Ct 866/migrate hook tests fixed
  .changes/unreleased/Under the Hood-20220905-001749.yaml
  core/dbt/events/functions.py
  test/integration/014_hook_tests/configured-models/hooks.sql
  test/integration/014_hook_tests/error-models/hooks.sql
  test/integration/014_hook_tests/kwargs-models/hooks.sql
  test/integration/014_hook_tests/macros/before-and-after.sql
  test/integration/014_hook_tests/macros/hook.sql
  test/integration/014_hook_tests/models/hooks.sql
  test/integration/014_hook_tests/ref-hook-models/hooked.sql
  test/integration/014_hook_tests/ref-hook-models/post.sql
  test/integration/014_hook_tests/ref-hook-models/pre.sql
  test/integration/014_hook_tests/seed-models/schema.yml
  test/integration/014_hook_tests/seeds/example_seed.csv
  test/integration/014_hook_tests/test-kwargs-snapshots/snapshots.sql
  test/integration/014_hook_tests/test-snapshot-models/schema.yml
  test/integration/014_hook_tests/test-snapshots/snapshots.sql
  test/integration/014_hook_tests/test_model_hooks.py
  test/integration/014_hook_tests/test_run_hooks.py
  test/integration/base.py
  tests/functional/hooks/data/seed_model.sql
  tests/functional/hooks/data/seed_run.sql
  tests/functional/hooks/fixtures.py
  tests/functional/hooks/test_model_hooks.py
  tests/functional/hooks/test_run_hooks.py
  tests/functional/simple_snapshot/test_hard_delete_snapshot.py
Labels: cla:yes

#5763 Update makefile to match our CI
  Makefile
Labels: cla:yes, Skip Changelog

#5759 Add extra rm command in make clean to remove all .coverage files
  .changes/unreleased/Fixes-20220903-155409.yaml
  Makefile
Labels: cla:yes

#5703 Include py.typed in MANIFEST.in
  .changes/unreleased/Fixes-20220823-112633.yaml
  core/MANIFEST.in
Labels: cla:yes, ready_for_review

#5722 Add Window Attribute for Metrics
  .changes/unreleased/Features-20220831-121319.yaml
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schemas.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes, Team:Language, ready_for_review

#5786 Call build_flat_graph in merge_from_artifact
  .changes/unreleased/Under the Hood-20220908-145644.yaml
  core/dbt/contracts/graph/manifest.py
  tests/functional/metrics/test_metric_deferral.py
Labels: cla:yes

#5782 Add invocation_args_dict to ProviderContext
  .changes/unreleased/Features-20220908-081315.yaml
  core/dbt/context/providers.py
  test/unit/test_context.py
  tests/functional/context_methods/test_builtin_functions.py
Labels: cla:yes, Team:Language, ready_for_review

#5752 Convert test/integration/074_postgres_unlogged_table_tests
  test/integration/074_postgres_unlogged_table_tests/models/schema.yml
  test/integration/074_postgres_unlogged_table_tests/models/table_unlogged.sql
  test/integration/074_postgres_unlogged_table_tests/test_postgres_unlogged_table.py
  tests/functional/postgres/test_postgres_unlogged_table.py
Labels: cla:yes, Skip Changelog

#5749 Remove tmp file after test passed
  .changes/unreleased/Fixes-20220909-092832.yaml
  tests/functional/simple_seed/test_seed.py
Labels: cla:yes, ready_for_review

#5800 Fix warnings as errors during tests
  .changes/unreleased/Fixes-20220909-095627.yaml
  core/dbt/events/types.py
  core/dbt/task/printer.py
Labels: cla:yes

#5775 Renaming Attributes In Metric Spec
  .changes/unreleased/Breaking Changes-20220906-154521.yaml
  core/dbt/contracts/graph/metrics.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_renderer.py
  core/dbt/parser/schemas.py
  test/integration/068_partial_parsing_tests/test-files/env_var_metrics.yml
  test/integration/068_partial_parsing_tests/test-files/my_metric.yml
  test/integration/068_partial_parsing_tests/test-files/people_metrics.yml
  test/integration/068_partial_parsing_tests/test-files/people_metrics2.yml
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
  test/unit/test_yaml_renderer.py
  tests/functional/metrics/test_metric_helper_functions.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes, Team:Language, ready_for_review

#5793 Altering Window Metric Attribute To Match Freshness Tests
  .changes/unreleased/Under the Hood-20220908-180731.yaml
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  schemas/dbt/manifest/v7.json
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
  tests/functional/metrics/test_metric_deferral.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes

#5802 add a base python job helper class
  .changes/unreleased/Under the Hood-20220909-115220.yaml
  core/dbt/adapters/base/__init__.py
  core/dbt/adapters/base/impl.py
  core/dbt/include/global_project/macros/python_model/python.sql
Labels: cla:yes

#5820 Convert default selectors tests to pytest
  .changes/unreleased/Under the Hood-20220912-134000.yaml
  test/integration/073_default_selectors_tests/models/model_a.sql
  test/integration/073_default_selectors_tests/models/model_b.sql
  test/integration/073_default_selectors_tests/models/schema.yml
  test/integration/073_default_selectors_tests/seeds/model_c.csv
  test/integration/073_default_selectors_tests/test_default_selectors.py
  tests/functional/selectors/test_default_selectors.py
Labels: cla:yes

#5789 Complete CLI modeling for Click
  .changes/unreleased/Features-20220908-104149.yaml
  core/dbt/cli/README.md
  core/dbt/cli/__init__.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/setup.py
  tests/unit/test_cli.py
Labels: cla:yes

#5699 [CT-1050] convert 020_ephemeral_test
  test/integration/020_ephemeral_tests/ephemeral-errors/base/base.sql
  test/integration/020_ephemeral_tests/ephemeral-errors/base/base_copy.sql
  test/integration/020_ephemeral_tests/ephemeral-errors/dependent.sql
  test/integration/020_ephemeral_tests/models-n/ephemeral.sql
  test/integration/020_ephemeral_tests/models-n/ephemeral_level_two.sql
  test/integration/020_ephemeral_tests/models-n/root_view.sql
  test/integration/020_ephemeral_tests/models-n/source_table.sql
  test/integration/020_ephemeral_tests/models/base/base.sql
  test/integration/020_ephemeral_tests/models/base/base_copy.sql
  test/integration/020_ephemeral_tests/models/base/female_only.sql
  test/integration/020_ephemeral_tests/models/dependent.sql
  test/integration/020_ephemeral_tests/models/double_dependent.sql
  test/integration/020_ephemeral_tests/models/super_dependent.sql
  test/integration/020_ephemeral_tests/seed.sql
  test/integration/020_ephemeral_tests/test_ephemeral.py
  tests/adapter/dbt/tests/adapter/ephemeral/test_ephemeral.py
Labels: cla:yes, Skip Changelog

#5815 Add config to disable metrics/exposures
  .changes/unreleased/Features-20220913-095924.yaml
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/context/context_config.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/exceptions.py
  core/dbt/graph/selector.py
  core/dbt/parser/base.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v7.json
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/exposures/test_exposure_configs.py
  tests/functional/metrics/test_metric_configs.py
Labels: cla:yes

#5753 [CT-1100] 021_test_concurrency test conversion
  .pre-commit-config.yaml
  core/dbt/tests/util.py
  test/integration/021_concurrency_tests/models/dep.sql
  test/integration/021_concurrency_tests/models/invalid.sql
  test/integration/021_concurrency_tests/models/skip.sql
  test/integration/021_concurrency_tests/models/table_a.sql
  test/integration/021_concurrency_tests/models/table_b.sql
  test/integration/021_concurrency_tests/models/view_model.sql
  test/integration/021_concurrency_tests/models/view_with_conflicting_cascade.sql
  test/integration/021_concurrency_tests/seed.sql
  test/integration/021_concurrency_tests/test_concurrency.py
  test/integration/021_concurrency_tests/update.sql
  tests/adapter/dbt/tests/adapter/concurrency/test_concurrency.py
Labels: cla:yes, Skip Changelog

#5818 remove key as reserved keyword from test_bool_or
  .changes/unreleased/Under the Hood-20220912-190341.yaml
  tests/adapter/dbt/tests/adapter/utils/fixture_bool_or.py
Labels: cla:yes, Team:Adapters, ready_for_review

#5825 Back/fwd compatibility for renamed `metrics` attributes
  .changes/unreleased/Under the Hood-20220913-111744.yaml
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/util.py
  core/dbt/deprecations.py
  core/dbt/parser/schema_renderer.py
  tests/functional/artifacts/data/state/v4/manifest.json
  tests/functional/artifacts/data/state/v5/manifest.json
  tests/functional/artifacts/data/state/v6/manifest.json
  tests/functional/artifacts/data/state/v7/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes, Team:Language

#5850 fix multiple dbt.config.get in python model
  core/dbt/include/global_project/macros/python_model/python.sql
  core/dbt/parser/models.py
  test/unit/test_parser.py
Labels: cla:yes, Skip Changelog

#5790 Flags work with Click
  .changes/unreleased/Features-20220908-123650.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/main.py
  core/dbt/cli/option_types.py
  core/dbt/cli/params.py
  tests/unit/test_cli.py
Labels: cla:yes

#5839 remove source quoting setting in adapter tests
  .changes/unreleased/Under the Hood-20220914-193933.yaml
  tests/adapter/dbt/tests/adapter/basic/test_docs_generate.py
Labels: cla:yes, Team:Adapters, ready_for_review, support_rotation

#5845 add support for custom file ending
  core/dbt/contracts/files.py
  core/dbt/parser/sql.py
Labels: cla:yes, Skip Changelog

#5794 Add metadata env method to provider context
  .changes/unreleased/Features-20220909-204643.yaml
  core/dbt/context/providers.py
  test/unit/test_context.py
  tests/functional/context_methods/test_builtin_functions.py
Labels: cla:yes, Team:Language, ready_for_review

#5822 restrict python submission
  core/dbt/adapters/base/impl.py
  core/dbt/clients/jinja.py
  core/dbt/compilation.py
  core/dbt/context/manifest.py
  core/dbt/context/providers.py
  core/dbt/include/global_project/macros/etc/statement.sql
  core/dbt/task/run.py
  test/unit/test_context.py
Labels: cla:yes, Team:Language, Skip Changelog

#5858 Ct 1191 event history cleanup
  .changes/unreleased/Fixes-20220916-091723.yaml
  core/dbt/adapters/factory.py
  core/dbt/clients/system.py
  core/dbt/contracts/project.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/main.py
  core/dbt/parser/manifest.py
  core/dbt/task/base.py
  core/dbt/task/run_operation.py
  core/dbt/task/sql.py
  core/dbt/utils.py
  test/unit/test_events.py
  test/unit/test_flags.py
Labels: cla:yes

#5828 [CT-1101] 024_custom_schema_tests
  .gitignore
  core/dbt/tests/util.py
  test/integration/024_custom_schema_tests/custom-macros-configs/schema.sql
  test/integration/024_custom_schema_tests/custom-macros/schema.sql
  test/integration/024_custom_schema_tests/dot-models/first_schema.view_1.sql
  test/integration/024_custom_schema_tests/dot-models/second_schema.view_2.sql
  test/integration/024_custom_schema_tests/dot-models/view_3.sql
  test/integration/024_custom_schema_tests/models/view_1.sql
  test/integration/024_custom_schema_tests/models/view_2.sql
  test/integration/024_custom_schema_tests/models/view_3.sql
  test/integration/024_custom_schema_tests/package_macro_overrides/dbt_project.yml
  test/integration/024_custom_schema_tests/package_macro_overrides/macros/macros.sql
  test/integration/024_custom_schema_tests/seed.sql
  test/integration/024_custom_schema_tests/seed/first_schema.my_seed.csv
  test/integration/024_custom_schema_tests/seed/second_schema.my_agg.csv
  test/integration/024_custom_schema_tests/test_custom_schema.py
  tests/functional/schema/fixtures/macros.py
  tests/functional/schema/fixtures/sql.py
  tests/functional/schema/test_custom_schema.py
Labels: cla:yes, Skip Changelog

#5891 Manifest deserialization error with disabled models
  core/dbt/contracts/util.py
Labels: cla:yes, Skip Changelog

#5875 implement type_boolean macro
  .changes/unreleased/Features-20220919-231414.yaml
  core/dbt/adapters/base/column.py
  core/dbt/include/global_project/macros/utils/data_types.sql
  tests/adapter/dbt/tests/adapter/utils/data_types/test_type_boolean.py
Labels: cla:yes, Team:Adapters, ready_for_review

#5889 ConfigSelectorMethod should check for bools
  .changes/unreleased/Fixes-20220920-181856.yaml
  core/dbt/graph/selector_methods.py
  test/unit/test_graph_selector_methods.py
Labels: cla:yes, Team:Execution, ready_for_review

#5841 Add name validation for metrics
  .changes/unreleased/Under the Hood-20220914-132632.yaml
  core/dbt/contracts/graph/unparsed.py
  tests/functional/metrics/fixture_metrics.py
  tests/functional/metrics/test_metric_configs.py
  tests/functional/metrics/test_metric_helper_functions.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes

#5844 Validate exposure names and add label
  .changes/unreleased/Under the Hood-20220914-150058.yaml
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/deprecations.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v7.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/exposures/test_exposures.py
Labels: cla:yes, Refinement

#5892 Profiling and Adapter management work with Click
  .changes/unreleased/Under the Hood-20220920-144842.yaml
  core/dbt/adapters/factory.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
Labels: cla:yes

#5879 add optional shorthand to full refresh command
  .changes/unreleased/Features-20220919-112903.yaml
  core/dbt/cli/params.py
  core/dbt/main.py
  tests/functional/materializations/test_runtime_materialization.py
Labels: cla:yes, cli, Team:Execution, ready_for_review

#5870 Adding missing permissions on GHA
  .github/workflows/jira-transition.yml
  .github/workflows/release.yml
  .github/workflows/schema-check.yml
  .github/workflows/stale.yml
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#5897 .dbtignore
  .changes/unreleased/Features-20220921-145222.yaml
  core/dbt/clients/system.py
  core/dbt/parser/macros.py
  core/dbt/parser/read_files.py
  core/dbt/parser/search.py
  core/setup.py
  test/unit/test_graph.py
  test/unit/test_system_client.py
  tests/fixtures/jaffle_shop.py
  tests/functional/basic/test_jaffle_shop.py
Labels: cla:yes

#5906 PySpark dataframe related tests
  tests/adapter/dbt/tests/adapter/python_model/test_spark.py
Labels: cla:yes, Skip Changelog

#5908 update flag to -f
  .changes/unreleased/Fixes-20220922-083926.yaml
  core/dbt/cli/params.py
  core/dbt/main.py
  tests/functional/materializations/test_runtime_materialization.py
Labels: cla:yes, cli

#5909 update disabled metrics/exposures to use add_disabled
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  tests/functional/partial_parsing/test_pp_disabled_config.py
Labels: cla:yes, Skip Changelog

#5895 improve error message for parsing args
  core/dbt/main.py
  core/dbt/parser/models.py
  test/unit/test_parser.py
Labels: cla:yes, Skip Changelog

#5920 CT 815 partial parsing handling of deleted metrics
  .changes/unreleased/Under the Hood-20220923-133525.yaml
  core/dbt/parser/partial.py
  test/integration/068_partial_parsing_tests/test-files/metric_model_a.sql
  test/integration/068_partial_parsing_tests/test-files/people_metrics3.yml
  test/integration/068_partial_parsing_tests/test_pp_metrics.py
Labels: cla:yes

#5896 Click CLI profiles directory
  core/dbt/cli/params.py
  core/dbt/cli/resolvers.py
Labels: cla:yes, Team:Execution, Skip Changelog, ready_for_review

#5935 Tests for `current_timestamp`
  tests/adapter/dbt/tests/adapter/utils/test_current_timestamp.py
Labels: cla:yes, Skip Changelog

#5928 Test for Koalas DataFrames
  tests/adapter/dbt/tests/adapter/python_model/test_spark.py
Labels: cla:yes, Skip Changelog

#5457 merge exclude columns for incremental models
  .changes/unreleased/Features-20220716-142116.yaml
  core/dbt/include/global_project/macros/materializations/models/incremental/column_helpers.sql
  core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql
Labels: cla:yes, Team:Adapters, ready_for_review

#5823 Array macros
  .changes/unreleased/Features-20220912-222227.yaml
  core/dbt/include/global_project/macros/utils/array_append.sql
  core/dbt/include/global_project/macros/utils/array_concat.sql
  core/dbt/include/global_project/macros/utils/array_construct.sql
  tests/adapter/dbt/tests/adapter/utils/base_array_utils.py
  tests/adapter/dbt/tests/adapter/utils/fixture_array_append.py
  tests/adapter/dbt/tests/adapter/utils/fixture_array_concat.py
  tests/adapter/dbt/tests/adapter/utils/fixture_array_construct.py
  tests/adapter/dbt/tests/adapter/utils/test_array_append.py
  tests/adapter/dbt/tests/adapter/utils/test_array_concat.py
  tests/adapter/dbt/tests/adapter/utils/test_array_construct.py
Labels: cla:yes, Team:Adapters, ready_for_review

#5693 Fix typos of comments in core/dbt/adapters/
  .changes/unreleased/Fixes-20220822-194238.yaml
  core/dbt/adapters/cache.py
  core/dbt/adapters/protocol.py
Labels: cla:yes, Team:Adapters, ready_for_review

#5873 Adding metric expression validation
  .changes/unreleased/Under the Hood-20220916-154712.yaml
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes, Team:Language, metrics

#5953 Remove parsers/source.py type ignores
  core/dbt/parser/sources.py
Labels: cla:yes, Skip Changelog

#5963 Update Version Bump to include Homebrew in PATH
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#5973 Update 0.0.0.md
  .changes/0.0.0.md
Labels: Skip Changelog

#5868 Disabled Models in schema files
  .changes/unreleased/Fixes-20220916-104854.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  test/integration/068_partial_parsing_tests/test-files/models-schema4.yml
  test/integration/068_partial_parsing_tests/test-files/models-schema4b.yml
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
  tests/functional/configs/fixtures.py
  tests/functional/configs/test_disabled_model.py
Labels: cla:yes

#5838 Consolidate date macros into timestamps.sql
  .changes/unreleased/Features-20220914-095625.yaml
  .changie.yaml
  core/dbt/clients/jinja_static.py
  core/dbt/include/global_project/macros/adapters/freshness.sql
  core/dbt/include/global_project/macros/adapters/timestamps.sql
  core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql
  core/dbt/tests/util.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  plugins/postgres/dbt/include/postgres/macros/timestamps.sql
  test/unit/test_macro_calls.py
  tests/adapter/dbt/tests/adapter/utils/test_timestamps.py
Labels: cla:yes

#5979 consolidate timestamp logic
  .changes/unreleased/Features-20220914-095625.yaml
Labels: cla:yes, Skip Changelog
