Repository dbt-labs/dbt-core, pull requests merged in 2022-02, with the labels that each got.

#4644 added semver official regex pattern
  CHANGELOG.md
  core/dbt/contracts/project.py
Labels: cla:yes, ok_to_test, Team:Language

#4655 Backport 4647 to 1.0.latest
  CHANGELOG.md
  core/dbt/events/types.py
Labels: cla:yes

#4659 Chenyu l inx patch 1
  CHANGELOG.md
Labels: cla:yes

#4658 [Backport] Run check_if_can_write_profile before create_profile_using_project_pr…
  CHANGELOG.md
  core/dbt/task/init.py
Labels: cla:yes

#4616 Docker release CT-3
  .bumpversion.cfg
  .github/actions/latest-wrangler/Dockerfile
  .github/actions/latest-wrangler/README.md
  .github/actions/latest-wrangler/action.yml
  .github/actions/latest-wrangler/examples/example_workflow.yml
  .github/actions/latest-wrangler/examples/example_workflow_dispatch.json
  .github/actions/latest-wrangler/main.py
  .github/workflows/release_docker.yml
  .github/workflows/test/.actrc
  .github/workflows/test/.gitignore
  .github/workflows/test/.secrets.EXAMPLE
  .github/workflows/test/inputs/release_docker.json
  docker/Dockerfile
Labels: cla:yes

#4660 Alternative Modified Backport of #4619
  core/dbt/adapters/cache.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  test/unit/test_events.py
Labels: cla:yes

#4654 Initial file creation of code documentation READMEs
  ARCHITECTURE.md
  core/dbt/README.md
  core/dbt/adapters/README.md
  core/dbt/clients/README.md
  core/dbt/config/README.md
  core/dbt/context/README.md
  core/dbt/contracts/README.md
  core/dbt/deps/README.md
  core/dbt/graph/README.md
  core/dbt/include/README.md
  core/dbt/parser/README.md
  core/dbt/task/README.md
  test/integration/README.md
  test/unit/README.md
Labels: cla:yes

#4665 Avoid saving secrets in SecretContext
  core/dbt/context/secret.py
  test/integration/068_partial_parsing_tests/test_pp_vars.py
Labels: cla:yes

#4618 [#2479] Allow unique_id to take a list
  CHANGELOG.md
  core/dbt/contracts/graph/model_config.py
  core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql
  test/integration/029_docs_generate_tests/test_docs_generate.py
  test/integration/047_dbt_ls_tests/test_ls.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/utils.py
Labels: cla:yes

#4672 Avoid saving secrets in SecretContext (#4665)
  CHANGELOG.md
  core/dbt/context/secret.py
  test/integration/068_partial_parsing_tests/test_pp_vars.py
Labels: cla:yes

#4673 add changelog entry for #4665
  CHANGELOG.md
Labels: cla:yes

#4675 Validate project names in interactive dbt init (#4536)
  CHANGELOG.md
  core/dbt/contracts/project.py
  core/dbt/task/init.py
  test/integration/040_init_test/test_init.py
Labels: cla:yes

#4565 adapter compability messaging added.
  CHANGELOG.md
  core/dbt/version.py
  test/unit/test_version.py
Labels: cla:yes, Team:Execution

#4676 fix comparision for new model/body (#4631)
  CHANGELOG.md
  core/dbt/graph/selector_methods.py
  test/unit/test_graph_selector_methods.py
Labels: cla:yes

#4677 Chenyu/backport 4565
  CHANGELOG.md
  core/dbt/version.py
  test/unit/test_version.py
Labels: cla:yes

#4623 Set flags from args in lib module for dbt-server
  core/dbt/lib.py
Labels: cla:yes, Team:Execution

#4682 fix test to use a secret username
  test/integration/068_partial_parsing_tests/test_pp_vars.py
Labels: cla:yes

#4683 [backport] fix test to use a secret username
  test/integration/068_partial_parsing_tests/test_pp_vars.py
Labels: cla:yes

#4681 task init: support older click v7.0
  CHANGELOG.md
  core/dbt/task/init.py
  core/setup.py
Labels: cla:yes, Team:Execution

#4701 Add `--quiet` flag and `print` Jinja function
  CHANGELOG.md
  core/dbt/context/base.py
  core/dbt/events/functions.py
  core/dbt/flags.py
  core/dbt/main.py
  test/integration/044_run_operations_tests/macros/happy_macros.sql
  test/integration/044_run_operations_tests/test_run_operations.py
  test/unit/test_context.py
  test/unit/test_flags.py
Labels: cla:yes

#4639 Pre commit Hooks (black, flake8, mypy, etc) [CT-105]
  .flake8
  .github/workflows/main.yml
  .github/workflows/release.yml
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  dev-requirements.txt
  tox.ini
Labels: cla:yes

#4604 Allow override of Column string and numeric type by classes inheritin…
  CHANGELOG.md
  core/dbt/adapters/base/column.py
Labels: cla:yes, Team:Adapters

#4686 Initital pass at deps README
  CHANGELOG.md
  core/dbt/deps/README.md
Labels: cla:yes

#4727 ignore markdown files for trim-trailing-whitespace hook
  .pre-commit-config.yaml
Labels: cla:yes

#4726 Ensure meta is both at node top level and in node.config. Fix snapshots with schema config.
  CHANGELOG.md
  core/dbt/contracts/graph/parsed.py
  core/dbt/parser/snapshots.py
  test/integration/004_simple_snapshot_tests/models/schema.yml
  test/integration/039_config_tests/test_configs_in_schema_files.py
Labels: cla:yes

#4746 Pin `MarkupSafe==2.0.1`
  core/setup.py
Labels: cla:yes, backport 1.0.latest

#4749 Pin `MarkupSafe==2.0.1 (#4746)`
  CHANGELOG.md
  core/setup.py
Labels: cla:yes

#4758 Fix bug accessing target in deps and clean commands
  CHANGELOG.md
  core/dbt/config/runtime.py
  core/dbt/helper_types.py
  test/integration/006_simple_dependency_tests/test_simple_dependency.py
Labels: cla:yes

#4759 [Backport] Fix bug accessing target in deps and clean commands
  CHANGELOG.md
  core/dbt/config/runtime.py
  core/dbt/helper_types.py
  test/integration/006_simple_dependency_test/test_simple_dependency.py
Labels: cla:yes

#4521 Deduplicate postgres relations (#3058)
  CHANGELOG.md
  plugins/postgres/dbt/include/postgres/macros/relations.sql
Labels: cla:yes, Team:Adapters

#4545 Fixed misspellings, typos, and duplicated words
  CHANGELOG.md
  core/dbt/adapters/sql/impl.py
  core/dbt/clients/agate_helper.py
  core/dbt/clients/jinja.py
  core/dbt/clients/system.py
  core/dbt/context/providers.py
  core/dbt/contracts/connection.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/dataclass_schema.py
  core/dbt/exceptions.py
  core/dbt/flags.py
  core/dbt/graph/selector_spec.py
  core/dbt/logger.py
  core/dbt/main.py
  core/dbt/parser/manifest.py
  core/dbt/task/generate.py
  core/dbt/utils.py
  test/integration/015_cli_invocation_tests/test_cli_invocation.py
  test/integration/073_default_selectors_tests/test_default_selectors.py
Labels: cla:yes

#4774 [Backport] Fix bug causing empty node level meta, snapshot config errors
  CHANGELOG.md
  core/dbt/contracts/graph/parsed.py
  core/dbt/parser/snapshots.py
  test/integration/004_simple_snapshot_test/models/schema.yml
  test/integration/039_config_test/test_configs_in_schema_files.py
Labels: cla:yes

#4779 update flake8 to remove line length req
  .flake8
Labels: cla:yes

#4773 Fix "dbt found two resources" error with multiple snapshot blocks in one file
  CHANGELOG.md
  core/dbt/parser/partial.py
  test/integration/068_partial_parsing_tests/test-files/snapshot.sql
  test/integration/068_partial_parsing_tests/test-files/snapshot2.sql
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
Labels: cla:yes

#4767 Fix errors on Windows tests in new tests/functional
  CHANGELOG.md
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  tests/fixtures/jaffle_shop.py
  tests/functional/basic/test_copy_uppercase.py
  tests/functional/basic/test_simple_copy.py
  tests/functional/basic/test_simple_reference.py
Labels: cla:yes, test windows, test all

#4783 rewrite graph selection
  test/integration/007_graph_selection_tests/.gitkeep
  test/integration/007_graph_selection_tests/models/alternative.users.sql
  test/integration/007_graph_selection_tests/models/base_users.sql
  test/integration/007_graph_selection_tests/models/emails.sql
  test/integration/007_graph_selection_tests/models/emails_alt.sql
  test/integration/007_graph_selection_tests/models/never_selected.sql
  test/integration/007_graph_selection_tests/models/schema.yml
  test/integration/007_graph_selection_tests/models/test/subdir.sql
  test/integration/007_graph_selection_tests/models/test/subdir/nested_users.sql
  test/integration/007_graph_selection_tests/models/users.sql
  test/integration/007_graph_selection_tests/models/users_rollup.sql
  test/integration/007_graph_selection_tests/models/users_rollup_dependency.sql
  test/integration/007_graph_selection_tests/seed.sql
  test/integration/007_graph_selection_tests/test_graph_selection.py
  test/integration/007_graph_selection_tests/test_intersection_syntax.py
  test/integration/007_graph_selection_tests/test_schema_test_graph_selection.py
  test/integration/007_graph_selection_tests/test_tag_selection.py
  tests/functional/graph_selection/data/seed.csv
  tests/functional/graph_selection/data/summary_expected.csv
  tests/functional/graph_selection/fixtures.py
  tests/functional/graph_selection/test_graph_selection.py
  tests/functional/graph_selection/test_intersection_syntax.py
  tests/functional/graph_selection/test_schema_test_graph_selection.py
  tests/functional/graph_selection/test_tag_selection.py
Labels: cla:yes

#4763 updated index file to fix DAG errors for operations & work around null columns
  CHANGELOG.md
  core/dbt/include/index.html
Labels: cla:yes

#4795 ct-237 test conversion 002_varchar_widening_tests
  test/integration/002_varchar_widening_tests/models/incremental.sql
  test/integration/002_varchar_widening_tests/models/materialized.sql
  test/integration/002_varchar_widening_tests/test_varchar_widening.py
  tests/functional/basic/data/varchar10_seed.sql
  tests/functional/basic/data/varchar300_seed.sql
  tests/functional/basic/test_varchar_widening.py
Labels: cla:yes

#4791 add coverage
  dev-requirements.txt
  tox.ini
Labels: cla:yes

#4797 [backport] updated index file to fix DAG errors for operations & work…
  CHANGELOG.md
  core/dbt/include/index.html
Labels: cla:yes
