Repository dbt-labs/dbt-core, pull requests merged in 2022-06, with the labels that each got.

#5320 fix pip upgrade step in CI for windows
  .changes/unreleased/Under the Hood-20220601-105245.yaml
  .github/workflows/main.yml
  Makefile
Labels: cla:yes

#5324 CT-710 fix test graph selection
  .changes/unreleased/Under the Hood-20220601-112648.yaml
  core/dbt/graph/selector_spec.py
  test/unit/test_graph_selection.py
Labels: cla:yes

#5326 New ancestor/descendant algo
  .changes/unreleased/Fixes-20220601-135908.yaml
  core/dbt/graph/graph.py
Labels: cla:yes

#5334 Update context README
  .changes/unreleased/Under the Hood-20220606-230353.yaml
  core/dbt/config/renderer.py
  core/dbt/context/README.md
  core/dbt/context/base.py
  core/dbt/context/secret.py
Labels: cla:yes

#5335 Backports: networkx, context cleanup
  .changes/unreleased/Dependencies-20220606-234258.yaml
  .changes/unreleased/Under the Hood-20220606-230353.yaml
  core/dbt/config/renderer.py
  core/dbt/context/README.md
  core/dbt/context/base.py
  core/dbt/context/secret.py
  core/setup.py
Labels: cla:yes

#5304 Remove duplicate dbt script entry
  .changes/unreleased/Fixes-20220601-081314.yaml
  core/scripts/dbt
  core/setup.py
Labels: cla:yes, Team:Execution

#5355 [Backport] fix pip upgrade step in CI for windows for 1.0.latest
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/version-bump.yml
Labels: cla:yes, test all, Skip Changelog

#5345 python model adr
  docs/arch/adr-004-python-model-arch.md
Labels: cla:yes, Skip Changelog

#5264 require lower version of networkx in py37
  core/setup.py
Labels: cla:yes, Skip Changelog

#5349 Adding scheduled CI testing Action
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#5376 Backport #5334 to 1.0.latest
  .changes/unreleased/Under the Hood-20220606-230353.yaml
  core/dbt/config/renderer.py
  core/dbt/context/README.md
  core/dbt/context/base.py
  core/dbt/context/secret.py
Labels: cla:yes

#5332 Adapters README (doc days of winter)
  core/dbt/adapters/README.md
Labels: cla:yes, Skip Changelog

#5383 Backport #5346 to 1.1.latest
  .changes/unreleased/Fixes-20220608-080914.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/util.py
  tests/functional/artifacts/data/previous/v1/manifest.json
  tests/functional/artifacts/data/previous/v2/manifest.json
  tests/functional/artifacts/data/previous/v3/manifest.json
  tests/functional/artifacts/data/previous/v4/manifest.json
  tests/functional/artifacts/data/previous/v5/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes

#5117 deleting scaffold and create_adater_plugin.py file from scripts section of core as they a…
  .changes/unreleased/Under the Hood-20220420-120025.yaml
  core/scripts/create_adapter_plugins.py
Labels: cla:yes

#5366 Early return from dbt init if no available adapters
  .changes/unreleased/Features-20220614-082051.yaml
  core/dbt/task/init.py
  test/integration/040_init_tests/test_init.py
Labels: cla:yes, Team:Execution, awaiting_response

#5403 [Fix]: remove duplicate key checking
  .changes/unreleased/Fixes-20220623-082431.yaml
  core/dbt/clients/yaml_helper.py
  tests/functional/duplications/test_basic_duplications.py
Labels: cla:yes

#5405 Removing old script from bumpversion
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#5391 Ct 488/migrate invalid model tests
  test/integration/006_simple_dependency_tests/hook_models/actual.sql
  test/integration/006_simple_dependency_tests/hook_models/expected.sql
  test/integration/006_simple_dependency_tests/macros/main_macro.sql
  test/integration/006_simple_dependency_tests/macros_schema_override/schema.sql
  test/integration/006_simple_dependency_tests/models/.gitkeep
  test/integration/006_simple_dependency_tests/models/disabled_one.sql
  test/integration/006_simple_dependency_tests/models/disabled_two.sql
  test/integration/006_simple_dependency_tests/models/empty.sql
  test/integration/006_simple_dependency_tests/models/view_summary.sql
  test/integration/006_simple_dependency_tests/models_missing_dependency/iterate.sql
  test/integration/006_simple_dependency_tests/test_local_dependency.py
  test/integration/006_simple_dependency_tests/test_simple_dependency.py
  test/integration/006_simple_dependency_tests/test_simple_dependency_with_configs.py
  tests/functional/dependencies/data/seed.sql
  tests/functional/dependencies/data/update.sql
  tests/functional/dependencies/duplicate_dependency/dbt_project.yml
  tests/functional/dependencies/early_hook_dependency/dbt_project.yml
  tests/functional/dependencies/late_hook_dependency/dbt_project.yml
  tests/functional/dependencies/local_dependency/dbt_project.yml
  tests/functional/dependencies/local_dependency/macros/dep_macro.sql
  tests/functional/dependencies/local_dependency/macros/generate_schema_name.sql
  tests/functional/dependencies/local_dependency/models/model_to_import.sql
  tests/functional/dependencies/local_dependency/models/schema.yml
  tests/functional/dependencies/local_dependency/seeds/seed.csv
  tests/functional/dependencies/models_local/dep_source_model.sql
  tests/functional/dependencies/models_local/my_configured_model.sql
  tests/functional/dependencies/models_local/my_model.sql
  tests/functional/dependencies/models_local/schema.yml
  tests/functional/dependencies/models_local/source_override_model.sql
  tests/functional/dependencies/test_local_dependency.py
  tests/functional/dependencies/test_simple_dependency.py
  tests/functional/dependencies/test_simple_dependency_with_configs.py
Labels: cla:yes, Skip Changelog

#5414 Backport #5382 to 1.0.latest
  .changes/unreleased/Under the Hood-20220616-120516.yaml
  .changie.yaml
  core/dbt/config/renderer.py
  test/integration/013_context_var_tests/test_context_vars.py
Labels: cla:yes

#5415 Backport #5382 to 1.1.latest
  .changes/unreleased/Under the Hood-20220616-120516.yaml
  .changie.yaml
  core/dbt/config/renderer.py
  test/integration/013_context_var_tests/test_context_vars.py
Labels: cla:yes

#5394 [CT-679] flip logic around reset color detection
  .changes/unreleased/Fixes-20220617-160027.yaml
  core/dbt/events/functions.py
Labels: cla:yes, Team:Language, ready_for_review

#5356 Improve pluralizations for Documentation and SqlOperation NodeTypes
  .changes/unreleased/Fixes-20220609-115246.yaml
  core/dbt/node_types.py
  test/unit/test_node_types.py
Labels: cla:yes, ok_to_test, Team:Language, ready_for_review
