Repository dbt-labs/dbt-core, pull requests merged in 2022-07, with the labels that each got.

#5430 Bumping manifest version to v6
  .changes/unreleased/Under the Hood-20220705-142120.yaml
  core/dbt/contracts/graph/manifest.py
  schemas/dbt/manifest/v6.json
  test/unit/test_manifest.py
  tests/functional/artifacts/expected_manifest.py
Labels: cla:yes

#5370 feature/deps-regex-semver
  .changes/unreleased/Under the Hood-20220613-170703.yaml
  core/dbt/semver.py
  test/unit/test_semver.py
Labels: cla:yes, ok_to_test, Team:Language, ready_for_review

#5348 Add inheritance to materialization macro resolution
  .changes/unreleased/Fixes-20220608-104251.yaml
  core/dbt/contracts/graph/manifest.py
  test/unit/test_manifest.py
Labels: cla:yes, ok_to_test, Team:Language, Team:Adapters, awaiting_response

#5440 Clean up test_previous_version_state, update for v6
  tests/functional/artifacts/data/state/v1/manifest.json
  tests/functional/artifacts/data/state/v2/manifest.json
  tests/functional/artifacts/data/state/v3/manifest.json
  tests/functional/artifacts/data/state/v4/manifest.json
  tests/functional/artifacts/data/state/v5/manifest.json
  tests/functional/artifacts/data/state/v6/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes, Skip Changelog

#5027 (#4884) Add support for ratio metrics
  .changes/unreleased/Features-20220705-083026.yaml
  .changes/unreleased/Under the Hood-20220705-142120.yaml
  core/dbt/compilation.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/metrics.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/contracts/util.py
  core/dbt/exceptions.py
  core/dbt/main.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_renderer.py
  core/dbt/parser/schemas.py
  core/dbt/task/init.py
  schemas/dbt/manifest/v6.json
  test/unit/test_context.py
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_manifest.py
  test/unit/utils.py
  tests/functional/artifacts/data/state/v1/manifest.json
  tests/functional/artifacts/data/state/v2/manifest.json
  tests/functional/artifacts/data/state/v3/manifest.json
  tests/functional/artifacts/data/state/v4/manifest.json
  tests/functional/artifacts/data/state/v5/manifest.json
  tests/functional/artifacts/data/state/v6/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_previous_version_state.py
  tests/functional/metrics/fixture_metrics.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes, Team:Language

#5446 add new index file for dbt-docs for 1.2.0 release
  .changes/unreleased/Docs-20220706-142029.yaml
  .changes/unreleased/Docs-20220706-142142.yaml
  .changes/unreleased/Docs-20220706-142226.yaml
  .changes/unreleased/Docs-20220706-142300.yaml
  .changes/unreleased/Docs-20220706-142410.yaml
  .changes/unreleased/Docs-20220706-142505.yaml
  core/dbt/include/index.html
Labels: cla:yes

#5402 Add `--target-path` CLI flag
  .changes/unreleased/Features-20220622-192329.yaml
  core/dbt/config/project.py
  core/dbt/flags.py
  core/dbt/main.py
  test/integration/075_custom_target_path/models/do_nothing_1.sql
  test/integration/075_custom_target_path/models/do_nothing_2.sql
  test/integration/075_custom_target_path/models/do_nothing_3.sql
  test/integration/075_custom_target_path/test_target_path.py
  test/unit/test_flags.py
Labels: cla:yes

#5447 CT-808 grant adapter tests
  .changes/unreleased/Under the Hood-20220706-215001.yaml
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
  core/dbt/adapters/base/impl.py
  core/dbt/include/global_project/macros/adapters/apply_grants.sql
  core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql
  core/dbt/parser/manifest.py
  core/dbt/tests/util.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  test/setup_db.sh
  tests/adapter/dbt/tests/adapter/grants/test_models.py
  tests/functional/configs/test_grant_configs.py
Labels: cla:yes

#5369 Add Grant SQL Macros
  .changes/unreleased/Features-20220711-111514.yaml
  .changes/unreleased/Under the Hood-20220706-215001.yaml
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
  core/dbt/adapters/base/impl.py
  core/dbt/context/base.py
  core/dbt/include/global_project/macros/adapters/apply_grants.sql
  core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql
  core/dbt/include/global_project/macros/materializations/models/table/table.sql
  core/dbt/include/global_project/macros/materializations/models/view/create_or_replace_view.sql
  core/dbt/include/global_project/macros/materializations/models/view/view.sql
  core/dbt/include/global_project/macros/materializations/seeds/seed.sql
  core/dbt/include/global_project/macros/materializations/snapshots/snapshot.sql
  core/dbt/parser/manifest.py
  core/dbt/tests/util.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  test/setup_db.sh
  test/unit/test_context.py
  tests/adapter/dbt/tests/adapter/grants/base_grants.py
  tests/adapter/dbt/tests/adapter/grants/test_incremental_grants.py
  tests/adapter/dbt/tests/adapter/grants/test_invalid_grants.py
  tests/adapter/dbt/tests/adapter/grants/test_model_grants.py
  tests/adapter/dbt/tests/adapter/grants/test_seed_grants.py
  tests/adapter/dbt/tests/adapter/grants/test_snapshot_grants.py
  tests/functional/configs/test_grant_configs.py
Labels: cla:yes

#5470 Test/partial parsing python
  test/unit/test_partial_parsing.py
Labels: cla:yes, Skip Changelog

#5477 Fix: Rename try methods to strict
  .changes/unreleased/Fixes-20220715-231148.yaml
  core/dbt/context/base.py
  test/unit/test_context.py
  tests/functional/context_methods/test_builtin_functions.py
Labels: cla:yes, backport 1.2.latest

#5478 Fix: Rename try methods to strict (#5477)
  .changes/unreleased/Fixes-20220715-231148.yaml
  core/dbt/context/base.py
  test/unit/test_context.py
  tests/functional/context_methods/test_builtin_functions.py
Labels: cla:yes

#5432 [CT-472] feat: Retrying method for acquiring connection handles
  .changes/unreleased/Features-20220715-035555.yaml
  core/dbt/adapters/base/connections.py
  plugins/postgres/dbt/adapters/postgres/connections.py
  test/unit/test_adapter_connection_manager.py
Labels: cla:yes, Team:Adapters, ready_for_review

#5494 [Backport 1.2.lastest] Retrying method for acquiring connection handles (#5432)
  .changes/unreleased/Features-20220715-035555.yaml
  core/dbt/adapters/base/connections.py
  plugins/postgres/dbt/adapters/postgres/connections.py
  test/unit/test_adapter_connection_manager.py
Labels: cla:yes

#5118 Bump mashumaro from 2.9 to 3.0.3 in /core
  .changes/unreleased/Under the Hood-20220720-115226.yaml
  core/dbt/contracts/graph/manifest.py
  core/setup.py
  third-party-stubs/mashumaro/__init__.pyi
  third-party-stubs/mashumaro/config.pyi
  third-party-stubs/mashumaro/core/__init__.pyi
  third-party-stubs/mashumaro/core/const.pyi
  third-party-stubs/mashumaro/core/helpers.pyi
  third-party-stubs/mashumaro/core/meta/__init__.pyi
  third-party-stubs/mashumaro/core/meta/builder.pyi
  third-party-stubs/mashumaro/core/meta/helpers.pyi
  third-party-stubs/mashumaro/core/meta/patch.pyi
  third-party-stubs/mashumaro/dialect.pyi
  third-party-stubs/mashumaro/dialects/__init__.pyi
  third-party-stubs/mashumaro/dialects/msgpack.pyi
  third-party-stubs/mashumaro/exceptions.pyi
  third-party-stubs/mashumaro/helper.pyi
  third-party-stubs/mashumaro/meta/helpers.pyi
  third-party-stubs/mashumaro/meta/macros.pyi
  third-party-stubs/mashumaro/mixins/__init__.pyi
  third-party-stubs/mashumaro/mixins/dict.pyi
  third-party-stubs/mashumaro/mixins/json.pyi
  third-party-stubs/mashumaro/mixins/msgpack.pyi
  third-party-stubs/mashumaro/mixins/yaml.pyi
  third-party-stubs/mashumaro/serializer/base/__init__.pyi
  third-party-stubs/mashumaro/serializer/base/dict.pyi
  third-party-stubs/mashumaro/serializer/base/helpers.pyi
  third-party-stubs/mashumaro/serializer/base/metaprogramming.pyi
  third-party-stubs/mashumaro/serializer/json.pyi
  third-party-stubs/mashumaro/serializer/msgpack.pyi
  third-party-stubs/mashumaro/serializer/yaml.pyi
  third-party-stubs/mashumaro/types.pyi
Labels: cla:yes

#5479 snyk automation plus bot changelog consolidation
  .changie.yaml
  .github/workflows/bot-changelog.yml
  .github/workflows/dependency-changelog.yml
Labels: cla:yes, Skip Changelog

#5503 postgres: add exponential backoff to connection retries
  .changes/unreleased/Features-20220720-171257.yaml
  plugins/postgres/dbt/adapters/postgres/connections.py
Labels: cla:yes

#5359 Initial refactoring of incremental materialization
  .changes/unreleased/Features-20220610-105647.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql
  core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql
  core/dbt/include/global_project/macros/materializations/models/incremental/strategies.sql
  plugins/postgres/dbt/adapters/postgres/impl.py
  plugins/postgres/dbt/include/postgres/macros/materializations/incremental_strategies.sql
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/materializations/test_incremental.py
Labels: cla:yes

#5508 reformat changie.yaml to ignore dependabot
  .changie.yaml
Labels: cla:yes, Skip Changelog

#5512 add model_language to run
  core/dbt/task/run.py
Labels: cla:yes, Skip Changelog

#5511 validate python model args
  core/dbt/parser/models.py
  test/unit/test_parser.py
  tests/adapter/dbt/tests/adapter/python_model/test_python_model.py
Labels: cla:yes, Skip Changelog

#5510 A decorator for log code execution
  core/dbt/adapters/base/impl.py
  core/dbt/events/types.py
  core/dbt/task/runnable.py
  test/unit/test_events.py
  tests/adapter/dbt/tests/adapter/python_model/test_python_model.py
Labels: cla:yes, Skip Changelog

#5507 Remove markupsafe pin
  .changes/unreleased/Dependencies-20220721-093233.yaml
  core/setup.py
Labels: cla:yes

#5487 add readme to .github
  .github/README.md
Labels: cla:yes, Skip Changelog

#5469 Add language to tracked fields in run_model
  .changes/unreleased/Under the Hood-20220713-124925.yaml
  core/dbt/task/run.py
  core/dbt/tracking.py
Labels: cla:yes

#5499 Proper internal representation option 1
  core/dbt/adapters/base/impl.py
  core/dbt/compilation.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/compiled.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/sql.py
  core/dbt/contracts/util.py
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/include/global_project/macros/materializations/snapshots/snapshot.sql
  core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql
  core/dbt/main.py
  core/dbt/parser/base.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/macros.py
  core/dbt/parser/models.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sql.py
  core/dbt/task/run.py
  core/dbt/task/sql.py
  core/dbt/utils.py
  schemas/dbt/manifest/v7.json
  test/integration/015_cli_invocation_tests/test_cli_invocation.py
  test/integration/033_event_tracking_tests/test_events.py
  test/integration/062_defer_state_tests/test_defer_state.py
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
  test/unit/test_compiler.py
  test/unit/test_context.py
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_events.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
  test/unit/test_parser.py
  test/unit/test_partial_parsing.py
  test/unit/utils.py
  tests/functional/artifacts/data/state/v6/manifest.json
  tests/functional/artifacts/data/state/v7/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/artifacts/test_previous_version_state.py
  tests/functional/list/test_list.py
  tests/functional/metrics/test_metrics.py
  tests/functional/schema_tests/test_schema_v2_tests.py
  tests/functional/source_overrides/test_simple_source_override.py
  tests/functional/sources/test_source_fresher_state.py
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes, Skip Changelog

#5393 Improve CompilationException messaging for generic test Jinja rendering
  .changes/unreleased/Under the Hood-20220617-150744.yaml
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/schemas.py
  tests/functional/schema_tests/fixtures.py
  tests/functional/schema_tests/test_schema_v2_tests.py
Labels: cla:yes, Team:Language, ready_for_review

#5518 [CT-700] [Bug] Logging tons of asterisks for sensitive env vars
  .changes/unreleased/Fixes-20220723-215330.yaml
  core/dbt/events/functions.py
Labels: cla:yes, Team:Language, ready_for_review

#5560 Fix handling of top-level exceptions
  .changes/unreleased/Fixes-20220726-113636.yaml
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/test_types.py
  core/dbt/events/types.py
  core/dbt/main.py
Labels: cla:yes

#5571 Add python incremental materialization test
  .changes/unreleased/Under the Hood-20220728-094536.yaml
  tests/adapter/dbt/tests/adapter/python_model/test_python_model.py
Labels: cla:yes

#5563 Add changelog and whitespace fix to version bump Action
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#5573 [Backport 1.1.latest] Add changelog and whitespace fix to version bump Action
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#5577 add changelog from dbt-docs
  .changes/unreleased/Docs-20220728-140258.yaml
  .changes/unreleased/Docs-20220728-140329.yaml
  .changes/unreleased/Docs-20220728-140351.yaml
  .changes/unreleased/Docs-20220728-140425.yaml
  .changes/unreleased/Docs-20220728-140449.yaml
  .changes/unreleased/Docs-20220728-140620.yaml
  .changes/unreleased/Docs-20220728-140806.yaml
  .changes/unreleased/Features-20220510-165130.yaml
  .changes/unreleased/Under the Hood-20220713-124925.yaml
Labels: cla:yes

#5576 add info on basics of using actions
  .github/README.md
Labels: cla:yes, Skip Changelog

#5295 use MethodName.File when value ends with .py
  .changes/unreleased/Features-20220526-165323.yaml
  core/dbt/graph/selector_spec.py
  test/unit/test_graph_selector_methods.py
Labels: cla:yes, Team:Execution

#5580 fix passing in Rlock error in rpc
  core/dbt/task/runnable.py
Labels: cla:yes, Skip Changelog

#5515 Convert git deps to local, faster tests
  tests/fixtures/dbt_integration_project.py
  tests/functional/context_methods/test_cli_vars.py
  tests/functional/graph_selection/test_schema_test_graph_selection.py
  tests/functional/schema_tests/test_schema_v2_tests.py
Labels: cla:yes, Skip Changelog
