Repository dbt-labs/dbt-core, pull requests merged in 2022-11, with the labels that each got.

#6105 converting 023_exit_codes_tests
  test/integration/023_exit_codes_tests/models/bad.sql
  test/integration/023_exit_codes_tests/models/dupe.sql
  test/integration/023_exit_codes_tests/models/good.sql
  test/integration/023_exit_codes_tests/models/schema.yml
  test/integration/023_exit_codes_tests/seeds-bad/data.csv
  test/integration/023_exit_codes_tests/seeds-good/data.csv
  test/integration/023_exit_codes_tests/snapshots-bad/b.sql
  test/integration/023_exit_codes_tests/snapshots-good/g.sql
  test/integration/023_exit_codes_tests/test_exit_codes.py
  tests/CONVERTING.md
  tests/functional/exit_codes/fixtures.py
  tests/functional/exit_codes/test_exit_codes.py
Labels: cla:yes, Skip Changelog

#6197 Default timegrains to all
  core/dbt/parser/manifest.py
Labels: cla:yes

#6204 Add python version to main workflow and upgrade action
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#6210 [backport 1.2.latest] add python version and upgrade action (#6204)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#6192 add typing to DepsTask.run
  core/dbt/deps/base.py
  core/dbt/events/types.py
  core/dbt/task/deps.py
  tests/unit/test_events.py
Labels: cla:yes, Skip Changelog

#6209 [backport 1.1.latest] add python version and upgrade action (#6204)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#6202 Updates lib to use new profile name functionality
  .changes/unreleased/Features-20221102-150003.yaml
  core/dbt/lib.py
Labels: cla:yes

#6174 Combine various print result log events with different levels
  .changes/unreleased/Under the Hood-20221028-110344.yaml
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/task/base.py
  core/dbt/task/freshness.py
  core/dbt/task/run.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  core/dbt/task/snapshot.py
  core/dbt/task/test.py
  tests/unit/test_events.py
  tests/unit/test_proto_events.py
Labels: cla:yes

#6172 CT 1443 remove root path
  .changes/unreleased/Under the Hood-20221028-104837.yaml
  core/dbt/context/providers.py
  core/dbt/contracts/graph/compiled.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/util.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/base.py
  core/dbt/parser/docs.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/macros.py
  core/dbt/parser/schemas.py
  core/dbt/parser/seeds.py
  core/dbt/parser/sources.py
  core/dbt/parser/sql.py
  schemas/dbt/manifest/v8.json
  test/unit/test_compiler.py
  test/unit/test_context.py
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_docs_blocks.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
  test/unit/test_parser.py
  test/unit/test_partial_parsing.py
  test/unit/utils.py
  tests/functional/artifacts/data/state/v8/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes

#6059 properly track hook running
  .changes/unreleased/Fixes-20221107-095314.yaml
  core/dbt/contracts/results.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
Labels: cla:yes

#6226 Convert threading tests to pytest
  .changes/unreleased/Under the Hood-20221108-074550.yaml
  test/integration/031_thread_count_tests/models/.gitkeep
  test/integration/031_thread_count_tests/models/do_nothing_1.sql
  test/integration/031_thread_count_tests/models/do_nothing_10.sql
  test/integration/031_thread_count_tests/models/do_nothing_11.sql
  test/integration/031_thread_count_tests/models/do_nothing_12.sql
  test/integration/031_thread_count_tests/models/do_nothing_13.sql
  test/integration/031_thread_count_tests/models/do_nothing_14.sql
  test/integration/031_thread_count_tests/models/do_nothing_15.sql
  test/integration/031_thread_count_tests/models/do_nothing_16.sql
  test/integration/031_thread_count_tests/models/do_nothing_17.sql
  test/integration/031_thread_count_tests/models/do_nothing_18.sql
  test/integration/031_thread_count_tests/models/do_nothing_19.sql
  test/integration/031_thread_count_tests/models/do_nothing_2.sql
  test/integration/031_thread_count_tests/models/do_nothing_20.sql
  test/integration/031_thread_count_tests/models/do_nothing_3.sql
  test/integration/031_thread_count_tests/models/do_nothing_4.sql
  test/integration/031_thread_count_tests/models/do_nothing_5.sql
  test/integration/031_thread_count_tests/models/do_nothing_6.sql
  test/integration/031_thread_count_tests/models/do_nothing_7.sql
  test/integration/031_thread_count_tests/models/do_nothing_8.sql
  test/integration/031_thread_count_tests/models/do_nothing_9.sql
  test/integration/031_thread_count_tests/test_thread_count.py
  tests/functional/threading/test_thread_count.py
Labels: cla:yes

#6230 Convert color tests to pytest
  .changes/unreleased/Under the Hood-20221108-133104.yaml
  test/integration/061_use_colors_tests/models/do_nothing_then_fail.sql
  test/integration/061_use_colors_tests/test_no_use_colors.py
  test/integration/061_use_colors_tests/test_use_colors.py
  tests/functional/colors/test_colors.py
Labels: cla:yes

#6228 Convert postgres index tests
  .changes/unreleased/Under the Hood-20221108-115633.yaml
  test/integration/065_postgres_index_tests/models-invalid/invalid_columns_type.sql
  test/integration/065_postgres_index_tests/models-invalid/invalid_type.sql
  test/integration/065_postgres_index_tests/models-invalid/invalid_unique_config.sql
  test/integration/065_postgres_index_tests/models-invalid/missing_columns.sql
  test/integration/065_postgres_index_tests/models/incremental.sql
  test/integration/065_postgres_index_tests/models/table.sql
  test/integration/065_postgres_index_tests/seeds/seed.csv
  test/integration/065_postgres_index_tests/snapshots/colors.sql
  test/integration/065_postgres_index_tests/test_postgres_indexes.py
  tests/functional/postgres/fixtures.py
  tests/functional/postgres/test_postgres_indexes.py
Labels: cla:yes

#6122 converting 044_test_run_operations
  test/integration/044_run_operations_tests/macros/sad_macros.sql
  test/integration/044_run_operations_tests/models/model.sql
  test/integration/044_run_operations_tests/test_run_operations.py
  tests/functional/run_operations/fixtures.py
  tests/functional/run_operations/test_run_operations.py
Labels: cla:yes, ci/cd, tech_debt, Skip Changelog

#6125 [CT-1262] Convert dbt_debug
  test/integration/049_dbt_debug_tests/models/model.sql
  test/integration/049_dbt_debug_tests/test_debug.py
  tests/adapter/dbt/tests/adapter/dbt_debug/test_dbt_debug.py
Labels: cla:yes, Skip Changelog

#6252 s/gitlab/github for flake8 precommit repo
  .pre-commit-config.yaml
Labels: cla:yes, Skip Changelog

#6267 Backport dbt-docs changes to 1.3.latest
  .changes/unreleased/Docs-20221017-171411.yaml
  .changes/unreleased/Docs-20221116-155743.yaml
  core/dbt/include/index.html
Labels: cla:yes

#6281 Revert "Bump python from 3.10.7-slim-bullseye to 3.11.0-slim-bullseye in /docker"
  .changes/unreleased/Dependency-20221031-000329.yaml
  docker/Dockerfile
Labels: cla:yes, Skip Changelog

#6298 add back in conditional node length check
  core/dbt/graph/selector.py
Labels: cla:yes, Skip Changelog

#6293 CT 1537 fix event test and rename a couple of fields
  core/dbt/adapters/base/connections.py
  core/dbt/context/base.py
  core/dbt/events/README.md
  core/dbt/events/proto_types.py
  core/dbt/events/test_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/task/seed.py
  tests/unit/test_events.py
  tests/unit/test_proto_events.py
Labels: cla:yes, Skip Changelog

#6260 DepsTask with Click
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/config/project.py
  core/dbt/deps/git.py
  core/dbt/deps/local.py
  core/dbt/deps/resolver.py
  core/dbt/task/base.py
  core/dbt/task/clean.py
  core/dbt/task/debug.py
  core/dbt/task/deps.py
  core/dbt/task/init.py
  core/dbt/tracking.py
  test/unit/test_deps.py
Labels: cla:yes, Skip Changelog

#6247 BaseContext: expose md5 function in context
  .changes/unreleased/Features-20221114-185207.yaml
  core/dbt/context/base.py
  test/unit/test_context.py
Labels: cla:yes, Team:Language, ready_for_review

#6305 Convert test 067.
  test/integration/067_store_test_failures_tests/models/fine_model.sql
  test/integration/067_store_test_failures_tests/models/fine_model_but_with_a_no_good_very_long_name.sql
  test/integration/067_store_test_failures_tests/models/problematic_model.sql
  test/integration/067_store_test_failures_tests/models/schema.yml
  test/integration/067_store_test_failures_tests/seeds/expected/expected_accepted_values.csv
  test/integration/067_store_test_failures_tests/seeds/expected/expected_failing_test.csv
  test/integration/067_store_test_failures_tests/seeds/expected/expected_not_null_problematic_model_id.csv
  test/integration/067_store_test_failures_tests/seeds/expected/expected_unique_problematic_model_id.csv
  test/integration/067_store_test_failures_tests/seeds/people.csv
  test/integration/067_store_test_failures_tests/test_store_test_failures.py
  test/integration/067_store_test_failures_tests/tests/failing_test.sql
  test/integration/067_store_test_failures_tests/tests/passing_test.sql
  tests/functional/store_test_failures_tests/fixtures.py
  tests/functional/store_test_failures_tests/test_store_test_failures.py
Labels: cla:yes, Skip Changelog

#6258 Update to use the shared stale bot Action
  .github/workflows/stale.yml
Labels: cla:yes, Skip Changelog

#6187 Add GHA workflow to build CLI API docs
  .changes/unreleased/Under the Hood-20221116-130037.yaml
  .github/workflows/generate-cli-api-docs.yml
  .gitignore
  .pre-commit-config.yaml
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/docs/build/html/.buildinfo
  core/dbt/docs/build/html/_sources/index.rst.txt
  core/dbt/docs/build/html/_static/_sphinx_javascript_frameworks_compat.js
  core/dbt/docs/build/html/_static/alabaster.css
  core/dbt/docs/build/html/_static/basic.css
  core/dbt/docs/build/html/_static/custom.css
  core/dbt/docs/build/html/_static/doctools.js
  core/dbt/docs/build/html/_static/documentation_options.js
  core/dbt/docs/build/html/_static/file.png
  core/dbt/docs/build/html/_static/jquery-3.6.0.js
  core/dbt/docs/build/html/_static/jquery.js
  core/dbt/docs/build/html/_static/language_data.js
  core/dbt/docs/build/html/_static/minus.png
  core/dbt/docs/build/html/_static/plus.png
  core/dbt/docs/build/html/_static/pygments.css
  core/dbt/docs/build/html/_static/searchtools.js
  core/dbt/docs/build/html/_static/sphinx_highlight.js
  core/dbt/docs/build/html/_static/underscore-1.13.1.js
  core/dbt/docs/build/html/_static/underscore.js
  core/dbt/docs/build/html/genindex.html
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/objects.inv
  core/dbt/docs/build/html/search.html
  core/dbt/docs/build/html/searchindex.js
  core/dbt/docs/source/conf.py
Labels: cla:yes

#6304 Ct 1518/convert 063 relation names tests
  test/integration/063_relation_name_tests/models/my_name_is_51_characters_incremental_abcdefghijklmn.sql
  test/integration/063_relation_name_tests/models/my_name_is_52_characters_abcdefghijklmnopqrstuvwxyz0.sql
  test/integration/063_relation_name_tests/models/my_name_is_63_characters_abcdefghijklmnopqrstuvwxyz012345678901.sql
  test/integration/063_relation_name_tests/models/my_name_is_64_characters_abcdefghijklmnopqrstuvwxyz0123456789012.sql
  test/integration/063_relation_name_tests/seeds/seed.csv
  test/integration/063_relation_name_tests/test_relation_name.py
  tests/functional/relation_names/test_relation_name.py
Labels: cla:yes, Skip Changelog

#6330 Ct 288/convert 070 incremental test
  test/integration/070_incremental_schema_tests/models/incremental_append_new_columns.sql
  test/integration/070_incremental_schema_tests/models/incremental_append_new_columns_remove_one.sql
  test/integration/070_incremental_schema_tests/models/incremental_append_new_columns_remove_one_target.sql
  test/integration/070_incremental_schema_tests/models/incremental_append_new_columns_target.sql
  test/integration/070_incremental_schema_tests/models/incremental_fail.sql
  test/integration/070_incremental_schema_tests/models/incremental_ignore.sql
  test/integration/070_incremental_schema_tests/models/incremental_ignore_target.sql
  test/integration/070_incremental_schema_tests/models/incremental_sync_all_columns.sql
  test/integration/070_incremental_schema_tests/models/incremental_sync_all_columns_target.sql
  test/integration/070_incremental_schema_tests/models/incremental_sync_remove_only.sql
  test/integration/070_incremental_schema_tests/models/incremental_sync_remove_only_target.sql
  test/integration/070_incremental_schema_tests/models/model_a.sql
  test/integration/070_incremental_schema_tests/models/schema.yml
  test/integration/070_incremental_schema_tests/test_incremental_schema.py
  test/integration/070_incremental_schema_tests/tests/select_from_a.sql
  test/integration/070_incremental_schema_tests/tests/select_from_incremental_append_new_columns.sql
  test/integration/070_incremental_schema_tests/tests/select_from_incremental_append_new_columns_target.sql
  test/integration/070_incremental_schema_tests/tests/select_from_incremental_ignore.sql
  test/integration/070_incremental_schema_tests/tests/select_from_incremental_ignore_target.sql
  test/integration/070_incremental_schema_tests/tests/select_from_incremental_sync_all_columns.sql
  test/integration/070_incremental_schema_tests/tests/select_from_incremental_sync_all_columns_target.sql
  tests/functional/incremental_schema_tests/fixtures.py
  tests/functional/incremental_schema_tests/test_incremental_schema.py
Labels: cla:yes, Skip Changelog

#6329 Moving syntax params around to make flake8's new version happy again.
  core/dbt/clients/jinja.py
  core/dbt/context/macros.py
  core/dbt/graph/cli.py
Labels: cla:yes, Skip Changelog
