Repository dbt-labs/dbt-core, pull requests merged in 2022-08, with the labels that each got.

#5592 Fix flake8
  core/dbt/semver.py
Labels: cla:yes, Skip Changelog

#5581 use MethodName.File when value ends with .csv
  .changes/unreleased/Features-20220729-173231.yaml
  core/dbt/graph/selector_spec.py
  test/unit/test_graph_selector_methods.py
Labels: cla:yes, Team:Execution, ready_for_review

#4514 Add defer to docs and compile commands
  .changes/unreleased/Features-20220314-181127.yaml
  core/dbt/main.py
  core/dbt/task/compile.py
  core/dbt/task/run.py
  test/integration/062_defer_state_tests/test_defer_state.py
  tests/functional/artifacts/test_docs_generate_defer.py
Labels: cla:yes, Team:Execution, awaiting_response

#5597 rename .github readme
  .github/_README.md
Labels: cla:yes, Skip Changelog

#5589 Store when default env vars are used in manifest
  .changes/unreleased/Under the Hood-20220802-112936.yaml
  core/dbt/config/renderer.py
  core/dbt/constants.py
  core/dbt/context/base.py
  core/dbt/context/configured.py
  core/dbt/context/providers.py
  core/dbt/context/secret.py
  core/dbt/events/functions.py
  core/dbt/logger.py
  core/dbt/parser/partial.py
  test/integration/068_partial_parsing_tests/test_pp_vars.py
  tests/functional/context_methods/test_env_vars.py
  tests/functional/context_methods/test_secret_env_vars.py
Labels: cla:yes

#5565 convert to reusable action
  .github/_README.md
  .github/workflows/changelog-check.yml
  .github/workflows/changelog-existence.yml
Labels: cla:yes, Skip Changelog

#5608 modify tests to meet standards
  tests/functional/configs/test_custom_node_colors_configs.py
Labels: cla:yes, Skip Changelog

#5604 Stop test_previous_version_state.py from modifying test data
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes, Skip Changelog

#5397 Add docs as a real node config and support `node_color` for coloring the DAG
  .changes/unreleased/Features-20220803-104230.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/graph/utils.py
  core/dbt/parser/base.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v7.json
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  tests/functional/artifacts/data/state/v7/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_custom_node_colors_configs.py
  tests/functional/list/test_list.py
Labels: cla:yes, Team:Language, ready_for_review

#5614 bring in new index and add changelog
  .changes/unreleased/Docs-20220804-134138.yaml
  core/dbt/include/index.html
Labels: cla:yes

#5603 Do not render metrics description field when doing render_data
  .changes/unreleased/Fixes-20220803-144221.yaml
  core/dbt/parser/schema_renderer.py
  test/unit/test_yaml_renderer.py
Labels: cla:yes, backport 1.2.latest

#5607 Adding Metric Helper Functions
  .changes/unreleased/Features-20220804-120936.yaml
  .gitignore
  core/dbt/contracts/graph/metrics.py
  tests/functional/metrics/test_metric_helper_functions.py
Labels: cla:yes, Team:Language

#5628 link changelog to dbt-docs for Docs kind
  .changes/1.3.0/Docs-20220728-140258.yaml
  .changes/1.3.0/Docs-20220728-140329.yaml
  .changes/1.3.0/Docs-20220728-140351.yaml
  .changes/1.3.0/Docs-20220728-140425.yaml
  .changes/1.3.0/Docs-20220728-140449.yaml
  .changes/1.3.0/Docs-20220728-140620.yaml
  .changes/1.3.0/Docs-20220728-140806.yaml
  .changes/unreleased/Docs-20220804-134138.yaml
  .changie.yaml
Labels: cla:yes, Skip Changelog

#5292 Fix postgres handling for unlimited varchars
  .changes/unreleased/Fixes-20220523-103843.yaml
  plugins/postgres/dbt/adapters/postgres/relation.py
Labels: cla:yes, Team:Adapters, ready_for_review

#5344 CT-729 Include schema model config in unrendered config
  .changes/unreleased/Fixes-20220607-123058.yaml
  core/dbt/parser/base.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_configs_in_schema_files.py
Labels: cla:yes

#5627 Use sys.exit instead of exit
  .changes/unreleased/Fixes-20220808-112001.yaml
  core/dbt/task/init.py
Labels: cla:yes, Team:Execution, ready_for_review, backport 1.2.latest

#5640 [Backport] #5627 to 1.2.latest
  .changes/unreleased/Fixes-20220808-112001.yaml
  core/dbt/task/init.py
Labels: cla:yes

#5620 Extended validations for the project names
  .changes/unreleased/Fixes-20220805-221022.yaml
  core/dbt/task/init.py
Labels: cla:yes, Team:Execution, ready_for_review

#5505 Incremental model show reason for on_schema_change fail failures
  .changes/unreleased/Fixes-20220720-213746.yaml
  core/dbt/include/global_project/macros/materializations/models/incremental/on_schema_change.sql
Labels: cla:yes, Team:Adapters, ready_for_review

#5395 Fix/incremental column precision changes
  .changes/unreleased/Fixes-20220617-193731.yaml
  core/dbt/include/global_project/macros/materializations/models/incremental/column_helpers.sql
  tests/adapter/dbt/tests/adapter/basic/files.py
  tests/adapter/dbt/tests/adapter/basic/test_incremental.py
Labels: cla:yes, Team:Adapters, ready_for_review

#5659 Print more information on log line interop test failures
  .changes/unreleased/Under the Hood-20220816-122032.yaml
  test/interop/log_parsing/src/main.rs
Labels: cla:yes

#5635 fix multiple args for ref and source
  .changes/unreleased/Fixes-20220816-153401.yaml
  core/dbt/include/global_project/macros/python_model/python.sql
  tests/adapter/dbt/tests/adapter/python_model/test_python_model.py
Labels: cla:yes

#5656 Change postgres name truncation logic to be overridable.
  .changes/unreleased/Fixes-20220815-230409.yaml
  core/dbt/adapters/cache.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
Labels: cla:yes

#5678 Update "Homepage" link for dbt-tests-adapter on PyPI
  tests/adapter/setup.py
Labels: cla:yes, Skip Changelog

#5651 Check dbt-core version requirements when installing Hub packages
  .changes/unreleased/Features-20220815-134312.yaml
  core/dbt/clients/registry.py
  core/dbt/deps/registry.py
  core/dbt/deps/resolver.py
  core/dbt/exceptions.py
  test/unit/test_deps.py
Labels: cla:yes, Team:Language

#5677 more complex visit_Call to parse chained command
  .changes/unreleased/Fixes-20220817-163642.yaml
  core/dbt/parser/models.py
  test/unit/test_parser.py
Labels: cla:yes

#5695 Add supported languages to materializations
  .changes/unreleased/Under the Hood-20220822-103739.yaml
  core/dbt/clients/jinja.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/parser/macros.py
  core/dbt/task/run.py
  schemas/dbt/manifest/v7.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/materializations/test_supported_languages.py
Labels: cla:yes

#5694 Update CODEOWNERS to reflect latest sub-team ownership
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#5726 ADR for why we're using betterproto for protobuf
  docs/arch/adr-005-betterproto.md
Labels: cla:yes, Skip Changelog

#5715 Test priority order of profiles directory configuration
  core/dbt/tests/util.py
  tests/functional/profiles/test_profile_dir.py
Labels: cla:yes, Team:Language, Skip Changelog, ready_for_review

#5748 Roadmap update (Aug 2022)
  docs/roadmap/2022-08-back-for-more.md
Labels: cla:yes, Skip Changelog
