Repository dbt-labs/dbt-core, pull requests merged in 2022-04, with the labels that each got.

#4993 Remove unneeded code in default snapshot materialization
  .changes/unreleased/Under the Hood-20220404-144708.yaml
  core/dbt/include/global_project/macros/materializations/snapshots/snapshot.sql
Labels: cla:yes, Team:Execution, Team:Adapters

#4982 [CT-352] catch and retry malformed json
  .changes/unreleased/Fixes-20220331-143923.yaml
  core/dbt/clients/registry.py
  core/dbt/events/types.py
  test/unit/test_events.py
  tests/functional/permission/test_permissions.py
Labels: cla:yes, backport 1.0.latest

#4685 include directory README
  core/dbt/include/README.md
Labels: cla:yes, Skip Changelog

#5000 add DO_NOT_TRACK environment variable support
  .changes/unreleased/Features-20220406-080328.yaml
  core/dbt/flags.py
  dev-requirements.txt
  test/unit/test_flags.py
  test/unit/test_tracking.py
Labels: cla:yes, Team:Execution

#5010 Fixing broken CI for `1.0.latest`
  setup.py
Labels: cla:yes, Skip Changelog

#5007 Backport 4982 deps
  .changes/unreleased/Fixes-20220331-143923.yaml
  core/dbt/clients/registry.py
  core/dbt/events/types.py
  test/integration/012_deprecation_tests/test_deprecations.py
  test/unit/test_events.py
Labels: cla:yes

#5011 updated event message
  .changes/unreleased/Fixes-20220407-161134.yaml
  core/dbt/events/types.py
Labels: cla:yes

#4939 adapter_methods
  test/integration/054_adapter_methods_tests/models/expected.sql
  test/integration/054_adapter_methods_tests/models/model.sql
  test/integration/054_adapter_methods_tests/models/upstream.sql
  test/integration/054_adapter_methods_tests/test_adapter_methods.py
  test/integration/054_adapter_methods_tests/tests/get_columns_in_relation.sql
  tests/adapter/dbt/tests/adapter/basic/test_adapter_methods.py
Labels: cla:yes, Skip Changelog

#5012 make graph_selection tests just checking selection
  tests/functional/graph_selection/test_graph_selection.py
  tests/functional/graph_selection/test_intersection_syntax.py
  tests/functional/graph_selection/test_schema_test_graph_selection.py
  tests/functional/graph_selection/test_tag_selection.py
Labels: cla:yes, Skip Changelog

#5019 added git-blame-ignore-revs file
  .changes/unreleased/Under the Hood-20220408-135525.yaml
  .git-blame-ignore-revs
Labels: cla:yes

#4981 Decouple project creation logic from tasks CT-299
  .changes/unreleased/Under the Hood-20220330-101439.yaml
  core/dbt/config/utils.py
  test/integration/039_config_tests/models-ok/ok.sql
  test/integration/039_config_tests/project/dbt_project.yml
  test/integration/039_config_tests/project/profiles.yml
  test/integration/039_config_tests/test_configs.py
Labels: cla:yes

#5020 Fix hard_delete_snapshot test to do the right thing.
  .changes/unreleased/Fixes-20220408-155512.yaml
  tests/functional/simple_snapshot/test_hard_delete_snapshot.py
Labels: cla:yes

#5026 Convert --version tests to pytest
  .changes/unreleased/Under the Hood-20220411-090536.yaml
  dev-requirements.txt
  test/unit/test_version.py
  tests/unit/test_version.py
Labels: cla:yes

#4995 Update index file for docs generation
  .changes/unreleased/Docs-20220404-201021.yaml
  .changes/unreleased/Docs-20220404-201057.yaml
  .changes/unreleased/Docs-20220404-201203.yaml
  core/dbt/include/index.html
Labels: cla:yes

#4854 Added no-print flag
  .changes/unreleased/Features-20220408-114118.yaml
  core/dbt/context/base.py
  core/dbt/flags.py
  core/dbt/main.py
  test/unit/test_flags.py
Labels: cla:yes, Team:Language

#5028 cache after retrying not while retrying
  core/dbt/clients/registry.py
Labels: cla:yes, Skip Changelog

#4256 Smart Source Freshness Runs
  .changes/unreleased/Features-20220328-134743.yaml
  core/dbt/contracts/state.py
  core/dbt/graph/selector_methods.py
  core/dbt/task/runnable.py
  test/unit/test_graph_selector_methods.py
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_simple_source.py
  tests/functional/sources/test_source_fresher_state.py
Labels: cla:yes, Team:Execution

#5025 Updating tests and doc to support Python 3.10
  .changes/unreleased/Under the Hood-20220411-103724.yaml
  .github/workflows/main.yml
  CONTRIBUTING.md
  Dockerfile.test
  core/setup.py
  plugins/postgres/setup.py
Labels: cla:yes

#5008 Add enabled as a source config
  .changes/unreleased/Features-20220408-132725.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/sources.py
  test/unit/test_contracts_graph_unparsed.py
  tests/functional/permission/test_permissions.py
  tests/functional/sources/test_source_configs.py
Labels: cla:yes

#5036 Add experimental `cache_selected_only` config
  .changes/unreleased/Breaking Changes-20220412-152450.yaml
  .changes/unreleased/Features-20220316-003847.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/contracts/project.py
  core/dbt/flags.py
  core/dbt/main.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  plugins/postgres/dbt/adapters/postgres/impl.py
  test/integration/038_caching_tests/models_multi_schemas/another_schema_model.sql
  test/integration/038_caching_tests/models_multi_schemas/model.sql
  test/integration/038_caching_tests/test_caching.py
  test/unit/test_flags.py
Labels: cla:yes

#5001 Add `selected_resources` to the Jinja context
  .changes/unreleased/Features-20220404-190439.yaml
  core/dbt/context/providers.py
  core/dbt/graph/selector.py
  core/dbt/selected_resources.py
  test/unit/test_context.py
  tests/functional/selected_resources/fixtures.py
  tests/functional/selected_resources/test_selected_resources.py
Labels: cla:yes, Team:Execution, Team:Language

#5040 Backport 5037 changie contributors cleanup
  .changie.yaml
Labels: cla:yes, Skip Changelog

#5029 Update version output and logic
  .changes/unreleased/Under the Hood-20220411-154626.yaml
  core/dbt/version.py
  tests/unit/test_version.py
Labels: cla:yes

#4602 Performance Regression Testing Revamp Stage 1
  .changes/unreleased/Under the Hood-20220309-142133.yaml
  .github/workflows/performance.yml
  performance/README.md
  performance/baselines/.gitignore
  performance/images/normal.svg
  performance/runner/Cargo.lock
  performance/runner/Cargo.toml
  performance/runner/src/calculate.rs
  performance/runner/src/exceptions.rs
  performance/runner/src/fs.rs
  performance/runner/src/main.rs
  performance/runner/src/measure.rs
  performance/runner/src/types.rs
Labels: cla:yes

#5032 Bumping manifest schema to v5
  .changes/unreleased/Under the Hood-20220411-213914.yaml
  core/dbt/contracts/graph/manifest.py
  test/integration/029_docs_generate_tests/test_docs_generate.py
  test/unit/test_manifest.py
Labels: cla:yes

#5039 Flexibilize MarkupSafe pinned version
  .changes/unreleased/Fixes-20220413-151735.yaml
  core/setup.py
Labels: cla:yes

#5055 Add updated dbt diagram for readme
  README.md
  etc/dbt-transform.png
Labels: cla:yes, Skip Changelog

#4802 Clarify steps to reopen a stale issue
  .github/workflows/stale.yml
Labels: cla:yes, Skip Changelog

#5069 move deprecation check outside package caching
  .changes/unreleased/Under the Hood-20220414-132206.yaml
  core/dbt/clients/registry.py
Labels: cla:yes

#5060 Ct 488/migrate simple seed
  .changes/unreleased/Under the Hood-20220409-040539.yaml
  test/integration/005_simple_seed_tests/data-big/my_seed.csv
  test/integration/005_simple_seed_tests/macros/schema_test.sql
  test/integration/005_simple_seed_tests/models-downstream-seed/model.sql
  test/integration/005_simple_seed_tests/models-exist/model.sql
  test/integration/005_simple_seed_tests/models-pg/schema.yml
  test/integration/005_simple_seed_tests/seeds-bad/seed.csv
  test/integration/005_simple_seed_tests/seeds-big/.gitignore
  test/integration/005_simple_seed_tests/seeds-config/seed_disabled.csv
  test/integration/005_simple_seed_tests/seeds-config/seed_enabled.csv
  test/integration/005_simple_seed_tests/seeds-config/seed_tricky.csv
  test/integration/005_simple_seed_tests/seeds-dottedseed/seed.with.dots.csv
  test/integration/005_simple_seed_tests/test_seed_type_override.py
  test/integration/005_simple_seed_tests/test_simple_seed.py
  tests/functional/simple_seed/data/seed.with.dots.csv
  tests/functional/simple_seed/data/seed_actual.csv
  tests/functional/simple_seed/data/seed_bom.csv
  tests/functional/simple_seed/data/seed_expected.sql
  tests/functional/simple_seed/data/seed_unicode.csv
  tests/functional/simple_seed/fixtures.py
  tests/functional/simple_seed/test_seed.py
  tests/functional/simple_seed/test_seed_type_override.py
Labels: cla:yes

#5042 backport perf readme
  .changes/1.0.5/Under the Hood-20220311-101851.yaml
  .changes/unreleased/Docs-20220412-161008.yaml
  performance/README.md
Labels: cla:yes

#5082 Updating backport action to latest
  .github/workflows/backport.yml
Labels: cla:yes, Skip Changelog

#5034 CT-476 convert deprecation tests
  core/dbt/tests/fixtures/project.py
  test/integration/012_deprecation_tests/models-trivial/model.sql
  test/integration/012_deprecation_tests/models/already_exists.sql
  test/integration/012_deprecation_tests/test_deprecations.py
  tests/functional/deprecations/test_deprecations.py
Labels: cla:yes, Skip Changelog

#5110 [Backport 1.0.latest] Flexibilize MarkupSafe pinned version (#5039)
  .changes/unreleased/Fixes-20220413-151735.yaml
  core/setup.py
Labels: cla:yes

#5113 remove commas from changelog yaml
  .changes/1.1.0-rc1.md
  .changes/1.1.0/Features-20220328-134743.yaml
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#5058 Convert docs_generate_tests to new framework
  .changes/unreleased/Under the Hood-20220413-183014.yaml
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  schemas/dbt/catalog/v1.json
  schemas/dbt/manifest/v5.json
  schemas/dbt/run-results/v4.json
  schemas/dbt/sources/v3.json
  test/integration/029_docs_generate_tests/assets/lorem-ipsum.txt
  test/integration/029_docs_generate_tests/fail_macros/failure.sql
  test/integration/029_docs_generate_tests/macros/dummy_test.sql
  test/integration/029_docs_generate_tests/macros/macro.md
  test/integration/029_docs_generate_tests/macros/schema.yml
  test/integration/029_docs_generate_tests/models/model.sql
  test/integration/029_docs_generate_tests/models/readme.md
  test/integration/029_docs_generate_tests/models/schema.yml
  test/integration/029_docs_generate_tests/models/second_model.sql
  test/integration/029_docs_generate_tests/ref_models/docs.md
  test/integration/029_docs_generate_tests/ref_models/ephemeral_copy.sql
  test/integration/029_docs_generate_tests/ref_models/ephemeral_summary.sql
  test/integration/029_docs_generate_tests/ref_models/schema.yml
  test/integration/029_docs_generate_tests/ref_models/view_summary.sql
  test/integration/029_docs_generate_tests/seed/schema.yml
  test/integration/029_docs_generate_tests/seed/seed.csv
  test/integration/029_docs_generate_tests/snapshot/snapshot_seed.sql
  test/integration/029_docs_generate_tests/test_docs_generate.py
  test/integration/029_docs_generate_tests/trivial_models/model.sql
  tests/adapter/dbt/tests/adapter/basic/expected_catalog.py
  tests/adapter/dbt/tests/adapter/basic/test_docs_generate.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/expected_run_results.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/artifacts/test_override.py
  tests/functional/sources/test_source_fresher_state.py
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes, Skip Changelog

#5065 add new GHA for dependabot PRs
  .github/workflows/changelog-check.yml
  .github/workflows/dependency-changelog.yml
Labels: cla:yes, Skip Changelog

#5126 Restore ability to utilize `updated_at` for check_cols snapshots (#5077)
  .changes/unreleased/Fixes-20220415-112927.yaml
  core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql
  core/dbt/tests/util.py
  tests/functional/simple_snapshot/test_check_cols_updated_at_snapshot.py
Labels: cla:yes

#4967 GH hygiene: contributing guide, templates, stalebot
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/pull_request_template.md
  .github/workflows/stale.yml
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#5137 fix retry logic failures
  .changes/unreleased/Fixes-20220422-131227.yaml
  core/dbt/utils.py
  tests/unit/test_connection_retries.py
Labels: cla:yes

#5121 Updating backport Action permissions
  .github/workflows/backport.yml
Labels: cla:yes, Skip Changelog

#5147 Backport 5137 5069
  .changes/unreleased/Fixes-20220422-131227.yaml
  .changes/unreleased/Under the Hood-20220414-132206.yaml
  core/dbt/clients/registry.py
  core/dbt/utils.py
  test/unit/test_connection_retries.py
Labels: cla:yes

#5148 Backport 5137 to 1.1.latest
  .changes/unreleased/Fixes-20220422-131227.yaml
  core/dbt/utils.py
  tests/unit/test_connection_retries.py
Labels: cla:yes

#5136 Use yaml renderer (with target context) for rendering selectors
  .changes/unreleased/Fixes-20220422-135645.yaml
  core/dbt/config/renderer.py
  core/dbt/config/selectors.py
  core/dbt/config/utils.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  test/integration/028_cli_vars_tests/models_complex/complex_model.sql
  test/integration/028_cli_vars_tests/models_complex/schema.yml
  test/integration/028_cli_vars_tests/models_override/schema.yml
  test/integration/028_cli_vars_tests/models_override/test_vars.sql
  test/integration/028_cli_vars_tests/models_simple/schema.yml
  test/integration/028_cli_vars_tests/models_simple/simple_model.sql
  test/integration/028_cli_vars_tests/test_cli_var_override.py
  test/integration/028_cli_vars_tests/test_cli_vars.py
  tests/functional/cli_vars/test_cli_var_override.py
  tests/functional/cli_vars/test_cli_vars.py
Labels: cla:yes, backport 1.1.latest

#5158 Even more scrubbing (#5152)
  .changes/unreleased/Fixes-20220425-203924.yaml
  core/dbt/clients/git.py
  core/dbt/exceptions.py
  test/integration/013_context_var_tests/test_context_vars.py
Labels: cla:yes

#5160 Backport 1.0 ct 540 use target context for selectors
  .changes/unreleased/Fixes-20220422-135645.yaml
  core/dbt/config/renderer.py
  core/dbt/config/selectors.py
Labels: cla:yes

#5164 add triage label workflow
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#5168 Tweak `triage-label.yml` to trigger off issue labels instead of PR labels
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#5143 Ct 488/migrate invalid model tests
  core/dbt/tests/fixtures/project.py
  test/integration/011_invalid_model_tests/bad-macros/macros.sql
  test/integration/011_invalid_model_tests/models-disabled/dependent.sql
  test/integration/011_invalid_model_tests/models-disabled/view_model.sql
  test/integration/011_invalid_model_tests/models-invalid-disabled/view_model.sql
  test/integration/011_invalid_model_tests/models-invalid-macro/bad_macro.sql
  test/integration/011_invalid_model_tests/models-not-found/dependent.sql
  test/integration/011_invalid_model_tests/seed.sql
  test/integration/011_invalid_model_tests/sources-disabled/model.sql
  test/integration/011_invalid_model_tests/sources-disabled/sources.yml
  test/integration/011_invalid_model_tests/sources-missing/model.sql
  test/integration/011_invalid_model_tests/test_invalid_models.py
  tests/functional/invalid_model_tests/test_invalid_models.py
Labels: cla:yes, Skip Changelog

#5140 Add itertools to modules
  .changes/unreleased/Features-20220424-132655.yaml
  core/dbt/context/base.py
Labels: cla:yes, ok_to_test, Team:Language

#5139 migrate 009_data_tests to new test framework
  test/integration/009_data_tests_tests/models/.gitkeep
  test/integration/009_data_tests_tests/models/table_copy.sql
  test/integration/009_data_tests_tests/test_data_tests.py
  test/integration/009_data_tests_tests/tests/fail_email_is_always_null.sql
  test/integration/009_data_tests_tests/tests/fail_no_ref.sql
  test/integration/009_data_tests_tests/tests/my_db.my_schema.table_copy.pass_id_not_null.sql
  test/integration/009_data_tests_tests/tests/pass_id_not_null.sql
  test/integration/009_data_tests_tests/tests/pass_no_ref.sql
  test/integration/base.py
  tests/functional/custom_singular_tests/data/seed_expected.sql
  tests/functional/custom_singular_tests/test_custom_singular_tests.py
Labels: cla:yes, Skip Changelog

#5163 remove extra class and add connection test
  core/dbt/task/debug.py
  core/dbt/tests/fixtures/project.py
  tests/adapter/dbt/tests/adapter/basic/test_validate_connection.py
Labels: cla:yes, Skip Changelog

#4827 Add selector method capabilities to selectors
  .changes/unreleased/Features-20220408-112610.yaml
  core/dbt/config/selectors.py
  core/dbt/graph/cli.py
  test/unit/test_graph_selector_parsing.py
  test/unit/test_manifest_selectors.py
Labels: cla:yes, Team:Execution

#4893 Fix adding new cols to check_cols in snapshots
  .changes/unreleased/Fixes-20220317-210916.yaml
  core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql
  tests/functional/simple_snapshot/test_changing_check_cols_snapshot.py
Labels: cla:yes, ok_to_test, Team:Adapters

#5173 Ct-65 metrics names with spaces
  .changes/unreleased/Fixes-20220426-202104.yaml
  core/dbt/contracts/graph/unparsed.py
  test/integration/075_metrics_tests/invalid-models/people.sql
  test/integration/075_metrics_tests/invalid-models/people_metrics.yml
  test/integration/075_metrics_tests/models/people.sql
  test/integration/075_metrics_tests/models/people_metrics.yml
  test/integration/075_metrics_tests/test_metrics.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes

#5176 When parsing 'all_sources' should be a list of unique dirs
  .changes/unreleased/Fixes-20220427-102648.yaml
  core/dbt/config/project.py
  core/dbt/tests/fixtures/project.py
  test/integration/039_config_tests/extra-alt/untagged.yml
  test/integration/039_config_tests/extra-alt/untagged2.yml
  test/integration/039_config_tests/models-alt/schema.yml
  test/integration/039_config_tests/models-alt/tagged/model.sql
  test/integration/039_config_tests/models-alt/untagged.sql
  test/integration/039_config_tests/models-get/any_model.sql
  test/integration/039_config_tests/models-ok/ok.sql
  test/integration/039_config_tests/models/schema.yml
  test/integration/039_config_tests/models/tagged/model.sql
  test/integration/039_config_tests/models/untagged.sql
  test/integration/039_config_tests/project/dbt_project.yml
  test/integration/039_config_tests/project/profiles.yml
  test/integration/039_config_tests/seeds-alt/some_seed.csv
  test/integration/039_config_tests/seeds/seed.csv
  test/integration/039_config_tests/test_configs.py
  test/integration/039_config_tests/test_configs_in_schema_files.py
  test/integration/039_config_tests/tests/failing.sql
  test/integration/039_config_tests/tests/sleeper_agent.sql
  test/unit/test_config.py
  tests/functional/configs/fixtures.py
  tests/functional/configs/test_configs.py
  tests/functional/configs/test_configs_in_schema_files.py
  tests/functional/configs/test_disabled_configs.py
  tests/functional/configs/test_dupe_paths.py
  tests/functional/configs/test_get_default.py
  tests/functional/configs/test_get_project_config.py
  tests/functional/configs/test_indiv_tests.py
  tests/functional/configs/test_unused_configs.py
Labels: cla:yes

#5182 Update README for dbt-tests-adapter
  tests/adapter/README.md
Labels: cla:yes, Skip Changelog, backport 1.1.latest

#5146 Fix: add warning on duplicated yaml keys
  .changes/unreleased/Fixes-20220428-100157.yaml
  core/dbt/clients/yaml_helper.py
  core/dbt/exceptions.py
  core/dbt/parser/schemas.py
  test/integration/006_simple_dependency_tests/local_dependency/models/schema.yml
  tests/functional/duplications/test_basic_duplications.py
Labels: cla:yes, Team:Language
