Repository dbt-labs/dbt-core, pull requests merged in 2022-01, with the labels that each got.

#4533 Fix small typo in architecture doc
  ARCHITECTURE.md
Labels: cla:yes

#4541 Commenting our Docker portion of Version Bump
  .github/workflows/version-bump.yml
Labels: cla:yes

#4474 copy over windows compat logic for colored log output
  CHANGELOG.md
  core/dbt/events/functions.py
Labels: cla:yes

#4542 Removing Docker from bumpversion script
  .bumpversion.cfg
Labels: cla:yes

#4544 [Backport] Bumping version to 1.0.1 (#4543)
  .bumpversion.cfg
  CHANGELOG.md
  core/dbt/version.py
  core/scripts/create_adapter_plugins.py
  core/setup.py
  plugins/postgres/dbt/adapters/postgres/__version__.py
  plugins/postgres/setup.py
  setup.py
Labels: cla:yes

#4548 Mirroring issues to Jira
  .github/workflows/jira-closed.yml
  .github/workflows/jira-creation.yml
Labels: cla:yes

#4550 Mirror labels to Jira
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
Labels: cla:yes

#4556 Fix test deprecation warnings
  CHANGELOG.md
  core/dbt/compilation.py
  core/dbt/graph/graph.py
  core/dbt/semver.py
  pytest.ini
  test/unit/test_graph.py
Labels: cla:yes, test all

#4589 Rename data directory to seeds
  CHANGELOG.md
  core/dbt/include/starter_project/seeds/.gitkeep
Labels: cla:yes, Team:Language

#4592 [BACKPORT] Rename data directory to seeds (#4589)
  CHANGELOG.md
  core/dbt/include/starter_project/seeds/.gitkeep
Labels: cla:yes

#4607 update cache action
  .github/workflows/performance.yml
Labels: cla:yes

#4605 Add Backport Action
  .github/workflows/backport.yml
Labels: cla:yes

#4536 Validate project names in interactive dbt init
  CHANGELOG.md
  core/dbt/contracts/project.py
  core/dbt/task/init.py
  test/integration/040_init_tests/test_init.py
Labels: cla:yes, Team:Execution

#4615 Changing Jira mirroring workflows to point to shared Actions
  .github/workflows/jira-closed.yml
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes

#4587 Clarify "incompatible package version" error msg
  core/dbt/config/project.py
Labels: cla:yes, Team:Language

#4610 [#4554] Don't require a profile for dbt deps and clean commands
  CHANGELOG.md
  core/dbt/config/runtime.py
  core/dbt/events/types.py
  test/integration/006_simple_dependency_tests/test_simple_dependency.py
  test/unit/test_events.py
Labels: cla:yes

#4447 Run check_if_can_write_profile before create_profile_using_project_profile_template [CT-67] [Backport 1.0.latest]
  CHANGELOG.md
  core/dbt/task/init.py
Labels: cla:yes, Team:Execution, jira

#4632 Proposed sub-team codeowners
  .github/CODEOWNERS
Labels: cla:yes

#4505 Use mashumaro for serializing logging events
  CHANGELOG.md
  core/dbt/adapters/cache.py
  core/dbt/adapters/sql/impl.py
  core/dbt/context/base.py
  core/dbt/contracts/graph/parsed.py
  core/dbt/events/README.md
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  core/dbt/events/serialization.py
  core/dbt/events/stubs.py
  core/dbt/events/types.py
  core/dbt/graph/selector.py
  core/dbt/main.py
  core/dbt/task/base.py
  core/dbt/task/freshness.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  core/dbt/task/snapshot.py
  core/dbt/task/test.py
  core/dbt/utils.py
  test/interop/log_parsing/src/main.rs
  test/unit/test_events.py
  tox.ini
Labels: cla:yes

#4620 Initial addition of CODEOWNERS file
  .github/CODEOWNERS
Labels: cla:yes

#4631 fix comparision for new model/body
  CHANGELOG.md
  core/dbt/graph/selector_methods.py
  test/unit/test_graph_selector_methods.py
Labels: cla:yes

#4609 Retry after failure to download or failure to open files
  CHANGELOG.md
  core/dbt/clients/registry.py
  core/dbt/clients/system.py
  core/dbt/deps/registry.py
  core/dbt/exceptions.py
  core/dbt/utils.py
  test/unit/test_core_dbt_utils.py
  test/unit/test_system_client.py
Labels: cla:yes, backport 1.0.latest

#4643 Drop support for Python <3.7.2
  CHANGELOG.md
  core/setup.py
  scripts/build-dist.sh
  setup.py
Labels: cla:yes

#4647 Change InvalidRefInTestNode level to DEBUG
  CHANGELOG.md
  core/dbt/events/types.py
Labels: cla:yes, Team:Language, backport 1.0.latest

#4649 [BACKPORT] Retry after failure to download or failure to open files (#4609)
  CHANGELOG.md
  core/dbt/clients/registry.py
  core/dbt/clients/system.py
  core/dbt/deps/registry.py
  core/dbt/exceptions.py
  core/dbt/utils.py
  test/unit/test_core_dbt_utils.py
  test/unit/test_system_client.py
Labels: cla:yes

#4619 Guard against unnecessarily calling dump_graph in logging
  core/dbt/adapters/cache.py
  core/dbt/events/README.md
  core/dbt/events/base_types.py
  core/dbt/events/serialization.py
  core/dbt/events/types.py
  core/dbt/helper_types.py
  test/unit/test_events.py
Labels: cla:yes

#4651 Backport [ct-25] dbt deps should not require a profile
  core/dbt/config/runtime.py
  core/dbt/events/types.py
  test/integration/006_simple_dependency_test/test_simple_dependency.py
  test/unit/test_events.py
Labels: cla:yes
