Repository dbt-labs/dbt-core, pull requests merged in 2023-06, with the labels that each got.

#7734 pass optional sql_header to empty subquery sql rendering
  .changes/unreleased/Fixes-20230531-131919.yaml
  core/dbt/include/global_project/macros/adapters/columns.sql
  core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
Labels: cla:yes, backport 1.5.latest

#7512 Fix constraint rendering for expressions and foreign key constraint types
  .changes/unreleased/Fixes-20230504-140642.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/contracts/graph/nodes.py
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
  tests/unit/test_base_adapter.py
Labels: user docs, cla:yes, backport 1.5.latest

#7754 add project_name to manifest metadata
  .changes/unreleased/Features-20230601-132223.yaml
  core/dbt/config/runtime.py
  core/dbt/contracts/graph/manifest.py
  schemas/dbt/manifest/v10.json
  tests/functional/artifacts/test_artifacts.py
Labels: cla:yes

#7767 force dependency between test models
  .changes/unreleased/Under the Hood-20230602-145743.yaml
  tests/functional/fail_fast/test_fail_fast_run.py
Labels: cla:yes

#7783 log PublicationArtifactAvailable even when partially parsing & public models unchanged
  .changes/unreleased/Fixes-20230605-121127.yaml
  core/dbt/parser/manifest.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes

#7776 Fix not equals comparison to be null-safe for adapters/utils tests
  .changes/unreleased/Features-20230604-080052.yaml
  tests/adapter/dbt/tests/adapter/utils/base_utils.py
  tests/adapter/dbt/tests/adapter/utils/fixture_concat.py
  tests/adapter/dbt/tests/adapter/utils/fixture_equals.py
  tests/adapter/dbt/tests/adapter/utils/fixture_hash.py
  tests/adapter/dbt/tests/adapter/utils/fixture_null_compare.py
  tests/adapter/dbt/tests/adapter/utils/test_equals.py
  tests/adapter/dbt/tests/adapter/utils/test_null_compare.py
Labels: cla:yes, ready_for_review

#7696 Improve warnings for constraints and materialization types
  .changes/unreleased/Fixes-20230525-073651.yaml
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/parser/schemas.py
  tests/functional/configs/test_contract_configs.py
  tests/unit/test_events.py
Labels: cla:yes, backport 1.5.latest

#7509 Package-namespaced generate_x_name macro resolution
  .changes/unreleased/Features-20230509-212935.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/base.py
  test/unit/test_manifest.py
  tests/functional/dependencies/local_dependency/macros/generate_schema_name.sql
  tests/functional/dependencies/local_dependency/models/schema.yml
  tests/functional/dependencies/test_local_dependency.py
Labels: cla:yes

#7805 generalize BaseModelConstraintsRuntimeEnforcement
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
Labels: cla:yes, Skip Changelog

#7806 [BACKPORT] Improve warning for constraints and mat types
  .changes/unreleased/Fixes-20230525-073651.yaml
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/parser/schemas.py
  tests/functional/configs/test_contract_configs.py
  tests/unit/test_events.py
Labels: cla:yes

#7794 Validate public models are not materialized as ephemeral
  .changes/unreleased/Features-20230605-222039.yaml
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  tests/functional/groups/test_access.py
Labels: cla:yes

#7735 fix error message for empty/None: --warn-error-options handling
  .changes/unreleased/Fixes-20230530-104228.yaml
  core/dbt/cli/option_types.py
  core/dbt/config/utils.py
  tests/unit/test_option_types.py
Labels: cla:yes, backport 1.5.latest

#7741 Adap 496/add test connection mode to debug
  .changes/unreleased/Features-20230604-025956.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/task/debug.py
  plugins/postgres/dbt/adapters/postgres/connections.py
  plugins/postgres/dbt/adapters/postgres/impl.py
  tests/adapter/dbt/tests/adapter/dbt_debug/test_dbt_debug.py
Labels: cla:yes

#7239 ADAP-2: Materialized Views
  .changes/unreleased/Features-20230329-120313.yaml
  core/dbt/adapters/base/relation.py
  core/dbt/adapters/relation_configs/README.md
  core/dbt/adapters/relation_configs/__init__.py
  core/dbt/adapters/relation_configs/config_base.py
  core/dbt/adapters/relation_configs/config_change.py
  core/dbt/adapters/relation_configs/config_validation.py
  core/dbt/context/exceptions_jinja.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/relation.py
  core/dbt/include/global_project/macros/adapters/indexes.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/alter_materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/create_materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/get_materialized_view_configuration_changes.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/refresh_materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/replace_materialized_view.sql
  core/dbt/include/global_project/macros/materializations/seeds/seed.sql
  plugins/postgres/dbt/adapters/postgres/impl.py
  plugins/postgres/dbt/adapters/postgres/relation.py
  plugins/postgres/dbt/adapters/postgres/relation_configs/__init__.py
  plugins/postgres/dbt/adapters/postgres/relation_configs/constants.py
  plugins/postgres/dbt/adapters/postgres/relation_configs/index.py
  plugins/postgres/dbt/adapters/postgres/relation_configs/materialized_view.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view.sql
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view/create.sql
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view/refresh.sql
  plugins/postgres/dbt/include/postgres/macros/relations.sql
  plugins/postgres/setup.py
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  tests/adapter/dbt/tests/adapter/materialized_view/base.py
  tests/adapter/dbt/tests/adapter/materialized_view/on_configuration_change.py
  tests/functional/README.md
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/materializations/materialized_view_tests/fixtures.py
  tests/functional/materializations/materialized_view_tests/test_materialized_view.py
Labels: cla:yes

#7812 Update spec MetricNode for dbt x MetricFlow integration
  .changes/unreleased/Breaking Changes-20230607-190309.yaml
  core/dbt/constants.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/manifest_upgrade.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_yaml_readers.py
  schemas/dbt/manifest/v10.json
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
  tests/functional/artifacts/data/state/v10/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/duplicates/test_duplicate_metric.py
  tests/functional/exposures/fixtures.py
  tests/functional/groups/test_access.py
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metric_deferral.py
  tests/functional/metrics/test_metric_helper_functions.py
  tests/functional/metrics/test_metrics.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/partial_parsing/test_pp_disabled_config.py
  tests/functional/partial_parsing/test_pp_metrics.py
Labels: cla:yes

#7826 [BACKPORT] add --target-path to snapshot command (#7419)
  .changes/unreleased/Fixes-20230420-104254.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#7829 Use project directory in path selector instead of cwd
  .changes/unreleased/Fixes-20230608-135952.yaml
  core/dbt/graph/selector_methods.py
  core/dbt/task/base.py
  core/dbt/task/contextvars.py
  tests/functional/graph_selection/test_graph_selection.py
Labels: cla:yes, backport 1.5.latest

#7779 update adapters url
  .changes/unreleased/Breaking Changes-20230612-161159.yaml
  core/dbt/exceptions.py
Labels: cla:yes

#7834 Allow ProjectDependency to have extra fields
  .changes/unreleased/Fixes-20230609-121930.yaml
  core/dbt/contracts/publication.py
  tests/functional/multi_project/test_publication.py
Labels: cla:yes

#7537 Respect column `quote` config in model contracts
  .changes/unreleased/Fixes-20230506-191813.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/sql/impl.py
  core/dbt/include/global_project/macros/adapters/columns.sql
  core/dbt/include/global_project/macros/materializations/models/table/create_table_as.sql
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  plugins/postgres/dbt/include/postgres/macros/utils/columns_spec_ddl.sql
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
Labels: cla:yes, backport 1.5.latest

#7848 Update SemanticModel node to match DSI 0.1.0dev3 protocols
  .changes/unreleased/Fixes-20230612-175854.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_models.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes, MetricFlow

#7875 Backport #7838 to 1.5.latest
  .changes/unreleased/Fixes-20230609-191546.yaml
  core/dbt/context/providers.py
  core/dbt/parser/manifest.py
  tests/functional/show/fixtures.py
  tests/functional/show/test_show.py
Labels: cla:yes

#7862 Add AdapterRegistered event log message
  .changes/unreleased/Features-20230613-151507.yaml
  core/dbt/adapters/factory.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  tests/unit/test_events.py
Labels: cla:yes, backport 1.5.latest

#7857 Allow setting packages in dependencies.yml and move dependencies to runtime config
  .changes/unreleased/Features-20230613-151917.yaml
  core/dbt/config/project.py
  core/dbt/config/renderer.py
  core/dbt/config/runtime.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/manifest.py
  core/dbt/tests/fixtures/project.py
  tests/functional/dependencies/test_simple_dependency.py
  tests/functional/multi_project/test_publication.py
  tests/functional/partial_parsing/test_partial_parsing.py
  tests/unit/test_config.py
  tests/unit/utils.py
Labels: cla:yes

#7885 [CT-2696] Skip jinia parsing of metric filters
  .changes/unreleased/Fixes-20230615-142949.yaml
  core/dbt/parser/schema_renderer.py
  tests/functional/duplicates/test_duplicate_metric.py
  tests/functional/metrics/fixtures.py
  tests/functional/partial_parsing/fixtures.py
  tests/unit/test_yaml_renderer.py
Labels: cla:yes

#7878 backport 7862 to 1.5.latest
  .changes/unreleased/Features-20230613-151507.yaml
  core/dbt/adapters/factory.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  tests/unit/test_events.py
Labels: cla:yes

#7888 Ct-2690 Support dbt-semantic-interfaces 0.1.0dev5
  .changes/unreleased/Under the Hood-20230615-163217.yaml
  core/setup.py
Labels: cla:yes, semantic

#7903 Upgrade core to support dbt-semantic-interfaces `0.1.0dev7`
  .changes/unreleased/Under the Hood-20230619-135201.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_models.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_manifest.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes, semantic

#7368 Reorganize, annotate, and revise dependency pins
  core/setup.py
Labels: cla:yes, Skip Changelog, dependency_conflicts

#7910 Do not jinja render packages from dependencies yml
  .changes/unreleased/Under the Hood-20230620-180852.yaml
  core/dbt/config/project.py
  core/dbt/config/renderer.py
  core/dbt/config/runtime.py
  tests/functional/dependencies/test_simple_dependency.py
  tests/unit/test_config.py
Labels: cla:yes

#7793 Remove --config-dir instead of fixing #7774
  .changes/unreleased/Fixes-20230621-030733.yaml
  core/dbt/cli/params.py
  core/dbt/task/debug.py
Labels: cla:yes, backport 1.5.latest

#7891 Refactor/unify public and model nodes
  .changes/unreleased/Under the Hood-20230616-131503.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/manifest_upgrade.py
  core/dbt/contracts/graph/node_args.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/publication.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/graph/selector.py
  core/dbt/parser/manifest.py
  core/dbt/task/list.py
  schemas/dbt/manifest/v10.json
  tests/functional/artifacts/data/state/v10/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/list/test_list.py
  tests/functional/multi_project/test_publication.py
  tests/functional/partial_parsing/fixtures.py
  tests/unit/test_contracts_graph_compiled.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_events.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_manifest.py
Labels: cla:yes

#7917 Further Integrate Semantic Models
  .changes/unreleased/Features-20230616-163045.yaml
  core/dbt/compilation.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  tests/functional/partial_parsing/test_pp_semantic_models.py
  tests/functional/retry/test_retry.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
  tests/unit/test_manifest.py
Labels: cla:yes

#7923 Fix: safe remove of external nodes from nodes.depends_on
  .changes/unreleased/Fixes-20230622-121907.yaml
  core/dbt/parser/manifest.py
  tests/functional/multi_project/test_publication.py
Labels: cla:yes

#7927 Rename the semantic_nodes collection to semantic_models
  core/dbt/compilation.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/manifest_upgrade.py
  core/dbt/parser/manifest.py
  schemas/dbt/manifest/v10.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
  tests/unit/test_manifest.py
Labels: cla:yes, Skip Changelog

#7876 Improved Semantic expr specification handling
  .changes/unreleased/Fixes-20230614-134933.yaml
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: bug, cla:yes, semantic

#7877 Improved Semantic Model Measure Percentile defaults
  .changes/unreleased/Fixes-20230614-145954.yaml
  core/dbt/contracts/graph/semantic_models.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: bug, cla:yes, semantic

#7936 Fix Selector Methods to Include Semantic Models
  core/dbt/graph/selector.py
Labels: cla:yes, Skip Changelog

#7951 update mashumaro to 3.8.1
  .changes/unreleased/Under the Hood-20230626-122339.yaml
  core/setup.py
Labels: cla:yes

#7932 Fix comment for `dbt retry`
  core/dbt/cli/main.py
Labels: cla:yes, Skip Changelog, ready_for_review

#7952 Factor Out Repeated Logic in the PartialParsing Class
  core/dbt/parser/partial.py
Labels: cla:yes, Skip Changelog

#5804 Fix macro namespace search packages
  .changes/unreleased/Fixes-20220909-164413.yaml
  core/dbt/context/providers.py
  tests/functional/macros/fixtures.py
  tests/functional/macros/test_macros.py
Labels: cla:yes, Team:Language, ready_for_review

#7930 allow setting enabled and depends_on_nodes from ModelNodeArgs
  .changes/unreleased/Features-20230627-152207.yaml
  core/dbt/contracts/graph/node_args.py
  core/dbt/contracts/graph/nodes.py
Labels: cla:yes

#7966 Set access model node args
  .changes/unreleased/Fixes-20230627-152528.yaml
  core/dbt/contracts/graph/node_args.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/manifest.py
Labels: cla:yes

#7964 Add Partial Parsing Support for Semantic Models
  .changes/unreleased/Features-20230627-123123.yaml
  core/dbt/parser/partial.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: cla:yes

#7961 Backport #7647 to v1.5.x
  .changes/unreleased/Fixes-20230516-152644.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#7925 Handle state:modified for external nodes
  .changes/unreleased/Features-20230622-142002.yaml
  core/dbt/contracts/graph/nodes.py
Labels: cla:yes

#7942 Add thread_id context var
  .changes/unreleased/Features-20230623-173357.yaml
  core/dbt/context/base.py
  tests/adapter/dbt/tests/adapter/hooks/data/seed_model.sql
  tests/adapter/dbt/tests/adapter/hooks/data/seed_run.sql
  tests/adapter/dbt/tests/adapter/hooks/fixtures.py
  tests/adapter/dbt/tests/adapter/hooks/test_model_hooks.py
  tests/adapter/dbt/tests/adapter/hooks/test_run_hooks.py
  tests/functional/context_methods/test_env_vars.py
  tests/functional/context_methods/test_secret_env_vars.py
  tests/unit/test_context.py
Labels: cla:yes, ready_for_review

#7414 Fix CTE insertion position when the model uses WITH RECURSIVE (#7350)
  .changes/unreleased/Fixes-20230420-123221.yaml
  core/dbt/compilation.py
  tests/functional/compile/fixtures.py
  tests/functional/compile/test_compile.py
  third-party-stubs/sqlparse/sql.pyi
Labels: cla:yes, ready_for_review

#7949 Use events.contextvar because of multiprocessing unable to pickle ContextVar
  .changes/unreleased/Fixes-20230626-115838.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/contextvars.py
  core/dbt/graph/selector_methods.py
  core/dbt/task/base.py
  core/dbt/task/contextvars.py
  core/dbt/task/runnable.py
Labels: cla:yes

#7978 Fix unit test which broke due to merge issues
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: cla:yes, Skip Changelog

#7984 CT-2707: Populate metric input measures
  .changes/unreleased/Under the Hood-20230628-142006.yaml
  core/dbt/parser/manifest.py
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metric_configs.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes, semantic

#7665 Unified to UTC
  .changes/unreleased/Fixes-20230525-091955.yaml
  tests/functional/simple_snapshot/test_hard_delete_snapshot.py
Labels: cla:yes, ready_for_review

#7992 type + fix typo in ModelNodeArgs.unique_id
  .changes/unreleased/Fixes-20230629-120321.yaml
  core/dbt/contracts/graph/node_args.py
Labels: cla:yes

#7993 Remove pin of sqlparse, minor refactoring, add tests
  .changes/unreleased/Fixes-20230621-185452.yaml
  core/dbt/compilation.py
  core/setup.py
  tests/functional/compile/test_compile.py
  tests/unit/test_inject_ctes.py
Labels: cla:yes

#7981 [BACKPORT to 1.5.latest] Use events.contextvar because of multiprocessing unable to pickle ContextVar (#7949)
  .changes/unreleased/Fixes-20230626-115838.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/contextvars.py
  core/dbt/graph/selector_methods.py
  core/dbt/task/base.py
  core/dbt/task/contextvars.py
  core/dbt/task/runnable.py
Labels: cla:yes

#7773 [CT-2551] Make state selection MECE
  .changes/unreleased/Features-20230603-141625.yaml
  core/dbt/graph/selector_methods.py
  tests/functional/defer_state/test_modified_state.py
  tests/unit/test_graph_selector_methods.py
Labels: cla:yes, ready_for_review

#7996 Add time spine table configuration to semantic manifest
  .changes/unreleased/Features-20230629-172524.yaml
  core/dbt/contracts/graph/manifest.py
  core/setup.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: cla:yes

#8006 allow on_schema_change: fail for incremental models with contracts
  .changes/unreleased/Fixes-20230629-221615.yaml
  core/dbt/contracts/graph/model_config.py
  tests/functional/configs/test_contract_configs.py
Labels: user docs, cla:yes, backport 1.5.latest

#8008 [BACKPORT to 1.5.latest] Remove pin of sqlparse to below 0.4.4
  .changes/unreleased/Fixes-20230621-185452.yaml
  core/setup.py
Labels: cla:yes

#7995 versioned node selection with underscore delimiting
  .changes/unreleased/Features-20230629-135758.yaml
  core/dbt/graph/selector_methods.py
  tests/unit/test_graph_selector_methods.py
Labels: user docs, cla:yes, model_versions

#7960 fire proper event for inline query error
  .changes/unreleased/Fixes-20230628-144125.yaml
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/task/compile.py
  dev-requirements.txt
  tests/functional/compile/test_compile.py
  tests/functional/show/test_show.py
  tests/unit/test_events.py
Labels: cla:yes, backport 1.5.latest
