Repository dbt-labs/dbt-core, pull requests merged in 2023-07, with the labels that each got.

#8012 Extract Methods to New SemanticManifest Class
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/parser/manifest.py
Labels: cla:yes, Skip Changelog

#8017 CT-2780 [Docs] Fix-toc-links-in-contributing-md
  .changes/unreleased/Docs-20230702-130158.yaml
  CONTRIBUTING.md
Labels: cla:yes

#8021 Backport #7960 to 1.5.latest
  .changes/unreleased/Fixes-20230628-144125.yaml
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/task/compile.py
  dev-requirements.txt
  tests/functional/compile/test_compile.py
  tests/functional/show/test_show.py
  tests/unit/test_events.py
Labels: cla:yes

#8024 Nicer error message for contracted model missing 'columns'
  .changes/unreleased/Fixes-20230704-114752.yaml
  core/dbt/exceptions.py
  core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql
  tests/functional/configs/test_contract_configs.py
Labels: cla:yes, backport 1.5.latest

#8038 ModelNodeArgs.unique_id - include v
  .changes/unreleased/Fixes-20230705-192039.yaml
  core/dbt/contracts/graph/node_args.py
  tests/unit/test_contracts_graph_node_args.py
Labels: cla:yes

#8050 pin click
  .changes/unreleased/Dependencies-20230707-104052.yaml
  core/setup.py
Labels: cla:yes

#8054 [BACKPORT to 1.3.latest] pin click (#8050)
  .changes/unreleased/Dependencies-20230707-104052.yaml
  core/setup.py
Labels: cla:yes

#8053 [BACKPORT to 1.4.latest] pin click (#8050)
  .changes/unreleased/Dependencies-20230707-104052.yaml
  core/setup.py
Labels: cla:yes

#8052 [BACKPORT to 1.5.latest] pin click (#8050)
  .changes/unreleased/Dependencies-20230707-104052.yaml
  core/setup.py
Labels: cla:yes

#8044 add workflow for flaky test testing
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#7973 Do not log traceback when log format is json
  .changes/unreleased/Fixes-20230627-224355.yaml
  core/dbt/events/functions.py
Labels: cla:yes

#8032 partial parse file path
  .changes/unreleased/Under the Hood-20230706-175507.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/parser/manifest.py
  tests/unit/test_parse_manifest.py
Labels: cla:yes

#7892 Update the PR template
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#8049 Semantic Model Validation
  .changes/unreleased/Features-20230707-112838.yaml
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/parser/manifest.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
  tests/unit/test_events.py
Labels: cla:yes

#7200 add negative part number test case for split part cross db util
  .changes/unreleased/Fixes-20230320-153225.yaml
  core/dbt/include/global_project/macros/utils/split_part.sql
  tests/adapter/dbt/tests/adapter/utils/fixture_split_part.py
Labels: cla:yes, Team:Adapters, ready_for_review, pr_tracked

#8068 Remove `create_metric` as a public facing `SemanticModel.Measure` property
  .changes/unreleased/Fixes-20230711-083213.yaml
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
Labels: cla:yes, semantic

#8055 Flaky Test Workflow
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#8071 Use Ubuntu 22.04.2 LTS (Jammy Jellyfish) since it is a long-term supported release
  .changes/unreleased/Fixes-20230711-145311.yaml
  Dockerfile.test
Labels: cla:yes

#8001 Add validate_sql method to base adapter with implementation for SQLAdapters
  .changes/unreleased/Features-20230629-175712.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/sql/connections.py
  core/dbt/adapters/sql/impl.py
  core/dbt/include/global_project/macros/adapters/validate_sql.sql
  tests/adapter/dbt/tests/adapter/utils/test_validate_sql.py
Labels: cla:yes, Team:Adapters

#8076 Update validate sql test classes to new nomenclature
  .changes/unreleased/Fixes-20230711-234737.yaml
  tests/adapter/dbt/tests/adapter/utils/test_validate_sql.py
Labels: cla:yes

#8069 Remove volume declaration
  .changes/unreleased/Fixes-20230711-141432.yaml
  docker/Dockerfile
Labels: cla:yes

#8073 update contributing.md reference to test/integration
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#8079 Er/ct 2675 test custom target
  tests/functional/retry/test_retry.py
Labels: cla:yes, Skip Changelog

#8078 Add semantic_models to tracked resource counts
  .changes/unreleased/Under the Hood-20230712-170559.yaml
  core/dbt/compilation.py
Labels: cla:yes

#8015 CT-2691 Fix the populating of a `Metric`'s `depends_on` property
  .changes/unreleased/Features-20230712-123724.yaml
  core/dbt/compilation.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_models.py
  core/dbt/parser/manifest.py
  core/setup.py
  tests/functional/access/test_access.py
  tests/functional/artifacts/test_previous_version_state.py
  tests/functional/exposures/fixtures.py
  tests/functional/exposures/test_exposure_configs.py
  tests/functional/exposures/test_exposures.py
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metric_configs.py
  tests/functional/metrics/test_metrics.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/partial_parsing/test_pp_disabled_config.py
  tests/functional/partial_parsing/test_pp_metrics.py
  tests/functional/partial_parsing/test_pp_vars.py
Labels: cla:yes, semantic

#8086 add __test__ = False to non-test classes that start with Test
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/schemas.py
Labels: cla:yes, Skip Changelog

#8087 gitignore .user.yml and profiles.yml
  .gitignore
Labels: cla:yes, Skip Changelog

#8084 Backport 8072 1.5.latest3
  .changes/unreleased/Fixes-20230712-164916.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/schemas.py
  test/unit/test_parser.py
  tests/functional/defer_state/fixtures.py
  tests/functional/defer_state/test_modified_state.py
Labels: cla:yes

#8089 [CT-2822] Fix `NonAdditiveDimension` Implementation
  .changes/unreleased/Fixes-20230712-172037.yaml
  core/dbt/contracts/graph/semantic_models.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes

#8085 [CT-2821] Support `dbt-semantic-interfaces~=0.1.0rc1`
  .changes/unreleased/Dependencies-20230712-165219.yaml
  .changes/unreleased/Fixes-20230712-172037.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_models.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: dependencies, cla:yes

#7928 Fix query comment tests
  .changes/unreleased/Fixes-20230623-092933.yaml
  tests/adapter/dbt/tests/adapter/query_comment/test_query_comment.py
Labels: cla:yes, ok_to_test, Team:Adapters, ready_for_review

#8097 add env vars for datadog ci visibility
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#8099 Apply new integration tests to existing framework to identify supported features
  .changes/unreleased/Features-20230714-144909.yaml
  core/dbt/tests/util.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view.sql
  tests/adapter/dbt/tests/adapter/materialized_view/base.py
  tests/adapter/dbt/tests/adapter/materialized_view/basic.py
  tests/adapter/dbt/tests/adapter/materialized_view/changes.py
  tests/adapter/dbt/tests/adapter/materialized_view/files.py
  tests/adapter/dbt/tests/adapter/materialized_view/on_configuration_change.py
  tests/functional/materializations/materialized_view_tests/fixtures.py
  tests/functional/materializations/materialized_view_tests/test_materialized_view.py
  tests/functional/materializations/materialized_view_tests/utils.py
Labels: cla:yes

#8111 bumpversion 1.7.0a1
  .bumpversion.cfg
  core/dbt/version.py
  core/setup.py
  docker/Dockerfile
  plugins/postgres/dbt/adapters/postgres/__version__.py
  plugins/postgres/setup.py
  tests/adapter/dbt/tests/adapter/__version__.py
  tests/adapter/setup.py
Labels: cla:yes, Skip Changelog

#8107 [Backport 1.5.latest] Add Datadog Env Vars + Flaky Tester
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#8105 [Backport 1.4.latest] Add Datadog Env Vars + Flaky Tester
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#8106 [Backport 1.3.latest] Add Datadog Env Vars + Flaky Tester
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  dev-requirements.txt
  tox.ini
Labels: cla:yes, Skip Changelog

#8129 wrap deprecation warnings in warn_or_error calls
  .changes/unreleased/Fixes-20230718-125518.yaml
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  tests/functional/deprecations/model_deprecations.py
Labels: cla:yes, backport 1.6.latest

#8147 Rm docs changelog entry
  .changes/unreleased/Docs-20230531-115419.yaml
Labels: cla:yes, Skip Changelog

#8150 Rearrange pp_versioned_models test
  .changes/unreleased/Under the Hood-20230719-124611.yaml
  tests/functional/partial_parsing/test_partial_parsing.py
  tests/functional/partial_parsing/test_versioned_models.py
Labels: cla:yes

#8143 format exception from dbtPlugin.initialize
  .changes/unreleased/Under the Hood-20230719-163334.yaml
  core/dbt/plugins/manager.py
  tests/unit/test_plugin_manager.py
Labels: cla:yes, backport 1.6.latest

#8101 Correcting spelling of partition
  .changes/unreleased/Docs-20230715-200907.yaml
  core/dbt/include/global_project/macros/etc/datetime.sql
  tests/functional/artifacts/data/state/v1/manifest.json
  tests/functional/artifacts/data/state/v10/manifest.json
  tests/functional/artifacts/data/state/v2/manifest.json
  tests/functional/artifacts/data/state/v3/manifest.json
  tests/functional/artifacts/data/state/v4/manifest.json
  tests/functional/artifacts/data/state/v5/manifest.json
  tests/functional/artifacts/data/state/v6/manifest.json
  tests/functional/artifacts/data/state/v7/manifest.json
  tests/functional/artifacts/data/state/v8/manifest.json
  tests/functional/artifacts/data/state/v9/manifest.json
Labels: cla:yes, ready_for_review

#8174 add a node status
  .changes/unreleased/Fixes-20230720-122723.yaml
  core/dbt/task/compile.py
Labels: cla:yes, backport 1.5.latest, backport 1.6.latest

#8176 Add implementation issue template
  .github/ISSUE_TEMPLATE/implementation-ticket.yml
Labels: cla:yes, Skip Changelog

#8182 [CT-1849] `_connection_exception_retry` handles `EOFError` exceptions
  .changes/unreleased/Fixes-20230720-172422.yaml
  core/dbt/utils.py
  tests/unit/test_core_dbt_utils.py
Labels: cla:yes

#7944 Fixed double underline
  .changes/unreleased/Fixes-20230625-142731.yaml
  core/dbt/include/global_project/macros/adapters/metadata.sql
  plugins/postgres/dbt/adapters/postgres/impl.py
  plugins/postgres/dbt/include/postgres/macros/relations.sql
Labels: cla:yes, Team:Adapters, ready_for_review

#8181 [CT-1483] Let macro names include word materialization
  .changes/unreleased/Fixes-20230720-170112.yaml
  core/dbt/parser/macros.py
  tests/functional/macros/fixtures.py
  tests/functional/macros/test_macros.py
Labels: cla:yes

#8180 [CT-2594] Fix serialization of `warn_error_options` on Contexts
  .changes/unreleased/Fixes-20230720-161513.yaml
  core/dbt/utils.py
  tests/unit/test_context.py
Labels: cla:yes

#8198 [CT-2594] Backport #8180 to 1.5.latest
  .changes/unreleased/Fixes-20230720-161513.yaml
  core/dbt/utils.py
  test/unit/test_context.py
Labels: cla:yes

#8197 [CT-2594] Backport #8180 to 1.6.latest
  .changes/unreleased/Fixes-20230720-161513.yaml
  core/dbt/utils.py
  tests/unit/test_context.py
Labels: cla:yes

#8196 [CT-1483] Backport #8181 to 1.6.latest
  .changes/unreleased/Fixes-20230720-170112.yaml
  core/dbt/parser/macros.py
  tests/functional/macros/fixtures.py
  tests/functional/macros/test_macros.py
Labels: cla:yes

#8193 Check for existing_relation immediately prior to renaming
  core/dbt/include/global_project/macros/materializations/models/table/table.sql
  core/dbt/include/global_project/macros/materializations/models/view/view.sql
Labels: cla:yes, Skip Changelog

#8200 add param to control maxBytes for single dbt.log file
  .changes/unreleased/Under the Hood-20230724-150654.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/events/eventmgr.py
  core/dbt/events/functions.py
  core/dbt/tests/fixtures/project.py
  tests/unit/test_cli_flags.py
  tests/unit/test_functions.py
  tests/unit/test_graph.py
Labels: cla:yes, backport 1.6.latest

#8206 Update Core for Latest dbt-extractor with Version Parsing
  .changes/unreleased/Under the Hood-20230725-102609.yaml
  core/dbt/parser/models.py
  core/setup.py
Labels: cla:yes

#8208 Update implementation-ticket.yml
  .github/ISSUE_TEMPLATE/implementation-ticket.yml
Labels: cla:yes, Skip Changelog

#8157 [Backport 1.5.latest] Rearrange pp_versioned_models test
  .changes/unreleased/Under the Hood-20230719-124611.yaml
  core/dbt/include/global_project/macros/materializations/models/table/table.sql
  core/dbt/include/global_project/macros/materializations/models/view/view.sql
  tests/functional/partial_parsing/test_partial_parsing.py
  tests/functional/partial_parsing/test_versioned_models.py
Labels: cla:yes

#8218 Bump timeout to 120 min
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#8215 Initialize sqlparse lexer and tweak order of setting compilation fields
  .changes/unreleased/Fixes-20230726-104448.yaml
  core/dbt/compilation.py
Labels: cla:yes

#8221 [Backport 1.5.latest] Initialize sqlparse lexer and tweak order of setting compilation fields
  .changes/unreleased/Fixes-20230726-104448.yaml
  core/dbt/compilation.py
Labels: cla:yes

#8117 Ensure that target_schema from snapshot config is promoted to node level
  .changes/unreleased/Fixes-20230717-160652.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/parser/base.py
  tests/functional/simple_snapshot/fixtures.py
  tests/functional/simple_snapshot/test_basic_snapshot.py
Labels: cla:yes, backport 1.5.latest, backport 1.6.latest

#8236 pin upper bound for sqlparse
  .changes/unreleased/Dependencies-20230727-145726.yaml
  core/setup.py
Labels: cla:yes

#8235 [CT-2879] Fix unbound variable error in `checked_agg_time_dimension_for_measure`
  .changes/unreleased/Fixes-20230727-125830.yaml
  core/dbt/contracts/graph/nodes.py
  tests/unit/test_semantic_models.py
Labels: cla:yes, semantic, backport 1.6.latest

#8237 [Fix] raise execution errors for runnable tasks
  .changes/unreleased/Fixes-20230728-115620.yaml
  core/dbt/task/runnable.py
  tests/functional/compile/test_compile.py
  tests/functional/dependencies/test_local_dependency.py
  tests/functional/show/test_show.py
Labels: cla:yes

#8240 [BACKPORT][CT-2879] Backport #8235 to 1.6.latest
  .changes/unreleased/Fixes-20230727-125830.yaml
  core/dbt/contracts/graph/nodes.py
  tests/unit/test_semantic_models.py
Labels: cla:yes

#8232 loosen the click pin
  .changes/unreleased/Dependencies-20230727-145703.yaml
  core/dbt/cli/params.py
  core/setup.py
Labels: cla:yes

#8250 [CT-2888] Support dbt-semantic-interfaces 0.2.0
  .changes/unreleased/Dependencies-20230728-135227.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  tests/functional/duplicates/test_duplicate_metric.py
  tests/functional/metrics/fixtures.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
  tests/unit/test_yaml_renderer.py
Labels: dependencies, cla:yes, semantic, backport 1.6.latest

#8251 [BACKPORT][CT-2888] Backport #8247 to 1.6.latest
  .changes/unreleased/Dependencies-20230728-135227.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  tests/functional/duplicates/test_duplicate_metric.py
  tests/functional/metrics/fixtures.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
  tests/unit/test_yaml_renderer.py
Labels: dependencies, cla:yes, semantic

#8258 hard code test splits
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#8226 Add tests for specifcally checking the population of `SemanticModel.depends_on`
  tests/functional/semantic_models/fixtures.py
  tests/functional/semantic_models/test_semantic_models.py
Labels: cla:yes, Skip Changelog

#8256 Fix flake8 failures
  core/dbt/clients/agate_helper.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  core/dbt/parser/schemas.py
Labels: cla:yes, Skip Changelog
