Repository dbt-labs/dbt-core, pull requests merged in 2023-08, with the labels that each got.

#7186 Support configurable delimiter for seed files, default to comma (#3990)
  .changes/unreleased/Features-20230714-202445.yaml
  core/dbt/clients/agate_helper.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/model_config.py
  tests/adapter/dbt/tests/adapter/simple_seed/fixtures.py
  tests/adapter/dbt/tests/adapter/simple_seed/seeds.py
  tests/adapter/dbt/tests/adapter/simple_seed/test_seed.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/unit/test_contracts_graph_parsed.py
Labels: cla:yes, ready_for_review

#8210 Issue One Event Per Node Failure
  .changes/unreleased/Breaking Changes-20230725-171359.yaml
  core/dbt/events/eventmgr.py
  core/dbt/events/functions.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/task/printer.py
  tests/unit/test_events.py
Labels: cla:yes

#8298 fix constructing param with 0 value
  .changes/unreleased/Fixes-20230802-141556.yaml
  core/dbt/cli/flags.py
  tests/unit/test_cli_flags.py
Labels: cla:yes

#8265 capitalize integration-report name
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#8259 Split integration tests into parallel groups / jobs (#6346)
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#8308 add formatting events into json logs
  core/dbt/events/functions.py
  tests/functional/logging/test_logging.py
Labels: cla:yes, Skip Changelog

#7998 [CT-2776] [Feature] Enable-post-parse-population-of-dbt-custom-env
  .changes/unreleased/Features-20230702-122813.yaml
  core/dbt/events/functions.py
Labels: cla:yes, ready_for_review

#8329 Update implementation-ticket.yml to reference adapters
  .github/ISSUE_TEMPLATE/implementation-ticket.yml
Labels: cla:yes, Skip Changelog

#8332 Update implementation-ticket.yml
  .github/ISSUE_TEMPLATE/implementation-ticket.yml
Labels: cla:yes, Skip Changelog

#8324 Fix missing quote in fixtures.py
  tests/functional/semantic_models/fixtures.py
Labels: cla:yes, Skip Changelog

#7447 Copy dir if symlink fails
  .changes/unreleased/Fixes-20230424-210734.yaml
  core/dbt/deps/local.py
  tests/unit/test_deps.py
Labels: cla:yes, test postgres, ready_for_review

#8222 fixed comment util.py
  .changes/unreleased/Docs-20230727-170900.yaml
  core/dbt/tests/util.py
Labels: cla:yes, ready_for_review

#8264 Detect changes to model access, deprecation_date, and latest_version in state:modified
  .changes/unreleased/Fixes-20230806-222319.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/node_types.py
  tests/functional/defer_state/test_modified_state.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_graph_selector_methods.py
Labels: cla:yes, backport 1.6.latest

#8336 track plugin.get_nodes
  .changes/unreleased/Under the Hood-20230809-094834.yaml
  core/dbt/plugins/manager.py
  core/dbt/tracking.py
  tests/unit/test_plugin_manager.py
Labels: cla:yes, backport 1.6.latest

#8365 add env vars to tox.ini
  tox.ini
Labels: cla:yes, Skip Changelog

#8362 track plugin.get_nodes (#8336)
  .changes/unreleased/Under the Hood-20230809-094834.yaml
  core/dbt/plugins/manager.py
  core/dbt/tracking.py
  tests/unit/test_plugin_manager.py
Labels: cla:yes

#8364 fix ModelNodeArgs.fqn
  .changes/unreleased/Fixes-20230811-204144.yaml
  core/dbt/contracts/graph/node_args.py
  core/dbt/contracts/graph/nodes.py
  tests/unit/test_contracts_graph_node_args.py
Labels: cla:yes, backport 1.6.latest

#8330 Fix: deleting models that depend on external nodes
  .changes/unreleased/Fixes-20230811-212008.yaml
  core/dbt/parser/manifest.py
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes, backport 1.6.latest

#8361 add --no-partial-parse-file-diff flag
  .changes/unreleased/Under the Hood-20230811-100902.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/parser/manifest.py
  tests/functional/partial_parsing/test_file_diff.py
Labels: cla:yes, backport 1.6.latest

#8310 [CT-2526] Add ability to automatically create metrics from semantic model measures
  .changes/unreleased/Features-20230803-151824.yaml
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/partial.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: cla:yes, semantic

#8231 [Backport 1.5.latest] Ensure that target_schema from snapshot config is promoted to node level
  .changes/unreleased/Fixes-20230717-160652.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/parser/base.py
  tests/functional/simple_snapshot/fixtures.py
  tests/functional/simple_snapshot/test_basic_snapshot.py
Labels: cla:yes

#8352 [Backport 1.6.latest] Update manifest schema to contain late-breaking manifest changes
  .changes/unreleased/Under the Hood-20230807-164509.yaml
  schemas/dbt/manifest/v10.json
Labels: cla:yes

#8413 Fix run_results.json Performance Regression
  .changes/unreleased/Fixes-20230815-104444.yaml
  core/dbt/task/runnable.py
Labels: cla:yes, backport 1.6.latest

#8252 [Backport 1.5.latest] loosen the click pin
  .changes/unreleased/Dependencies-20230727-145703.yaml
  core/dbt/cli/params.py
  core/setup.py
Labels: cla:yes

#8239 [BACKPORT 1.5.latest] pin upper bound for sqlparse (#8236)
  .changes/unreleased/Dependencies-20230727-145726.yaml
  core/setup.py
Labels: cla:yes

#8416 Add return values to functions to fix mypy warnings
  .changes/unreleased/Under the Hood-20230815-170307.yaml
  core/dbt/adapters/base/query_headers.py
  core/dbt/clients/jinja.py
  core/dbt/context/macro_resolver.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/common.py
  core/dbt/semver.py
  core/dbt/task/debug.py
  core/dbt/task/run.py
  core/dbt/tests/util.py
Labels: cla:yes

#8388 Fix using project-dir with list command and path selector
  .changes/unreleased/Fixes-20230814-145702.yaml
  core/dbt/task/list.py
  tests/functional/graph_selection/test_graph_selection.py
Labels: cla:yes

#8434 Temporarily Disable test_run_results_are_written_on_signal Test
  tests/functional/artifacts/test_run_results.py
Labels: cla:yes, Skip Changelog

#8418 change workflow trigger
  .github/workflows/docs-issue.yml
Labels: cla:yes, Skip Changelog

#8432 Fix test failures
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog, backport 1.6.latest

#8419 [Backport] Fix run_results.json Performance Regression
  .changes/unreleased/Fixes-20230815-104444.yaml
  core/dbt/task/runnable.py
  tests/functional/artifacts/test_run_results.py
Labels: cla:yes

#8440 Add doc string context to Identifier validion regex rule
  core/dbt/contracts/util.py
Labels: cla:yes, Skip Changelog

#8443 Fix mypy warnings for ManifestLoader.load()
  .changes/unreleased/Under the Hood-20230817-134548.yaml
  core/dbt/parser/manifest.py
  core/dbt/parser/read_files.py
Labels: cla:yes

#8445 revert python version for docker images
  .changes/unreleased/Fixes-20230817-130915.yaml
  docker/Dockerfile
Labels: cla:yes

#8442 [BACKPORT 1.6.latest] Fix test failures (#8432)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#8454 [CT-3013] Fix parsing of `window_groupings`
  .changes/unreleased/Fixes-20230818-095348.yaml
  core/dbt/contracts/graph/unparsed.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: cla:yes, backport 1.6.latest

#8306 update `Number` class to handle integer values
  .changes/unreleased/Fixes-20230803-093502.yaml
  core/dbt/clients/agate_helper.py
  tests/functional/show/fixtures.py
  tests/functional/show/test_show.py
  tests/unit/test_agate_helper.py
Labels: cla:yes, backport 1.6.latest

#8212 Improve docker image README
  .changes/unreleased/Docs-20230728-193438.yaml
  docker/README.md
Labels: cla:yes, ready_for_review

#8459 ADAP-814: Refactor prep for MV updates
  .changes/unreleased/Under the Hood-20230821-134801.yaml
  core/dbt/include/global_project/macros/adapters/drop_relation.sql
  core/dbt/include/global_project/macros/adapters/relation.sql
  core/dbt/include/global_project/macros/adapters/relations/materialized_view/_replace.sql
  core/dbt/include/global_project/macros/adapters/relations/materialized_view/alter.sql
  core/dbt/include/global_project/macros/adapters/relations/materialized_view/create.sql
  core/dbt/include/global_project/macros/adapters/relations/materialized_view/drop.sql
  core/dbt/include/global_project/macros/adapters/relations/materialized_view/refresh.sql
  core/dbt/include/global_project/macros/adapters/relations/table/drop.sql
  core/dbt/include/global_project/macros/adapters/relations/view/drop.sql
  core/dbt/include/global_project/macros/relations/drop.sql
  core/dbt/include/global_project/macros/relations/rename.sql
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/_replace.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/alter.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/create.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/describe.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/refresh.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/rename.sql
Labels: cla:yes, Skip Changelog

#8463 swap changelog workflow trigger
  .github/workflows/changelog-existence.yml
Labels: cla:yes, Skip Changelog

#8466 update the implementation template
  .github/ISSUE_TEMPLATE/implementation-ticket.yml
Labels: cla:yes, Skip Changelog

#8455 [Backport 1.6.latest] Fix parsing of `window_groupings` (#8454)
  .changes/unreleased/Fixes-20230818-095348.yaml
  core/dbt/contracts/graph/unparsed.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: cla:yes

#8474 Split tests into classes
  tests/functional/show/test_show.py
Labels: cla:yes, Skip Changelog

#8475 [BACKPORT] split up tests into classes
  tests/functional/show/test_show.py
Labels: cla:yes, Skip Changelog

#8478 revert update agate for int
  .changes/unreleased/Fixes-20230803-093502.yaml
  core/dbt/clients/agate_helper.py
  tests/functional/show/fixtures.py
  tests/functional/show/test_show.py
  tests/unit/test_agate_helper.py
Labels: cla:yes, Skip Changelog

#8485 ADAP-845: Update BaseAdapter to meet mypy standards
  .changes/unreleased/Under the Hood-20230823-194237.yaml
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/sql/connections.py
Labels: cla:yes

#8488 Fix ambiguous reference error for duplicate model names across packages with tests
  .changes/unreleased/Fixes-20230824-161024.yaml
  core/dbt/parser/schema_generic_tests.py
  core/dbt/parser/schemas.py
  tests/functional/duplicates/test_duplicate_model.py
  tests/unit/test_parser.py
Labels: cla:yes, backport 1.6.latest

#8495 Safely remove external nodes from manifest
  .changes/unreleased/Fixes-20230828-125858.yaml
  core/dbt/parser/manifest.py
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes

#8456 [CT-2840] Improved semantic layer protocol satisfaction tests
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes, Skip Changelog

#8477 8295 unit testing artifacts
  .changes/unreleased/Features-20230828-101825.yaml
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/compilation.py
  core/dbt/constants.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/manifest_upgrade.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/graph/selector_spec.py
  core/dbt/node_types.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  core/dbt/parser/unit_tests.py
  core/dbt/task/runnable.py
  core/dbt/task/unit_test.py
  schemas/dbt/manifest/v11.json
  tests/functional/artifacts/data/state/v11/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/graph_selection/test_graph_selection.py
  tests/unit/test_manifest.py
Labels: cla:yes

#8500 Backport 8210
  .changes/unreleased/Breaking Changes-20230725-171359.yaml
  core/dbt/events/eventmgr.py
  core/dbt/events/functions.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/task/printer.py
  tests/unit/test_events.py
Labels: cla:yes

#8492 Include Compiled Node Attributes in run_results.json
  .changes/unreleased/Features-20230821-103357.yaml
  core/dbt/contracts/results.py
  core/dbt/tests/util.py
  schemas/dbt/run-results/v5.json
  tests/functional/artifacts/expected_run_results.py
  tests/functional/assertions/test_runner.py
  tests/functional/compile/test_compile.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: cla:yes

#8523 Add return value to AdapterContainer.__init__ and AdapterMeta.__new__
  .changes/unreleased/Under the Hood-20230830-140231.yaml
  core/dbt/adapters/base/meta.py
  core/dbt/adapters/factory.py
Labels: cla:yes

#8502 Semantic model configs - enable/disable + groups
  .changes/unreleased/Features-20230828-092100.yaml
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/context/context_config.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/graph/selector.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_yaml_readers.py
  schemas/dbt/manifest/v11.json
  tests/functional/semantic_models/fixtures.py
  tests/functional/semantic_models/test_semantic_model_configs.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
  tests/functional/semantic_models/test_semantic_models.py
Labels: cla:yes

#8524 Fix snapshot success message to display "INSERT 0 1" (for example) instead of "success"
  .changes/unreleased/Fixes-20230830-150803.yaml
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/task/snapshot.py
Labels: cla:yes

#8531 [Backport to 1.5.latest] Fix snapshot success message
  .changes/unreleased/Fixes-20230830-150803.yaml
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/task/snapshot.py
Labels: cla:yes

#8532 [Backport to 1.4.latest] Fix snapshot success message
  .changes/unreleased/Fixes-20230830-150803.yaml
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/task/snapshot.py
Labels: cla:yes

#8525 Fix untyped functions in `core/dbt/context/base.py`
  core/dbt/context/base.py
  core/dbt/context/configured.py
  core/dbt/context/docs.py
  core/dbt/context/manifest.py
  core/dbt/context/providers.py
  core/dbt/context/secret.py
  core/dbt/context/target.py
Labels: cla:yes, Skip Changelog
