Repository dbt-labs/dbt-core, pull requests merged in 2023-02, with the labels that each got.

#6813 Lazily call --version
  .changes/unreleased/Under the Hood-20230131-141806.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/docs/build/doctrees/environment.pickle
Labels: cla:yes

#6810 [BACKPORT] fix contributor list generation (#6799)
  .changie.yaml
  .github/workflows/bot-changelog.yml
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#6809 [BACKPORT] fix contributor list generation (#6799)
  .changie.yaml
  .github/workflows/bot-changelog.yml
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#6808 [BACKPORT] fix contributor list generation (#6799)
  .changie.yaml
Labels: cla:yes, Skip Changelog

#6807 [BACKPORT] fix contributor list generation (#6799)
  .changie.yaml
  .github/workflows/bot-changelog.yml
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#6793 [CI/CD] Backport release workflow to `1.4.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, repo ci/cd, Skip Changelog

#6838 CT 2000 fix semver prerelease comparisons
  .changes/unreleased/Fixes-20230201-154418.yaml
  core/dbt/semver.py
  core/setup.py
  test/unit/test_semver.py
Labels: cla:yes

#6839 update regex to match all iterations
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#6816 move test_store_test_failures.py to adapter zone
  tests/adapter/dbt/tests/adapter/store_test_failures_tests/fixtures.py
  tests/adapter/dbt/tests/adapter/store_test_failures_tests/test_store_test_failures.py
Labels: cla:yes, Skip Changelog

#6790 [CI/CD] Backport release workflow to `1.1.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, repo ci/cd, Skip Changelog

#6792 [CI/CD] Backport release workflow to `1.3.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, repo ci/cd, Skip Changelog

#6791 [CI/CD] Backport release workflow to `1.2.latest`
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, repo ci/cd, Skip Changelog

#6856 Test fix: `TestProfileEnvVars::test_profile_env_vars`
  tests/functional/partial_parsing/test_pp_vars.py
Labels: cla:yes, Skip Changelog

#6846 [BACKPORT] 1.4.latest update regex to match all iterations (#6839)
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#6877 Remove unused `cli_runner`
  core/dbt/cli/main.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/setup.py
Labels: cla:yes, Skip Changelog

#6859 [CT-1959]: moving simple_seed tests to adapter zone
  .changes/unreleased/Under the Hood-20230203-143551.yaml
  core/dbt/tests/util.py
  tests/adapter/dbt/tests/adapter/simple_seed/fixtures.py
  tests/adapter/dbt/tests/adapter/simple_seed/seed_bom.csv
  tests/adapter/dbt/tests/adapter/simple_seed/seeds.py
  tests/adapter/dbt/tests/adapter/simple_seed/test_seed.py
  tests/adapter/dbt/tests/adapter/simple_seed/test_seed_type_override.py
  tests/functional/simple_seed/data/seed.with.dots.csv
  tests/functional/simple_seed/data/seed_actual.csv
  tests/functional/simple_seed/data/seed_unicode.csv
  tests/functional/simple_seed/fixtures.py
Labels: cla:yes

#6886 Fix a regression in the behavior of the -q/--quiet cli parameter
  .changes/unreleased/Fixes-20230207-143544.yaml
  core/dbt/events/functions.py
  core/dbt/main.py
Labels: cla:yes

#6887 flags.THREADS defaults to None
  .changes/unreleased/Under the Hood-20230207-165111.yaml
  core/dbt/cli/params.py
  core/dbt/docs/build/doctrees/environment.pickle
Labels: cla:yes

#6893 NoneConfig for DebugTask
  core/dbt/cli/main.py
  core/dbt/docs/build/doctrees/environment.pickle
Labels: cla:yes, Skip Changelog

#6682 Dynamically list all `.latest` branches for scheduled testing
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#6889 Backport to 1.4.latest: Fix a regression in the behavior of the -q/--quiet cli param…
  .changes/unreleased/Fixes-20230207-143544.yaml
  core/dbt/events/functions.py
  core/dbt/main.py
Labels: cla:yes

#6890 use UnsetProfile in deps and clean commands
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/docs/build/doctrees/environment.pickle
Labels: cla:yes, Skip Changelog

#6700 add base class for merge exclude tests
  .changes/unreleased/Fixes-20230123-132814.yaml
  tests/adapter/dbt/tests/adapter/incremental/test_incremental_merge_exclude_columns.py
Labels: cla:yes, Team:Adapters, ready_for_review

#6899 1.4 regression: Check if status has node attribute
  .changes/unreleased/Fixes-20230208-110551.yaml
  core/dbt/task/run.py
  tests/functional/hooks/fixtures.py
  tests/functional/hooks/test_run_hooks.py
Labels: cla:yes

#6904 [BACKPORT] 1.4 regression: Check if status has node attribute (#6899)
  .changes/unreleased/Fixes-20230208-110551.yaml
  core/dbt/task/run.py
  tests/functional/hooks/fixtures.py
  tests/functional/hooks/test_run_hooks.py
Labels: cla:yes

#6905 Docs generate doesn't write manifest
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/docs/build/html/.buildinfo
  core/dbt/docs/build/html/_static/_sphinx_javascript_frameworks_compat.js
  core/dbt/docs/build/html/_static/alabaster.css
  core/dbt/docs/build/html/_static/basic.css
  core/dbt/docs/build/html/_static/doctools.js
  core/dbt/docs/build/html/_static/jquery-3.6.0.js
  core/dbt/docs/build/html/_static/jquery.js
  core/dbt/docs/build/html/_static/language_data.js
  core/dbt/docs/build/html/_static/pygments.css
  core/dbt/docs/build/html/_static/searchtools.js
  core/dbt/docs/build/html/_static/underscore-1.13.1.js
  core/dbt/docs/build/html/_static/underscore.js
  core/dbt/docs/build/html/genindex.html
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/search.html
  tests/functional/docs/test_generate.py
Labels: cla:yes

#6910 profiles dir exists=False for dbt debug
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/docs/build/html/.buildinfo
  core/dbt/docs/build/html/_static/_sphinx_javascript_frameworks_compat.js
  core/dbt/docs/build/html/_static/alabaster.css
  core/dbt/docs/build/html/_static/basic.css
  core/dbt/docs/build/html/_static/doctools.js
  core/dbt/docs/build/html/_static/jquery-3.6.0.js
  core/dbt/docs/build/html/_static/jquery.js
  core/dbt/docs/build/html/_static/language_data.js
  core/dbt/docs/build/html/_static/pygments.css
  core/dbt/docs/build/html/_static/searchtools.js
  core/dbt/docs/build/html/_static/underscore-1.13.1.js
  core/dbt/docs/build/html/_static/underscore.js
  core/dbt/docs/build/html/genindex.html
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/search.html
Labels: cla:yes, Skip Changelog

#6851 Add back `depends_on` for seeds - only `macros`, never `nodes`
  .changes/unreleased/Fixes-20230203-135557.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/util.py
  schemas/dbt/manifest/v8.json
  test/unit/test_contracts_graph_parsed.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/hooks/test_model_hooks.py
  tests/functional/list/test_list.py
Labels: cla:yes, Team:Language

#6909 Ensure flush() after logging write()
  .changes/unreleased/Fixes-20230208-154935.yaml
  core/dbt/events/eventmgr.py
Labels: cla:yes

#6922 [Backport] [CT-2063] Ensure flush() called after write() for console log output
  .changes/unreleased/Fixes-20230208-154935.yaml
  core/dbt/events/eventmgr.py
Labels: cla:yes

#6898 Fix test_builtin_invocation_args_dict_function
  core/dbt/cli/flags.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/flags.py
  core/dbt/main.py
  core/dbt/tracking.py
  test/unit/test_manifest.py
  tests/functional/context_methods/test_builtin_functions.py
  tests/unit/test_cli_flags.py
Labels: cla:yes, Skip Changelog

#6883 Update link to `dbt` install docs
  .changes/unreleased/Docs-20230207-123807.yaml
  README.md
Labels: cla:yes

#6925 [BACKPORT] 1.4.latest Add most recent dbt-docs changes (#6923)
  .changes/unreleased/Docs-20230209-082901.yaml
  core/dbt/include/index.html
Labels: cla:yes

#6937 CT-2079: Re-apply accidentally reverted logging fix
  .changes/unreleased/Fixes-20230210-103028.yaml
  core/dbt/events/eventmgr.py
Labels: cla:yes

#6941 handle_and_check in main.py
  core/dbt/cli/main.py
  core/dbt/docs/build/doctrees/environment.pickle
Labels: cla:yes, Skip Changelog

#6947 Fix types.proto and test_events.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  tests/unit/test_events.py
Labels: cla:yes, Skip Changelog

#6912 ExposureOwner: Rename to Owner, accept additional fields, require one of 'name' or 'email'
  .changes/unreleased/Features-20230209-092059.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
Labels: cla:yes

#6907 remove '+nightly' from release test version
  .github/workflows/nightly-release.yml
Labels: cla:yes, Skip Changelog

#6961 CT 1921 add missing nodes to previous state test
  .changes/unreleased/Fixes-20230213-170723.yaml
  core/dbt/contracts/graph/manifest.py
  tests/functional/artifacts/data/state/v7/manifest.json
  tests/functional/artifacts/data/state/v8/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes

#6967 [BACKPORT 1.4.latest] Fix state comparison with disabled exposure (or metric)
  .changes/unreleased/Fixes-20230213-170723.yaml
  .changes/unreleased/Fixes-20230213-211257.yaml
  core/dbt/contracts/graph/manifest.py
Labels: cla:yes

#6940 Fix petits logging regressions from `feature/click-cli` merge
  .changes/unreleased/Fixes-20230213-130522.yaml
  core/dbt/cli/requires.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/events/functions.py
Labels: cla:yes

#6966 remove `+nightly` from version parsing
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#6854 Automate cutting new .latest branches
  .github/workflows/cut-release-branch.yml
Labels: cla:yes, Skip Changelog

#6908 dbt_project.yml log-path respects project directory
  core/dbt/cli/flags.py
  core/dbt/cli/resolvers.py
  core/dbt/docs/build/doctrees/environment.pickle
  tests/functional/cli/test_resolvers.py
  tests/unit/test_cli_flags.py
Labels: cla:yes, regression, Skip Changelog

#6949 Set relation_name in tests at compile time
  .changes/unreleased/Fixes-20230210-194157.yaml
  core/dbt/compilation.py
  tests/functional/artifacts/test_artifact_fields.py
Labels: cla:yes, backport 1.4.latest

#6964 add helper function for load project/profile
  core/dbt/lib.py
Labels: cla:yes, Skip Changelog

#6973 Point workflow to main
  .github/workflows/cut-release-branch.yml
Labels: cla:yes, Skip Changelog

#6977 Remove empty changie file
  .changes/unreleased/Fixes-20230213-170723.yaml
Labels: cla:yes, Skip Changelog

#6271 dbt Constraints / model contracts
  .changes/unreleased/Features-20221118-141120.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql
  core/dbt/include/global_project/macros/materializations/models/table/create_table_as.sql
  core/dbt/parser/base.py
  core/dbt/parser/schemas.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  plugins/postgres/dbt/include/postgres/macros/utils/columns_spec_ddl.sql
  schemas/dbt/manifest/v8.json
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_manifest.py
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_constraint_configs.py
  tests/functional/docs/test_good_docs_blocks.py
  tests/functional/list/test_list.py
Labels: cla:yes

#6982 Make use of hashlib.md5() FIPS compliant
  .changes/unreleased/Fixes-20230215-104536.yaml
  core/dbt/config/project.py
  core/dbt/contracts/connection.py
  core/dbt/deps/git.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/schemas.py
  core/dbt/utils.py
Labels: cla:yes, Team:Language, ready_for_review

#6934 Fixing exposure error
  .changes/unreleased/Under the Hood-20230210-084647.yaml
  core/dbt/parser/manifest.py
Labels: cla:yes, Team:Language

#6921 parse group resource
  .changes/unreleased/Features-20230209-093409.yaml
  core/dbt/compilation.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/util.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/node_types.py
  core/dbt/parser/README.md
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v8.json
  test/unit/test_manifest.py
  test/unit/test_node_types.py
  tests/functional/artifacts/data/state/v8/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes

#6742 Use IEC standard abbreviations (GiB, TiB, etc)
  .changes/unreleased/Under the Hood-20230130-153306.yaml
  core/dbt/utils.py
  test/unit/test_utils.py
Labels: cla:yes, ready_for_review

#6990 fix small issues with flags and logger to support dbt-rpc
  core/dbt/cli/flags.py
  core/dbt/cli/requires.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/events/functions.py
  core/dbt/flags.py
  core/dbt/lib.py
  core/dbt/task/base.py
  core/dbt/task/list.py
  core/dbt/tests/fixtures/project.py
Labels: cla:yes, Skip Changelog

#6995 CT 2026 test proto serialization of logging events
  .changes/unreleased/Under the Hood-20230216-143252.yaml
  .github/workflows/structured-logging-schema-check.yml
  core/dbt/events/adapter_endpoint.py
  core/dbt/events/eventmgr.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/task/snapshot.py
  tests/functional/timezones/test_timezones.py
  tests/unit/test_events.py
Labels: cla:yes

#6952 move hook tests to adapter zone
  tests/adapter/dbt/tests/adapter/hooks/data/seed_model.sql
  tests/adapter/dbt/tests/adapter/hooks/data/seed_run.sql
  tests/adapter/dbt/tests/adapter/hooks/fixtures.py
  tests/adapter/dbt/tests/adapter/hooks/test_model_hooks.py
  tests/adapter/dbt/tests/adapter/hooks/test_run_hooks.py
  tests/functional/hooks/data/seed_model.sql
  tests/functional/hooks/data/seed_run.sql
Labels: cla:yes, Skip Changelog

#7004 Update comment for build_manifest_state_check
  core/dbt/parser/manifest.py
Labels: cla:yes, Skip Changelog

#6718 Made project version optional (default None)
  .changes/unreleased/Features-20230124-135550.yaml
  core/dbt/config/project.py
  core/dbt/contracts/project.py
  core/dbt/tests/fixtures/project.py
  tests/functional/basic/test_project.py
Labels: cla:yes, Team:Language, ready_for_review

#7000 rename workflow to match other files
  .github/workflows/cut-release-branch.yml
Labels: cla:yes, Skip Changelog

#6179 Remove trailing slashes from source paths (#6102)
  .changes/unreleased/Fixes-20221030-102114.yaml
  core/dbt/config/project.py
  tests/functional/configs/test_dupe_paths.py
Labels: cla:yes, Team:Language, ready_for_review

#7019 remove old pass through method
  core/dbt/cli/main.py
  core/dbt/docs/build/doctrees/environment.pickle
Labels: cla:yes, Skip Changelog

#7029 CT-2160: Fix logbook (legacy logging) regression
  .changes/unreleased/Fixes-20230222-133304.yaml
  core/dbt/events/functions.py
Labels: cla:yes

#7023 CT 2057 Fix compilation logic for ephemeral nodes
  .changes/unreleased/Fixes-20230221-170630.yaml
  core/dbt/compilation.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  test/unit/test_compiler.py
  tests/functional/materializations/test_ephemeral_compilation.py
Labels: cla:yes

#7035 Revert "CT 2057 Fix compilation logic for ephemeral nodes (#7023) (#7…
  .changes/unreleased/Fixes-20230221-170630.yaml
  core/dbt/compilation.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  test/unit/test_compiler.py
  tests/functional/materializations/test_ephemeral_compilation.py
Labels: cla:yes, Skip Changelog

#7002 Rename "constraints_enabled" to "contract"
  .changes/unreleased/Under the Hood-20230217-105223.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/include/global_project/macros/materializations/models/table/create_table_as.sql
  core/dbt/parser/base.py
  core/dbt/parser/schemas.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  schemas/dbt/manifest/v8.json
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_manifest.py
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_constraint_configs.py
  tests/functional/list/test_list.py
Labels: cla:yes

#6965 parse group config on groupable nodes
  .changes/unreleased/Features-20230214-225134.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/util.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/parser/base.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v8.json
  test/unit/test_manifest.py
  tests/functional/artifacts/data/state/v8/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/list/test_list.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes

#7040 Fix regression in semver comparison logic
  .changes/unreleased/Fixes-20230224-001338.yaml
  core/dbt/semver.py
  test/unit/test_semver.py
Labels: cla:yes

#7043 Fixing the release secret
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#6994 Paw/ct 1844 log params take 2
  .changes/unreleased/Features-20230216-144534.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/contracts/project.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/events/functions.py
  core/dbt/tests/fixtures/project.py
  tests/unit/test_cli_flags.py
Labels: cla:yes

#7047 add group for selection logic
  .changes/unreleased/Features-20230224-134533.yaml
  core/dbt/graph/selector_methods.py
  test/unit/test_graph_selector_methods.py
  tests/functional/graph_selection/fixtures.py
  tests/functional/graph_selection/test_graph_selection.py
  tests/functional/graph_selection/test_group_selection.py
Labels: cla:yes

#7069 CT 1993 handle invalid access to private models
  .changes/unreleased/Features-20230224-182214.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v9.json
  tests/functional/artifacts/test_artifacts.py
  tests/functional/groups/test_access.py
Labels: cla:yes

#7077 fix: add pytz dependency
  .changes/unreleased/Fixes-20230228-130318.yaml
  core/setup.py
  dev-requirements.txt
Labels: cla:yes, ready_for_review

#7078 backport 7077 to 1.4
  .changes/unreleased/Fixes-20230228-130318.yaml
  core/setup.py
  dev-requirements.txt
Labels: cla:yes

#7079 backport 7077 to 1.3
  .changes/unreleased/Fixes-20230228-130318.yaml
  core/setup.py
  dev-requirements.txt
Labels: cla:yes

#7080 backport 7077 to 1.2
  .changes/unreleased/Fixes-20230228-130318.yaml
  core/setup.py
  dev-requirements.txt
Labels: cla:yes

#7068 Make output_keys param MultiOption
  .changes/unreleased/Under the Hood-20230227-102016.yaml
  core/dbt/cli/params.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/searchindex.js
  core/dbt/task/list.py
  tests/functional/list/test_list.py
  tests/functional/schema_tests/test_schema_v2_tests.py
Labels: cla:yes

#7090 Move check of invalid groups earlier in parsing
  .changes/unreleased/Under the Hood-20230228-140440.yaml
  core/dbt/parser/manifest.py
Labels: cla:yes

#7091 Roadmap update (Feb 2023)
  docs/roadmap/2023-02-back-to-basics.md
Labels: cla:yes, Skip Changelog
