Repository dbt-labs/dbt-core, pull requests merged in 2023-04, with the labels that each got.

#7262 Fix DepsNotifyUpdatesAvailable logging event
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  tests/unit/test_events.py
Labels: cla:yes, Skip Changelog

#7251 remove deprecated exception functions
  .changes/unreleased/Breaking Changes-20230331-133537.yaml
  core/dbt/exceptions.py
  test/unit/test_exceptions.py
  tests/unit/test_deprecations.py
Labels: cla:yes

#6897 Add double to float types for columns
  .changes/unreleased/Fixes-20230208-104230.yaml
  core/dbt/adapters/base/column.py
Labels: cla:yes, Team:Adapters

#7074 Backport 6982 to 1.4.latest
  .changes/unreleased/Fixes-20230215-104536.yaml
  core/dbt/config/project.py
  core/dbt/contracts/connection.py
  core/dbt/deps/git.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/schemas.py
  core/dbt/utils.py
Labels: cla:yes

#7253 CT 2346 fix read and check versions
  .changes/unreleased/Fixes-20230331-170417.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/manifest_upgrade.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/util.py
Labels: cla:yes

#7249 CT-2264, CT-2259, CT-1783: Improved event serialization failure handling
  .changes/unreleased/Fixes-20230331-095428.yaml
  core/dbt/events/base_types.py
  core/dbt/events/functions.py
  tests/unit/test_base_context.py
  tests/unit/test_events.py
  tests/unit/test_functions.py
Labels: cla:yes

#7285 Avoid revoking grants for views when `copy_grants=true`
  .changes/unreleased/Fixes-20230405-201553.yaml
  core/dbt/include/global_project/macros/materializations/models/view/create_or_replace_view.sql
Labels: cla:yes, ready_for_review

#7275 Moving simple_snapshot test from individual adapters to core adapter zone
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view/create.sql
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view/refresh.sql
  tests/adapter/dbt/tests/adapter/simple_snapshot/common.py
  tests/adapter/dbt/tests/adapter/simple_snapshot/seeds.py
  tests/adapter/dbt/tests/adapter/simple_snapshot/snapshots.py
  tests/adapter/dbt/tests/adapter/simple_snapshot/test_snapshot.py
Labels: cla:yes, Skip Changelog

#7293 Fix the base classes of simple snapshot for better import
  tests/adapter/dbt/tests/adapter/simple_snapshot/test_snapshot.py
Labels: cla:yes, Skip Changelog

#7194 Remove trivial nodes before building subdag
  .changes/unreleased/Under the Hood-20230319-172824.yaml
  core/dbt/graph/graph.py
Labels: cla:yes, Team:Execution, ready_for_review

#7211 ADAP-387: Stub materialized view as a materialization
  core/dbt/include/global_project/macros/db_api/materialized_view/create.sql
  core/dbt/include/global_project/macros/db_api/materialized_view/refresh.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/materialized_view.sql
  core/dbt/include/global_project/macros/strategies/materialized_view/create.sql
  core/dbt/include/global_project/macros/strategies/materialized_view/full_refresh.sql
  tests/functional/materializations/test_materialized_view_materialization.py
Labels: cla:yes, Skip Changelog

#7304 Add relation info to `node_info` in logging
  .changes/unreleased/Features-20230410-174824.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/README.md
  core/dbt/events/types.proto
  core/dbt/events/types_pb2.py
  tests/unit/test_proto_events.py
Labels: cla:yes

#7311 Prettify ListRelations message
  .changes/unreleased/Under the Hood-20230410-214724.yaml
  core/dbt/events/types.py
Labels: cla:yes

#7242 Handle internal exceptions in postflight
  .changes/unreleased/Fixes-20230329-113203.yaml
  core/dbt/cli/README.md
  core/dbt/cli/example.py
  core/dbt/cli/exceptions.py
  core/dbt/cli/flags.py
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/docs/source/index.rst
  core/dbt/tests/util.py
  tests/adapter/dbt/tests/adapter/dbt_debug/test_dbt_debug.py
  tests/functional/cli/test_cli_exit_codes.py
  tests/functional/cli/test_error_handling.py
  tests/functional/dbt_runner/test_dbt_runner.py
  tests/functional/defer_state/test_defer_state.py
  tests/functional/fail_fast/fixtures.py
  tests/functional/fail_fast/test_fail_fast_run.py
  tests/unit/test_cli_flags.py
Labels: cla:yes

#7279 fix: avoid dbtRunner default callbacks being shared across instances
  .changes/unreleased/Fixes-20230405-124315.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#7314 `Parse` command should return manifest when invoked via `dbtRunner`
  .changes/unreleased/Under the Hood-20230410-164543.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#7320 Update CLI/API docs example, header
  core/dbt/cli/example.py
  core/dbt/docs/source/index.rst
Labels: cla:yes, Skip Changelog

#7319 Rebase #7223: improve contracts error message
  .changes/unreleased/Features-20230325-192830.yaml
  core/dbt/exceptions.py
  core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
Labels: cla:yes

#7321 allow resources to be selected by patch path
  .changes/unreleased/Features-20230411-084645.yaml
  core/dbt/graph/selector_methods.py
  tests/functional/graph_selection/fixtures.py
  tests/functional/graph_selection/test_graph_selection.py
Labels: cla:yes

#7230 CT-1922: Parsing and postgres implementations for model level constraints
  .changes/unreleased/Features-20230329-102736.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql
  core/dbt/include/global_project/macros/materializations/models/table/create_table_as.sql
  core/dbt/parser/schemas.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  schemas/dbt/manifest/v9.json
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_manifest.py
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_contract_configs.py
Labels: cla:yes

#7307 Add option to skip relation cache population
  .changes/unreleased/Features-20230410-115538.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/contracts/project.py
  core/dbt/task/runnable.py
  tests/adapter/dbt/tests/adapter/caching/test_caching.py
Labels: cla:yes

#7270 remove functions and added time to remove the rest
  core/dbt/lib.py
  test/unit/test_lib.py
Labels: cla:yes, Skip Changelog

#7250 Generalize constraint warnings
  .changes/unreleased/Under the Hood-20230331-132119.yaml
  core/dbt/adapters/base/__init__.py
  core/dbt/adapters/base/impl.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql
  plugins/postgres/dbt/adapters/postgres/impl.py
  tests/functional/artifacts/expected_manifest.py
  tests/unit/test_events.py
Labels: cla:yes

#6780 Snapshot strategies: newline for subquery
  .changes/unreleased/Fixes-20230130-231456.yaml
  core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql
  tests/functional/simple_snapshot/test_comment_ending_snapshot.py
Labels: cla:yes, Team:Adapters, ready_for_review, pr_tracked

#7176 Update help text for commands + params in CLI and top-level API
  .gitattributes
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  tests/functional/partial_parsing/test_pp_docs.py
Labels: cla:yes, Team:Execution, Skip Changelog

#7296 Fix for simple snapshot for seed and test assert
  tests/adapter/dbt/tests/adapter/simple_snapshot/common.py
  tests/adapter/dbt/tests/adapter/simple_snapshot/seeds.py
  tests/adapter/dbt/tests/adapter/simple_snapshot/test_snapshot.py
Labels: cla:yes, Skip Changelog

#7229 add schema_string_type fixture to test_constraints
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
Labels: cla:yes, Skip Changelog

#7330 Add version selector method
  .changes/unreleased/Features-20230412-011138.yaml
  core/dbt/graph/selector_methods.py
  test/unit/test_graph_selector_methods.py
  tests/functional/graph_selection/fixtures.py
  tests/functional/graph_selection/test_graph_selection.py
  tests/functional/graph_selection/test_group_selection.py
  tests/functional/graph_selection/test_version_selection.py
Labels: cla:yes

#7326 compile inline query doesn't add node
  core/dbt/task/compile.py
  tests/functional/compile/test_compile.py
Labels: cla:yes, Skip Changelog

#7294 Allow greater mashumaro versions
  .changes/unreleased/Dependencies-20230412-191333.yaml
  core/setup.py
Labels: dependencies, cla:yes

#7322 ADAP-387: reverting db_api implementation
  core/dbt/adapters/base/relation.py
  core/dbt/contracts/relation.py
  core/dbt/include/global_project/macros/db_api/materialized_view/create.sql
  core/dbt/include/global_project/macros/db_api/materialized_view/refresh.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/create_materialized_view_as.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/refresh_materialized_view_data.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/replace_materialized_view.sql
  core/dbt/include/global_project/macros/strategies/materialized_view/create.sql
  core/dbt/include/global_project/macros/strategies/materialized_view/full_refresh.sql
  tests/adapter/dbt/tests/adapter/materialized_views/test_materialized_views.py
  tests/functional/README.md
  tests/functional/materializations/test_materialized_view_materialization.py
Labels: cla:yes, Skip Changelog

#7333 Adding a new column is not a breaking contract change
  .changes/unreleased/Fixes-20230412-133438.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/exceptions.py
  tests/functional/defer_state/fixtures.py
  tests/functional/defer_state/test_modified_state.py
Labels: cla:yes

#7385 dbt.include import issue for ci
  Makefile
Labels: Skip Changelog

#7383 dbt.include import issue for ci
  Makefile
Labels: cla:yes, Skip Changelog

#7367 Update docs link in ContractBreakingChangeError message
  .changes/unreleased/Under the Hood-20230417-114501.yaml
  core/dbt/exceptions.py
Labels: cla:yes, backport 1.5.latest

#7394 sqlparse <0.4.4
  core/setup.py
Labels: cla:yes, Skip Changelog

#7401 [Backport 1.2.latest] sqlparse <0.4.4
  core/setup.py
Labels: cla:yes, Skip Changelog

#7400 [Backport 1.3.latest] sqlparse <0.4.4
  core/setup.py
Labels: cla:yes, Skip Changelog

#7365 [Fix] Typo in statically parsed ref unpacking
  .changes/unreleased/Fixes-20230414-163642.yaml
  core/dbt/parser/models.py
  test/unit/test_graph.py
Labels: cla:yes, backport 1.5.latest

#7342 [BACKPORT 1.4.latest] Improved event log msg stringification
  .changes/unreleased/Fixes-20230331-095428.yaml
  core/dbt/events/functions.py
  core/dbt/events/types.py
  tests/unit/test_base_context.py
  tests/unit/test_functions.py
Labels: cla:yes

#7341 [BACKPORT 1.3.latest] Improved event log msg stringification
  .changes/unreleased/Fixes-20230331-095428.yaml
  core/dbt/context/base.py
  test/unit/test_base_context.py
Labels: cla:yes

#7340 [BACKPORT 1.2.latest] Improved event log msg stringification
  .changes/unreleased/Fixes-20230331-095428.yaml
  core/dbt/context/base.py
  test/unit/test_base_context.py
Labels: cla:yes

#7338 [BACKPORT 1.1.latest] Improved event log msg stringification
  .changes/unreleased/Fixes-20230331-095428.yaml
  core/dbt/context/base.py
  test/unit/test_base_context.py
Labels: cla:yes

#7389 Update `--help` text for cache-related parameters
  .changes/unreleased/Under the Hood-20230418-122323.yaml
  core/dbt/cli/params.py
Labels: cla:yes, backport 1.5.latest

#7412 fix target-path not working for sources.json
  .changes/unreleased/Fixes-20230419-142150.yaml
  core/dbt/cli/params.py
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes

#7406 add cloud-artifacts as codeowners of /schemas/dbt
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#7415 fix v0 ref resolution
  .changes/unreleased/Fixes-20230419-220910.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/schemas.py
  test/unit/test_manifest.py
  test/unit/test_parser.py
  test/unit/utils.py
  tests/functional/graph_selection/fixtures.py
Labels: cla:yes

#7426 Address mypy issues affecting scheduled CI runs on 1.1.latest
  .github/workflows/main.yml
  .pre-commit-config.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/protocol.py
  core/dbt/adapters/sql/impl.py
  core/dbt/clients/jinja.py
  core/dbt/clients/jinja_static.py
  core/dbt/clients/system.py
  core/dbt/deps/git.py
  core/dbt/deps/local.py
  core/dbt/deps/registry.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/analysis.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/hooks.py
  core/dbt/parser/macros.py
  core/dbt/parser/models.py
  core/dbt/parser/schemas.py
  core/dbt/parser/seeds.py
  core/dbt/parser/singular_test.py
  core/dbt/parser/snapshots.py
  core/dbt/parser/sql.py
  core/dbt/utils.py
  dev-requirements.txt
  mypy.ini
Labels: cla:yes, Skip Changelog

#7419 Add --target-path to snapshot command
  .changes/unreleased/Fixes-20230420-104254.yaml
  core/dbt/cli/main.py
Labels: cla:yes, ready_for_review

#7436 Fix `.gitignore` to take heed of `tests/functional/build`
  .gitignore
Labels: cla:yes, Skip Changelog

#7371 Clear cached `statement` results when retrieved from `ProviderContext` and subclasses
  .changes/unreleased/Under the Hood-20230417-122721.yaml
  core/dbt/context/providers.py
  core/dbt/exceptions.py
  tests/functional/statements/fixtures.py
  tests/functional/statements/test_statements.py
Labels: cla:yes

#7438 Fix groupable node partial parsing, raise DbtReferenceError in RuntimeRefResolver
  .changes/unreleased/Fixes-20230424-161843.yaml
  core/dbt/context/providers.py
  core/dbt/parser/partial.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes

#7435 UX improvements to model versions
  .changes/unreleased/Under the Hood-20230424-135300.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/parser/schemas.py
  test/unit/utils.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/partial_parsing/test_partial_parsing.py
  tests/unit/test_events.py
Labels: cla:yes, backport 1.5.latest

#7455 CT 2483 duplicate depends on nodes
  .changes/unreleased/Fixes-20230424-173404.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/manifest.py
  core/dbt/task/runnable.py
  tests/functional/artifacts/expected_manifest.py
Labels: cla:yes

#7388 Remove noisy parse events
  .changes/unreleased/Under the Hood-20230418-121236.yaml
  core/dbt/events/functions.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/macros.py
  core/dbt/parser/models.py
  tests/unit/test_events.py
Labels: cla:yes

#7244 ADAP-388: Stub materialized view as a materialization - postgres
  core/dbt/include/global_project/macros/materializations/models/materialized_view/alter_materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/create_materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/get_materialized_view_configuration_changes.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/refresh_materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/replace_materialized_view.sql
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view.sql
Labels: cla:yes, Skip Changelog

#7472 Update CODEOWNERS to include the OSS Tooling Guild
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#7358 CT-2414: Add graph summaries to target directory output
  .changes/unreleased/Features-20230425-142522.yaml
  core/dbt/compilation.py
  tests/functional/compile/test_compile.py
Labels: cla:yes

#7441 active project > local project in ConfiguredVar
  .changes/unreleased/Fixes-20230427-230714.yaml
  core/dbt/context/configured.py
  tests/functional/context_methods/first_dependency.py
  tests/functional/context_methods/test_var_dependency.py
Labels: cla:yes

#7431 Ignore parent tests added edges for build selection
  .changes/unreleased/Fixes-20230421-172428.yaml
  core/dbt/compilation.py
  core/dbt/graph/graph.py
  tests/functional/build/fixtures.py
  tests/functional/build/test_build.py
  tests/functional/defer_state/test_run_results_state.py
Labels: cla:yes, Team:Execution, ready_for_review
