Repository dbt-labs/dbt-core, pull requests merged in 2023-10, with the labels that each got.

#8755 rebuild manifest missed fields
  .changes/unreleased/Features-20230914-074429.yaml
  .changes/unreleased/Features-20230922-150754.yaml
  schemas/dbt/manifest/v11.json
Labels: cla:yes, Impact: CA

#8754 Add meta to SemanticModels
  .changes/unreleased/Features-20230929-170945.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  schemas/dbt/manifest/v11.json
  tests/functional/semantic_models/fixtures.py
  tests/functional/semantic_models/test_semantic_model_configs.py
Labels: cla:yes

#8766 remove top level meta attribute from SemanticModels
  .changes/unreleased/Features-20230929-170945.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  schemas/dbt/manifest/v11.json
  tests/functional/semantic_models/test_semantic_model_configs.py
Labels: cla:yes

#8765 [1.6.latest] regenerate v10 manifest
  .changes/unreleased/Fixes-20231004-075904.yaml
  schemas/dbt/manifest/v10.json
Labels: cla:yes

#8771 support doc blocks on versioned models
  .changes/unreleased/Fixes-20231004-144148.yaml
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_renderer.py
  tests/functional/docs/test_model_version_docs_blocks.py
Labels: cla:yes

#8777 add gha for dependabot checks
  .github/dependabot.yml
Labels: cla:yes, Skip Changelog

#8743 Enable inline csv format in unit testing
  .changes/unreleased/Features-20230928-163205.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/unit_tests.py
  schemas/dbt/manifest/v11.json
  tests/functional/unit_testing/test_unit_testing.py
  tests/unit/test_unit_test_parser.py
Labels: cla:yes

#8772 Selectors in docs generate limits catalog generation
  .changes/unreleased/Features-20231004-170155.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/task/generate.py
  tests/functional/defer_state/test_defer_state.py
  tests/functional/docs/test_generate.py
Labels: user docs, cla:yes

#8773 [Backport 1.6.latest] Support null coalescing properties for metric nodes (#8700)
  .changes/unreleased/Features-20230922-150754.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  schemas/dbt/manifest/v10.json
  tests/functional/metrics/fixtures.py
  tests/unit/test_contracts_graph_unparsed.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes

#8788 pin types-requests in dev-requirements
  .changes/unreleased/Under the Hood-20231006-093107.yaml
  dev-requirements.txt
Labels: cla:yes

#8615 Generate static index html documentation
  .changes/unreleased/Features-20230911-144126.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/include/index.html
  core/dbt/task/generate.py
  tests/functional/docs/test_static.py
Labels: cla:yes, ready_for_review

#8654 Add semantic model test to `test_contracts_graph_parsed.py`
  dev-requirements.txt
  tests/unit/README.md
  tests/unit/test_contracts_graph_parsed.py
Labels: cla:yes, Skip Changelog

#8408 Deps lock by justbldwn
  .changes/unreleased/Features-20230125-165933.yaml
  core/dbt/cli/main.py
  core/dbt/cli/option_types.py
  core/dbt/cli/params.py
  core/dbt/config/project.py
  core/dbt/constants.py
  core/dbt/deps/resolver.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/task/deps.py
  tests/functional/dependencies/test_dependency_options.py
  tests/functional/dependencies/test_simple_dependency.py
  tests/unit/test_events.py
Labels: user docs, cla:yes

#8785 [Backport 1.5.latest] support doc blocks on versioned models
  .changes/unreleased/Fixes-20231004-144148.yaml
  core/dbt/events/base_types.py
  core/dbt/events/eventmgr.py
  core/dbt/events/functions.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_renderer.py
  core/dbt/parser/schemas.py
  tests/functional/docs/test_model_version_docs_blocks.py
Labels: cla:yes

#8762 [Fix] respect project root when loading seeds
  .changes/unreleased/Fixes-20231006-134551.yaml
  core/dbt/context/providers.py
  core/dbt/tests/util.py
  tests/functional/partial_parsing/test_partial_parsing.py
  tests/functional/utils.py
Labels: cla:yes

#8592 Type aliasing for model contract column data_type
  .changes/unreleased/Features-20230907-161831.yaml
  core/dbt/adapters/base/column.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/base.py
  schemas/dbt/manifest/v11.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/list/test_list.py
  tests/unit/test_contracts_graph_compiled.py
  tests/unit/test_contracts_graph_parsed.py
Labels: user docs, cla:yes

#8744 Explanation of Parsing vs. Compilation vs. Runtime
  docs/eli64/parsing-vs-compilation-vs-runtime.md
Labels: cla:yes, Skip Changelog

#8792 Fix uncaught exception for group updates
  .changes/unreleased/Fixes-20231010-125948.yaml
  core/dbt/contracts/graph/manifest.py
  tests/functional/defer_state/fixtures.py
  tests/functional/defer_state/test_group_updates.py
Labels: cla:yes

#8653 ADAP-850: Support test results as a view
  .changes/unreleased/Features-20230915-174428.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/relation.py
  core/dbt/include/global_project/macros/materializations/tests/test.sql
  core/dbt/include/global_project/macros/relations/create.sql
  core/dbt/parser/generic_test_builders.py
  tests/adapter/dbt/tests/adapter/store_test_failures_tests/_files.py
  tests/adapter/dbt/tests/adapter/store_test_failures_tests/basic.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/store_test_failures/test_store_test_failures.py
Labels: user docs, cla:yes

#8833 fix changelog
  .changes/unreleased/Under the Hood-20230912-230619.yaml
Labels: cla:yes, Skip Changelog

#8832 fix changelog
  .changes/unreleased/Under the Hood-20230912-230619.yaml
Labels: Skip Changelog

#8817 Partial parsing issue when adding groups and updating models at the same time
  .changes/unreleased/Fixes-20231010-202148.yaml
  core/dbt/parser/partial.py
  tests/functional/partial_parsing/test_partial_parsing.py
  tests/functional/partial_parsing/test_pp_groups.py
Labels: cla:yes

#8834 update v10 manifest on main
  .changes/unreleased/Under the Hood-20231011-131211.yaml
  schemas/dbt/manifest/v10.json
Labels: cla:yes

#8795 Add support for getting freshness from DBMS metadata
  .changes/unreleased/Features-20231008-134329.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/capability.py
  core/dbt/clients/agate_helper.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/include/global_project/macros/adapters/metadata.sql
  core/dbt/parser/sources.py
  core/dbt/task/freshness.py
  plugins/postgres/dbt/adapters/postgres/impl.py
  tests/functional/source_overrides/fixtures.py
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_events.py
Labels: cla:yes

#8798 Add SavedQuery nodes
  .changes/unreleased/Features-20231010-154217.yaml
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/context/context_config.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/manifest_upgrade.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/node_types.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schema_renderer.py
  core/dbt/parser/schema_yaml_readers.py
  core/dbt/parser/schemas.py
  core/setup.py
  schemas/dbt/manifest/v11.json
  tests/functional/artifacts/data/state/v11/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/saved_queries/__init__.py
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_saved_query_parsing.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_manifest.py
  tests/unit/test_node_types.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes

#8820 Support dbt-semantic-interfaces 0.3.0
  .changes/unreleased/Dependencies-20231011-022252.yaml
  core/dbt/contracts/graph/manifest_upgrade.py
  tests/functional/artifacts/data/state/v10/manifest.json
  tests/functional/artifacts/data/state/v11/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes, artifacts, semantic

#8865 Fix partial parsing issue not working for changing semantic model name
  .changes/unreleased/Fixes-20231016-163953.yaml
  core/dbt/parser/partial.py
  tests/functional/semantic_models/fixtures.py
  tests/functional/semantic_models/test_semantic_models.py
Labels: cla:yes, backport 1.7.latest

#8886 add 1.7 changelog
  .changes/0.0.0.md
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#8889 Contract enforcement on temporary tables
  .changes/unreleased/Fixes-20231024-145504.yaml
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  tests/functional/contracts/test_contract_enforcement.py
Labels: cla:yes

#8856 Fix issues around new get_catalog_by_relations macro
  .changes/unreleased/Fixes-20231024-155400.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/task/generate.py
  tests/functional/docs/test_generate.py
  tests/unit/test_postgres_adapter.py
Labels: cla:yes

#8910 Add utils module
  .changes/unreleased/Features-20231026-110821.yaml
  .flake8
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/base/relation.py
  core/dbt/adapters/contracts/connection.py
  core/dbt/adapters/relation_configs/config_base.py
  core/dbt/adapters/sql/connections.py
  core/dbt/adapters/utils.py
  core/dbt/cli/requires.py
  core/dbt/clients/jinja.py
  core/dbt/common/util.py
  core/dbt/common/utils/__init__.py
  core/dbt/common/utils/casting.py
  core/dbt/common/utils/dict.py
  core/dbt/common/utils/encoding.py
  core/dbt/common/utils/executor.py
  core/dbt/config/renderer.py
  core/dbt/context/providers.py
  core/dbt/contracts/relation.py
  core/dbt/contracts/results.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  core/dbt/task/runnable.py
  core/dbt/task/snapshot.py
  core/dbt/utils.py
  tests/unit/common/test_utils.py
  tests/unit/test_utils.py
Labels: cla:yes

#8909 remove usage of dbt.config.PartialProject from dbt/adapters
  .changes/unreleased/Features-20231026-123913.yaml
  core/dbt/adapters/base/plugin.py
  tests/unit/test_adapter_factory.py
  tests/unit/test_manifest.py
Labels: cla:yes

#8940 Fix cased comparison in catalog-retrieval function
  .changes/unreleased/Fixes-20231030-093734.yaml
  core/dbt/adapters/base/impl.py
Labels: cla:yes

#8953 Backport Catalog Fix to 1.7.latest
  .changes/unreleased/Fixes-20231024-155400.yaml
  .changes/unreleased/Fixes-20231030-093734.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/task/generate.py
  tests/functional/docs/test_generate.py
  tests/unit/test_postgres_adapter.py
Labels: cla:yes

#8937 add a no-op runner for saved_query
  .changes/unreleased/Under the Hood-20231027-140048.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/compilation.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/task/build.py
  core/dbt/task/runnable.py
  tests/functional/saved_queries/test_saved_query_build.py
Labels: cla:yes, backport 1.7.latest
