Repository dbt-labs/dbt-core, pull requests merged in 2023-01, with the labels that each got.

#6417 adding pre-commit install to make dev
  .changes/unreleased/Fixes-20221212-115912.yaml
  CONTRIBUTING.md
  Makefile
Labels: cla:yes

#6494 Partial parsing bug with empty schema file - ensure None is not passed to load_yaml_text
  .changes/unreleased/Fixes-20230101-223405.yaml
  core/dbt/context/base.py
  core/dbt/flags.py
  core/dbt/parser/schemas.py
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
  tests/functional/context_methods/test_builtin_functions.py
Labels: cla:yes

#6307 Example click API usage
  core/dbt/cli/__init__.py
  core/dbt/cli/context.py
  core/dbt/cli/example.py
  core/dbt/docs/source/index.rst
Labels: cla:yes, Skip Changelog

#6496 Fix issue link for changelog entry from PR#5859
  .changes/1.4.0/Features-20220408-165459.yaml
Labels: cla:yes, Skip Changelog

#6505 [Backport 1.3.latest] Partial parsing bug with empty schema file
  .changes/unreleased/Fixes-20230101-223405.yaml
  core/dbt/context/base.py
  core/dbt/flags.py
  core/dbt/parser/schemas.py
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
  tests/functional/context_methods/test_builtin_functions.py
Labels: cla:yes

#6474 CT 1551 partial parsing logging events
  .changes/unreleased/Under the Hood-20221221-121904.yaml
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  tests/unit/test_events.py
Labels: cla:yes

#6514 [Backport 1.2.latest] Partial parsing bug with empty schema file - ensure None is not passe…
  .changes/unreleased/Fixes-20230101-223405.yaml
  .github/workflows/main.yml
  core/dbt/context/base.py
  core/dbt/flags.py
  core/dbt/parser/schemas.py
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
Labels: cla:yes

#6516 [Backport 1.1.latest] Partial parsing bug with empty schema file - en…
  .changes/unreleased/Fixes-20230101-223405.yaml
  .github/workflows/main.yml
  core/dbt/context/base.py
  core/dbt/flags.py
  core/dbt/parser/schemas.py
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
Labels: cla:yes

#6517 [Backport 1.0.latest] Partial parsing bug with empty schema file - en…
  .changes/unreleased/Fixes-20230101-223405.yaml
  .github/scripts/integration-test-matrix.js
  .github/workflows/changelog-check.yml
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .github/workflows/performance.yml
  .github/workflows/release.yml
  .github/workflows/schema-check.yml
  .github/workflows/version-bump.yml
  core/dbt/context/base.py
  core/dbt/flags.py
  core/dbt/parser/schemas.py
  test/integration/068_partial_parsing_tests/test_partial_parsing.py
Labels: cla:yes

#6392 DBT_FAVOR_STATE_STATE -> DBT_FAVOR_STATE
  .changes/unreleased/Fixes-20230104-141047.yaml
  core/dbt/flags.py
Labels: cla:yes, Team:Execution, ready_for_review

#6243 🎨 add missing fstrings, convert format to fstring
  .changes/unreleased/Fixes-20221113-104150.yaml
  core/dbt/events/types.py
Labels: cla:yes, Team:Language, ready_for_review

#6518 Updating metric attributes renamed event
  .changes/unreleased/Under the Hood-20230104-155257.yaml
  core/dbt/events/types.py
Labels: cla:yes

#6402 Making Metric Timestamps Optional
  .changes/unreleased/Features-20221207-091722.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes

#6504 Remove UnsetProfileConfig
  .changes/unreleased/Under the Hood-20230105-104748.yaml
  core/dbt/cli/main.py
  core/dbt/config/__init__.py
  core/dbt/config/runtime.py
  core/dbt/task/base.py
  core/dbt/task/deps.py
  test/unit/test_config.py
Labels: cla:yes

#6553 CT 1549 reorg logging events to have two top level keys
  .changes/unreleased/Under the Hood-20230109-095907.yaml
  core/dbt/clients/system.py
  core/dbt/events/base_types.py
  core/dbt/events/eventmgr.py
  core/dbt/events/functions.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/parser/schemas.py
  core/dbt/task/freshness.py
  core/dbt/task/parse.py
  core/dbt/task/run.py
  core/dbt/task/seed.py
  core/dbt/task/snapshot.py
  core/dbt/task/test.py
  test/unit/test_config.py
  test/unit/test_graph_selector_methods.py
  tests/functional/logging/test_logging.py
  tests/unit/test_events.py
  tests/unit/test_proto_events.py
Labels: cla:yes

#6540 add deprecation decorator
  .changes/unreleased/Breaking Changes-20221205-141937.yaml
  core/dbt/context/exceptions_jinja.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/internal_deprecations.py
  core/dbt/task/run.py
  core/dbt/task/test.py
  tests/unit/test_deprecations.py
  tests/unit/test_events.py
Labels: cla:yes

#6557 fix log msg format
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
Labels: cla:yes, Skip Changelog

#6556 Fix event level regression
  .changes/unreleased/Fixes-20230109-161254.yaml
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
Labels: cla:yes

#6560 Fix changelog entry for 5989/6432
  .changes/1.4.0/Fixes-20221213-112620.yaml
Labels: cla:yes, Skip Changelog

#6563 Remove duplicated changelog entry for 5521
  .changes/1.4.0-b1.md
  .changes/1.4.0/Features-20220914-095625.yaml
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#6564 Fix date serialization regression by adopting fixed mashumaro version
  .changes/unreleased/Fixes-20230110-124132.yaml
  core/setup.py
  tests/unit/test_events.py
Labels: cla:yes

#6493 Adds the meta field to node_info in logs
  .changes/unreleased/Features-20221230-104820.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/utils.py
  tests/functional/logging/test_meta_logging.py
  tests/unit/test_proto_events.py
Labels: cla:yes, ok_to_test, Team:Language, ready_for_review

#6435 Re-factor list of YAML keys for hooks to late-render
  .changes/unreleased/Fixes-20221213-092655.yaml
  core/dbt/config/renderer.py
  tests/functional/hooks/test_model_hooks.py
Labels: cla:yes, Team:Language

#6561 Ct 1716 cleanup logging events
  .changes/unreleased/Under the Hood-20230110-114233.yaml
  core/dbt/adapters/cache.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/task/base.py
  tests/unit/test_events.py
Labels: cla:yes

#6499 fixed minor typos
  .changes/unreleased/Docs-20230102-170216.yaml
  core/dbt/cli/params.py
  core/dbt/docs/build/html/index.html
  core/dbt/main.py
Labels: cla:yes, cli, Team:Execution, ready_for_review

#6366 Adds 'buildable' selection mode
  .changes/unreleased/Features-20230102-091335.yaml
  core/dbt/graph/cli.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_spec.py
  core/dbt/main.py
  test/unit/test_flags.py
  tests/functional/test_selection/fixtures.py
  tests/functional/test_selection/test_selection_expansion.py
Labels: cla:yes, cli, Team:Execution, ready_for_review

#6488 add defer_to_manifest in before_run to fix faulty deferred docs generate
  .changes/unreleased/Fixes-20221226-010211.yaml
  core/dbt/task/freshness.py
  core/dbt/task/list.py
  core/dbt/task/runnable.py
  test/integration/062_defer_state_tests/test_defer_state.py
Labels: cla:yes, Team:Execution, ready_for_review

#6567 Check length of escaped strings in the adapter test
  .changes/unreleased/Under the Hood-20230110-145648.yaml
  tests/adapter/dbt/tests/adapter/utils/fixture_escape_single_quotes.py
Labels: cla:yes

#6520 Add --warn-error-options
  .changes/unreleased/Features-20230104-181003.yaml
  core/dbt/cli/main.py
  core/dbt/cli/option_types.py
  core/dbt/cli/params.py
  core/dbt/config/utils.py
  core/dbt/contracts/project.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/html/.buildinfo
  core/dbt/docs/build/html/_static/_sphinx_javascript_frameworks_compat.js
  core/dbt/docs/build/html/_static/basic.css
  core/dbt/docs/build/html/_static/jquery-3.6.0.js
  core/dbt/docs/build/html/_static/jquery.js
  core/dbt/docs/build/html/_static/underscore-1.13.1.js
  core/dbt/docs/build/html/_static/underscore.js
  core/dbt/docs/build/html/genindex.html
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/search.html
  core/dbt/events/functions.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/flags.py
  core/dbt/helper_types.py
  core/dbt/main.py
  core/dbt/task/runnable.py
  core/dbt/utils.py
  core/dbt/version.py
  test/unit/test_flags.py
  tests/unit/test_events.py
  tests/unit/test_functions.py
  tests/unit/test_helper_types.py
Labels: cla:yes

#6572 Call `update_event_status` earlier + rename an event
  .changes/unreleased/Fixes-20230111-134058.yaml
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/task/base.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  tests/unit/test_events.py
Labels: cla:yes

#6590 convert 043_custom_alias_tests
  test/integration/043_custom_aliases_tests/macros-configs/macros.sql
  test/integration/043_custom_aliases_tests/macros/macros.sql
  test/integration/043_custom_aliases_tests/models/model1.sql
  test/integration/043_custom_aliases_tests/models/model2.sql
  test/integration/043_custom_aliases_tests/models/schema.yml
  test/integration/043_custom_aliases_tests/test_custom_aliases.py
  tests/functional/custom_aliases/fixtures.py
  tests/functional/custom_aliases/test_custom_aliases.py
Labels: cla:yes, tech_debt, Skip Changelog

#6594 finish message rename in types.proto
  core/dbt/config/utils.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/exceptions.py
Labels: cla:yes, Skip Changelog

#6595 convert adapter table materialization test
  test/integration/018_adapter_ddl_tests/models/materialized.sql
  test/integration/018_adapter_ddl_tests/seed.sql
  test/integration/018_adapter_ddl_tests/test_adapter_ddl.py
  tests/adapter/dbt/tests/adapter/basic/test_table_mat.py
Labels: cla:yes, Skip Changelog

#6588 converting 022_test_timezones
  test/integration/022_timezones_tests/models/timezones.sql
  test/integration/022_timezones_tests/test_timezones.py
  tests/functional/timezones/test_timezones.py
Labels: cla:yes, tech_debt, Skip Changelog

#6596 [BACKPORT] finish message rename in types.proto (#6594)
  core/dbt/config/utils.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/exceptions.py
Labels: cla:yes, Skip Changelog

#6600 migrate ref override
  test/integration/055_ref_override_tests/macros/ref_override_macro.sql
  test/integration/055_ref_override_tests/models/ref_override.sql
  test/integration/055_ref_override_tests/seeds/seed_1.csv
  test/integration/055_ref_override_tests/seeds/seed_2.csv
  test/integration/055_ref_override_tests/test_ref_override.py
  tests/adapter/dbt/tests/adapter/basic/test_table_materialization.py
  tests/functional/ref_override/test_ref_override.py
Labels: cla:yes, Skip Changelog

#6589 convert 037_external_references
  test/integration/037_external_reference_tests/models/my_model.sql
  test/integration/037_external_reference_tests/standalone_models/my_model.sql
  test/integration/037_external_reference_tests/test_external_reference.py
  tests/functional/external_reference/test_external_reference.py
Labels: cla:yes, tech_debt, Skip Changelog

#6607 convert 057_run_query_tests
  test/integration/057_run_query_tests/test_pg_types.py
  tests/functional/run_query/test_types.py
Labels: cla:yes, tech_debt, Skip Changelog

#6622 Reformat `tests/`
  .flake8
  core/dbt/parser/generic_test_builders.py
  core/dbt/task/test.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  pyproject.toml
  tests/adapter/dbt/tests/adapter/aliases/test_aliases.py
  tests/adapter/dbt/tests/adapter/basic/test_table_materialization.py
  tests/adapter/dbt/tests/adapter/dbt_debug/test_dbt_debug.py
  tests/adapter/dbt/tests/adapter/incremental/test_incremental_predicates.py
  tests/adapter/dbt/tests/adapter/relations/test_changing_relation_type.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/colors/test_colors.py
  tests/functional/configs/test_configs.py
  tests/functional/context_methods/test_builtin_functions.py
  tests/functional/context_methods/test_custom_env_vars.py
  tests/functional/custom_aliases/test_custom_aliases.py
  tests/functional/cycles/test_cycles.py
  tests/functional/exit_codes/fixtures.py
  tests/functional/exit_codes/test_exit_codes.py
  tests/functional/exposures/fixtures.py
  tests/functional/exposures/test_exposure_configs.py
  tests/functional/exposures/test_exposures.py
  tests/functional/external_reference/test_external_reference.py
  tests/functional/incremental_schema_tests/fixtures.py
  tests/functional/incremental_schema_tests/test_incremental_schema.py
  tests/functional/logging/test_logging.py
  tests/functional/logging/test_meta_logging.py
  tests/functional/metrics/test_metric_configs.py
  tests/functional/metrics/test_metric_helper_functions.py
  tests/functional/metrics/test_metrics.py
  tests/functional/persist_docs_tests/test_persist_docs.py
  tests/functional/postgres/test_postgres_indexes.py
  tests/functional/relation_names/test_relation_name.py
  tests/functional/run_operations/test_run_operations.py
  tests/functional/run_query/test_types.py
  tests/functional/schema_tests/test_schema_v2_tests.py
  tests/functional/severity/test_severity.py
  tests/functional/statements/test_statements.py
  tests/functional/store_test_failures_tests/test_store_test_failures.py
  tests/functional/test_selection/test_selection_expansion.py
  tests/functional/timezones/test_timezones.py
  tests/unit/test_deprecations.py
  tests/unit/test_events.py
  tests/unit/test_functions.py
  tests/unit/test_helper_types.py
  tests/unit/test_proto_events.py
Labels: cla:yes, Skip Changelog

#6605 CT 1440 Fix code to emit ConnectionReused event
  .changes/unreleased/Under the Hood-20230113-132513.yaml
  core/dbt/adapters/base/connections.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  tests/functional/logging/test_logging.py
Labels: cla:yes

#6635 update gh action set-output variables
  .changes/unreleased/Under the Hood-20230117-111737.yaml
  .github/_README.md
  .github/actions/latest-wrangler/main.py
  .github/workflows/main.yml
  .github/workflows/release-docker.yml
  .github/workflows/release.yml
  .github/workflows/version-bump.yml
Labels: cla:yes

#6604 update test matrix
  .github/workflows/release-branch-tests.yml
Labels: cla:yes, Skip Changelog

#6612 convert 038_caching_tests
  test/integration/038_caching_tests/test_caching.py
  tests/adapter/dbt/tests/adapter/caching/test_caching.py
Labels: cla:yes, Skip Changelog

#6640 Click snapshot as click command (#5972)
  .changes/unreleased/Under the Hood-20230117-162505.yaml
  core/dbt/cli/main.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/html/_static/alabaster.css
  core/dbt/docs/build/html/genindex.html
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/search.html
Labels: cla:yes

#6620 Respect quoting config in dbt-py models
  .changes/unreleased/Fixes-20230116-123645.yaml
  .changes/unreleased/Fixes-20230116-123709.yaml
  core/dbt/compilation.py
  core/dbt/include/global_project/macros/python_model/python.sql
Labels: cla:yes

#6618 mv `on_schema_change` tests -> "adapter zone"
  tests/adapter/dbt/tests/adapter/incremental/fixtures.py
  tests/adapter/dbt/tests/adapter/incremental/test_incremental_on_schema_change.py
Labels: cla:yes, Skip Changelog

#6616 convert 062_defer_state_tests
  core/dbt/main.py
  core/dbt/task/compile.py
  test/integration/062_defer_state_tests/changed_models/ephemeral_model.sql
  test/integration/062_defer_state_tests/changed_models/schema.yml
  test/integration/062_defer_state_tests/changed_models/table_model.sql
  test/integration/062_defer_state_tests/changed_models/view_model.sql
  test/integration/062_defer_state_tests/changed_models_bad/ephemeral_model.sql
  test/integration/062_defer_state_tests/changed_models_bad/schema.yml
  test/integration/062_defer_state_tests/changed_models_bad/table_model.sql
  test/integration/062_defer_state_tests/changed_models_bad/view_model.sql
  test/integration/062_defer_state_tests/changed_models_missing/schema.yml
  test/integration/062_defer_state_tests/changed_models_missing/table_model.sql
  test/integration/062_defer_state_tests/changed_models_missing/view_model.sql
  test/integration/062_defer_state_tests/macros/infinite_macros.sql
  test/integration/062_defer_state_tests/macros/macros.sql
  test/integration/062_defer_state_tests/models/ephemeral_model.sql
  test/integration/062_defer_state_tests/models/exposures.yml
  test/integration/062_defer_state_tests/models/schema.yml
  test/integration/062_defer_state_tests/models/table_model.sql
  test/integration/062_defer_state_tests/models/view_model.sql
  test/integration/062_defer_state_tests/previous_state/manifest.json
  test/integration/062_defer_state_tests/seeds/seed.csv
  test/integration/062_defer_state_tests/snapshots/my_snapshot.sql
  test/integration/062_defer_state_tests/test_defer_state.py
  test/integration/062_defer_state_tests/test_modified_state.py
  test/integration/062_defer_state_tests/test_run_results_state.py
  tests/functional/defer_state/fixtures.py
  tests/functional/defer_state/test_defer_state.py
  tests/functional/defer_state/test_modified_state.py
  tests/functional/defer_state/test_run_results_state.py
Labels: cla:yes, Skip Changelog

#6641 click working with list
  .changes/unreleased/Under the Hood-20230117-213729.yaml
  core/dbt/cli/main.py
  core/dbt/cli/option_types.py
  core/dbt/cli/options.py
  core/dbt/cli/params.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/searchindex.js
Labels: cla:yes

#6650 fix MP_CONTEXT is not JSON serializable
  core/dbt/utils.py
Labels: cla:yes, Skip Changelog

#6651 Seed and freshness works with click
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/docs/build/doctrees/environment.pickle
Labels: cla:yes, Skip Changelog

#6656 Add run-operation to click CLI (#5552)
  .changes/unreleased/Under the Hood-20230119-105304.yaml
  core/dbt/cli/main.py
  core/dbt/task/run_operation.py
  tests/unit/test_cli.py
Labels: cla:yes

#6684 Consolidate changelog entries from #6620
  .changes/unreleased/Fixes-20230116-123645.yaml
  .changes/unreleased/Fixes-20230116-123709.yaml
Labels: cla:yes

#6678 convert 069_build_tests
  test/integration/069_build_tests/models-circular-relationship/model_0.sql
  test/integration/069_build_tests/models-circular-relationship/model_1.sql
  test/integration/069_build_tests/models-circular-relationship/model_99.sql
  test/integration/069_build_tests/models-circular-relationship/test.yml
  test/integration/069_build_tests/models-failing/model_0.sql
  test/integration/069_build_tests/models-failing/model_1.sql
  test/integration/069_build_tests/models-failing/model_2.sql
  test/integration/069_build_tests/models-failing/model_3.sql
  test/integration/069_build_tests/models-failing/model_99.sql
  test/integration/069_build_tests/models-failing/test.yml
  test/integration/069_build_tests/models-interdependent/model_a.sql
  test/integration/069_build_tests/models-interdependent/model_c.sql
  test/integration/069_build_tests/models-interdependent/schema.yml
  test/integration/069_build_tests/models-simple-blocking/model_a.sql
  test/integration/069_build_tests/models-simple-blocking/model_b.sql
  test/integration/069_build_tests/models-simple-blocking/schema.yml
  test/integration/069_build_tests/models/model_0.sql
  test/integration/069_build_tests/models/model_1.sql
  test/integration/069_build_tests/models/model_2.sql
  test/integration/069_build_tests/models/model_99.sql
  test/integration/069_build_tests/models/test.yml
  test/integration/069_build_tests/seeds/countries.csv
  test/integration/069_build_tests/snapshots/snap_0.sql
  test/integration/069_build_tests/snapshots/snap_1.sql
  test/integration/069_build_tests/snapshots/snap_99.sql
  test/integration/069_build_tests/test-files/model_b.sql
  test/integration/069_build_tests/test-files/model_b_null.sql
  test/integration/069_build_tests/test_build.py
  test/integration/069_build_tests/tests-failing/model_0.sql
  test/integration/069_build_tests/tests-failing/model_1.sql
  test/integration/069_build_tests/tests-failing/model_2.sql
  test/integration/069_build_tests/tests-failing/model_99.sql
  test/integration/069_build_tests/tests-failing/test.yml
  tests/functional/build/fixtures.py
  tests/functional/build/test_build.py
Labels: cla:yes, Skip Changelog

#6680 dbt build works in click
  .changes/unreleased/Under the Hood-20230119-205650.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#6681 docs generate works with click
  .changes/unreleased/Under the Hood-20230119-211040.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#6686 mv `on_schema_change` tests -> "adapter zone" (#6618)
  tests/adapter/dbt/tests/adapter/incremental/fixtures.py
  tests/adapter/dbt/tests/adapter/incremental/test_incremental_on_schema_change.py
Labels: cla:yes, Skip Changelog

#6685 Improve error message for packages missing `dbt_project.yml`
  .changes/unreleased/Features-20230120-112921.yaml
  core/dbt/config/project.py
  test/unit/test_config.py
Labels: cla:yes, ready_for_review

#6541 Ct 738/dbt debug log fix
  .changes/unreleased/Features-20230107-003157.yaml
  core/dbt/compilation.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/main.py
  core/dbt/task/debug.py
  core/dbt/task/list.py
  test/unit/test_graph.py
  tests/functional/profiles/test_profile_dir.py
  tests/unit/test_events.py
Labels: enhancement, cla:yes, Team:Language

#6694 Cheeky performance improvement on big DAGs
  .changes/unreleased/Under the Hood-20230122-215235.yaml
  core/dbt/graph/queue.py
Labels: cla:yes

#6691 CT-1718: Add Note and Formatting event types
  .changes/unreleased/Under the Hood-20230120-172254.yaml
  core/dbt/events/functions.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/task/deps.py
  core/dbt/task/printer.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  core/dbt/task/serve.py
  tests/unit/test_events.py
Labels: cla:yes

#6565 Abstract manifest generation from tasks
  .changes/unreleased/Under the Hood-20230110-115725.yaml
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/docs/build/html/_sources/index.rst.txt
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/searchindex.js
  core/dbt/docs/source/_ext/dbt_click.py
  core/dbt/docs/source/index.rst
  core/dbt/main.py
  core/dbt/parser/manifest.py
  core/dbt/task/base.py
  core/dbt/task/compile.py
  core/dbt/task/generate.py
  core/dbt/task/list.py
  core/dbt/task/parse.py
  core/dbt/task/run.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  test/unit/test_config.py
Labels: cla:yes

#6645 add adapter_response for test
  .changes/unreleased/Features-20230118-233801.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/include/global_project/macros/adapters/freshness.sql
  core/dbt/task/freshness.py
  core/dbt/task/test.py
  tests/functional/custom_singular_tests/test_custom_singular_tests.py
  tests/functional/sources/test_source_fresher_state.py
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes, Team:Execution, Team:Adapters, ready_for_review

#6709 CT 1886 include adapter_response in NodeFinished log message
  .changes/unreleased/Fixes-20230124-115837.yaml
  core/dbt/contracts/results.py
  tests/functional/logging/test_logging.py
Labels: cla:yes

#6610 test_init conversion
  test/integration/040_init_tests/test_init.py
  tests/functional/init/test_init.py
Labels: cla:yes, Skip Changelog

#6716 Event Clean-Up
  .changes/unreleased/Under the Hood-20230124-153553.yaml
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/parser/models.py
  tests/unit/test_events.py
Labels: cla:yes

#6728 Migrate debug task to click
  .changes/unreleased/Under the Hood-20230125-102606.yaml
  core/dbt/cli/main.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/task/debug.py
Labels: cla:yes

#6690 [CT-1630] Convert Column_types tests
  test/integration/056_column_type_tests/macros/test_alter_column_type.sql
  test/integration/056_column_type_tests/pg_models/model.sql
  test/integration/056_column_type_tests/pg_models/schema.yml
  test/integration/056_column_type_tests/test_alter_column_types.py
  test/integration/056_column_type_tests/test_column_types.py
  tests/adapter/dbt/tests/adapter/column_types/fixtures.py
  tests/adapter/dbt/tests/adapter/column_types/test_column_types.py
Labels: cla:yes, Skip Changelog

#6713 CT 1894 log partial parsing var changes and sort cli vars before hashing
  .changes/unreleased/Fixes-20230124-141943.yaml
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  tests/unit/test_events.py
Labels: cla:yes

#6739 change `exposure_content` to `source_content`
  .changes/unreleased/Fixes-20230125-191739.yaml
  core/dbt/contracts/util.py
Labels: cla:yes

#6654 Ct 1827/064 column comments tests conversion
  test/integration/064_column_comments_tests/models/quote_model.sql
  test/integration/064_column_comments_tests/models/schema.yml
  test/integration/064_column_comments_tests/test_column_comments.py
  tests/functional/persist_docs_tests/fixtures.py
  tests/functional/persist_docs_tests/test_persist_docs.py
Labels: cla:yes, Skip Changelog

#6698 dbt init works with click
  .changes/unreleased/Under the Hood-20230124-175110.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#6720 Graph Analysis Optimization for Large Dags
  .changes/unreleased/Under the Hood-20230126-135939.yaml
  core/dbt/graph/queue.py
Labels: cla:yes

#6652 Ct 1629/052 column quoting tests conversion
  test/integration/052_column_quoting_tests/models-unquoted/model.sql
  test/integration/052_column_quoting_tests/models/model.sql
  test/integration/052_column_quoting_tests/seeds/seed.csv
  test/integration/052_column_quoting_tests/test_column_quotes.py
  tests/functional/column_quoting/test_column_quotes.py
Labels: cla:yes, Skip Changelog

#6602 [CI/CD] Update release workflow and introduce workflow for nightly releases
  .bumpversion.cfg
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  scripts/env-setup.sh
Labels: cla:yes, repo ci/cd, tech_debt, Skip Changelog

#6769 Adding nssalian to committers list
  .changie.yaml
Labels: cla:yes, Skip Changelog, onboarding

#6773 [CT-1940] Stand-alone Python module for PostgresColumn
  .changes/unreleased/Features-20230127-162812.yaml
  plugins/postgres/dbt/adapters/postgres/__init__.py
  plugins/postgres/dbt/adapters/postgres/column.py
  plugins/postgres/dbt/adapters/postgres/impl.py
  plugins/postgres/dbt/adapters/postgres/relation.py
Labels: cla:yes

#6778 [CI/CD] Update release workflow definition
  .github/workflows/release.yml
Labels: cla:yes, repo ci/cd, Skip Changelog

#6774 move favor state arg to click
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/searchindex.js
  tests/functional/defer_state/test_defer_state.py
Labels: cla:yes, Skip Changelog

#6771 mutually exclusive handling for warn_error_options and warn_error params in Click CLI
  .changes/unreleased/Under the Hood-20230130-180917.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/params.py
  core/dbt/events/functions.py
  core/dbt/flags.py
  core/dbt/helper_types.py
  test/unit/test_flags.py
  tests/unit/test_cli_flags.py
  tests/unit/test_dbt_runner.py
Labels: cla:yes

#6785 Enable the new Click Cli
  .changes/unreleased/Under the Hood-20230130-175752.yaml
  core/setup.py
Labels: cla:yes

#6648 Adding entity node to core
  .changes/unreleased/Features-20230118-134804.yaml
  core/dbt/compilation.py
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/context/context_config.py
  core/dbt/context/providers.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/graph/cli.py
  core/dbt/graph/queue.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/node_types.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  core/dbt/task/list.py
  schemas/dbt/catalog/v1.json
  schemas/dbt/manifest/v5.json
  schemas/dbt/manifest/v6.json
  schemas/dbt/manifest/v7.json
  schemas/dbt/manifest/v8.json
  schemas/dbt/run-results/v4.json
  schemas/dbt/sources/v3.json
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_manifest.py
  test/unit/test_node_types.py
  testing-project/postgres/.gitignore
  testing-project/postgres/dbt_project.yml
  testing-project/postgres/models/combined_orders_customers.sql
  testing-project/postgres/models/dim_customers.sql
  testing-project/postgres/models/dim_customers.yml
  testing-project/postgres/models/entities/customers.yml
  testing-project/postgres/models/entities/orders.yml
  testing-project/postgres/models/fact_orders.sql
  testing-project/postgres/models/fact_orders.yml
  testing-project/postgres/models/metrics/revenue.yml
  testing-project/postgres/seeds/dim_customers_source.csv
  testing-project/postgres/seeds/fact_orders_source.csv
  tests/functional/artifacts/data/state/v8/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes, Team:Language

#6802 Implement --version in click
  .changes/unreleased/Under the Hood-20230126-143102.yaml
  .github/workflows/main.yml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/docs/build/doctrees/environment.pickle
  tests/unit/test_cli_flags.py
Labels: cla:yes

#6799 fix contributor list generation
  .changie.yaml
Labels: cla:yes, Skip Changelog

#6766 Ct 1827/064 column comments tests conversion
  tests/adapter/dbt/tests/adapter/persist_docs/fixtures.py
  tests/adapter/dbt/tests/adapter/persist_docs/test_persist_docs.py
Labels: cla:yes, Skip Changelog

#6764 Add clearer directions for custom test suite vars in Makefile.
  .changes/unreleased/Features-20230126-154716.yaml
  .gitignore
  Makefile
Labels: cla:yes
