Repository dbt-labs/dbt-core, pull requests merged in 2023-09, with the labels that each got.

#8449 ADAP-814: Add support for replacing materialized views with tables/views and vice versa
  .changes/unreleased/Fixes-20230817-185739.yaml
  core/dbt/adapters/base/relation.py
  core/dbt/include/global_project/macros/adapters/relation.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/view/create_or_replace_view.sql
  core/dbt/include/global_project/macros/relations/create.sql
  core/dbt/include/global_project/macros/relations/create_backup.sql
  core/dbt/include/global_project/macros/relations/create_intermediate.sql
  core/dbt/include/global_project/macros/relations/drop.sql
  core/dbt/include/global_project/macros/relations/drop_backup.sql
  core/dbt/include/global_project/macros/relations/materialized_view/_replace.sql
  core/dbt/include/global_project/macros/relations/materialized_view/alter.sql
  core/dbt/include/global_project/macros/relations/materialized_view/create.sql
  core/dbt/include/global_project/macros/relations/materialized_view/drop.sql
  core/dbt/include/global_project/macros/relations/materialized_view/refresh.sql
  core/dbt/include/global_project/macros/relations/materialized_view/rename.sql
  core/dbt/include/global_project/macros/relations/rename.sql
  core/dbt/include/global_project/macros/relations/rename_intermediate.sql
  core/dbt/include/global_project/macros/relations/replace.sql
  core/dbt/include/global_project/macros/relations/table/drop.sql
  core/dbt/include/global_project/macros/relations/table/rename.sql
  core/dbt/include/global_project/macros/relations/view/drop.sql
  core/dbt/include/global_project/macros/relations/view/rename.sql
  plugins/postgres/dbt/adapters/postgres/relation.py
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/alter.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/drop.sql
  plugins/postgres/dbt/include/postgres/macros/relations/table/drop.sql
  plugins/postgres/dbt/include/postgres/macros/relations/table/rename.sql
  plugins/postgres/dbt/include/postgres/macros/relations/view/drop.sql
  plugins/postgres/dbt/include/postgres/macros/relations/view/rename.sql
  tests/functional/materializations/materialized_view_tests/test_materialized_view.py
  tests/unit/test_relation.py
Labels: cla:yes

#8527 Support dbt-cloud config dict in dbt_project.yml
  .changes/unreleased/Features-20230830-212828.yaml
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/contracts/project.py
  tests/functional/basic/test_project.py
Labels: cla:yes

#8555 [Backport] 1.6.latest dbt-cloud config
  .changes/unreleased/Features-20230830-212828.yaml
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/contracts/project.py
  tests/functional/basic/test_project.py
Labels: cla:yes

#8556 [Backport] 1.5.latest dbt-cloud config
  .changes/unreleased/Features-20230830-212828.yaml
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/contracts/project.py
  tests/functional/basic/test_project.py
Labels: cla:yes

#8557 remove label
  .github/workflows/docs-issue.yml
Labels: cla:yes, Skip Changelog

#8569 add typing to partially typed methods in runnable.py
  .changes/unreleased/Under the Hood-20230906-132435.yaml
  core/dbt/task/runnable.py
Labels: cla:yes

#8552 test advanced ref override
  .changes/unreleased/Under the Hood-20230906-110249.yaml
  tests/functional/ref_override/test_ref_override.py
Labels: cla:yes

#8559 make UnparsedVersion.__lt__ order-agnostic
  .changes/unreleased/Fixes-20230906-142213.yaml
  core/dbt/contracts/graph/unparsed.py
  tests/unit/test_contracts_graph_unparsed.py
  tests/unit/test_graph_selector_methods.py
Labels: cla:yes

#8591 Revert "Preserve decimal places for dbt show (#8561) (#8588)"
  .changes/unreleased/Fixes-20230803-093502.yaml
  core/dbt/clients/agate_helper.py
  tests/functional/show/fixtures.py
  tests/functional/show/test_show.py
  tests/unit/test_agate_helper.py
Labels: cla:yes, Skip Changelog

#8578 Unskip and rename test_expression_metric
  .changes/unreleased/Fixes-20230906-120212.yaml
  core/dbt/context/providers.py
  core/dbt/contracts/graph/metrics.py
  tests/functional/metrics/test_metric_helper_functions.py
Labels: cla:yes

#8613 update PR template
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#8539 ADAP-869: Support atomic replace in replace macro
  .changes/unreleased/Features-20230831-204804.yaml
  core/dbt/adapters/base/relation.py
  core/dbt/include/global_project/macros/materializations/models/materialized_view.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/get_materialized_view_configuration_changes.sql
  core/dbt/include/global_project/macros/materializations/models/table.sql
  core/dbt/include/global_project/macros/materializations/models/view.sql
  core/dbt/include/global_project/macros/materializations/models/view/helpers.sql
  core/dbt/include/global_project/macros/relations/column/columns_spec_ddl.sql
  core/dbt/include/global_project/macros/relations/materialized_view/_replace.sql
  core/dbt/include/global_project/macros/relations/materialized_view/alter.sql
  core/dbt/include/global_project/macros/relations/materialized_view/replace.sql
  core/dbt/include/global_project/macros/relations/replace.sql
  core/dbt/include/global_project/macros/relations/table/create.sql
  core/dbt/include/global_project/macros/relations/table/replace.sql
  core/dbt/include/global_project/macros/relations/view/create.sql
  core/dbt/include/global_project/macros/relations/view/replace.sql
  plugins/postgres/dbt/adapters/postgres/relation.py
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/_replace.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/alter.sql
  plugins/postgres/dbt/include/postgres/macros/relations/table/replace.sql
  plugins/postgres/dbt/include/postgres/macros/relations/view/replace.sql
  tests/unit/test_relation.py
Labels: cla:yes

#8619 [BACKPORT 1.6.latest] Preserve decimal places for dbt show (#8561)
  .changes/unreleased/Fixes-20230803-093502.yaml
  core/dbt/clients/agate_helper.py
  tests/functional/show/fixtures.py
  tests/functional/show/test_show.py
  tests/unit/test_agate_helper.py
Labels: cla:yes

#8603 [BACKPORT] Split integration tests into parallel groups / jobs (#6346)
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#8622 Revert "Merge branch 'main' into main"
  .github/workflows/release-docker.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
Labels: cla:yes, Skip Changelog

#8565 unit test config
  .changes/unreleased/Features-20230906-234741.yaml
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/context/context_config.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/parser/unit_tests.py
  schemas/dbt/manifest/v11.json
  tests/unit/test_parser.py
  tests/unit/test_unit_test_parser.py
  tests/unit/utils.py
Labels: user docs, cla:yes

#8610 Flaky Tests: split up dbt show test class
  tests/functional/show/test_show.py
Labels: cla:yes, Skip Changelog, backport 1.6.latest

#8637 replace is_replaceable function with can_be_replaced call
  core/dbt/include/global_project/macros/relations/replace.sql
Labels: cla:yes, Skip Changelog

#8639 Add additional functional test for unit testing selection, artifacts, etc
  .changes/unreleased/Under the Hood-20230912-190506.yaml
  tests/functional/unit_testing/test_unit_testing.py
Labels: cla:yes

#8644 Fix test_numeric_values of the show test
  .changes/unreleased/Under the Hood-20230913-141651.yaml
  tests/functional/show/test_show.py
Labels: cla:yes

#8647 Loosen type on replaceable_relation and renameable_relation and provide guidance in docstrings
  .changes/unreleased/Features-20230913-182707.yaml
  core/dbt/adapters/base/relation.py
Labels: cla:yes

#8635 Allow setting access in config in addition to properties
  .changes/unreleased/Features-20230912-153013.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/base.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v11.json
  tests/functional/access/test_access.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/unit/test_contracts_graph_compiled.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_manifest.py
  tests/unit/test_parser.py
Labels: user docs, cla:yes

#7450 Use profile specified in --profile with dbt init
  .changes/unreleased/Fixes-20230424-161642.yaml
  core/dbt/cli/params.py
  core/dbt/task/init.py
  tests/functional/init/test_init.py
Labels: user docs, cla:yes, ready_for_review

#8604 [BACKPORT] 1.4.latest - 7630
  .changes/unreleased/Fixes-20230515-142851.yaml
  core/dbt/config/renderer.py
Labels: cla:yes

#8605 [BACKPORT] 1.3.latest 7630
  .changes/unreleased/Fixes-20230515-142851.yaml
  core/dbt/config/renderer.py
Labels: cla:yes

#8536 More Type Annotations
  .changes/unreleased/Under the Hood-20230831-164435.yaml
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/base/plugin.py
  core/dbt/adapters/base/query_headers.py
  core/dbt/adapters/cache.py
  core/dbt/adapters/protocol.py
  core/dbt/cli/main.py
  core/dbt/cli/options.py
  core/dbt/clients/agate_helper.py
  core/dbt/compilation.py
  core/dbt/config/profile.py
  core/dbt/config/renderer.py
  core/dbt/config/runtime.py
  core/dbt/contracts/connection.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/metrics.py
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/results.py
  core/dbt/contracts/state.py
  core/dbt/events/adapter_endpoint.py
  core/dbt/events/base_types.py
  core/dbt/events/eventmgr.py
  core/dbt/events/format.py
  core/dbt/events/functions.py
  core/dbt/events/types.py
  core/dbt/exceptions.py
  core/dbt/graph/graph.py
  core/dbt/graph/queue.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/graph/selector_spec.py
  core/dbt/logger.py
  core/dbt/parser/models.py
  core/dbt/parser/partial.py
  core/dbt/parser/schema_yaml_readers.py
  core/dbt/plugins/manager.py
  core/dbt/semver.py
  core/dbt/task/base.py
  core/dbt/task/deps.py
  core/dbt/task/generate.py
  core/dbt/task/list.py
  core/dbt/task/retry.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/dbt/task/show.py
  core/dbt/task/sql.py
  core/dbt/task/test.py
  core/dbt/tracking.py
  core/dbt/utils.py
Labels: cla:yes

#8643 Allow adapters to include python package logging in dbt logs
  .changes/unreleased/Features-20230915-123733.yaml
  core/dbt/events/adapter_endpoint.py
  core/dbt/events/event_handler.py
  core/dbt/events/functions.py
  tests/unit/test_event_handler.py
  tests/unit/test_events.py
Labels: cla:yes

#8646 Support labels for semantic_models, dimensions, measures and entities
  .changes/unreleased/Features-20230914-074429.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_models.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/semantic_models/fixtures.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: user docs, cla:yes

#8687 Update pull request template to include type annotations as part of checklist
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#8665 Support quoted parameter list for MultiOption cli options
  .changes/unreleased/Features-20230918-150855.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/options.py
  tests/functional/cli/test_multioption.py
  tests/functional/retry/fixtures.py
  tests/functional/retry/test_retry.py
  tests/unit/test_cli_flags.py
Labels: cla:yes, backport 1.5.latest, backport 1.6.latest

#8684 Lower bound of `8.0.2` for `click`
  .changes/unreleased/Fixes-20230920-165635.yaml
  core/setup.py
Labels: cla:yes, ready_for_review

#8700 Support null coalescing properties for metric nodes
  .changes/unreleased/Features-20230922-150754.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/metrics/fixtures.py
  tests/unit/test_contracts_graph_unparsed.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes

#8616 Add date spine macros to core
  .changes/unreleased/Features-20230922-112531.yaml
  core/dbt/include/global_project/macros/utils/date_spine.sql
  core/dbt/include/global_project/macros/utils/generate_series.sql
  tests/adapter/dbt/tests/adapter/utils/fixture_date_spine.py
  tests/adapter/dbt/tests/adapter/utils/fixture_generate_series.py
  tests/adapter/dbt/tests/adapter/utils/fixture_get_intervals_between.py
  tests/adapter/dbt/tests/adapter/utils/fixture_get_powers_of_two.py
  tests/adapter/dbt/tests/adapter/utils/test_date_spine.py
  tests/adapter/dbt/tests/adapter/utils/test_generate_series.py
  tests/adapter/dbt/tests/adapter/utils/test_get_intervals_between.py
  tests/adapter/dbt/tests/adapter/utils/test_get_powers_of_two.py
Labels: user docs, cla:yes, test macos

#8696 CT-3144 Fix test edges type filter on Graph
  .changes/unreleased/Fixes-20230922-223313.yaml
  core/dbt/graph/graph.py
Labels: cla:yes, ready_for_review

#8686 Automated Repo Cleanup
  .github/workflows/repository-cleanup.yml
Labels: cla:yes, Skip Changelog

#8703 [Backport 1.5.latest] Support quoted parameter list for MultiOption cli options
  .changes/unreleased/Features-20230918-150855.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/options.py
  tests/functional/cli/test_multioption.py
Labels: cla:yes

#8716 CT-3144 Fix test edges type filter on Graph (#8696)
  .changes/unreleased/Fixes-20230922-223313.yaml
  core/dbt/graph/graph.py
Labels: cla:yes, backport 1.6.latest

#8589 Dc/8546 semantic models in graph selection
  .changes/unreleased/Fixes-20230925-233306.yaml
  core/dbt/cli/params.py
  core/dbt/compilation.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/graph/cli.py
  core/dbt/graph/selector_methods.py
  core/dbt/task/list.py
  tests/functional/list/fixtures.py
  tests/functional/list/test_list.py
  tests/unit/test_graph_selector_methods.py
Labels: user docs, cla:yes, backport 1.6.latest

#8721 Model contracts: raise warning for numeric types without specified scale
  .changes/unreleased/Features-20230926-134728.yaml
  core/dbt/include/global_project/macros/adapters/columns.sql
  tests/functional/contracts/test_contract_precision.py
Labels: cla:yes

#8641 Inline limit in SQL sent from `dbt show`
  .changes/unreleased/Fixes-20230913-153924.yaml
  core/dbt/include/global_project/macros/adapters/show.sql
  core/dbt/task/show.py
  tests/adapter/dbt/tests/adapter/dbt_show/fixtures.py
  tests/adapter/dbt/tests/adapter/dbt_show/test_dbt_show.py
  tests/functional/show/fixtures.py
  tests/functional/show/test_show.py
Labels: user docs, cla:yes, backport 1.5.latest, backport 1.6.latest

#8322 [CT-748] feat: resolve packages with same git repo and unique subdirectory
  .changes/unreleased/Features-20230916-120547.yaml
  core/dbt/deps/git.py
  tests/unit/test_deps.py
Labels: cla:yes, ready_for_review

#8731 [Backport 1.5.latest] Inline limit in SQL sent from `dbt show` (#8641)
  .changes/unreleased/Fixes-20230913-153924.yaml
  core/dbt/include/global_project/macros/adapters/show.sql
  core/dbt/task/show.py
  tests/adapter/dbt/tests/adapter/dbt_show/fixtures.py
  tests/adapter/dbt/tests/adapter/dbt_show/test_dbt_show.py
  tests/functional/show/fixtures.py
  tests/functional/show/test_show.py
Labels: cla:yes

#8737 Fix changelog kind
  .changes/unreleased/Features-20230918-150855.yaml
Labels: cla:yes

#8735 update changelog type
  .changes/unreleased/Features-20230918-150855.yaml
Labels: cla:yes

#8736 fix changelog kind
  .changes/unreleased/Features-20230918-150855.yaml
Labels: cla:yes

#8740 Fix: avoid double-rendering sql_header in dbt show
  .changes/unreleased/Fixes-20230928-184856.yaml
  core/dbt/include/global_project/macros/adapters/show.sql
  tests/adapter/dbt/tests/adapter/dbt_show/fixtures.py
  tests/adapter/dbt/tests/adapter/dbt_show/test_dbt_show.py
Labels: cla:yes, backport 1.5.latest, backport 1.6.latest

#8747 fix duplication of docs issues
  .github/workflows/docs-issue.yml
Labels: cla:yes, Skip Changelog

#8750 Fix `tag:` selection for projects with semantic models
  .changes/unreleased/Fixes-20230929-175342.yaml
  core/dbt/graph/selector_methods.py
  tests/unit/test_graph_selector_methods.py
Labels: cla:yes, backport 1.6.latest

#8648 Add new get_catalog_relations macro, Supporting Changes
  .changes/unreleased/Features-20230929-154743.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/base/relation.py
  core/dbt/include/global_project/macros/adapters/metadata.sql
  plugins/postgres/dbt/adapters/postgres/impl.py
  plugins/postgres/dbt/include/postgres/macros/catalog.sql
  tests/functional/artifacts/test_override.py
  tests/unit/test_postgres_adapter.py
Labels: cla:yes

#8671 Report Resource Usage Statistics When a dbt Command Finishes
  .changes/unreleased/Features-20230919-102148.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/events/base_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  tests/functional/events/events.py
  tests/unit/test_events.py
Labels: cla:yes
