Repository dbt-labs/dbt-core, pull requests merged in 2023-11, with the labels that each got.

#8950 DSI 0.4.0 and Saved Query Exports
  .changes/unreleased/Dependencies-20231031-131954.yaml
  .changes/unreleased/Features-20231031-132022.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/saved_queries.py
  core/dbt/contracts/graph/semantic_layer_common.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_renderer.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  schemas/dbt/manifest/v11.json
  tests/functional/artifacts/data/state/v11/manifest.json
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_saved_query_parsing.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_manifest.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: user docs, cla:yes, artifacts

#8945 ADAP-974: Fix issue where materialized views were not showing up in catalog queries
  .changes/unreleased/Fixes-20231031-005345.yaml
  plugins/postgres/dbt/include/postgres/macros/catalog.sql
  tests/functional/catalog_tests/files.py
  tests/functional/catalog_tests/test_relation_types.py
Labels: cla:yes, backport 1.6.latest, backport 1.7.latest

#8973 [Backport 1.7.latest] DSI 0.4.0 and Saved Query Exports
  .changes/unreleased/Dependencies-20231031-131954.yaml
  .changes/unreleased/Features-20231031-132022.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/saved_queries.py
  core/dbt/contracts/graph/semantic_layer_common.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_renderer.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  schemas/dbt/manifest/v11.json
  tests/functional/artifacts/data/state/v11/manifest.json
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_saved_query_parsing.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_manifest.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes

#8931 remove dbt.flags.MP_CONTEXT usage in dbt/adapters
  .changes/unreleased/Under the Hood-20231101-102758.yaml
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/factory.py
  core/dbt/cli/flags.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/flags.py
  core/dbt/mp_context.py
  tests/unit/test_cli_flags.py
  tests/unit/test_context.py
  tests/unit/test_postgres_adapter.py
Labels: cla:yes

#8975 Make relation Filtering None-tolerant for maximal flexibility
  .changes/unreleased/Fixes-20231101-155824.yaml
  core/dbt/adapters/base/impl.py
Labels: backport 1.7.latest

#8978 [Backport] Make relation filtering None-tolerant for maximal flexibility
  .changes/unreleased/Fixes-20231101-155824.yaml
  core/dbt/adapters/base/impl.py
Labels: cla:yes

#8933 remove dbt.flags.LOG_CACHE_EVENTS usage in dbt/adapters
  .changes/unreleased/Under the Hood-20231101-173124.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/cache.py
  core/dbt/adapters/contracts/connection.py
  core/dbt/config/profile.py
  core/dbt/config/runtime.py
Labels: cla:yes

#8891 Support unit testing incremental models
  .changes/unreleased/Features-20231101-101845.yaml
  core/dbt/context/providers.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/exceptions.py
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/test_unit_testing.py
Labels: cla:yes

#8988 update unit test key: unit -> unit-tests
  core/dbt/config/project.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/project.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/test_unit_testing.py
  tests/unit/test_unit_test_parser.py
Labels: cla:yes, Skip Changelog

#8966 convert to use unit test name at top level key
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/partial.py
  core/dbt/parser/unit_tests.py
  core/dbt/task/unit_test.py
  tests/functional/unit_testing/test_unit_testing.py
  tests/unit/test_unit_test_parser.py
Labels: cla:yes, Skip Changelog

#8842 Update capability.py
  core/dbt/adapters/capability.py
Labels: cla:yes, Skip Changelog

#9009 Fix back compat for run_results pre-v5
  .changes/unreleased/Fixes-20231106-155933.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/results.py
  core/dbt/contracts/util.py
  tests/functional/artifacts/data/results/v4/run_results.json
  tests/functional/artifacts/data/results/v5/run_results.json
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes, backport 1.7.latest

#9017 [Backport] of run results back compat
  .changes/unreleased/Fixes-20231106-155933.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/results.py
  core/dbt/contracts/util.py
  tests/functional/artifacts/data/results/v4/run_results.json
  tests/functional/artifacts/data/results/v5/run_results.json
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes

#9008 Remove `documentable` as it isn't used anywhere
  .changes/unreleased/Under the Hood-20231106-105730.yaml
  core/dbt/node_types.py
Labels: cla:yes

#9021 Use MANIFEST.in to identify package data, allows recursive include
  .changes/unreleased/Fixes-20231107-094130.yaml
  plugins/postgres/MANIFEST.in
  plugins/postgres/setup.py
Labels: cla:yes, backport 1.7.latest

#9004 Support new agate Integer data_type in adapter code
  .changes/unreleased/Fixes-20231031-144837.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/sql/impl.py
  tests/adapter/dbt/tests/adapter/simple_seed/test_seed.py
  tests/unit/mock_adapter.py
Labels: cla:yes

#9019 Fix lock for git subduer
  .changes/unreleased/Fixes-20231107-092358.yaml
  core/dbt/deps/base.py
  core/dbt/deps/git.py
  core/dbt/deps/local.py
  core/dbt/deps/registry.py
  core/dbt/deps/tarball.py
  core/dbt/task/deps.py
  tests/functional/dependencies/test_simple_dependency.py
Labels: cla:yes

#9002 fix: get_custom_database docs describe postfix when default behaviour…
  .changes/unreleased/Docs-20231106-123157.yaml
  core/dbt/include/global_project/macros/get_custom_name/get_custom_database.sql
Labels: cla:yes, ready_for_review

#9036 [Backport 1.6.latest] Support new agate Integer type and test empty seed file
  .changes/unreleased/Fixes-20231031-144837.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/sql/impl.py
  tests/adapter/dbt/tests/adapter/simple_seed/test_seed.py
  tests/unit/mock_adapter.py
Labels: cla:yes

#8994 [IDE] also treat SystemExit exception as an interrupt.
  .changes/unreleased/Under the Hood-20231106-080422.yaml
  core/dbt/task/runnable.py
Labels: cla:yes, ready_for_review, backport 1.6.latest, Impact: Exp, backport 1.7.latest

#8868 Add drop_schema_named macro
  .changes/unreleased/Features-20231017-143620.yaml
  core/dbt/include/global_project/macros/relations/schema.sql
  tests/adapter/dbt/tests/adapter/relations/test_dropping_schema_named.py
Labels: cla:yes, ready_for_review

#9012 Update typing-extensions version to >=4.4
  .changes/unreleased/Dependencies-20231106-130051.yaml
  core/setup.py
Labels: cla:yes

#8203 [Feature] Supports non half width alphanumeric for generic test
  .changes/unreleased/Features-20230725-122847.yaml
  core/dbt/parser/generic_test_builders.py
  tests/adapter/dbt/tests/adapter/basic/files.py
  tests/adapter/dbt/tests/adapter/basic/test_generic_tests.py
Labels: cla:yes, ready_for_review

#8952 Migrate TestCatalogRelationTypes to the shared adapter tests framework
  .changes/unreleased/Under the Hood-20231103-195222.yaml
  tests/adapter/dbt/tests/adapter/catalog/files.py
  tests/adapter/dbt/tests/adapter/catalog/relation_types.py
  tests/functional/catalog_tests/test_relation_types.py
Labels: cla:yes

#9044 csv file fixtures
  .changes/unreleased/Features-20231106-194752.yaml
  core/dbt/config/project.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_csv_fixtures.py
  tests/functional/unit_testing/test_unit_testing.py
Labels: cla:yes

#9048 Revert "[Feature] Supports non half width alphanumeric for generic te…
  .changes/unreleased/Features-20230725-122847.yaml
  core/dbt/parser/generic_test_builders.py
  tests/adapter/dbt/tests/adapter/basic/files.py
  tests/adapter/dbt/tests/adapter/basic/test_generic_tests.py
Labels: cla:yes, Skip Changelog

#9032 Unit test support for `state:modified` and `--defer`
  .changes/unreleased/Features-20231107-231006.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/unit_tests.py
  core/dbt/task/unit_test.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_state.py
  tests/functional/unit_testing/test_unit_testing.py
  tests/unit/test_unit_test_parser.py
Labels: cla:yes

#9065 Support hierarchical config setting for SavedQueryExport configs
  .changes/unreleased/Features-20231110-154255.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_configs.py
Labels: cla:yes

#9068 Fix dbt deps failing on tarballs
  .changes/unreleased/Fixes-20231113-114956.yaml
  core/dbt/deps/tarball.py
  tests/functional/dependencies/test_simple_dependency.py
Labels: cla:yes

#9059 Allow use of sources as unit testing inputs
  .changes/unreleased/Features-20231111-191150.yaml
  core/dbt/adapters/base/relation.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/test_ut_sources.py
Labels: cla:yes

#8984 Use daff for diff formatting in unit testing
  .changes/unreleased/Features-20231114-101555.yaml
  core/dbt/clients/agate_helper.py
  core/dbt/task/unit_test.py
  core/setup.py
  third-party-stubs/daff/__init__.pyi
Labels: cla:yes

#9085 document scripts/collect-artifact-schema
  core/dbt/contracts/README.md
Labels: Skip Changelog

#9090 test pinning ddtrace
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#9097 [Backport 1.3.latest] test pinning ddtrace (#9090)
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#9101 Add test asserting GraphRunnableTasks attempt to cancel connections on SystemExit
  tests/unit/test_graph_runnable_task.py
Labels: cla:yes, Skip Changelog

#9106 roll back agate pin
  core/setup.py
Labels: cla:yes, Skip Changelog

#8855 import nested tarball package dependencies
  .changes/unreleased/Fixes-20231013-130943.yaml
  core/dbt/deps/tarball.py
  tests/functional/dependencies/test_simple_dependency.py
  tests/unit/test_deps.py
Labels: cla:yes, ready_for_review

#9118 Update comment regarding setting input_measures in metric parsing
  core/dbt/parser/schema_yaml_readers.py
Labels: cla:yes, tech_debt, Skip Changelog

#9120 Roadmap update (Nov 2023)
  docs/roadmap/2023-11-dbt-tng.md
Labels: cla:yes, Skip Changelog

#9051 Remove usage of dbt.deprecations in dbt/adapters, enable core & adapter-specific
  .changes/unreleased/Under the Hood-20231116-174251.yaml
  .pre-commit-config.yaml
  Makefile
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/base/meta.py
  core/dbt/adapters/cache.py
  core/dbt/adapters/contracts/connection.py
  core/dbt/adapters/events/README.md
  core/dbt/adapters/events/__init__.py
  core/dbt/adapters/events/adapter_types.proto
  core/dbt/adapters/events/adapter_types_pb2.py
  core/dbt/adapters/events/base_types.py
  core/dbt/adapters/events/types.py
  core/dbt/adapters/factory.py
  core/dbt/adapters/sql/connections.py
  core/dbt/adapters/sql/impl.py
  core/dbt/common/events/adapter_endpoint.py
  core/dbt/common/events/base_types.py
  core/dbt/common/events/eventmgr.py
  core/dbt/common/events/types.proto
  core/dbt/common/events/types.py
  core/dbt/common/events/types_pb2.py
  core/dbt/deprecations.py
  core/dbt/events/README.md
  core/dbt/events/__init__.py
  core/dbt/events/base_types.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/internal_deprecations.py
  core/dbt/parser/manifest.py
  core/dbt/task/generate.py
  core/dbt/task/run.py
  core/dbt/tests/fixtures/project.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/test_events.py
  tests/unit/test_proto_events.py
Labels: cla:yes

#9031 Cache plugin modules
  .changes/unreleased/Under the Hood-20231107-191546.yaml
  core/dbt/plugins/manager.py
Labels: cla:yes

#9054 Decouple adapter constraints from core
  .changes/unreleased/Under the Hood-20231120-183214.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/common/contracts/constraints.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/common.py
  core/dbt/parser/schemas.py
  plugins/postgres/dbt/adapters/postgres/impl.py
Labels: cla:yes

#9058 Fix test_current_timestamp_matches_utc
  .changes/unreleased/Under the Hood-20231111-175350.yaml
  tests/adapter/dbt/tests/adapter/utils/test_current_timestamp.py
Labels: cla:yes, backport 1.5.latest, backport 1.6.latest, backport 1.7.latest

#9147 Fixups for deps lock file
  .changes/unreleased/Fixes-20231127-154310.yaml
  .changes/unreleased/Fixes-20231127-154347.yaml
  core/dbt/clients/git.py
  core/dbt/config/project.py
  core/dbt/contracts/project.py
  core/dbt/deps/git.py
  core/dbt/deps/tarball.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/task/deps.py
  tests/functional/context_methods/test_secret_env_vars.py
  tests/functional/dependencies/test_dependency_options.py
  tests/functional/dependencies/test_simple_dependency.py
  tests/unit/test_config.py
  tests/unit/test_deps.py
  tests/unit/test_events.py
Labels: cla:yes, backport 1.7.latest

#9134 remove adapter.get_compiler
  .changes/unreleased/Breaking Changes-20231127-114757.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/protocol.py
  core/dbt/compilation.py
  core/dbt/task/base.py
  core/dbt/task/build.py
  core/dbt/task/compile.py
  core/dbt/task/run.py
  core/dbt/task/sql.py
Labels: cla:yes

#9165 Move adapter logger to adapters
  .changes/unreleased/Breaking Changes-20231128-134356.yaml
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/events/README.md
  core/dbt/adapters/events/logging.py
  core/dbt/common/events/README.md
  core/dbt/common/events/__init__.py
  plugins/postgres/dbt/adapters/postgres/connections.py
  tests/unit/test_adapter_connection_manager.py
  tests/unit/test_events.py
Labels: cla:yes

#9157 Restore warning on unpinned git packages
  core/dbt/deps/git.py
Labels: cla:yes, Skip Changelog

#9156 Backport #9147 to 1.7.latest
  .changes/unreleased/Fixes-20231127-154310.yaml
  .changes/unreleased/Fixes-20231127-154347.yaml
  core/dbt/clients/git.py
  core/dbt/config/project.py
  core/dbt/contracts/project.py
  core/dbt/deps/git.py
  core/dbt/deps/tarball.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/task/deps.py
  tests/functional/context_methods/test_secret_env_vars.py
  tests/functional/dependencies/test_dependency_options.py
  tests/functional/dependencies/test_simple_dependency.py
  tests/unit/test_config.py
  tests/unit/test_deps.py
  tests/unit/test_events.py
Labels: cla:yes

#9166 Move the semver package to common and alter references.
  .changes/unreleased/Under the Hood-20231128-170732.yaml
  core/dbt/adapters/factory.py
  core/dbt/clients/registry.py
  core/dbt/common/semver.py
  core/dbt/config/project.py
  core/dbt/deps/registry.py
  core/dbt/version.py
  tests/functional/dependencies/test_local_dependency.py
  tests/unit/test_config.py
  tests/unit/test_deps.py
  tests/unit/test_semver.py
Labels: cla:yes

#9184 Enable unit testing in non-root packages
  .changes/unreleased/Features-20231130-130948.yaml
  core/dbt/adapters/base/relation.py
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/test_ut_dependency.py
Labels: cla:yes
