Repository dbt-labs/dbt-core, pull requests merged in 2023-12, with the labels that each got.

#9180 Refactor EventManager setup and interaction
  .changes/unreleased/Breaking Changes-20231130-135348.yaml
  .changes/unreleased/Under the Hood-20231130-135432.yaml
  core/dbt/adapters/cache.py
  core/dbt/adapters/events/logging.py
  core/dbt/cli/requires.py
  core/dbt/common/events/__init__.py
  core/dbt/common/events/base_types.py
  core/dbt/common/events/event_handler.py
  core/dbt/common/events/event_manager.py
  core/dbt/common/events/event_manager_client.py
  core/dbt/common/events/functions.py
  core/dbt/common/invocation.py
  core/dbt/common/utils/formatting.py
  core/dbt/compilation.py
  core/dbt/contracts/results.py
  core/dbt/contracts/util.py
  core/dbt/events/logging.py
  core/dbt/task/docs/generate.py
  core/dbt/task/runnable.py
  core/dbt/tests/fixtures/project.py
  core/dbt/utils.py
  tests/unit/test_event_handler.py
  tests/unit/test_events.py
  tests/unit/test_functions.py
  tests/unit/test_graph.py
  tests/unit/test_manifest.py
Labels: cla:yes

#9160 adapter migration progress tracking script
  scripts/migrate-adapters.py
Labels: cla:yes, Skip Changelog

#9149 Decouple macro generator from adapters
  .changes/unreleased/Under the Hood-20231205-093544.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/base/query_headers.py
  core/dbt/adapters/clients/__init__.py
  core/dbt/adapters/clients/jinja.py
  core/dbt/cli/flags.py
  core/dbt/clients/jinja.py
  core/dbt/clients/jinja_static.py
  core/dbt/common/clients/_jinja_blocks.py
  core/dbt/common/clients/jinja.py
  core/dbt/common/exceptions/macros.py
  core/dbt/common/utils/__init__.py
  core/dbt/common/utils/jinja.py
  core/dbt/config/renderer.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/exceptions.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/macros.py
  core/dbt/parser/search.py
  core/dbt/utils.py
  tests/unit/common/test_jinja.py
  tests/unit/test_jinja.py
Labels: cla:yes

#9207 Remove usage of dbt.contracts.relation in dbt/adapters
  .changes/unreleased/Under the Hood-20231205-120559.yaml
  core/dbt/adapters/base/relation.py
  core/dbt/adapters/contracts/relation.py
  core/dbt/adapters/protocol.py
  core/dbt/common/exceptions/__init__.py
  core/dbt/common/exceptions/contracts.py
  core/dbt/config/runtime.py
  core/dbt/context/exceptions_jinja.py
  core/dbt/contracts/util.py
  core/dbt/exceptions.py
  plugins/postgres/dbt/adapters/postgres/relation.py
  tests/adapter/dbt/tests/adapter/materialized_view/basic.py
  tests/adapter/dbt/tests/adapter/materialized_view/changes.py
  tests/unit/test_postgres_adapter.py
  tests/unit/test_relation.py
Labels: cla:yes

#9155 Fix ensuring we produce valid jsonschema artifacts for manifest, catalog, sources, and run-results
  .changes/unreleased/Fixes-20231127-165244.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/results.py
  core/dbt/contracts/util.py
  schemas/dbt/catalog/v1.json
  schemas/dbt/manifest/v12.json
  schemas/dbt/run-results/v6.json
  schemas/dbt/sources/v3.json
  tests/functional/artifacts/data/results/v6/run_results.json
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
  tests/unit/test_manifest.py
Labels: cla:yes, Impact: CA

#9211 Remove ResultNode usage from connections
  .changes/unreleased/Under the Hood-20231205-165812.yaml
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/base/query_headers.py
  core/dbt/task/base.py
  core/dbt/task/freshness.py
Labels: cla:yes

#9210 Add RelationConfig Protocol for use in Relation.create_from
  .changes/unreleased/Under the Hood-20231205-170725.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/base/relation.py
  core/dbt/adapters/contracts/__init__.py
  core/dbt/adapters/contracts/relation.py
  core/dbt/adapters/protocol.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/manifest.py
  core/dbt/task/clone.py
  core/dbt/task/freshness.py
Labels: cla:yes

#9240 Merge main into feature/decouple-adapters-from-core
  .changes/unreleased/Features-20231116-234049.yaml
  .changes/unreleased/Fixes-20231127-165244.yaml
  core/dbt/adapters/base/relation.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/results.py
  core/dbt/contracts/util.py
  core/dbt/deps/git.py
  schemas/dbt/catalog/v1.json
  schemas/dbt/manifest/v12.json
  schemas/dbt/run-results/v6.json
  schemas/dbt/sources/v3.json
  tests/adapter/dbt/tests/adapter/empty/test_empty.py
  tests/functional/artifacts/data/results/v6/run_results.json
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
  tests/unit/test_manifest.py
  tests/unit/test_providers.py
  tests/unit/test_relation.py
Labels: cla:yes

#9224 Move BaseConfig to Common
  .changes/unreleased/Under the Hood-20231205-185022.yaml
  core/dbt/adapters/protocol.py
  core/dbt/common/contracts/config/__init__.py
  core/dbt/common/contracts/config/base.py
  core/dbt/common/contracts/config/materialization.py
  core/dbt/common/contracts/config/metadata.py
  core/dbt/common/contracts/config/properties.py
  core/dbt/context/context_config.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/util.py
  core/dbt/plugins/contracts.py
  tests/adapter/dbt/tests/adapter/materialized_view/changes.py
  tests/unit/common/test_model_config.py
Labels: cla:yes

#9242 Remove manifest from catalog and connection method signatures
  .changes/unreleased/Under the Hood-20231205-235830.yaml
  .changes/unreleased/Under the Hood-20231206-000343.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/task/docs/generate.py
  core/dbt/task/runnable.py
  tests/unit/test_postgres_adapter.py
Labels: cla:yes

#9248 pass context to MacroQueryStringSetter
  .changes/unreleased/Under the Hood-20231207-224139.yaml
  core/dbt/adapters/base/connections.py
  core/dbt/adapters/base/query_headers.py
  core/dbt/adapters/protocol.py
  core/dbt/parser/manifest.py
  tests/unit/test_postgres_adapter.py
  tests/unit/test_query_headers.py
Labels: cla:yes

#9229 [Backport 1.7.latest] Fix ensuring we produce valid jsonschema artifacts for manifest, catalog, sources, and run-results
  .changes/unreleased/Fixes-20231127-165244.yaml
  core/dbt/contracts/util.py
  schemas/dbt/catalog/v1.json
  schemas/dbt/manifest/v11.json
  schemas/dbt/run-results/v5.json
  schemas/dbt/sources/v3.json
Labels: Impact: CA

#9169 Remove `--dry-run` flag from `dbt deps`
  .changes/unreleased/Breaking Changes-20231129-091921.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/task/deps.py
  tests/functional/dependencies/test_dependency_options.py
Labels: user docs, cla:yes

#9255 [Backport 1.7.latest] Update parser to support conversion metrics #9173
  .changes/unreleased/Features-20231206-181458.yaml
  core/dbt/contracts/graph/metrics.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  schemas/dbt/manifest/v11.json
  tests/functional/artifacts/data/state/v11/manifest.json
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metrics.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes, Impact: CA

#9195 adding clean_up methods to basic and unique_id tests
  tests/adapter/dbt/tests/adapter/basic/test_adapter_methods.py
  tests/adapter/dbt/tests/adapter/basic/test_base.py
  tests/adapter/dbt/tests/adapter/basic/test_docs_generate.py
  tests/adapter/dbt/tests/adapter/basic/test_generic_tests.py
  tests/adapter/dbt/tests/adapter/basic/test_incremental.py
  tests/adapter/dbt/tests/adapter/basic/test_singular_tests.py
  tests/adapter/dbt/tests/adapter/basic/test_singular_tests_ephemeral.py
  tests/adapter/dbt/tests/adapter/basic/test_snapshot_check_cols.py
  tests/adapter/dbt/tests/adapter/basic/test_snapshot_timestamp.py
  tests/adapter/dbt/tests/adapter/incremental/test_incremental_unique_id.py
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes, Skip Changelog

#9275 Pass mp_context to adapter factory
  .changes/unreleased/Under the Hood-20231212-154842.yaml
  core/dbt/adapters/factory.py
  core/dbt/cli/requires.py
  core/dbt/task/debug.py
  core/dbt/tests/fixtures/project.py
  tests/unit/test_graph.py
Labels: cla:yes

#9286 Fix include for decoupling
  core/MANIFEST.in
Labels: cla:yes, Skip Changelog

#9288 Fix include for decoupling
  core/MANIFEST.in
Labels: cla:yes, Skip Changelog

#9294 move system client to common
  .changes/unreleased/Under the Hood-20231214-164107.yaml
  core/dbt/clients/git.py
  core/dbt/clients/registry.py
  core/dbt/common/clients/system.py
  core/dbt/common/exceptions/base.py
  core/dbt/common/semver.py
  core/dbt/common/utils/connection.py
  core/dbt/compilation.py
  core/dbt/config/profile.py
  core/dbt/config/project.py
  core/dbt/config/selectors.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/results.py
  core/dbt/contracts/util.py
  core/dbt/deps/README.md
  core/dbt/deps/base.py
  core/dbt/deps/git.py
  core/dbt/deps/local.py
  core/dbt/deps/tarball.py
  core/dbt/exceptions.py
  core/dbt/logger.py
  core/dbt/parser/manifest.py
  core/dbt/parser/read_files.py
  core/dbt/parser/search.py
  core/dbt/task/debug.py
  core/dbt/task/deps.py
  core/dbt/task/docs/generate.py
  core/dbt/task/init.py
  core/dbt/utils.py
  scripts/collect-artifact-schema.py
  tests/functional/docs/test_static.py
  tests/unit/common/__init__.py
  tests/unit/common/test_system_client.py
  tests/unit/test_connection_retries.py
  tests/unit/test_core_dbt_utils.py
  tests/unit/test_deps.py
  tests/unit/test_graph.py
Labels: cla:yes

#9291 Update materialized views to use RelationConfigs and remove refs to dbt.utils
  .changes/unreleased/Under the Hood-20231214-122134.yaml
  plugins/postgres/dbt/adapters/postgres/impl.py
  plugins/postgres/dbt/adapters/postgres/relation.py
  plugins/postgres/dbt/adapters/postgres/relation_configs/materialized_view.py
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/alter.sql
Labels: cla:yes

#9300 Add config field to RelationConfig
  core/dbt/adapters/contracts/relation.py
Labels: cla:yes, Skip Changelog

#9305 merge main into feature/decouple-adapters-from-core
  .changes/unreleased/Breaking Changes-20231129-091921.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/task/deps.py
  tests/adapter/dbt/tests/adapter/basic/test_adapter_methods.py
  tests/adapter/dbt/tests/adapter/basic/test_base.py
  tests/adapter/dbt/tests/adapter/basic/test_docs_generate.py
  tests/adapter/dbt/tests/adapter/basic/test_generic_tests.py
  tests/adapter/dbt/tests/adapter/basic/test_incremental.py
  tests/adapter/dbt/tests/adapter/basic/test_singular_tests.py
  tests/adapter/dbt/tests/adapter/basic/test_singular_tests_ephemeral.py
  tests/adapter/dbt/tests/adapter/basic/test_snapshot_check_cols.py
  tests/adapter/dbt/tests/adapter/basic/test_snapshot_timestamp.py
  tests/adapter/dbt/tests/adapter/incremental/test_incremental_unique_id.py
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
  tests/functional/dependencies/test_dependency_options.py
Labels: cla:yes

#9273 In build command run unit tests before models
  .changes/unreleased/Breaking Changes-20231129-091921.yaml
  .changes/unreleased/Features-20231212-150556.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/compilation.py
  core/dbt/graph/graph.py
  core/dbt/graph/selector.py
  core/dbt/task/build.py
  core/dbt/task/deps.py
  core/dbt/task/runnable.py
  docker-compose.yml
  schemas/dbt/manifest/v12.json
  tests/adapter/dbt/tests/adapter/basic/test_adapter_methods.py
  tests/adapter/dbt/tests/adapter/basic/test_base.py
  tests/adapter/dbt/tests/adapter/basic/test_docs_generate.py
  tests/adapter/dbt/tests/adapter/basic/test_generic_tests.py
  tests/adapter/dbt/tests/adapter/basic/test_incremental.py
  tests/adapter/dbt/tests/adapter/basic/test_singular_tests.py
  tests/adapter/dbt/tests/adapter/basic/test_singular_tests_ephemeral.py
  tests/adapter/dbt/tests/adapter/basic/test_snapshot_check_cols.py
  tests/adapter/dbt/tests/adapter/basic/test_snapshot_timestamp.py
  tests/adapter/dbt/tests/adapter/incremental/test_incremental_unique_id.py
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/test_previous_version_state.py
  tests/functional/dependencies/test_dependency_options.py
  tests/functional/unit_testing/test_unit_testing.py
  tests/functional/unit_testing/test_ut_sources.py
Labels: cla:yes

#9311 Resolve unparsed.py conflict
  core/dbt/contracts/graph/unparsed.py
Labels: cla:yes
