Repository dbt-labs/dbt-core, pull requests merged in 2023-03, with the labels that each got.

#7089 Remove cli doc generation workflow
  .changes/unreleased/Under the Hood-20230228-130435.yaml
  .github/workflows/generate-cli-api-docs.yml
Labels: cla:yes

#7095 Remove python 3.9 from main workflow in 1.0
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#6986 get_column_schema_from_query macro
  .changes/unreleased/Features-20230222-130632.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/sql/connections.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/include/global_project/macros/adapters/columns.sql
  core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql
  plugins/postgres/dbt/adapters/postgres/connections.py
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
Labels: cla:yes

#7134 Make mypy version consistently 0.981
  .github/workflows/main.yml
  .pre-commit-config.yaml
Labels: cla:yes, Skip Changelog

#6873 CT 1808 diff based partial parsing
  .changes/unreleased/Features-20230206-084749.yaml
  core/dbt/clients/system.py
  core/dbt/contracts/files.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/read_files.py
  core/dbt/tests/util.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/partial_parsing/test_file_diff.py
  tests/unit/test_events.py
Labels: cla:yes

#7120 model contracts on models materialized as views
  .changes/unreleased/Features-20230222-130632.yaml
  core/dbt/include/global_project/macros/materializations/models/view/create_view_as.sql
  core/dbt/parser/base.py
  core/dbt/parser/schemas.py
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
  tests/functional/configs/test_constraint_configs.py
Labels: cla:yes

#7086 Create method for env var deprecation
  .changes/unreleased/Under the Hood-20230224-132811.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/deprecations.py
  core/dbt/docs/build/doctrees/environment.pickle
  core/dbt/docs/build/doctrees/index.doctree
  core/dbt/docs/build/html/.buildinfo
  core/dbt/docs/build/html/_static/_sphinx_javascript_frameworks_compat.js
  core/dbt/docs/build/html/_static/alabaster.css
  core/dbt/docs/build/html/_static/basic.css
  core/dbt/docs/build/html/_static/doctools.js
  core/dbt/docs/build/html/_static/jquery-3.6.0.js
  core/dbt/docs/build/html/_static/jquery.js
  core/dbt/docs/build/html/_static/language_data.js
  core/dbt/docs/build/html/_static/pygments.css
  core/dbt/docs/build/html/_static/searchtools.js
  core/dbt/docs/build/html/_static/underscore-1.13.1.js
  core/dbt/docs/build/html/_static/underscore.js
  core/dbt/docs/build/html/genindex.html
  core/dbt/docs/build/html/index.html
  core/dbt/docs/build/html/search.html
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  tests/unit/test_cli.py
  tests/unit/test_cli_flags.py
  tests/unit/test_events.py
Labels: cla:yes

#7142 Add most recent dbt-docs changes
  .changes/unreleased/Docs-20230307-174951.yaml
  core/dbt/include/index.html
Labels: cla:yes

#7115 update to allow adapters to change model name resolution in py models
  .changes/unreleased/Fixes-20230303-112519.yaml
  core/dbt/include/global_project/macros/python_model/python.sql
Labels: cla:yes

#6659 add env DBT_PROJECT_DIR support #6078
  .changes/unreleased/Features-20230119-141156.yaml
  core/dbt/cli/params.py
Labels: cla:yes, cli, Team:Execution, ready_for_review

#7152 backport 7115 to 1.4.latest
  .changes/unreleased/Fixes-20230303-112519.yaml
  core/dbt/include/global_project/macros/python_model/python.sql
Labels: cla:yes

#7159 use timezone with no DST in test
  tests/functional/timezones/test_timezones.py
Labels: cla:yes, Skip Changelog

#7148 Support contract config outside model yaml
  .changes/unreleased/Features-20230222-130632.yaml
  core/dbt/context/exceptions_jinja.py
  core/dbt/exceptions.py
  core/dbt/include/global_project/macros/adapters/columns.sql
  core/dbt/parser/base.py
  core/dbt/parser/schemas.py
  tests/functional/configs/test_constraint_configs.py
Labels: cla:yes

#7161 CT 2196, CT2121 constraints column order
  .changes/unreleased/Features-20230313-135917.yaml
  core/dbt/clients/jinja.py
  core/dbt/context/exceptions_jinja.py
  core/dbt/exceptions.py
  core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql
  core/dbt/include/global_project/macros/materializations/models/table/create_table_as.sql
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
  tests/functional/configs/test_contract_configs.py
Labels: cla:yes

#7185 Add deprecation warnings for `log-path`, `target-path` in dbt_project.yml
  .changes/unreleased/Breaking Changes-20230317-110033.yaml
  core/dbt/cli/flags.py
  core/dbt/config/project.py
  core/dbt/deprecations.py
  core/dbt/events/README.md
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/include/starter_project/dbt_project.yml
  core/dbt/tests/fixtures/project.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/init/test_init.py
  tests/functional/partial_parsing/test_pp_vars.py
  tests/unit/test_events.py
Labels: cla:yes

#7201 Stop ignoring test directory for precommit
  .pre-commit-config.yaml
  pyproject.toml
  test/unit/mock_adapter.py
  test/unit/test_adapter_factory.py
  test/unit/test_agate_helper.py
  test/unit/test_base_column.py
  test/unit/test_cache.py
  test/unit/test_config.py
  test/unit/test_context.py
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  test/unit/test_contracts_project.py
  test/unit/test_core_dbt_utils.py
  test/unit/test_deps.py
  test/unit/test_docs_blocks.py
  test/unit/test_docs_generate.py
  test/unit/test_exceptions.py
  test/unit/test_flags.py
  test/unit/test_graph.py
  test/unit/test_graph_selection.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_graph_selector_parsing.py
  test/unit/test_graph_selector_spec.py
  test/unit/test_jinja.py
  test/unit/test_lib.py
  test/unit/test_linker.py
  test/unit/test_macro_calls.py
  test/unit/test_macro_resolver.py
  test/unit/test_manifest.py
  test/unit/test_manifest_selectors.py
  test/unit/test_model_config.py
  test/unit/test_parse_manifest.py
  test/unit/test_parser.py
  test/unit/test_partial_parsing.py
  test/unit/test_postgres_adapter.py
  test/unit/test_query_headers.py
  test/unit/test_registry_get_request_exception.py
  test/unit/test_selector_errors.py
  test/unit/test_semver.py
  test/unit/test_sql_result.py
  test/unit/test_system_client.py
  test/unit/test_tracking.py
  test/unit/test_utils.py
  test/unit/test_yaml_renderer.py
  test/unit/utils.py
Labels: cla:yes, Skip Changelog

#7180 CT-2049: Add CommandCompleted event
  .changes/unreleased/Under the Hood-20230316-123305.yaml
  core/dbt/cli/requires.py
  core/dbt/events/proto_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  tests/unit/test_events.py
Labels: cla:yes

#7130 ct-2198: Unify constraints and check_constraints fields
  .changes/unreleased/Features-20230315-135108.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql
  core/dbt/parser/manifest.py
  core/dbt/parser/models.py
  core/dbt/parser/schemas.py
  plugins/postgres/dbt/include/postgres/macros/utils/columns_spec_ddl.sql
  schemas/dbt/manifest/v9.json
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_contracts_graph_unparsed.py
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
  tests/functional/artifacts/data/state/v9/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/docs/test_good_docs_blocks.py
  tests/unit/test_constraint_parsing.py
Labels: cla:yes

#7190 CT 1998 use google protobuf to enable more flexible dictionaries
  .changes/unreleased/Features-20230318-164326.yaml
  .gitattributes
  .pre-commit-config.yaml
  Makefile
  core/dbt/adapters/base/impl.py
  core/dbt/adapters/cache.py
  core/dbt/adapters/reference_keys.py
  core/dbt/adapters/sql/impl.py
  core/dbt/clients/system.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/results.py
  core/dbt/events/README.md
  core/dbt/events/adapter_endpoint.py
  core/dbt/events/base_types.py
  core/dbt/events/contextvars.py
  core/dbt/events/eventmgr.py
  core/dbt/events/functions.py
  core/dbt/events/helpers.py
  core/dbt/events/proto_types.py
  core/dbt/events/test_types.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/parser/models.py
  core/dbt/task/deps.py
  core/dbt/task/runnable.py
  core/dbt/tests/util.py
  core/setup.py
  dev-requirements.txt
  docs/arch/adr-005-betterproto.md
  test/unit/test_cache.py
  test/unit/test_context.py
  tests/functional/compile/test_compile.py
  tests/functional/logging/test_logging.py
  tests/functional/logging/test_meta_logging.py
  tests/unit/test_events.py
  tests/unit/test_proto_events.py
Labels: cla:yes

#7205 Convert simple copy.
  tests/adapter/dbt/tests/adapter/simple_copy/fixtures.py
  tests/adapter/dbt/tests/adapter/simple_copy/test_copy_uppercase.py
  tests/adapter/dbt/tests/adapter/simple_copy/test_simple_copy.py
  tests/functional/basic/test_copy_uppercase.py
  tests/functional/basic/test_simple_copy.py
Labels: cla:yes, Skip Changelog

#7214 CT-1928: dbtRunner to EventManager callback support
  .changes/unreleased/Features-20230322-124615.yaml
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/events/eventmgr.py
  core/dbt/events/functions.py
  tests/unit/test_dbt_runner.py
Labels: cla:yes

#7217 Use function for datetime in CommandCompleted and throw error when testing
  core/dbt/cli/requires.py
  core/dbt/events/base_types.py
  tests/functional/logging/test_logging.py
  tests/unit/test_events.py
Labels: cla:yes, Skip Changelog

#7212 Add postflight to handle click exc and exit codes
  .changes/unreleased/Fixes-20230321-141804.yaml
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  tests/functional/cli/test_cli_exit_codes.py
  tests/functional/cli/test_error_handling.py
Labels: cla:yes

#7009 CT-2129 Bug: added timeout for dbt version
  .changes/unreleased/Fixes-20230219-114435.yaml
  core/dbt/version.py
Labels: cla:yes, Team:Execution, ready_for_review

#7167 Enforce model contracts for incremental materializations
  .changes/1.5.0/Features-20230222-130632.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/parser/schemas.py
  core/dbt/tests/util.py
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
  tests/functional/configs/test_contract_configs.py
Labels: cla:yes, Skip Changelog

#7169 Allow `--select` and `--exclude` multiple times
  .changes/unreleased/Breaking Changes-20230314-161505.yaml
  core/dbt/cli/options.py
  core/dbt/cli/params.py
  tests/functional/graph_selection/test_graph_selection.py
  tests/functional/list/test_list.py
Labels: cla:yes, Team:Execution, ready_for_review

#7222 convert contract to dict
  .changes/1.5.0/Under the Hood-20230217-105223.yaml
  .changes/unreleased/Under the Hood-20230217-105223.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/include/global_project/macros/materializations/models/table/create_table_as.sql
  core/dbt/include/global_project/macros/materializations/models/view/create_view_as.sql
  core/dbt/parser/base.py
  core/dbt/parser/schemas.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  schemas/dbt/manifest/v9.json
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  tests/adapter/dbt/tests/adapter/constraints/fixtures.py
  tests/adapter/dbt/tests/adapter/constraints/test_constraints.py
  tests/functional/artifacts/data/state/v9/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/list/test_list.py
Labels: cla:yes

#7216 Detect breaking changes to column names and data types in state:modified check
  .changes/unreleased/Features-20230323-133026.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/exceptions.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/base.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v9.json
  test/unit/test_contracts_graph_compiled.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/defer_state/fixtures.py
  tests/functional/defer_state/test_modified_state.py
Labels: cla:yes

#7231 Replace tracking events: `project_id`, `adapter_info`
  .changes/unreleased/Fixes-20230327-193850.yaml
  core/dbt/task/base.py
  core/dbt/tracking.py
  events/README.md
Labels: cla:yes

#7240 [Missed Commit] Replace tracking events: `project_id`, `adapter_info`
  core/dbt/cli/requires.py
  core/dbt/task/base.py
Labels: cla:yes, Skip Changelog

#7238 Remove unnecessary "version" keys in partial parsing pp_dict
  .changes/unreleased/Fixes-20230329-111451.yaml
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  test/unit/test_parser.py
  tests/functional/partial_parsing/fixtures.py
Labels: cla:yes
