Repository dbt-labs/dbt-core, pull requests merged in 2023-05, with the labels that each got.

#7276 Initial implementation of cross-project ref
  .changes/unreleased/Features-20230420-124756.yaml
  core/dbt/adapters/base/relation.py
  core/dbt/compilation.py
  core/dbt/constants.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/manifest_upgrade.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/publication.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  schemas/dbt/manifest/v10.json
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_graph_selector_methods.py
  test/unit/test_manifest.py
  tests/functional/artifacts/data/state/v10/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/artifacts/test_previous_version_state.py
  tests/functional/docs/test_generate.py
  tests/functional/experimental_parser/test_all_experimental_parser.py
  tests/functional/groups/test_access.py
  tests/functional/list/test_list.py
  tests/functional/multi_project/conftest.py
  tests/functional/multi_project/test_publication.py
  tests/unit/test_events.py
Labels: cla:yes

#5851 Adding perf testing GHA
  .github/workflows/model_performance.yml
Labels: cla:yes, Skip Changelog

#7524 Fix inverted `--print/--no-print` flag
  .changes/unreleased/Fixes-20230505-132545.yaml
  core/dbt/context/base.py
Labels: cla:yes, ready_for_review, backport 1.5.latest

#7535 Back compat for previous return type of `collect_freshness`
  .changes/unreleased/Fixes-20230506-173315.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/deprecations.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/task/freshness.py
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/test_events.py
Labels: cla:yes, backport 1.5.latest

#7554 Do not rewrite `manifest.json` during `docs serve` command
  .changes/unreleased/Fixes-20230508-142518.yaml
  core/dbt/cli/main.py
Labels: cla:yes, backport 1.5.latest

#7548 [Backport 1.5.latest] Back compat for previous return type of `collect_freshness`
  .changes/unreleased/Fixes-20230506-173315.yaml
  core/dbt/adapters/base/impl.py
  core/dbt/deprecations.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/task/freshness.py
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/test_events.py
Labels: cla:yes

#7374 Allow duplicate refable node names across packages
  .changes/unreleased/Features-20230429-155057.yaml
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  test/unit/test_manifest.py
  tests/functional/duplicates/test_duplicate_model.py
  tests/functional/multi_project/test_publication.py
Labels: cla:yes

#7566 CT 2552 pin protobuf to >=4.0.0
  .changes/unreleased/Fixes-20230509-123159.yaml
  core/setup.py
  dev-requirements.txt
Labels: cla:yes

#7574 CT-2556: pin urllib3 to 1.x
  .changes/unreleased/Fixes-20230509-153530.yaml
  core/setup.py
Labels: cla:yes

#7558 CT 2494 check for project level dependency cycles
  .changes/unreleased/Features-20230509-094147.yaml
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  tests/functional/multi_project/test_publication.py
Labels: cla:yes

#7577 CT 2510 Throw error for duplicate versioned and non versioned model names
  .changes/unreleased/Fixes-20230509-165007.yaml
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes

#7476 Detect breaking changes to constraints in state:modifed
  .changes/unreleased/Features-20230503-101100.yaml
  core/dbt/adapters/factory.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/exceptions.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  test/unit/test_contracts_graph_compiled.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_graph_selector_methods.py
  tests/functional/defer_state/fixtures.py
  tests/functional/defer_state/test_modified_state.py
Labels: cla:yes

#7546 Allow missing `profiles.yml` for `dbt deps` and `dbt init`
  .changes/unreleased/Fixes-20230508-072929.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  tests/functional/profiles/test_profile_dir.py
Labels: cla:yes, backport 1.5.latest

#7590 add publication artifact to schemas
  schemas/dbt/publication/v1.json
  scripts/collect-artifact-schema.py
Labels: cla:yes, Skip Changelog

#7334 ADAP-402: Add configuration change option - postgres
  core/dbt/include/global_project/macros/adapters/indexes.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/get_materialized_view_configuration_changes.sql
  core/dbt/include/global_project/macros/materializations/models/materialized_view/materialized_view.sql
  plugins/postgres/dbt/adapters/postgres/relation.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view.sql
  tests/adapter/dbt/tests/adapter/materialized_views/base.py
  tests/adapter/dbt/tests/adapter/materialized_views/test_basic.py
  tests/adapter/dbt/tests/adapter/materialized_views/test_on_configuration_change.py
  tests/functional/materializations/test_materialized_view.py
Labels: cla:yes, Skip Changelog

#7599 add --artifact flag to scripts/collect-artifact-schema
  scripts/collect-artifact-schema.py
  tests/functional/artifacts/test_artifacts.py
Labels: cla:yes, Skip Changelog

#7605 CT 2510 Throw error for duplicate versioned and non versioned model n…
  .changes/unreleased/Fixes-20230509-165007.yaml
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes

#7626 Feature/drop relation/ct 2581
  .changes/unreleased/Features-20230515-122304.yaml
  core/dbt/include/global_project/macros/adapters/drop_relation.sql
  core/dbt/include/global_project/macros/adapters/relation.sql
Labels: cla:yes

#7614 updates for github deprecations
  .github/workflows/backport.yml
  .github/workflows/bot-changelog.yml
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
  .github/workflows/release-docker.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#7628 bugfix: Deps hangs when using relative paths via `--project-dir`
  .changes/unreleased/Fixes-20230515-123654.yaml
  core/dbt/clients/system.py
  core/dbt/task/deps.py
  tests/functional/dependencies/test_local_dependency.py
Labels: cla:yes, backport 1.0.latest

#7638 [Backport] 1.5.latest gh deprecations
  .github/workflows/backport.yml
  .github/workflows/release-docker.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#7636 [Backport] 1.4.latest gh deprecations
  .github/_README.md
  .github/actions/latest-wrangler/main.py
  .github/workflows/main.yml
  .github/workflows/release-docker.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#7635 [Backport] 1.3.latest gh deprecations
  .github/_README.md
  .github/actions/latest-wrangler/main.py
  .github/workflows/main.yml
  .github/workflows/release-docker.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#7637 [Backport] 1.2.latest gh deprecations
  .github/_README.md
  .github/actions/latest-wrangler/main.py
  .github/workflows/main.yml
  .github/workflows/release-docker.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#7634 [Backport] 1.1.latest gh deprecations
  .github/_README.md
  .github/actions/latest-wrangler/main.py
  .github/workflows/backport.yml
  .github/workflows/main.yml
  .github/workflows/release-docker.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#7633 [Backport] 1.0.latest gh deprecations
  .github/_README.md
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#7336 ADAP-395: Implement native materialized view DDL
  core/dbt/include/global_project/macros/materializations/models/materialized_view/materialized_view.sql
  plugins/postgres/dbt/adapters/postgres/relation.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  plugins/postgres/dbt/include/postgres/macros/materializations/materialized_view.sql
  plugins/postgres/dbt/include/postgres/macros/relations.sql
  tests/adapter/dbt/tests/adapter/materialized_views/test_on_configuration_change.py
  tests/functional/materializations/test_materialized_view.py
Labels: cla:yes, Skip Changelog

#7642 Missed PR fedback
  tests/functional/dependencies/test_local_dependency.py
Labels: cla:yes, Skip Changelog, backport 1.5.latest

#7647 add target-path to more cli commands that use it.
  .changes/unreleased/Fixes-20230516-152644.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#7640 Move node patch method to schema parser patch_node_properties and refactor schema parsing
  .changes/unreleased/Under the Hood-20230516-094241.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/common.py
  core/dbt/parser/generic_test.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_generic_tests.py
  core/dbt/parser/schema_yaml_readers.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  test/unit/test_contracts_graph_parsed.py
  test/unit/test_parser.py
  tests/functional/defer_state/test_modified_state.py
Labels: cla:yes

#7630 Exclude some profile fields from Jinja rendering when they are not valid Jinja.
  .changes/unreleased/Fixes-20230515-142851.yaml
  core/dbt/config/renderer.py
  tests/functional/profiles/test_profiles_yml.py
Labels: cla:yes

#7645 Add "other" relation to reffable node classes
  .changes/unreleased/Under the Hood-20230515-152107.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  test/unit/test_manifest.py
Labels: cla:yes

#7651 update used gh actions ahead of node12 deprecation
  .github/_README.md
  .github/actions/latest-wrangler/README.md
  .github/actions/latest-wrangler/examples/example_workflow.yml
  .github/workflows/main.yml
  .github/workflows/release-branch-tests.yml
  .github/workflows/schema-check.yml
Labels: cla:yes, Skip Changelog

#7653 Profile Jinja Rendering, 1.5 Backport
  .changes/unreleased/Fixes-20230515-142851.yaml
  core/dbt/config/renderer.py
  tests/functional/profiles/test_profiles_yml.py
Labels: cla:yes

#7656 Accept PublicationArtifacts in dbtRunner.invoke
  .changes/unreleased/Features-20230517-185627.yaml
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/contracts/publication.py
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  core/dbt/tests/util.py
  tests/functional/multi_project/test_publication.py
Labels: cla:yes

#7669 Windows MemoryError on CI runs
  .changes/unreleased/Under the Hood-20230519-153059.yaml
  tox.ini
Labels: cla:yes

#7677 [Backport] Allow missing profiles.yml for dbt deps and dbt init
  .changes/unreleased/Fixes-20230508-072929.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  tests/functional/profiles/test_profile_dir.py
Labels: cla:yes

#7661 Remove `DelayedFileHandler`
  .changes/unreleased/Under the Hood-20230518-114251.yaml
  core/dbt/logger.py
Labels: cla:yes

#7562 Model Deprecation
  .changes/unreleased/Features-20230509-233329.yaml
  core/dbt/config/renderer.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/publication.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  core/dbt/utils.py
  pytest.ini
  schemas/dbt/manifest/v10.json
  test/unit/test_manifest.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/deprecations/model_deprecations.py
  tests/unit/test_events.py
  third-party-stubs/msgpack/__init__.pyi
  third-party-stubs/msgpack/_version.pyi
  third-party-stubs/msgpack/exceptions.pyi
  third-party-stubs/msgpack/ext.pyi
  third-party-stubs/msgpack/fallback.pyi
Labels: user docs, cla:yes

#7609 Honor `--skip-profile-setup` parameter when inside an existing project
  .changes/unreleased/Fixes-20230511-140441.yaml
  core/dbt/exceptions.py
  core/dbt/task/init.py
  tests/functional/init/test_init.py
Labels: cla:yes, ready_for_review

#7672 Include null checks in utils test base
  .changes/unreleased/Under the Hood-20230521-125720.yaml
  tests/adapter/dbt/tests/adapter/utils/base_utils.py
  tests/adapter/dbt/tests/adapter/utils/fixture_null_compare.py
  tests/adapter/dbt/tests/adapter/utils/test_null_compare.py
Labels: cla:yes, test postgres, ready_for_review

#7678 CT 2516 ensure that paths in Jinja context flags object are strings
  .changes/unreleased/Fixes-20230522-135007.yaml
  core/dbt/flags.py
Labels: cla:yes

#7681 Relaxed the pyyaml dependency to >=5.3.
  .changes/unreleased/Dependencies-20230522-212201.yaml
  core/setup.py
Labels: cla:yes

#7693 Updating CODEOWNERS to consolidate
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#7686 CT 2590 write pub artifact to log
  .changes/unreleased/Under the Hood-20230523-122137.yaml
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/parser/manifest.py
  core/dbt/tests/util.py
  tests/functional/multi_project/test_publication.py
  tests/unit/test_events.py
Labels: cla:yes

#7699 Add `%` to adapter suite test cases for `persist_docs`
  .changes/unreleased/Fixes-20230524-160648.yaml
  tests/adapter/dbt/tests/adapter/persist_docs/fixtures.py
Labels: cla:yes, ready_for_review

#7676 Update to reusable workflow for branch testing
  .github/workflows/jira-creation.yml
  .github/workflows/jira-transition.yml
  .github/workflows/release-branch-tests.yml
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#7706 Target path should be relative to project dir, rather than current working directory
  .changes/unreleased/Fixes-20230525-165053.yaml
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/compilation.py
  core/dbt/config/project.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/state.py
  core/dbt/parser/manifest.py
  core/dbt/task/compile.py
  core/dbt/task/freshness.py
  core/dbt/task/generate.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  core/dbt/task/serve.py
  test/unit/test_graph_selector_methods.py
  tests/functional/configs/test_configs.py
  tests/functional/defer_state/test_defer_state.py
  tests/functional/multi_project/test_publication.py
Labels: cla:yes

#7623 Dropped support for Python 3.7
  .changes/unreleased/Breaking Changes-20230515-053148.yaml
  .github/workflows/main.yml
  CONTRIBUTING.md
  Dockerfile.test
  core/setup.py
  plugins/postgres/setup.py
  tests/adapter/setup.py
  tox.ini
Labels: cla:yes

#7451 Template rendering optimization
  .changes/unreleased/Features-20230424-163611.yaml
  core/dbt/clients/jinja.py
Labels: cla:yes

#7710 fix StopIteration error when publication not found
  .changes/unreleased/Fixes-20230526-153738.yaml
  core/dbt/contracts/publication.py
  core/dbt/parser/manifest.py
  tests/functional/multi_project/test_publication.py
Labels: cla:yes
