Repository dbt-labs/dbt-core, pull requests merged in 2024-06, with the labels that each got.

#10260 update dbt_utils version to 1.2.0
  tests/functional/dependencies/test_dependency_options.py
Labels: cla:yes, Skip Changelog

#10243 Move to test concrete class over abstract class
  tests/unit/README.md
  tests/unit/task/test_clone.py
  tests/unit/task/test_run.py
  tests/unit/task/test_runnable.py
Labels: cla:yes

#10245 [Feature] add generic config for generic tests
  .changes/unreleased/Features-20240531-150816.yaml
  core/dbt/parser/generic_test_builders.py
  tests/functional/schema_tests/data_test_config.py
  tests/functional/schema_tests/fixtures.py
Labels: cla:yes

#10262 [Backport 1.7.latest] update dbt_utils version to 1.2.0
  tests/functional/dependencies/test_dependency_options.py
Labels: cla:yes, Skip Changelog

#10264 Fix issues with inline nodes and selectors
  .changes/unreleased/Fixes-20240605-111652.yaml
  core/dbt/cli/flags.py
  core/dbt/task/compile.py
  core/dbt/task/runnable.py
  tests/functional/dbt_runner/test_dbt_runner.py
  tests/functional/graph_selection/test_inline.py
Labels: cla:yes

#10244 Fire skipped events at debug level
  .changes/unreleased/Fixes-20240113-073615.yaml
  core/dbt/task/printer.py
  tests/functional/minimal_cli/test_minimal_cli.py
Labels: cla:yes, community

#10276 Update semantic interface requirement
  core/setup.py
Labels: cla:yes, Skip Changelog

#10282 Migrate selector tests to pytest
  tests/unit/graph/test_selector.py
  tests/unit/parser/test_manifest.py
  tests/unit/utils/config.py
  tests/unit/utils/manifest.py
Labels: cla:yes, Skip Changelog

#10253 Move CatalogKey, ColumnMetadata, ColumnMap, CatalogTable to dbt-common
  core/dbt/artifacts/schemas/catalog/__init__.py
  core/dbt/artifacts/schemas/catalog/v1/catalog.py
  core/setup.py
Labels: cla:yes, Skip Changelog, artifact_minor_upgrade

#10291 create a happy path project fixture
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  tests/functional/adapter/basic/test_adapter_methods.py
  tests/functional/fixtures/__init__.py
  tests/functional/fixtures/happy_path_fixture.py
  tests/functional/fixtures/happy_path_project/analyses/a.sql
  tests/functional/fixtures/happy_path_project/dbt_project.yml
  tests/functional/fixtures/happy_path_project/macros/macro_stuff.sql
  tests/functional/fixtures/happy_path_project/models/docs.md
  tests/functional/fixtures/happy_path_project/models/ephemeral.sql
  tests/functional/fixtures/happy_path_project/models/incremental.sql
  tests/functional/fixtures/happy_path_project/models/m.yml
  tests/functional/fixtures/happy_path_project/models/metricflow_time_spine.sql
  tests/functional/fixtures/happy_path_project/models/outer.sql
  tests/functional/fixtures/happy_path_project/models/schema.yml
  tests/functional/fixtures/happy_path_project/models/sm.yml
  tests/functional/fixtures/happy_path_project/models/sq.yml
  tests/functional/fixtures/happy_path_project/models/sub/inner.sql
  tests/functional/fixtures/happy_path_project/seeds/seed.csv
  tests/functional/fixtures/happy_path_project/snapshots/snapshot.sql
  tests/functional/fixtures/happy_path_project/tests/t.sql
  tests/functional/list/test_list.py
  tests/functional/test_selection/fixtures.py
  tests/functional/test_selection/test_selection_expansion.py
Labels: cla:yes, Skip Changelog

#10302 update on_skip to adjust for node that do not have schema
  .changes/unreleased/Fixes-20240612-124256.yaml
  core/dbt/task/base.py
  tests/unit/task/test_build.py
Labels: cla:yes

#10308 Fix TestHooksInSourceFreshnessDisabled flaky test
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes, Skip Changelog

#10312 Stop mis-identifying `unit_test` config paths in `dbt_project.yaml` as unused
  .changes/unreleased/Fixes-20240613-183117.yaml
  core/dbt/contracts/graph/manifest.py
  tests/unit/graph/test_selector_methods.py
  tests/unit/parser/test_manifest.py
  tests/unit/utils/manifest.py
Labels: cla:yes

#10258 Call adapter.pre_model_hook + adapter.post_model_hook within tests
  .changes/unreleased/Features-20240606-112334.yaml
  core/dbt/task/test.py
  tests/functional/data_tests/test_hooks.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_ut_adapter_hooks.py
Labels: cla:yes, Skip Changelog

#10315 add empty to context flags
  .changes/unreleased/Features-20240617-103948.yaml
  core/dbt/flags.py
  tests/unit/context/test_base.py
Labels: cla:yes, backport 1.8.latest

#10314 [Backport 1.8.latest] Stop mis-identifying unit_test config paths in dbt_project.yaml as unused
  .changes/unreleased/Fixes-20240613-183117.yaml
  core/dbt/contracts/graph/manifest.py
  tests/unit/graph/test_selector_methods.py
  tests/unit/parser/test_manifest.py
  tests/unit/utils/manifest.py
Labels: cla:yes

#10196 Add initial unit tests for `ModelRunner` class
  tests/unit/task/test_run.py
  tests/unit/utils/adapter.py
  tests/unit/utils/manifest.py
Labels: cla:yes, Skip Changelog

#10295 Implement state:modified for saved queries
  .changes/unreleased/Fixes-20240612-152139.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/graph/selector_methods.py
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_saved_query_parsing.py
  tests/unit/graph/test_selector_methods.py
Labels: cla:yes

#10333 [Tidy first] move non-circular import to top of manifest.py
  core/dbt/contracts/graph/manifest.py
Labels: cla:yes, Skip Changelog, tidy_first

#10336 Add `get_catalog_for_single_relation` to `MockAdapter`
  tests/unit/mock_adapter.py
Labels: cla:yes, Skip Changelog

#10332 Remove unnecessary IntermediateSnapshotNode and EmptySnapshotConfig
  .changes/unreleased/Under the Hood-20240618-140652.yaml
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/base.py
  core/dbt/parser/snapshots.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes, tidy_first

#10347 Fix Schema Check path for 1.6.latest
  .github/workflows/schema-check.yml
Labels: cla:yes, Skip Changelog

#10263 Support DIFF as a recording mode
  core/dbt/cli/requires.py
Labels: cla:yes, Skip Changelog

#10346 [Backport 1.6.latest] Add most recent dbt-docs changes
  .changes/unreleased/Docs-20240613-151048.yaml
  core/dbt/include/index.html
Labels: cla:yes

#10335 [Backport 1.7.latest] Add most recent dbt-docs changes
  .changes/unreleased/Docs-20240613-151048.yaml
  core/dbt/include/index.html
Labels: cla:yes

#10338 Add unit tests for `Graph` class
  tests/unit/graph/test_graph.py
Labels: cla:yes, Skip Changelog

#10348 Mark test_metric_type_params_satisfies_protocol test as skipped
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes, Skip Changelog

#10337 add a check to make sure unit tests are considered when changing code
  codecov.yml
Labels: cla:yes

#10358 pin versions so CI and local dev match
  .pre-commit-config.yaml
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10359 Fix setting `silence` of `warn_error_options` via `dbt_project.yaml` flags
  .changes/unreleased/Fixes-20240624-171729.yaml
  core/dbt/cli/flags.py
  tests/functional/configs/test_warn_error_options.py
Labels: cla:yes

#10363 Make time spine model name a constant
  core/dbt/constants.py
  core/dbt/contracts/graph/semantic_manifest.py
Labels: cla:yes, Skip Changelog, community

#10375 Limit data test deprecation warning to root_project
  .changes/unreleased/Fixes-20240627-154448.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  tests/functional/dependencies/test_local_dependency.py
Labels: cla:yes
