Repository dbt-labs/dbt-core, pull requests merged in 2024-04, with the labels that each got.

#9833 automate docker release
  .github/workflows/release-docker.yml
  .github/workflows/release.yml
Labels: cla:yes

#9809 Expect that the `args` variable is un-modified by `dbt.invoke(args)`
  .changes/unreleased/Fixes-20240323-122018.yaml
  core/dbt/cli/main.py
  tests/functional/dbt_runner/test_dbt_runner.py
  tests/unit/test_cli_flags.py
Labels: cla:yes

#9844 [BUG] Exclude password-like fields for considering reparse
  .changes/unreleased/Fixes-20240402-135556.yaml
  core/dbt/parser/manifest.py
  tests/functional/partial_parsing/test_partial_parsing.py
  tests/functional/partial_parsing/test_pp_vars.py
  tests/unit/test_parse_manifest.py
Labels: cla:yes

#9856 [Tidy first] Add "Flags" to args parameters in tasks
  core/dbt/cli/flags.py
  core/dbt/task/base.py
  core/dbt/task/build.py
  core/dbt/task/debug.py
  core/dbt/task/list.py
  core/dbt/task/retry.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
Labels: cla:yes, Skip Changelog, tidy_first

#9838 Removing unwanted dev dependency
  .changes/unreleased/Dependencies-20240331-103917.yaml
  dev-requirements.txt
Labels: cla:yes, community

#9810 Only create the `packages-install-path` / `dbt_packages` folder during `dbt deps`
  .changes/unreleased/Fixes-20240323-124558.yaml
  core/dbt/compilation.py
  tests/functional/list/test_list.py
Labels: cla:yes

#9877 Remove try/except logic for importing `Empty` from `queue` library
  tests/unit/test_graph.py
  tests/unit/test_linker.py
Labels: cla:yes, Skip Changelog, tidy_first

#9879 [BACKPORT 1.6] Exclude password-like fields for considering reparse
  .changes/unreleased/Fixes-20240402-135556.yaml
  core/dbt/parser/manifest.py
  tests/functional/partial_parsing/test_partial_parsing.py
  tests/functional/partial_parsing/test_pp_vars.py
  tests/unit/test_parse_manifest.py
Labels: cla:yes

#9857 [BACKPORT 1.7] Exclude password-like fields for considering reparse (#9844)
  .changes/unreleased/Fixes-20240402-135556.yaml
  core/dbt/parser/manifest.py
  tests/functional/partial_parsing/test_partial_parsing.py
  tests/functional/partial_parsing/test_pp_vars.py
  tests/unit/test_parse_manifest.py
Labels: cla:yes

#9373 fix(core): relax pathspec upper bound version limitation
  .changes/unreleased/Dependencies-20240117-100818.yaml
  core/setup.py
Labels: cla:yes, ready_for_review, community

#9347 Fix configuration of turning test warnings into failures
  .changes/unreleased/Fixes-20240108-232035.yaml
  core/dbt/task/test.py
  tests/functional/test_singular_tests.py
Labels: cla:yes, community

#9878 Delete empty files that have been floating around with no future plans
  core/dbt/contracts/graph/searcher.py
  tests/unit/test_compiler.py
Labels: cla:yes, Skip Changelog, tidy_first

#9894 Allow for customization of the environment in which test fixtures are…
  core/dbt/tests/fixtures/project.py
  tests/functional/partial_parsing/test_pp_vars.py
Labels: cla:yes, Skip Changelog

#9887 Fix changlogs, remove PR reference
  .changes/1.8.0/Dependencies-20231005-151848.yaml
  .changes/1.8.0/Dependencies-20231031-131954.yaml
  .changes/1.8.0/Dependencies-20231106-130051.yaml
  .changes/1.8.0/Dependencies-20231122-001840.yaml
  .changes/1.8.0/Dependencies-20231204-000945.yaml
  .changes/1.8.0/Dependencies-20231211-005651.yaml
  .changes/1.8.0/Dependencies-20240115-012030.yaml
  .changes/1.8.0/Dependencies-20240123-105843.yaml
  .changes/1.8.0/Dependencies-20240129-005734.yaml
  .changes/1.8.0/Dependencies-20240129-005743.yaml
  .changes/1.8.0/Dependencies-20240212-011324.yaml
  .changes/1.8.0/Dependencies-20240222-102947.yaml
  .changes/1.8.0/Dependencies-20240226-004412.yaml
  .changes/1.8.0/Dependencies-20240226-123502.yaml
  .changes/1.8.0/Dependencies-20240227-151115.yaml
  .changes/1.8.0/Security-20240222-152445.yaml
  .changes/unreleased/Dependencies-20240117-100818.yaml
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#9799 [1.7] Fix Workflow Deprecations
  .github/actions/latest-wrangler/examples/example_workflow.yml
  .github/workflows/main.yml
  .github/workflows/model_performance.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release-docker.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#9897 [Tidy first] Fix three unit tests without set_args, fix mock in test_graph.py
  tests/unit/test_docs_blocks.py
  tests/unit/test_graph.py
  tests/unit/test_linker.py
Labels: cla:yes, Skip Changelog, tidy_first

#9891 Disambiguate FreshnessConfigProblem error message
  .changes/unreleased/Fixes-20240412-095718.yaml
  core/dbt/parser/sources.py
Labels: cla:yes

#9886 Begin warning people about spaces in model names
  .changes/unreleased/Fixes-20240409-233347.yaml
  core/dbt/contracts/project.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  tests/functional/manifest_validations/test_check_for_spaces_in_model_names.py
  tests/unit/test_events.py
  tests/unit/test_graph.py
Labels: cla:yes

#9749 `source freshness` precomputes metadata-based freshness in batch, if possible
  .changes/unreleased/Features-20240404-170728.yaml
  core/dbt/task/freshness.py
  dev-requirements.txt
  tests/unit/test_freshness_task.py
Labels: cla:yes

#9927 Migrate from custom `_error_tag` to `dbt-common` defined `error_tag`
  .changes/unreleased/Under the Hood-20240412-134502.yaml
  core/dbt/events/types.py
  core/setup.py
Labels: cla:yes

#9921 [BACKPORT 1.3.latest] update to wrk for all versions (#9916)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#9917 [BACKPORT 1.5.latest] distrobution regex
  .github/workflows/main.yml
Labels: Skip Changelog

#9918 [BACKPORT 1.6.latest] update to wrk for all versions (#9916)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#9919 [BACKPORT 1.7.latest] update to wrk for all versions (#9916)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#9936 be less explicit in source regex
  .github/workflows/main.yml
Labels: cla:yes

#9680 Fix conflict with newer versions of Snowplow tracker
  .changes/unreleased/Fixes-20240206-152435.yaml
  core/dbt/tracking.py
Labels: cla:yes, ready_for_review, community

#9945 [Backport 1.6.latest] be less explicit in source regex
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#9944 [Backport 1.5.latest] be less explicit in source regex
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#9942 [Backport 1.3.latest] be less explicit in source regex
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#9939 [Backport 1.2.latest] be less explicit in source regex
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#9940 [Backport 1.1.latest] be less explicit in source regex
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#9938 [Backport 1.0.latest] be less explicit in source regex
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#9694 Remove core imports from dbt.artifacts component
  .changes/unreleased/Under the Hood-20240412-132000.yaml
  core/dbt/artifacts/exceptions/__init__.py
  core/dbt/artifacts/exceptions/schemas.py
  core/dbt/artifacts/resources/v1/config.py
  core/dbt/artifacts/schemas/base.py
  core/dbt/artifacts/schemas/results.py
  core/dbt/artifacts/schemas/run/v5/run.py
  core/dbt/artifacts/utils/validation.py
  core/dbt/contracts/state.py
  core/dbt/exceptions.py
  tests/functional/artifacts/test_previous_version_state.py
Labels: cla:yes, artifact_minor_upgrade

#9928 Simplify docker release process in the release pipeline
  docker/Dockerfile
  docker/README.md
Labels: cla:yes, Skip Changelog

#9912 [Backport 1.6] Fix Workflow Deprecations (#9799)
  .github/actions/latest-wrangler/examples/example_workflow.yml
  .github/workflows/main.yml
  .github/workflows/model_performance.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release-docker.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#9951 bump sqlparse to 0.5
  .changes/unreleased/Dependencies-20240415-202426.yaml
  core/setup.py
Labels: cla:yes

#9950 stop bumping version in DockerFile
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#9954 Fix nightly release & Docker drafts
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#9733 Scrub secret vars
  .changes/unreleased/Features-20240307-153622.yaml
  core/dbt/artifacts/schemas/run/v5/run.py
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  tests/functional/context_methods/test_cli_vars.py
  tests/unit/test_parse_manifest.py
Labels: cla:yes, ready_for_review, artifact_minor_upgrade, community

#9930 Reorganize fixtures and implement a happy path test for semantic_manifest
  .changes/unreleased/Under the Hood-20240416-150030.yaml
  core/dbt/artifacts/resources/v1/semantic_model.py
  tests/unit/conftest.py
  tests/unit/contracts/__init__.py
  tests/unit/contracts/graph/__init__.py
  tests/unit/contracts/graph/test_semantic_manifest.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/utils/__init__.py
  tests/unit/utils/manifest.py
Labels: cla:yes, artifact_minor_upgrade

#9873 Support using sql in unit testing fixtures
  .changes/unreleased/Features-20240408-094132.yaml
  core/dbt/artifacts/resources/v1/unit_test_definition.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/fixtures.py
  core/dbt/parser/read_files.py
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/test_sql_format.py
Labels: cla:yes, artifact_minor_upgrade

#9911 [Backport 1.5] Fix Workflow Deprecations (#9799)
  .github/actions/latest-wrangler/examples/example_workflow.yml
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release-docker.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#9910 [Backport 1.4] Fix Workflow Deprecations (#9799)
  .github/actions/latest-wrangler/examples/example_workflow.yml
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release-docker.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#9909 [Backport 1.3] Fix Workflow Deprecations (#9799)
  .github/actions/latest-wrangler/examples/example_workflow.yml
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release-docker.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#9908 [Backport 1.2] Fix Workflow Deprecations (#9799)
  .github/actions/latest-wrangler/examples/example_workflow.yml
  .github/workflows/main.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release-docker.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#9929 add test for unit test that depends on ephemeral model
  tests/functional/unit_testing/test_ut_ephemeral.py
Labels: cla:yes, Skip Changelog

#9861 Fix query comments test
  .changes/unreleased/Fixes-20240408-130646.yaml
  tests/functional/adapter/query_comment/fixtures.py
  tests/functional/adapter/query_comment/test_query_comment.py
Labels: cla:yes, Team:Adapters, ready_for_review, community

#9964 Fix changelog kind
  .changes/unreleased/Dependencies-20240415-202426.yaml
  .changes/unreleased/Security-20240417-141316.yaml
Labels: cla:yes

#9963 updated unit test paths
  tests/unit/task/test_freshness.py
  tests/unit/task/test_runnable.py
Labels: cla:yes, Skip Changelog

#9975 fix changelogs
  .changes/unreleased/Dependencies-20240227-142138.yaml
  .changes/unreleased/Dependencies-20240410-183321.yaml
Labels: cla:yes

#9966 [Robust Testing] Move tests to tests/unit/context
  core/dbt/cli/requires.py
  core/dbt/context/manifest.py
  core/dbt/context/query_header.py
  core/dbt/parser/manifest.py
  tests/unit/context/test_context.py
  tests/unit/context/test_providers.py
  tests/unit/context/test_query_header.py
Labels: cla:yes, Skip Changelog

#9978 clear DBT_DEBUG after test_env_vars_secrets
  tests/functional/context_methods/test_env_vars.py
Labels: cla:yes, Skip Changelog

#9968 [BACKPORT 1.6] bump sqlparse
  .changes/unreleased/Security-20240417-141316.yaml
  core/setup.py
Labels: cla:yes

#9965 [BACKPORT 1.7] bump sqlparse
  .changes/unreleased/Security-20240417-141316.yaml
  core/setup.py
Labels: cla:yes

#9794 Fix #9534: Add NodeRelation to SavedQuery Export
  .changes/unreleased/Fixes-20240410-181741.yaml
  core/dbt/artifacts/resources/v1/saved_query.py
  core/dbt/parser/base.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_configs.py
Labels: cla:yes, artifact_minor_upgrade

#9988 Reorganize some unittest
  tests/unit/cli/test_flags.py
  tests/unit/cli/test_main.py
  tests/unit/config/__init__.py
  tests/unit/config/test_profile.py
  tests/unit/config/test_project.py
  tests/unit/config/test_runtime.py
  tests/unit/task/test_base.py
  tests/unit/test_base_column.py
  tests/unit/test_cache.py
  tests/unit/test_config.py
Labels: Skip Changelog

#9960 Change from unittest to pytest for manifestLoader
  tests/unit/contracts/graph/test_unparsed.py
  tests/unit/parser/test_manifest.py
  tests/unit/test_parse_manifest.py
Labels: cla:yes, Skip Changelog

#9999 pin proto-types to match proto pin
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10003 [BACKPORT 1.5.lates] pin proto-types to match proto pin (#9999)
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10004 [BACKPORT 1.6.latest] pin proto-types to match proto pin (#9999)
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10005 [BACKPORT 1.7.lates]pin proto-types to match proto pin (#9999)
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#9994 [BACKPORT 1.5.latest] Fix changlogs, remove PR reference (#9887)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#9995 [BACKPORT 1.6.latest] Fix changlogs, remove PR reference (#9887)
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#10012 remove test_relation(moved to dbt-adapters)
  tests/unit/test_relation.py
Labels: cla:yes, Skip Changelog

#10015 Fix #9715: Simplify error message if test severity isn't 'warn' or 'error'
  .changes/unreleased/Fixes-20240423-120112.yaml
  core/dbt/artifacts/resources/v1/config.py
  tests/unit/test_parser.py
Labels: cla:yes, Impact: Exp, artifact_minor_upgrade

#9956 Add flags.deprecate_package_materialization_builtin_override
  .changes/unreleased/Features-20240422-173703.yaml
  core/dbt/cli/flags.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/project.py
  core/dbt/events/types.py
  tests/functional/materializations/test_custom_materialization.py
  tests/unit/test_manifest.py
Labels: cla:yes, backport 1.6.latest, backport 1.7.latest

#9986 Add more package validation
  .changes/unreleased/Fixes-20240422-152244.yaml
  core/dbt/contracts/project.py
  tests/functional/dependencies/test_simple_dependency.py
Labels: cla:yes

#9959 Materialized Views not updating cache
  .changes/unreleased/Fixes-20240423-172407.yaml
  plugins/postgres/dbt/adapters/postgres/relation.py
  plugins/postgres/dbt/include/postgres/macros/adapters.sql
  tests/functional/materializations/materialized_view_tests/test_posgres_materialized_view.py
  tests/unit/test_renamed_relations.py
Labels: cla:yes, Skip Changelog

#10006 Use consistent secret scrubbing
  .changes/unreleased/Fixes-20240422-145811.yaml
  core/dbt/config/renderer.py
  core/dbt/constants.py
  core/dbt/context/base.py
  core/dbt/context/secret.py
  tests/functional/dependencies/test_dependency_secrets.py
Labels: cla:yes, artifact_minor_upgrade

#10023 add script to override dev dependencies in tests
  dev-requirements.txt
  scripts/update_dev_packages.sh
Labels: cla:yes, Skip Changelog

#10019 Import SECRET_ENV_PREFIX from dbt-common
  .changes/unreleased/Under the Hood-20240423-143055.yaml
  core/dbt/artifacts/schemas/run/v5/run.py
  core/dbt/config/renderer.py
  core/dbt/constants.py
  core/dbt/context/base.py
  core/dbt/context/configured.py
  core/dbt/context/providers.py
  core/dbt/context/secret.py
  core/dbt/exceptions.py
  core/dbt/parser/manifest.py
  tests/functional/context_methods/test_env_vars.py
  tests/functional/context_methods/test_secret_env_vars.py
  tests/functional/partial_parsing/test_pp_vars.py
Labels: cla:yes, artifact_minor_upgrade

#10027 add --empty flag to dbt build
  .changes/unreleased/Features-20240424-180639.yaml
  core/dbt/cli/main.py
  tests/functional/adapter/empty/__init__.py
  tests/functional/test_empty.py
Labels: cla:yes

#9972 Reorganize a number of our unit tests
  tests/unit/config/test_selectors.py
  tests/unit/graph/test_nodes.py
  tests/unit/parser/test_schema_renderer.py
  tests/unit/parser/test_unit_tests.py
  tests/unit/test_semantic_models.py
  tests/unit/test_sql_result.py
  tests/unit/test_tracking.py
Labels: cla:yes, Skip Changelog

#10031 Pin `macos` test runners to `macos-12`
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#10040 [Backport 1.6.latest] pin macos test runners to macos-12 (#10031)
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#10037 [Backport 1.5.latest] pin macos test runners to macos-12 (#10031)
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#10038 [Backport 1.4.latest] pin macos test runners to macos-12 (#10031)
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#10041 [Backport 1.2.latest] pin macos test runners to macos-12 (#10031)
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#10042 [Backport 1.1.latest] pin macos test runners to macos-12 (#10031)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#10044 [Backport 1.7.latest] [Bug] Use a list instead of a set for index changes to perserve order (dbt-postgres#73)
  .changes/unreleased/Fixes-20240425-133401.yaml
  plugins/postgres/dbt/adapters/postgres/relation.py
  plugins/postgres/dbt/adapters/postgres/relation_configs/materialized_view.py
  tests/unit/test_postgres_adapter.py
Labels: cla:yes, backport 1.6.latest

#10047 [Backport 1.6.latest] [Bug] Use a list instead of a set for index changes to perserve order (dbt-postgres#73)
  .changes/unreleased/Fixes-20240425-133401.yaml
  plugins/postgres/dbt/adapters/postgres/relation.py
  plugins/postgres/dbt/adapters/postgres/relation_configs/materialized_view.py
  tests/unit/test_postgres_adapter.py
Labels: cla:yes

#10045 Paw/record final
  .changes/unreleased/Under the Hood-20240425-170138.yaml
  core/dbt/cli/requires.py
  tests/functional/record/record.py
Labels: cla:yes

#10052 [Backport 1.7.latest] convert SECRET_ENV_PREFIX from DBT_ENV_SECRET_ to DBT_ENV_SECRET
  .changes/unreleased/Under the Hood-20240426-090222.yaml
  core/dbt/constants.py
  core/dbt/context/secret.py
  tests/functional/context_methods/test_env_vars.py
  tests/functional/context_methods/test_secret_env_vars.py
  tests/functional/partial_parsing/test_pp_vars.py
Labels: cla:yes

#10043 [Backport 1.0.latest] pin macos test runners to macos-12 (#10031)
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#10055 [Backport 1.6.latest] convert SECRET_ENV_PREFIX from DBT_ENV_SECRET_ …
  .changes/unreleased/Under the Hood-20240426-090222.yaml
  core/dbt/constants.py
  core/dbt/context/secret.py
  tests/functional/context_methods/test_env_vars.py
  tests/functional/context_methods/test_secret_env_vars.py
  tests/functional/partial_parsing/test_pp_vars.py
Labels: cla:yes

#9998 [Backport] deprecate materialization overrides from imported packages
  .changes/unreleased/Features-20231218-195854.yaml
  .changes/unreleased/Features-20240422-173703.yaml
  .changes/unreleased/Under the Hood-20240418-172528.yaml
  core/dbt/cli/flags.py
  core/dbt/config/__init__.py
  core/dbt/config/profile.py
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/contracts/connection.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/flags.py
  core/dbt/include/starter_project/dbt_project.yml
  core/dbt/tests/fixtures/project.py
  core/dbt/tracking.py
  core/dbt/utils.py
  tests/functional/basic/test_mixed_case_db.py
  tests/functional/basic/test_project.py
  tests/functional/configs/test_disabled_configs.py
  tests/functional/dependencies/test_local_dependency.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/fail_fast/test_fail_fast_run.py
  tests/functional/init/test_init.py
  tests/functional/materializations/conftest.py
  tests/functional/materializations/test_custom_materialization.py
  tests/functional/metrics/test_metric_deferral.py
  tests/functional/run_operations/test_run_operations.py
  tests/unit/test_cli_flags.py
  tests/unit/test_config.py
  tests/unit/test_events.py
  tests/unit/test_flags.py
  tests/unit/test_graph.py
  tests/unit/test_graph_selection.py
  tests/unit/test_manifest.py
Labels: cla:yes

#10059 Hardcode dbt version for `project` fixture in repository unit tests
  tests/unit/config/test_project.py
  tests/unit/utils/project.py
Labels: cla:yes, Skip Changelog

#10060 Reorganize more of the repository's unit tests
  tests/unit/cli/test_option_types.py
  tests/unit/context/test_macro_resolver.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/plugins/test_manager.py
  tests/unit/task/test_retry.py
Labels: cla:yes

#10058 Add ability to `silence` warnings AND allow `error` and `warn` to be used for `include` and `exclude`
  .changes/unreleased/Features-20240426-233126.yaml
  .changes/unreleased/Features-20240426-233208.yaml
  core/dbt/cli/option_types.py
  core/dbt/config/project.py
  core/dbt/config/utils.py
  core/dbt/exceptions.py
  core/setup.py
  tests/functional/configs/test_warn_error_options.py
  tests/functional/manifest_validations/test_check_for_spaces_in_model_names.py
  tests/functional/utils.py
  tests/unit/config/test_utils.py
Labels: cla:yes
