Repository dbt-labs/dbt-core, pull requests merged in 2024-07, with the labels that each got.

#10379 [Backport 1.8.latest] Limit data test deprecation warning to root_project
  .changes/unreleased/Fixes-20240627-154448.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  tests/functional/dependencies/test_local_dependency.py
Labels: cla:yes

#10391 Tweak project-test-config deprecation test for misc deprecations
  tests/functional/dependencies/test_local_dependency.py
Labels: cla:yes, Skip Changelog

#10350 Add `CumulativeTypeParams` & sub-daily granularities to semantic manifest
  .changes/unreleased/Features-20240625-095107.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/v1/metric.py
  core/dbt/contracts/README.md
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  schemas/dbt/catalog/v1.json
  schemas/dbt/manifest/v12.json
  schemas/dbt/run-results/v6.json
  schemas/dbt/sources/v3.json
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metrics.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: user docs, cla:yes, semantic, Impact: CA, artifact_minor_upgrade

#10392 Skip failing DSI tests
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes, Skip Changelog

#10394 [TIDY-FIRST] Fix isort for dbt-semantic-interfaces
  .isort.cfg
  core/dbt/artifacts/resources/v1/metric.py
  core/dbt/artifacts/resources/v1/saved_query.py
  core/dbt/artifacts/resources/v1/semantic_layer_components.py
  core/dbt/artifacts/resources/v1/semantic_model.py
  core/dbt/contracts/graph/metrics.py
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/metrics/test_metrics.py
  tests/functional/saved_queries/test_configs.py
  tests/functional/saved_queries/test_saved_query_parsing.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/contracts/graph/test_nodes_parsed.py
  tests/unit/graph/test_nodes.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
  tests/unit/utils/manifest.py
Labels: cla:yes, Skip Changelog, artifact_minor_upgrade, tidy_first

#10400 add testing slack notification
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#10390 Add additional logging information to capture skipped ephemeral model info
  .changes/unreleased/Under the Hood-20240701-131750.yaml
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/task/base.py
  core/dbt/task/runnable.py
  tests/unit/test_events.py
Labels: cla:yes

#10380 [Tidy first] Add some mypy types to parser files
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/base.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_yaml_readers.py
  core/dbt/parser/schemas.py
  core/dbt/parser/unit_tests.py
  tests/unit/parser/test_parser.py
Labels: cla:yes, Skip Changelog, tidy_first

#10420 Update README.md
  .github/workflows/check-artifact-changes.yml
  core/dbt/artifacts/README.md
Labels: cla:yes, Skip Changelog

#10423 Global CLI flag should override env var flag
  .changes/unreleased/Fixes-20240709-172440.yaml
  core/dbt/cli/flags.py
  tests/unit/cli/test_flags.py
Labels: cla:yes

#10404 GitHub issue template for documentation internal to `dbt-core`
  .github/ISSUE_TEMPLATE/code-docs.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla:yes, community

#10366 Support for redshift 821
  .changes/unreleased/Fixes-20240625-171737.yaml
  core/dbt/parser/unit_tests.py
  tests/unit/parser/test_unit_tests.py
Labels: cla:yes

#10446 Revert "Support for redshift 821"
  .changes/unreleased/Fixes-20240625-171737.yaml
  core/dbt/parser/unit_tests.py
  tests/unit/parser/test_unit_tests.py
Labels: cla:yes, Skip Changelog

#10449 update test__model_contract_true
  tests/functional/configs/test_contract_configs.py
Labels: cla:yes, Skip Changelog

#10378 Add `Metric.time_granularity` to metric spec
  .changes/unreleased/Features-20240627-162953.yaml
  core/dbt/artifacts/resources/v1/metric.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  schemas/dbt/manifest/v12.json
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metrics.py
Labels: user docs, cla:yes, semantic, Impact: CA, artifact_minor_upgrade, community

#10456 [tidy first] generate protos w protoc version 5.26.1
  .changes/unreleased/Under the Hood-20240716-205703.yaml
  core/dbt/events/core_types_pb2.py
Labels: cla:yes

#10407 bump black in dev-requirements and pre-commit-config
  .changes/unreleased/Under the Hood-20240716-184859.yaml
  .flake8
  .pre-commit-config.yaml
  core/dbt/artifacts/schemas/run/v5/run.py
  core/dbt/cli/requires.py
  core/dbt/config/runtime.py
  core/dbt/context/context_config.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/logging.py
  core/dbt/parser/models.py
  core/dbt/task/base.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  dev-requirements.txt
  tests/functional/adapter/constraints/test_constraints.py
  tests/functional/list/test_list.py
  tests/unit/parser/test_manifest.py
  tests/unit/parser/test_partial.py
  tests/unit/test_compilation.py
  tests/unit/utils/__init__.py
  tests/unit/utils/adapter.py
  third-party-stubs/mashumaro/jsonschema/models.pyi
Labels: cla:yes, artifact_minor_upgrade

#10451 Fix multiple semantic models with generated metrics
  .changes/unreleased/Fixes-20240716-133703.yaml
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/semantic_models/fixtures.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
  tests/unit/contracts/files/test_schema_source_file.py
Labels: cla:yes

#10453 Warn error options invalid when warn or error set to none
  .changes/unreleased/Fixes-20240716-171427.yaml
  core/dbt/cli/option_types.py
  core/dbt/config/project.py
  core/dbt/config/utils.py
  tests/functional/configs/test_warn_error_options.py
  tests/unit/config/test_utils.py
Labels: cla:yes

#10445 test: cover additional listagg cases
  tests/functional/adapter/utils/fixture_listagg.py
Labels: cla:yes, community

#10462 [Backport 1.8.latest] Warn error options invalid when warn or error set to none
  .changes/unreleased/Fixes-20240716-171427.yaml
  core/dbt/cli/option_types.py
  core/dbt/config/project.py
  core/dbt/config/utils.py
  tests/functional/configs/test_warn_error_options.py
  tests/unit/config/test_utils.py
Labels: cla:yes

#10463 swap source dist install + check and wheel install + check in build packages step in main.yml
  .github/workflows/main.yml
Labels: cla:yes, backport 1.0.latest, Skip Changelog, backport 1.1.latest, backport 1.2.latest

#10467 Backport 10463 to 1.1.latest
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#10466 install & check source distributions before wheels
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#10439 Modify snapshot config to allow using schema/database/alias macros
  .changes/unreleased/Features-20240712-214546.yaml
  core/dbt/artifacts/resources/v1/snapshot.py
  core/dbt/parser/base.py
  core/dbt/parser/hooks.py
  core/dbt/parser/snapshots.py
  tests/functional/snapshots/data/invalidate_postgres.sql
  tests/functional/snapshots/data/seed_pg.sql
  tests/functional/snapshots/data/shared_macros.sql
  tests/functional/snapshots/data/update.sql
  tests/functional/snapshots/fixtures.py
  tests/functional/snapshots/test_basic_snapshot.py
  tests/functional/snapshots/test_changing_check_cols_snapshot.py
  tests/functional/snapshots/test_changing_strategy_snapshot.py
  tests/functional/snapshots/test_check_cols_snapshot.py
  tests/functional/snapshots/test_check_cols_updated_at_snapshot.py
  tests/functional/snapshots/test_comment_ending_snapshot.py
  tests/functional/snapshots/test_cross_schema_snapshot.py
  tests/functional/snapshots/test_hard_delete_snapshot.py
  tests/functional/snapshots/test_invalid_namespace_snapshot.py
  tests/functional/snapshots/test_long_text_snapshot.py
  tests/functional/snapshots/test_missing_strategy_snapshot.py
  tests/functional/snapshots/test_renamed_source_snapshot.py
  tests/functional/snapshots/test_select_exclude_snapshot.py
  tests/functional/snapshots/test_slow_query_snapshot.py
  tests/functional/snapshots/test_snapshot_config.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: user docs, cla:yes, artifact_minor_upgrade

#10468 Backport 10463 to 1.0.latest
  .github/actions/setup-postgres-macos/action.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#10448 Support for redshift 821
  .changes/unreleased/Fixes-20240625-171737.yaml
  core/dbt/parser/unit_tests.py
  tests/unit/parser/test_unit_tests.py
Labels: cla:yes

#10478 Update `pytest` examples for contributors
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#10479 [Tidy First] Update PR template punctuation
  .github/pull_request_template.md
Labels: cla:yes

#10482 add predicate to EventCatcher test util
  tests/utils.py
Labels: cla:yes, Skip Changelog

#10443 Fix typing for artifact schemas
  .changes/unreleased/Fixes-20240714-100254.yaml
  core/dbt/artifacts/schemas/base.py
Labels: cla:yes, artifact_minor_upgrade, community

#10414 parse + compile `constraint.to` and `constraint.to_columns` on foreign key constraints
  .changes/unreleased/Features-20240719-161841.yaml
  core/dbt/clients/jinja_static.py
  core/dbt/compilation.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/exceptions.py
  core/dbt/parser/schemas.py
  tests/functional/constraints/fixtures.py
  tests/functional/constraints/test_foreign_key_constraints.py
  tests/unit/clients/test_jinja_static.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/graph/test_nodes.py
Labels: cla:yes

#10486 Remove newlines from JSON schema files
  .pre-commit-config.yaml
  schemas/dbt/manifest/v10.json
  schemas/dbt/manifest/v11.json
  schemas/dbt/manifest/v12.json
  schemas/dbt/manifest/v5.json
  schemas/dbt/manifest/v6.json
  schemas/dbt/manifest/v7.json
  schemas/dbt/manifest/v8.json
  schemas/dbt/manifest/v9.json
Labels: cla:yes, Skip Changelog, community

#10489 Bump dbt common 1.6
  .changes/unreleased/Features-20240719-161841.yaml
  core/setup.py
Labels: cla:yes

#10483 Support time spine configs for sub-daily granularity
  .changes/unreleased/Features-20240722-202238.yaml
  Makefile
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/model.py
  core/dbt/constants.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/common.py
  core/dbt/parser/schemas.py
  core/setup.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/docs/test_good_docs_blocks.py
  tests/functional/fixtures/happy_path_project/models/metricflow_time_spine_second.sql
  tests/functional/fixtures/happy_path_project/models/schema.yml
  tests/functional/list/test_list.py
  tests/functional/time_spines/fixtures.py
  tests/functional/time_spines/test_time_spines.py
  tests/unit/contracts/graph/test_manifest.py
Labels: user docs, cla:yes, semantic, artifact_minor_upgrade, community

#10499 Bump dbt-adapters to 1.3.0
  core/setup.py
Labels: cla:yes, Skip Changelog

#10507 Bump DSI version to release new time spine validations
  core/setup.py
Labels: cla:yes, Skip Changelog, community
