Repository dbt-labs/dbt-core, pull requests merged in 2024-10, with the labels that each got.

#10802 When retrying microbatch models, propagate prior successful state
  .changes/unreleased/Fixes-20240930-153158.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/task/retry.py
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/contracts/graph/test_manifest.py
Labels: cla:yes

#10805 [tidy_first] Set default for STATE_MODIFIED_COMPARE_VARS flag, mark TestProjInfo as not a test class
  core/dbt/cli/flags.py
  core/dbt/tests/fixtures/project.py
Labels: cla:yes, Skip Changelog

#10806 `--inline-direct` is an internal CLI flag
  core/dbt/cli/params.py
Labels: cla:yes, Skip Changelog

#10807 Fix case-sensitivity in validation warning
  core/setup.py
Labels: cla:yes, Skip Changelog, semantic, community

#10820 Validate `--event-time-start` is before `--event-time-end`
  .changes/unreleased/Features-20241003-170529.yaml
  core/dbt/cli/flags.py
  tests/functional/cli/test_option_interaction_validations.py
Labels: cla:yes

#10826 Stop making microbatch batches with filters that will never have any rows
  .changes/unreleased/Fixes-20241004-133630.yaml
  core/dbt/materializations/incremental/microbatch.py
  tests/unit/materializations/incremental/test_microbatch.py
Labels: cla:yes

#10767 add builder config to test node config
  .changes/unreleased/Fixes-20240925-154514.yaml
  core/dbt/context/context_config.py
  core/dbt/parser/schema_generic_tests.py
  tests/functional/configs/test_configs.py
  tests/functional/configs/test_disabled_model.py
  tests/functional/schema_tests/data_test_config.py
  tests/functional/schema_tests/fixtures.py
Labels: cla:yes

#10780 Enable setting datetime value for dbt_valid_to when the record is current
  .changes/unreleased/Features-20240925-120855.yaml
  core/dbt/artifacts/resources/v1/snapshot.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/logging/test_logging.py
  tests/functional/snapshots/data/seed_dbt_valid_to.sql
  tests/functional/snapshots/test_snapshot_column_names.py
  tests/unit/test_events.py
Labels: cla:yes

#10835 Add better typing in jinja_static.py
  core/dbt/clients/jinja_static.py
Labels: cla:yes, Skip Changelog, tidy_first

#10845 [Tidy-First] Fix `node_status` for hooks
  core/dbt/task/run.py
  tests/functional/adapter/hooks/test_on_run_hooks.py
Labels: cla:yes, Skip Changelog

#10850 Fix #2578: Allow instances of generic data tests to be documented
  .changes/unreleased/Fixes-20241014-212135.yaml
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/schema_generic_tests.py
  tests/functional/generic_test_description/fixtures.py
  tests/functional/generic_test_description/test_generic_test_description.py
  tests/unit/parser/test_parser.py
Labels: cla:yes

#10854 Remove dbt_valid_to_current test (will go in adapter zone)
  tests/functional/snapshots/test_snapshot_column_names.py
Labels: cla:yes, Skip Changelog

#10852 Refactor code to properly handle reference deprecations
  .changes/unreleased/Fixes-20241015-121825.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/manifest.py
  tests/functional/deprecations/test_model_deprecations.py
Labels: cla:yes

#10830 Ensure consistent `current_time` across microbatch models in an invocation
  .changes/unreleased/Features-20241007-115853.yaml
  core/dbt/config/runtime.py
  core/dbt/materializations/incremental/microbatch.py
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes

#10861 Remove Python 3.8 from various places
  .changes/unreleased/Under the Hood-20241016-144056.yaml
  .github/workflows/main.yml
  .github/workflows/model_performance.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
  .pre-commit-config.yaml
  Dockerfile.test
  core/setup.py
Labels: cla:yes

#10532 Add `order_by` and `limit` fields to saved queries
  .changes/unreleased/Features-20240806-144859.yaml
  core/dbt/artifacts/resources/v1/saved_query.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  schemas/dbt/catalog/v1.json
  schemas/dbt/manifest/v12.json
  schemas/dbt/run-results/v6.json
  schemas/dbt/sources/v3.json
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_saved_query_parsing.py
Labels: cla:yes, artifact_minor_upgrade, community

#10869 Remove python 3.8 for dbt 1.8
  .changes/unreleased/Under the Hood-20241016-144056.yaml
  .github/workflows/main.yml
  .github/workflows/model_performance.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
  .pre-commit-config.yaml
  Dockerfile.test
  core/setup.py
  tests/functional/logging/test_logging.py
  tests/unit/test_events.py
Labels: cla:yes

#10870 Remove python 3.8 for dbt 1.7
  .changes/unreleased/Under the Hood-20241016-144056.yaml
  .github/workflows/main.yml
  .github/workflows/model_performance.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
  .pre-commit-config.yaml
  Dockerfile.test
  core/setup.py
Labels: cla:yes

#10871 Remove Python 3.8 for dbt 1.6
  .changes/unreleased/Under the Hood-20241016-144056.yaml
  .github/workflows/main.yml
  .github/workflows/model_performance.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
  .pre-commit-config.yaml
  Dockerfile.test
  core/setup.py
Labels: cla:yes

#10872 Remove python 3.8 for dbt 1.5
  .changes/unreleased/Under the Hood-20241016-144056.yaml
  .github/workflows/main.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
  .pre-commit-config.yaml
  Dockerfile.test
  core/setup.py
Labels: cla:yes

#10873 Remove Python 3.8 for dbt 1.4
  .changes/unreleased/Under the Hood-20241016-144056.yaml
  .github/workflows/main.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
  .pre-commit-config.yaml
  Dockerfile.test
  core/setup.py
Labels: cla:yes

#10882 [Tidy-First]: Fix `timings` object for hooks and macros, and make types of timings explicit
  core/dbt/artifacts/schemas/results.py
  core/dbt/task/run.py
  core/dbt/task/run_operation.py
  schemas/dbt/run-results/v6.json
  schemas/dbt/sources/v3.json
  tests/functional/adapter/hooks/test_on_run_hooks.py
  tests/functional/microbatch/test_microbatch.py
  tests/functional/run_operations/test_run_operations.py
  tests/unit/test_events.py
Labels: cla:yes, Skip Changelog, artifact_minor_upgrade

#10885 exclude hook results from results in on-run-end context
  .changes/unreleased/Fixes-20241018-135810.yaml
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  tests/functional/adapter/hooks/test_on_run_hooks.py
Labels: cla:yes, backport 1.9.latest

#10884 Update microbatch tests to handle update wherein incremental strategies are always validated
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes, Skip Changelog

#10894 pin internal dependencies with upper bounds
  .changes/unreleased/Dependencies-20241021-131923.yaml
  core/setup.py
  dev-requirements.txt
Labels: cla:yes

#10897 Loosen Type in TimingInfo
  core/dbt/artifacts/schemas/results.py
  schemas/dbt/run-results/v6.json
  schemas/dbt/sources/v3.json
Labels: cla:yes, Skip Changelog, artifact_minor_upgrade

#10795 Support multiple unique keys in snapshots
  .changes/unreleased/Features-20241001-134051.yaml
  core/dbt/artifacts/resources/v1/snapshot.py
  core/setup.py
  schemas/dbt/manifest/v12.json
  tests/functional/adapter/simple_snapshot/fixtures.py
  tests/functional/adapter/simple_snapshot/test_various_configs.py
Labels: cla:yes

#10907 Partial parse yaml snapshots
  .changes/unreleased/Fixes-20241022-222927.yaml
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  tests/functional/snapshots/fixtures.py
  tests/functional/snapshots/test_basic_snapshot.py
Labels: cla:yes

#10915 Fix regression when an exposure references a deprecated model
  .changes/unreleased/Fixes-20241024-104938.yaml
  core/dbt/parser/manifest.py
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_deprecations.py
Labels: cla:yes

#10876 Change microbatch `lookback` default from `0` to `1`
  .changes/unreleased/Fixes-20241017-134857.yaml
  core/dbt/artifacts/resources/v1/config.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/unit/context/test_providers.py
  tests/unit/contracts/graph/test_nodes.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes, artifact_minor_upgrade

#10905 Fix: Source quoting ignores global configuration
  .changes/unreleased/Fixes-20241023-152054.yaml
  core/dbt/context/providers.py
  tests/functional/relation_quoting/test_relation_quoting.py
Labels: cla:yes, backport 1.8.latest

#10859 Add adapter telemetry to snowplow event.
  core/dbt/task/run.py
  core/dbt/tracking.py
  dev-requirements.txt
  tests/unit/task/test_run.py
Labels: cla:yes, Skip Changelog

#10917 Microbatch: store `model` context var as dict, not ModelNode
  .changes/unreleased/Fixes-20241028-132751.yaml
  core/dbt/materializations/incremental/microbatch.py
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/materializations/incremental/test_microbatch.py
Labels: cla:yes

#10930 restore dev-requirements for dbt-adapters@main
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10929 raise MicrobatchModelNoEventTimeInputs warning when no microbatch input has event_time config
  .changes/unreleased/Features-20241028-173419.yaml
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/test_events.py
Labels: cla:yes

#10878 Make `--event-time-start` and `--event-time-end` mutually required
  .changes/unreleased/Fixes-20241017-145357.yaml
  core/dbt/cli/flags.py
  tests/functional/cli/test_option_interaction_validations.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes

#10883 Update microbatch `end_time` to the `batch_size` ceiling
  .changes/unreleased/Fixes-20241029-161615.yaml
  core/dbt/materializations/incremental/microbatch.py
  tests/unit/materializations/incremental/test_microbatch.py
Labels: cla:yes

#10947 Bump dbt adapters minior minimum to 1.8.0
  .changes/unreleased/Dependencies-20241030-134526.yaml
  core/setup.py
Labels: cla:yes

#10941 Ensure run results artifact get written during "after run hooks"
  .changes/unreleased/Fixes-20241029-182034.yaml
  core/dbt/task/run.py
  tests/unit/task/test_run.py
Labels: cla:yes

#10940 Emit `ArtifactWritten` event when artifacts are written
  .changes/unreleased/Features-20241029-181728.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/sql.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  core/dbt/task/docs/generate.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  tests/functional/artifacts/test_artifacts.py
  tests/unit/test_events.py
Labels: cla:yes

#10857 Behavior change for mf timespine without yaml configuration
  .changes/unreleased/Under the Hood-20241031-093251.yaml
  .gitignore
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/events/README.md
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/setup.py
  tests/unit/contracts/graph/test_semantic_manifest.py
  tests/unit/test_events.py
Labels: cla:yes, community

#10879 Ensure `KeyboardInterrupt` halts microbatch model execution
  .changes/unreleased/Fixes-20241017-153022.yaml
  core/dbt/task/run.py
  tests/unit/task/test_run.py
Labels: cla:yes
