Repository dbt-labs/dbt-core, pull requests merged in 2024-05, with the labels that each got.

#10063 Consistent behavior change flag names + deprecation warnings
  .changes/unreleased/Breaking Changes-20240430-165247.yaml
  .changes/unreleased/Under the Hood-20240429-142342.yaml
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  core/dbt/task/freshness.py
  docs/eli64/behavior-change-flags.md
  tests/functional/manifest_validations/test_check_for_spaces_in_model_names.py
  tests/functional/materializations/test_custom_materialization.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/test_events.py
Labels: cla:yes

#10069 Fix #9672: Artifact Schema Check
  .github/workflows/schema-check.yml
Labels: cla:yes, Skip Changelog

#10008 deprecate materialization overrides from imported packages (#9971)
  .changes/unreleased/Features-20231218-195854.yaml
  .changes/unreleased/Features-20240422-173703.yaml
  .changes/unreleased/Under the Hood-20240418-172528.yaml
  core/dbt/cli/flags.py
  core/dbt/config/__init__.py
  core/dbt/config/profile.py
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/constants.py
  core/dbt/contracts/connection.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/events/types.proto
  core/dbt/events/types.py
  core/dbt/events/types_pb2.py
  core/dbt/flags.py
  core/dbt/include/starter_project/dbt_project.yml
  core/dbt/tests/fixtures/project.py
  core/dbt/tracking.py
  core/dbt/utils.py
  tests/functional/basic/test_mixed_case_db.py
  tests/functional/basic/test_project.py
  tests/functional/configs/test_disabled_configs.py
  tests/functional/dependencies/test_local_dependency.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/fail_fast/test_fail_fast_run.py
  tests/functional/init/test_init.py
  tests/functional/materializations/conftest.py
  tests/functional/materializations/test_custom_materialization.py
  tests/functional/metrics/test_metric_deferral.py
  tests/functional/run_operations/test_run_operations.py
  tests/unit/test_cli_flags.py
  tests/unit/test_config.py
  tests/unit/test_events.py
  tests/unit/test_flags.py
  tests/unit/test_graph.py
  tests/unit/test_graph_selection.py
  tests/unit/test_manifest.py
Labels: cla:yes

#9270 Add current package selection syntax
  .changes/unreleased/Features-20231212-163409.yaml
  core/dbt/graph/selector_methods.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/utils/manifest.py
Labels: user docs, cla:yes, ready_for_review, community

#9199 Move deferral resolution from `merge_from_artifact` to `RuntimeRefResolver`
  .changes/unreleased/Under the Hood-20240201-003033.yaml
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/cli/requires.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  core/dbt/parser/unit_tests.py
  core/dbt/task/clone.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  tests/functional/adapter/dbt_clone/test_dbt_clone.py
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/defer_state/test_defer_state.py
  tests/functional/sources/test_source_fresher_state.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_state.py
  tests/unit/context/test_providers.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/fixtures.py
  tests/unit/test_contracts_graph_compiled.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_events.py
Labels: cla:yes, artifact_minor_upgrade

#10065 Recognize when loaded_at_field is explicitly set to null
  .changes/unreleased/Fixes-20240429-114610.yaml
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  tests/functional/sources/test_source_loaded_at_field.py
Labels: cla:yes

#10081 update readme install methods
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#10046 move partial parsing tests and add more examples
  tests/unit/parser/test_partial.py
  tests/unit/test_partial_parsing.py
  tests/unit/utils/manifest.py
Labels: cla:yes, Skip Changelog

#10066 test minor artifact changes for backward + forward compatability
  core/dbt/artifacts/README.md
  tests/unit/artifacts/test_base_resource.py
Labels: cla:yes, Skip Changelog

#10095 [Tidy First] Re-lint imports section of `test_base_resource.py`
  tests/unit/artifacts/test_base_resource.py
Labels: cla:yes, Skip Changelog, tidy_first

#10077 Update docs links + slightly tweak language for behavior change deprecations
  core/dbt/artifacts/README.md
  core/dbt/events/types.py
  docs/eli64/behavior-change-flags.md
Labels: cla:yes, Skip Changelog, artifact_minor_upgrade

#10084 Better error message for Private package definition
  .changes/unreleased/Under the Hood-20240502-154430.yaml
  core/dbt/contracts/project.py
  core/dbt/deps/resolver.py
  tests/functional/configs/test_custom_node_colors_configs.py
  tests/unit/test_deps.py
Labels: cla:yes

#10104 [Backport 1.8.latest] Enable serialization context (#10094)
  .changes/unreleased/Under the Hood-20240506-145511.yaml
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/model.py
  core/dbt/artifacts/resources/v1/seed.py
  core/dbt/artifacts/resources/v1/snapshot.py
  core/dbt/artifacts/schemas/base.py
  core/dbt/artifacts/schemas/catalog/v1/catalog.py
  core/dbt/artifacts/schemas/manifest/v12/manifest.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/manifest.py
  third-party-stubs/mashumaro/jsonschema/builder.pyi
  third-party-stubs/mashumaro/jsonschema/models.pyi
  third-party-stubs/mashumaro/mixins/dict.pyi
Labels: cla:yes, artifact_minor_upgrade

#10103 Fix #10098 by undoing conditional `agate` import in one place
  core/dbt/artifacts/schemas/run/v5/run.py
  tests/functional/artifacts/test_run_results.py
Labels: cla:yes, backport 1.8.latest

#10106 Backport #10103 to 1.8.latest
  .changes/unreleased/Fixes-20240508-132133.yaml
  core/dbt/artifacts/schemas/run/v5/run.py
  tests/functional/artifacts/test_run_results.py
Labels: cla:yes, artifact_minor_upgrade

#10102 Unit test selection method
  .changes/unreleased/Features-20240507-162717.yaml
  core/dbt/graph/selector_methods.py
  tests/unit/graph/test_selector_methods.py
Labels: cla:yes

#10108 Check if ref'd resource is selected before favoring state
  .changes/unreleased/Fixes-20240508-151127.yaml
  core/dbt/context/providers.py
  tests/functional/defer_state/test_defer_state.py
Labels: cla:yes, backport 1.8.latest

#10109 [1.8 backport] Unit test selection method (#10102)
  .changes/unreleased/Features-20240507-162717.yaml
  core/dbt/graph/selector_methods.py
  tests/unit/graph/test_selector_methods.py
Labels: cla:yes

#10117 empty unit test csv fixture values default to null
  .changes/unreleased/Fixes-20240509-091411.yaml
  core/dbt/events/types.py
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_csv_fixtures.py
Labels: cla:yes

#10118 [Backport 1.8] empty unit test csv fixture values default to null (#10117)
  .changes/unreleased/Fixes-20240509-091411.yaml
  core/dbt/events/types.py
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_csv_fixtures.py
Labels: cla:yes

#7756 fix: #7586, Remove unused check_new method
  .changes/unreleased/Fixes-20230601-204157.yaml
  core/dbt/graph/selector_methods.py
Labels: cla:yes, ready_for_review, community

#10123 Update minimum req for dbt-common + dbt-adapters
  core/setup.py
Labels: cla:yes, Skip Changelog, backport 1.8.latest

#10096 Add `primary_key` to manifest
  .changes/unreleased/Features-20240506-175642.yaml
  core/dbt/artifacts/README.md
  core/dbt/artifacts/resources/v1/model.py
  core/dbt/parser/manifest.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/primary_keys/fixtures.py
  tests/functional/primary_keys/test_primary_keys.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/fixtures.py
  tests/unit/test_contracts_graph_compiled.py
  tests/unit/test_contracts_graph_parsed.py
Labels: cla:yes, artifact_minor_upgrade

#10136 Fix #9970: Add security policy to project
  SECURITY.md
Labels: cla:yes, Skip Changelog

#10119 remove logbook
  .changes/unreleased/Dependencies-20240509-093717.yaml
  core/dbt/README.md
  core/dbt/artifacts/schemas/base.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/contracts/sql.py
  core/dbt/flags.py
  core/dbt/logger.py
  core/dbt/parser/manifest.py
  core/dbt/task/base.py
  core/dbt/task/printer.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  core/dbt/task/sql.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  core/dbt/tracking.py
  core/setup.py
  dev-requirements.txt
  tests/functional/list/test_list.py
  third-party-stubs/logbook/__init__.pyi
  third-party-stubs/logbook/__version__.pyi
  third-party-stubs/logbook/_fallback.pyi
  third-party-stubs/logbook/_termcolors.pyi
  third-party-stubs/logbook/base.pyi
  third-party-stubs/logbook/compat.pyi
  third-party-stubs/logbook/concurrency.pyi
  third-party-stubs/logbook/handlers.pyi
  third-party-stubs/logbook/helpers.pyi
  third-party-stubs/logbook/more.pyi
  third-party-stubs/logbook/notifiers.pyi
  third-party-stubs/logbook/queues.pyi
  third-party-stubs/logbook/ticketing.pyi
  third-party-stubs/logbook/utils.pyi
Labels: cla:yes, artifact_minor_upgrade

#10137 Fix #9907: Add retry to tox to reduce flaky tests due to network failures
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#10140 [Tidy First] Remove `wheel` and `twine` from `dev-requirements.txt`
  dev-requirements.txt
Labels: cla:yes, Skip Changelog, tidy_first

#10141 Rename the "Explain It Like I'm 64" folder to "guides"
  docs/guides/behavior-change-flags.md
  docs/guides/parsing-vs-compilation-vs-runtime.md
Labels: cla:yes, Skip Changelog

#10147 Repository unit tests for `ManifestLoader.get_full_manifest`
  tests/unit/conftest.py
  tests/unit/parser/test_manifest.py
  tests/unit/utils/adapter.py
  tests/unit/utils/project.py
Labels: cla:yes, Skip Changelog

#10153 Standardize event catching during repository unit tests
  tests/functional/configs/test_warn_error_options.py
  tests/functional/manifest_validations/test_check_for_spaces_in_model_names.py
  tests/unit/conftest.py
  tests/unit/events/test_logging.py
  tests/unit/test_functions.py
  tests/unit/utils/event_manager.py
  tests/utils.py
Labels: cla:yes, Skip Changelog

#10177 Add more accurate RSS high water mark measurement for Linux
  .changes/unreleased/Under the Hood-20240519-155946.yaml
  core/dbt/cli/requires.py
  core/dbt/utils.py
Labels: cla:yes

#10190 Improved flags fixturing for for repository unit tests
  tests/unit/conftest.py
  tests/unit/context/test_context.py
  tests/unit/context/test_query_header.py
  tests/unit/events/test_logging.py
  tests/unit/parser/test_manifest.py
  tests/unit/test_compilation.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_deprecations.py
  tests/unit/test_events.py
  tests/unit/test_graph_selection.py
  tests/unit/test_proto_events.py
  tests/unit/utils/flags.py
  tests/unit/utils/manifest.py
Labels: cla:yes, Skip Changelog

#10178 [Backport 1.0.latest] Fix #9907: Add retry to tox to reduce flaky tests due to network failures
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes

#10179 [Backport 1.1.latest] Fix #9907: Add retry to tox to reduce flaky tests due to network failures
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#10182 [Backport 1.2.latest] Fix #9907: Add retry to tox to reduce flaky tests due to network failures
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#10180 [Backport 1.3.latest] Fix #9907: Add retry to tox to reduce flaky tests due to network failures
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#10183 [Backport 1.4.latest] Fix #9907: Add retry to tox to reduce flaky tests due to network failures
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#10184 [Backport 1.5.latest] Fix #9907: Add retry to tox to reduce flaky tests due to network failures (#10137)
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#10186 [Backport 1.6.latest] Fix #9907: Add retry to tox to reduce flaky tests due to network failures (#10137)
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#10168 add saved query resource type
  .changes/unreleased/Fixes-20240516-223510.yaml
  core/dbt/artifacts/resources/v1/saved_query.py
Labels: cla:yes, artifact_minor_upgrade

#10191 Reorganize tests to match their code location
  tests/unit/clients/__init__.py
  tests/unit/clients/test_jinja.py
  tests/unit/clients/test_jinja_static.py
  tests/unit/clients/test_registry.py
  tests/unit/config/test_selectors.py
  tests/unit/context/__init__.py
  tests/unit/context/test_base.py
  tests/unit/contracts/graph/test_node_args.py
  tests/unit/contracts/graph/test_nodes.py
  tests/unit/contracts/graph/test_nodes_parsed.py
  tests/unit/contracts/graph/test_unparsed.py
  tests/unit/contracts/test_project.py
  tests/unit/deps/__init__.py
  tests/unit/deps/test_deps.py
  tests/unit/events/__init__.py
  tests/unit/events/test_types.py
  tests/unit/graph/test_cli.py
  tests/unit/graph/test_nodes.py
  tests/unit/graph/test_selector_spec.py
  tests/unit/parser/__init__.py
  tests/unit/parser/test_docs.py
  tests/unit/parser/test_parser.py
  tests/unit/parser/test_unit_tests.py
  tests/unit/task/__init__.py
  tests/unit/task/test_docs.py
  tests/unit/test_contracts_graph_unparsed.py
  tests/unit/test_graph_selector_spec.py
  tests/unit/test_infer_primary_key.py
  tests/unit/test_inject_ctes.py
  tests/unit/test_internal_deprecations.py
  tests/unit/test_manifest_selectors.py
  tests/unit/test_semver.py
Labels: cla:yes

#10131 Remove Print and use event system
  .changes/unreleased/Fixes-20240516-153913.yaml
  core/dbt/context/base.py
  core/dbt/events/types.py
  core/dbt/task/list.py
  core/setup.py
  tests/unit/task/test_list.py
Labels: cla:yes

#10194 [Backport 1.7.latest] Fix the semicolon semantics for indexes while respecting other bug fix
  .changes/unreleased/Fixes-20240514-193201.yaml
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/alter.sql
  plugins/postgres/dbt/include/postgres/macros/relations/materialized_view/create.sql
  tests/functional/postgres/test_multiple_indexes.py
Labels: cla:yes

#10199 [Backport 1.0.latest] [Tidy First] Remove wheel and twine from dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10206 [Backport 1.6.latest] [Tidy First] Remove wheel and twine from dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10205 [Backport 1.5.latest] [Tidy First] Remove wheel and twine from dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10204 [Backport 1.4.latest] [Tidy First] Remove wheel and twine from dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10203 [Backport 1.3.latest] [Tidy First] Remove wheel and twine from dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10201 [Backport 1.2.latest] [Tidy First] Remove wheel and twine from dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10200 [Backport 1.1.latest] [Tidy First] Remove wheel and twine from dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10207 [Backport 1.7.latest] [Tidy First] Remove wheel and twine from dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#10208 change port bind and add a unittest
  .changes/unreleased/Security-20240522-094540.yaml
  core/dbt/task/docs/serve.py
  tests/unit/task/docs/__init__.py
  tests/unit/task/docs/test_serve.py
Labels: cla:yes

#10215 backport 10168- fix for saved_query node not showing up properly in dbt-docs
  .changes/unreleased/Fixes-20240516-223510.yaml
  core/dbt/artifacts/resources/v1/saved_query.py
Labels: cla:yes, artifact_minor_upgrade

#10202 Fix: Order-insensitive unit test equality assertion for expected/actual with multiple nulls
  .changes/unreleased/Fixes-20240522-182855.yaml
  core/dbt/task/test.py
  tests/functional/unit_testing/test_ut_diffing.py
  tests/unit/task/test_test.py
Labels: cla:yes

#10221 [Fix] Renaming or removing a contracted model raises a BreakingChange warning/error
  .changes/unreleased/Fixes-20240523-204251.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/manifest.py
  tests/functional/defer_state/fixtures.py
  tests/functional/defer_state/test_modified_state.py
  tests/unit/graph/test_nodes.py
Labels: cla:yes

#10175 add recording types
  .changes/unreleased/Under the Hood-20240529-102814.yaml
  core/dbt/cli/requires.py
Labels: cla:yes

#10238 Move `StatsItem`, `StatsDict`, `TableMetadata` to `dbt-common`
  core/dbt/artifacts/schemas/catalog/__init__.py
  core/dbt/artifacts/schemas/catalog/v1/catalog.py
  core/setup.py
Labels: cla:yes, Skip Changelog, artifact_minor_upgrade

#10239 Button to open an issue for the docs.getdbt.com documentation repo
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla:yes, Skip Changelog

#10242 Create `RuntimeConfig` fixture
  tests/functional/basic/test_project.py
  tests/unit/config/test_project.py
  tests/unit/config/test_runtime.py
  tests/unit/conftest.py
  tests/unit/utils/config.py
  tests/unit/utils/project.py
Labels: cla:yes, Skip Changelog
