Repository dbt-labs/dbt-core, pull requests merged in 2024-11, with the labels that each got.

#10962 Support --empty option for 'snapshot' command
  .changes/unreleased/Features-20241031-163149.yaml
  core/dbt/cli/main.py
  tests/functional/snapshots/test_snapshot_empty.py
Labels: user docs, cla:yes

#10909 Behavior change cumulative type param
  .changes/unreleased/Under the Hood-20241031-094609.yaml
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  tests/unit/contracts/graph/test_semantic_manifest.py
  tests/unit/test_events.py
Labels: cla:yes, community

#10974 upgrade macos version
  .github/actions/setup-postgres-macos/action.yml
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes

#10977 [Backport 1.8.latest] upgrade macos version (#10974)
  .github/actions/setup-postgres-macos/action.yml
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes

#10978 [Backport 1.7.latest] upgrade macos version (#10974)
  .github/actions/setup-postgres-macos/action.yml
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#10982 [Backport 1.6.latest] upgrade macos version (#10974)
  .github/actions/setup-postgres-macos/action.yml
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#10981 [Backport 1.5.latest] upgrade macos version (#10974)
  .github/actions/setup-postgres-macos/action.yml
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#10980 [Backport 1.4.latest] upgrade macos version (#10974)
  .github/actions/setup-postgres-macos/action.yml
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes, Skip Changelog

#10831 Support disabling unit tests
  .changes/unreleased/Fixes-20241007-121402.yaml
  core/dbt/artifacts/resources/v1/unit_test_definition.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/graph/selector.py
  core/dbt/parser/unit_tests.py
  schemas/dbt/manifest/v12.json
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_ut_list.py
  tests/unit/parser/test_unit_tests.py
Labels: cla:yes, ready_for_review, artifact_minor_upgrade, community

#10975 [Fix] assert resolver.model is ModelNode prior to resolving event_time_filter
  .changes/unreleased/Fixes-20241105-151459.yaml
  core/dbt/context/providers.py
  tests/unit/context/test_providers.py
Labels: cla:yes

#10799 Replace environment variable with a project flag to gate microbatch functionality
  .changes/unreleased/Features-20241001-161422.yaml
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
  tests/functional/microbatch/test_microbatch_config_validation.py
  tests/unit/context/test_providers.py
  tests/unit/test_events.py
Labels: cla:yes

#10998 Bump minimum dbt-adapters requirement to 1.9.0
  .changes/unreleased/Dependencies-20241113-112043.yaml
  core/setup.py
Labels: cla:yes

#10995 Fix #10988: Validate manifest has group_map during group_lookup init
  .changes/unreleased/Fixes-20241113-171516.yaml
  core/dbt/task/group_lookup.py
  tests/functional/logging/test_logging.py
Labels: cla:yes

#10889 fix: unit tests with versioned refs
  .changes/unreleased/Fixes-20241021-093047.yaml
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/test_unit_testing.py
Labels: cla:yes, ready_for_review, community

#11003 fire GenericExceptionOnRun for batch-level exception
  .changes/unreleased/Fixes-20241114-112535.yaml
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes

#8538 fix: override materialization python models
  .changes/unreleased/Fixes-20241002-142638.yaml
  core/dbt/parser/base.py
  tests/unit/parser/test_parser.py
Labels: cla:yes, ready_for_review, community

#11008 [QOL] add index.html to .gitignore
  .gitignore
Labels: cla:yes, Skip Changelog, tidy_first

#9958 Parseable JSON and text output in quiet mode for `dbt show` and `dbt compile`
  .changes/unreleased/Features-20240416-123234.yaml
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/task/compile.py
  core/dbt/task/show.py
  tests/functional/compile/test_compile.py
  tests/functional/show/test_show.py
Labels: cla:yes, proto update

#10969 Use protobuf >=5.0,<=6.0
  .changes/unreleased/Under the Hood-20241104-110509.yaml
  .github/workflows/main.yml
  core/dbt/events/core_types_pb2.py
  core/setup.py
  dev-requirements.txt
Labels: cla:yes

#11014 Fix restrict-access to not restrict within same package
  .changes/unreleased/Fixes-20241119-162338.yaml
  core/dbt/contracts/graph/manifest.py
  tests/functional/access/test_access.py
Labels: cla:yes

#10958 Microbatch parallelism
  .changes/unreleased/Features-20241118-160038.yaml
  core/dbt/artifacts/resources/v1/config.py
  core/dbt/artifacts/schemas/batch_results.py
  core/dbt/clients/jinja_static.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  core/dbt/task/build.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/setup.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/clients/test_jinja_static.py
  tests/unit/task/test_run.py
  tests/unit/test_events.py
Labels: cla:yes, artifact_minor_upgrade, proto update

#11002 Fix plural of "partial success"
  .changes/unreleased/Fixes-20241114-170328.yaml
  core/dbt/events/types.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/test_events.py
Labels: cla:yes

#11028 add 1.8 changelogs
  CHANGELOG.md
Labels: Skip Changelog

#11029 Bump libpq-dev to 13.18-0+deb11u1 in docker/Dockerfile
  docker/Dockerfile
Labels: Skip Changelog

#11023 Fix #11012: Catch DbtRuntimeError for hooks
  .changes/unreleased/Fixes-20241121-181739.yaml
  core/dbt/task/run.py
  tests/functional/adapter/hooks/test_on_run_hooks.py
Labels: cla:yes

#10972 Add New Config Properties and Schema for Snapshot Hard Deletes
  .changes/unreleased/Features-20241104-120053.yaml
  core/dbt/artifacts/resources/v1/snapshot.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
Labels: cla:yes, artifact_minor_upgrade

#11046 Pin mashumaro to <3.15
  core/setup.py
Labels: Skip Changelog, backport 1.9.latest

#10591 Fixes dbt retry does not respect --threads
  .changes/unreleased/Fixes-20240822-122132.yaml
  core/dbt/task/retry.py
  tests/functional/retry/fixtures.py
  tests/functional/retry/test_retry_threads.py
Labels: cla:yes, ready_for_review, community

#11056 Rename internal `batch_info` variable to `previous_batch_results`
  core/dbt/contracts/graph/nodes.py
  core/dbt/task/retry.py
  core/dbt/task/run.py
  tests/unit/contracts/graph/test_manifest.py
Labels: cla:yes, Skip Changelog, tidy_first

#11031 Add `batch` context object to microbatch jinja context
  .changes/unreleased/Features-20241121-125630.yaml
  core/dbt/context/providers.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/materializations/incremental/microbatch.py
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/materializations/incremental/test_microbatch.py
Labels: cla:yes

#11063 [Tidy first] move microbatch compilation to .compile method
  core/dbt/task/run.py
Labels: cla:yes, Skip Changelog, tidy_first, backport 1.9.latest
