Repository dbt-labs/dbt-core, pull requests merged in 2024-09, with the labels that each got.

#10580 Filter out empty nodes after graph selection
  .changes/unreleased/Fixes-20240816-140807.yaml
  core/dbt/graph/selector.py
  tests/unit/graph/test_selector.py
Labels: cla:yes

#10352 Warn if timestamp updated_at field uses incompatible timestamp
  .changes/unreleased/Features-20240621-141635.yaml
  core/dbt/context/exceptions_jinja.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  tests/functional/snapshots/test_snapshot_timestamps.py
  tests/unit/test_events.py
Labels: cla:yes

#10670 Remove deprecation warning to change "tests:" config to "data_tests:"
  .changes/unreleased/Fixes-20240905-180248.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/events/types.py
  core/dbt/parser/schemas.py
  tests/functional/deprecations/test_config_deprecations.py
Labels: cla:yes

#10644 Add flags from dbt_project.yml to the Project and RuntimeConfig objects
  .changes/unreleased/Features-20240829-135320.yaml
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/contracts/project.py
  tests/unit/config/test_project.py
  tests/unit/utils/project.py
Labels: cla:yes

#10679 [1.3.latest] Avoid packaging for semver
  .changes/unreleased/Fixes-20230201-154418.yaml
  .changes/unreleased/Fixes-20230224-001338.yaml
  core/dbt/semver.py
  core/setup.py
  test/unit/test_semver.py
Labels: cla:yes, Skip Changelog

#10684 [Backport 1.1 latest] Avoid packaging for semver
  .changes/unreleased/Fixes-20230201-154418.yaml
  .changes/unreleased/Fixes-20230224-001338.yaml
  core/dbt/semver.py
  core/setup.py
  test/unit/test_semver.py
Labels: cla:yes, Skip Changelog

#10685 [Backport 1.0.latest] Avoid packaging for semver
  .changes/unreleased/Fixes-20230201-154418.yaml
  .changes/unreleased/Fixes-20230224-001338.yaml
  core/dbt/semver.py
  core/setup.py
  test/unit/test_semver.py
Labels: cla:yes, Skip Changelog

#10687 install postgres-16 in CI
  .github/actions/setup-postgres-linux/action.yml
  .github/actions/setup-postgres-macos/action.yml
  .github/actions/setup-postgres-windows/action.yml
  test/setup_db.sh
Labels: cla:yes, Skip Changelog

#10594 Microbatch: event_time ref + source filtering
  .changes/unreleased/Features-20240911-121029.yaml
  core/dbt/artifacts/resources/types.py
  core/dbt/artifacts/resources/v1/config.py
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/context/providers.py
  core/setup.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/context/test_providers.py
  tests/unit/contracts/graph/test_nodes.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes, artifact_minor_upgrade

#10710 [tidy first] delete extraneous EventCatcher
  tests/functional/utils.py
Labels: Skip Changelog, tidy_first

#10712 add patch_microbatch_event_time
  .changes/unreleased/Under the Hood-20240913-213312.yaml
  core/dbt/tests/util.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes

#10719 Update docs and title for schemas.getdbt.com changes
  .github/workflows/schema-check.yml
  core/dbt/artifacts/README.md
Labels: cla:yes, Skip Changelog

#10717 [tidy first] Fix a couple misspellings in code comments
  core/dbt/graph/selector.py
Labels: cla:yes, Skip Changelog

#10720 Update docs-issue.yml
  .github/workflows/docs-issue.yml
Labels: cla:yes

#10716 Add functional tests for custom incremental strategies names 'microbatch'
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes, Skip Changelog

#10664 Add custom granularities to YAML spec
  .changes/unreleased/Features-20240904-182320.yaml
  core/dbt/artifacts/resources/v1/model.py
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schemas.py
  core/setup.py
  schemas/dbt/manifest/v12.json
  tests/functional/time_spines/fixtures.py
  tests/functional/time_spines/test_time_spines.py
Labels: cla:yes, semantic, artifact_minor_upgrade, community

#10730 Fix `--resource-type test` for `dbt list` and `dbt build`
  .changes/unreleased/Fixes-20240917-174446.yaml
  core/dbt/task/build.py
  core/dbt/task/list.py
  core/dbt/task/test.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_ut_resource_types.py
Labels: cla:yes

#10677 Microbatch: batched execution
  .changes/unreleased/Features-20240913-232111.yaml
  core/dbt/context/providers.py
  core/dbt/materializations/__init__.py
  core/dbt/materializations/incremental/__init__.py
  core/dbt/materializations/incremental/microbatch.py
  core/dbt/task/docs/index.html
  core/dbt/task/run.py
  core/dbt/tests/util.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/context/test_providers.py
  tests/unit/materializations/incremental/test_microbatch.py
Labels: cla:yes

#10723 [Backport 1.8.latest] Add flags from dbt_project.yml to the Project and RuntimeConfig objects
  .changes/unreleased/Features-20240829-135320.yaml
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/contracts/project.py
  tests/unit/config/test_project.py
  tests/unit/utils/project.py
Labels: cla:yes

#10731 Update template for docs issues
  .github/workflows/docs-issue.yml
Labels: cla:yes, community

#10721 Add Snowplow tracking for behavior flags
  .changes/unreleased/Under the Hood-20240911-162730.yaml
  core/dbt/events/logging.py
  core/dbt/tracking.py
  tests/unit/events/test_logging.py
  tests/unit/test_behavior_flags.py
Labels: cla:yes

#10718 Replace `TestSelector` with `ResourceTypeSelector`
  .changes/unreleased/Under the Hood-20240916-102201.yaml
  core/dbt/task/build.py
  core/dbt/task/list.py
  core/dbt/task/test.py
Labels: cla:yes

#10736 Remove deprecated `track_struct_event`
  core/dbt/tracking.py
Labels: Skip Changelog

#10737 Split out model vs microbatch execution
  core/dbt/task/run.py
Labels: cla:yes, Skip Changelog

#10706 Enable `--resource-type` and `--exclude-resource-type` CLI flags and environment variables for `dbt test`
  .changes/unreleased/Features-20240903-132428.yaml
  core/dbt/cli/main.py
  core/dbt/node_types.py
  core/dbt/task/test.py
  tests/functional/unit_testing/test_unit_testing.py
  tests/functional/unit_testing/test_ut_resource_types.py
Labels: user docs, cla:yes

#10739 Standardize returning `ResourceTypeSelector` instances in `dbt list` and `dbt build`
  .changes/unreleased/Under the Hood-20240918-170325.yaml
  core/dbt/task/build.py
  core/dbt/task/list.py
Labels: cla:yes

#10608 Allow configuration of snapshot column names
  .changes/unreleased/Features-20240903-154133.yaml
  core/dbt/artifacts/resources/v1/snapshot.py
  core/dbt/context/context_config.py
  core/dbt/parser/models.py
  core/setup.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/snapshots/data/seed_cn.sql
  tests/functional/snapshots/test_snapshot_column_names.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes

#10762 Allow snapshots to be defined with YAML only.
  .changes/unreleased/Features-20240920-110447.yaml
  core/dbt/parser/schemas.py
  tests/functional/snapshots/fixtures.py
  tests/functional/snapshots/test_basic_snapshot.py
Labels: user docs, cla:yes

#10764 ignore --empty in unit test ref/source calls
  .changes/unreleased/Fixes-20240923-202024.yaml
  core/dbt/context/providers.py
  tests/functional/test_empty.py
Labels: cla:yes

#10744 Fix #9005: Allow singular tests to be documented in `properties.yml`
  .changes/unreleased/Fixes-20240923-190758.yaml
  core/dbt/config/project.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/common.py
  core/dbt/parser/schemas.py
  tests/functional/data_test_patch/fixtures.py
  tests/functional/data_test_patch/test_singular_test_patch.py
  tests/unit/config/test_project.py
  tests/unit/config/test_runtime.py
Labels: user docs, cla:yes

#10743 Write microbatch compiled + run code to separate target files
  .changes/unreleased/Features-20240920-172419.yaml
  core/dbt/compilation.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/materializations/incremental/microbatch.py
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/graph/test_nodes.py
  tests/unit/materializations/incremental/test_microbatch.py
Labels: cla:yes

#10756 Add required 'begin' config support for microbatch models
  .changes/unreleased/Features-20240923-155903.yaml
  core/dbt/artifacts/resources/v1/config.py
  core/dbt/materializations/incremental/microbatch.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/materializations/incremental/test_microbatch.py
Labels: cla:yes, artifact_minor_upgrade

#8268 Test case for `merge_exclude_columns`
  .changes/unreleased/Fixes-20230801-094626.yaml
  tests/functional/adapter/incremental/test_incremental_merge_exclude_columns.py
Labels: cla:yes

#10755 Fix unit tests for incremental models with alias
  .changes/unreleased/Fixes-20240922-133527.yaml
  core/dbt/context/providers.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_unit_testing.py
Labels: cla:yes, community

#10752 Microbatch Config Validation
  .changes/unreleased/Features-20240924-154639.yaml
  core/dbt/parser/manifest.py
  tests/functional/microbatch/test_microbatch.py
  tests/functional/microbatch/test_microbatch_config_validation.py
Labels: cla:yes, artifact_minor_upgrade

#10770 Add '--inline-direct' parameter to 'dbt show'.
  .changes/unreleased/Features-20240924-152922.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/task/show.py
  tests/functional/show/test_show.py
Labels: cla:yes

#10782 Improve performance of infer primary key
  .changes/unreleased/Fixes-20240925-160543.yaml
  core/dbt/parser/manifest.py
Labels: cla:yes

#10751 Enable `retry` support for Microbatch models
  .changes/unreleased/Features-20240925-165002.yaml
  core/dbt/artifacts/schemas/batch_results.py
  core/dbt/artifacts/schemas/results.py
  core/dbt/artifacts/schemas/run/v5/run.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/materializations/incremental/microbatch.py
  core/dbt/task/base.py
  core/dbt/task/build.py
  core/dbt/task/clone.py
  core/dbt/task/compile.py
  core/dbt/task/printer.py
  core/dbt/task/retry.py
  core/dbt/task/run.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  core/dbt/task/show.py
  core/dbt/task/test.py
  schemas/dbt/manifest/v12.json
  schemas/dbt/run-results/v6.json
  tests/functional/artifacts/data/results/v6/run_results.json
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/expected_run_results.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/task/test_run.py
  tests/unit/test_events.py
Labels: cla:yes, artifact_minor_upgrade

#10787 Fix changie doc for microbatch retry functionality
  .changes/unreleased/Features-20240925-165002.yaml
Labels: cla:yes

#10784 Attempt to skip saved query processing when no semantic manifest changes
  .changes/unreleased/Fixes-20240926-101220.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/manifest.py
Labels: cla:yes

#10775 [CORE-388] Add group metadata info to `LogModelResult` and `LogTestResult`
  .changes/unreleased/Under the Hood-20240926-143448.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/task/group_lookup.py
  core/dbt/task/printer.py
  core/dbt/task/run.py
  core/dbt/task/test.py
  tests/functional/adapter/basic/files.py
  tests/functional/adapter/basic/test_generic_tests.py
  tests/functional/invalid_model_tests/test_model_logging.py
  tests/functional/invalid_model_tests/test_model_warning.py
  tests/functional/logging/test_logging.py
Labels: cla:yes

#10788 [CT-10785] Microbatch models should respect `full_refresh` model config
  .changes/unreleased/Features-20240926-153210.yaml
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/task/test_run.py
Labels: cla:yes

#10765 Add missing changelog entry
  CHANGELOG.md
Labels: cla:yes

#9284 Add contributor to 1.1.0 release
  CHANGELOG.md
Labels: cla:yes, Skip Changelog, ready_for_review

#10790 Revert "Fix #9005: Allow singular tests to be documented in `properties.yml`"
  .changes/unreleased/Fixes-20240923-190758.yaml
  core/dbt/config/project.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/common.py
  core/dbt/parser/schemas.py
  tests/functional/data_test_patch/fixtures.py
  tests/functional/data_test_patch/test_singular_test_patch.py
  tests/unit/config/test_project.py
  tests/unit/config/test_runtime.py
Labels: cla:yes, Skip Changelog

#10789 Add new validations for custom granularities
  .changes/unreleased/Features-20240926-151057.yaml
  core/setup.py
Labels: cla:yes, community

#10769 [Backport 1.8.latest] Fix unit tests for incremental models with alias
  .changes/unreleased/Fixes-20240922-133527.yaml
  core/dbt/context/providers.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_unit_testing.py
Labels: cla:yes

#10793 state:modified vars, behind "state_modified_compare_vars" behaviour flag
  .changes/unreleased/Features-20240729-173203.yaml
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/exposure.py
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/context/configured.py
  core/dbt/context/providers.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/project.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/schema_yaml_readers.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/defer_state/test_modified_state.py
  tests/functional/list/test_list.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/contracts/graph/test_nodes.py
  tests/unit/contracts/graph/test_nodes_parsed.py
  tests/unit/graph/test_selector_methods.py
  tests/unit/parser/test_parser.py
Labels: user docs, cla:yes, artifact_minor_upgrade

#10758 add model_incremental_strategy to track_model_run
  .changes/unreleased/Features-20240923-155335.yaml
  core/dbt/task/run.py
  core/dbt/tracking.py
Labels: cla:yes
