Repository dbt-labs/dbt-core, pull requests merged in 2024-08, with the labels that each got.

#10508 more defensive node.all_constraints access
  .changes/unreleased/Fixes-20240731-095152.yaml
  core/dbt/compilation.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/parser/schemas.py
  tests/functional/configs/test_disabled_configs.py
  tests/unit/contracts/graph/test_manifest.py
Labels: cla:yes

#10529 Remove Undocumented Property
  core/dbt/context/providers.py
Labels: cla:yes, Skip Changelog, tidy_first

#10480 Parameterized testing examples utilizing happy path fixture
  tests/functional/conftest.py
  tests/functional/list/test_commands.py
Labels: cla:yes, Skip Changelog

#10541 Backport 10534 to 1.8.latest
  .changes/unreleased/Fixes-20240806-194843.yaml
  core/dbt/cli/flags.py
  core/dbt/config/project.py
  core/dbt/deprecations.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/test_deprecations.py
  tests/unit/test_internal_deprecations.py
Labels: cla:yes

#10530 Depend on Un-forked snowplow-tracker
  .changes/unreleased/Under the Hood-20240806-155406.yaml
  core/setup.py
Labels: cla:yes

#10542 [1.7 backport] buffer deprecations to respect --quiet and --warn-error-options
  .changes/unreleased/Fixes-20240806-194843.yaml
  core/dbt/cli/flags.py
  core/dbt/config/project.py
  core/dbt/deprecations.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/test_deprecations.py
  tests/unit/test_internal_deprecations.py
Labels: cla:yes

#10543 [1.6 backport] buffer deprecations to respect --quiet and --warn-error-options
  .changes/unreleased/Fixes-20240806-194843.yaml
  core/dbt/cli/flags.py
  core/dbt/config/project.py
  core/dbt/deprecations.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/test_deprecations.py
  tests/unit/test_internal_deprecations.py
Labels: cla:yes

#10536 Propagate the measure label when using create_metric option
  .changes/unreleased/Fixes-20240806-172110.yaml
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/semantic_models/fixtures.py
  tests/functional/semantic_models/test_semantic_model_parsing.py
Labels: cla:yes, community

#10544 Revert "Remove Undocumented Property"
  core/dbt/context/providers.py
Labels: cla:yes, Skip Changelog

#10545 [Tests] reset deprecations prior to usage in unit tests
  tests/unit/test_deprecations.py
Labels: cla:yes, Skip Changelog

#10550 Fix add_ephemeral_prefix to identifier instead of name
  core/dbt/compilation.py
Labels: cla:yes, Skip Changelog

#10526 Improve tree traversal of select_children
  .changes/unreleased/Under the Hood-20240809-130234.yaml
  core/dbt/graph/graph.py
Labels: cla:yes, community

#10371 Incremental models with a contract don't need their columns modified
  .changes/unreleased/Fixes-20240728-221421.yaml
  tests/functional/materializations/test_incremental_with_contract.py
Labels: cla:yes

#10568 Remove unneeded TODO
  core/dbt/contracts/graph/semantic_manifest.py
Labels: cla:yes, Skip Changelog, community

#10567 Backport #10526
  .changes/unreleased/Under the Hood-20240809-130234.yaml
  core/dbt/graph/graph.py
Labels: cla:yes

#10535 [CORE-364] Add `group` info to `RunResultError`, `RunResultFailure`, `RunResultWarning` log lines
  .changes/unreleased/Under the Hood-20240807-155652.yaml
  core/dbt/context/providers.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/task/printer.py
  core/dbt/task/run.py
  tests/functional/logging/test_logging.py
Labels: cla:yes

#10583 type ignore original_abspath + comment
  core/dbt/context/providers.py
Labels: cla:yes, Skip Changelog

#10588 Add test for source names with quotes
  .changes/unreleased/Under the Hood-20240821-095516.yaml
  tests/functional/sources/test_name_chars.py
Labels: cla:yes

#10565 Fix state:modified check for exports
  .changes/unreleased/Fixes-20240813-154235.yaml
  core/dbt/artifacts/resources/v1/saved_query.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/schema_yaml_readers.py
  schemas/dbt/manifest/v12.json
  tests/functional/saved_queries/test_saved_query_parsing.py
Labels: cla:yes, artifact_minor_upgrade, community

#10610 Updated saved query tests and fixtures
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_saved_query_build.py
  tests/functional/saved_queries/test_saved_query_parsing.py
Labels: cla:yes, Skip Changelog, community

#10603 Enable calling a macro in a pre- or post-hook config in `properties.yml`
  .changes/unreleased/Fixes-20240824-210903.yaml
  core/dbt/parser/schema_renderer.py
  tests/functional/adapter/hooks/fixtures.py
  tests/functional/adapter/hooks/test_model_hooks.py
Labels: user docs, cla:yes, backport 1.8.latest

#10613 [TIDY FIRST] Fix `core/dbt/version.py` type hinting
  .changes/unreleased/Under the Hood-20240827-105014.yaml
  core/dbt/version.py
Labels: cla:yes, tidy_first

#10615 [TIDY FIRST] Fix typing errors in `core/dbt/contracts/sql.py`
  .changes/unreleased/Under the Hood-20240827-113123.yaml
  core/dbt/contracts/sql.py
Labels: cla:yes, tidy_first

#10617 [TIDY FIRST] Fix typing issues in `dbt/core/tasks/clean.py`
  .changes/unreleased/Under the Hood-20240827-114810.yaml
  core/dbt/deprecations.py
  core/dbt/task/clean.py
Labels: cla:yes, tidy_first

#10622 Add More Typing to the dbt.task Module
  core/dbt/compilation.py
  core/dbt/plugins/manifest.py
  core/dbt/task/base.py
  core/dbt/task/build.py
  core/dbt/task/clone.py
  core/dbt/task/compile.py
  core/dbt/task/debug.py
  core/dbt/task/freshness.py
  core/dbt/task/list.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  core/dbt/task/show.py
  core/dbt/task/snapshot.py
  core/dbt/task/sql.py
  core/dbt/task/test.py
Labels: cla:yes, Skip Changelog

#10619 [Tidy First] add typing to dbt/cli/exceptions.py
  core/dbt/cli/exceptions.py
Labels: cla:yes, Skip Changelog, tidy_first

#10627 [Backport 1.7.latest] Fix test after dbt-utils release
  tests/functional/dependencies/test_dependency_options.py
Labels: cla:yes, Skip Changelog

#10633 update dep for psycopg
  docker/Dockerfile
Labels: cla:yes, Skip Changelog
