Repository dbt-labs/dbt-core, pull requests merged in 2024-03, with the labels that each got.

#9585 Handle exceptions during node execution more elegantly.
  .changes/unreleased/Fixes-20240216-145632.yaml
  core/dbt/task/README.md
  core/dbt/task/runnable.py
Labels: cla:yes

#9722 Stop trying to parse deleted schema files
  .changes/unreleased/Fixes-20240301-135536.yaml
  core/dbt/parser/partial.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/partial_parsing/test_pp_metrics.py
Labels: cla:yes

#9737 Fix #9117: Bump version of dbt-semantic-interfaces
  core/setup.py
Labels: cla:yes, Skip Changelog

#9736 Fix listing saved queries
  .changes/unreleased/Fixes-20240307-142459.yaml
  core/dbt/cli/params.py
  core/dbt/task/list.py
  tests/functional/list/fixtures.py
  tests/functional/list/test_list.py
Labels: cla:yes

#9748 [Backport 1.7.latest][MANUAL] Fix listing saved queries
  .changes/unreleased/Fixes-20240307-142459.yaml
  core/dbt/cli/params.py
  core/dbt/task/list.py
  tests/functional/list/fixtures.py
  tests/functional/list/test_list.py
Labels: cla:yes

#9709 Enable list filters for input metrics & measures
  .changes/unreleased/Fixes-20240229-114207.yaml
  core/dbt/parser/schema_renderer.py
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metrics.py
Labels: cla:yes

#9688 Update codeowners post adapters-decoupling
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#9714 [#9570] Fix fixtures in fixtures/subfolders throwing parsing error
  .changes/unreleased/Fixes-20240301-000355.yaml
  core/dbt/parser/manifest.py
  tests/unit/test_parse_manifest.py
Labels: cla:yes, ready_for_review

#9758 fix source selection during catalog generation of over 100 relations
  .changes/unreleased/Fixes-20240312-165357.yaml
  core/dbt/task/docs/generate.py
  tests/functional/docs/test_generate.py
Labels: cla:yes

#9626 Unit Testing: Support overriding macros in packages
  .changes/unreleased/Fixes-20240315-145538.yaml
  core/dbt/context/providers.py
  tests/functional/unit_testing/test_ut_overrides.py
  tests/unit/test_context.py
Labels: cla:yes

#9723 merge source meta and table meta on SourceDefinition.meta
  .changes/unreleased/Features-20240315-161209.yaml
  core/dbt/parser/sources.py
  tests/unit/test_parser.py
Labels: cla:yes

#9341 Fix package-lock file's bad indentation
  .changes/unreleased/Fixes-20240106-003649.yaml
  core/dbt/task/deps.py
  tests/functional/dependencies/test_dependency_options.py
  tests/functional/dependencies/test_simple_dependency.py
Labels: cla:yes, ready_for_review

#9744 Make `dbt` CLI cold start load up to 8% faster with lazy loading of task modules and `agate`
  .changes/unreleased/Under the Hood-20240309-141054.yaml
  core/dbt/artifacts/schemas/run/v5/run.py
  core/dbt/cli/main.py
  core/dbt/context/providers.py
  core/dbt/exceptions.py
  core/dbt/task/run_operation.py
  core/dbt/task/test.py
Labels: cla:yes, artifact_minor_upgrade

#9763 Fix #9511: Handle exceptions for failing `on-run-*` hooks in `source freshness`
  .changes/unreleased/Fixes-20240316-231152.yaml
  core/dbt/artifacts/schemas/freshness/v3/freshness.py
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes, artifact_minor_upgrade

#9769 Fix #9593: Validation of unit test parsing for incremental models
  .changes/unreleased/Fixes-20240317-005611.yaml
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_unit_testing.py
Labels: cla:yes

#9772 Fix retry of a command with defer
  .changes/unreleased/Fixes-20240318-153338.yaml
  core/dbt/cli/flags.py
  core/dbt/task/runnable.py
  tests/functional/defer_state/test_defer_state.py
  tests/unit/test_cli_flags.py
Labels: cla:yes

#9778 [Backport to 1.7.latest] Handle exceptions during node execution more elegantly. (#9585)
  .changes/unreleased/Fixes-20240216-145632.yaml
  core/dbt/task/README.md
  core/dbt/task/runnable.py
Labels: cla:yes

#9786 Move `protobuf` dep to a more applicable section of `setup.py`
  core/setup.py
Labels: cla:yes, Skip Changelog

#9779 Enable use of env vars for --resource-types and --exclude-resource-types
  .changes/unreleased/Features-20240312-140407.yaml
  core/dbt/cli/option_types.py
  core/dbt/task/base.py
  tests/functional/list/test_list.py
  tests/functional/unit_testing/test_unit_testing.py
  tests/unit/test_cli_flags.py
Labels: cla:yes

#9682 Add factory wrappers to renamed_relations
  .changes/unreleased/Fixes-20240226-215842.yaml
  core/dbt/adapters/base/relation.py
  plugins/postgres/dbt/adapters/postgres/relation.py
  tests/unit/test_renamed_relations.py
Labels: cla:yes

#9081 Add --target and --profile to global config
  .changes/unreleased/Features-20231115-092005.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
Labels: cla:yes

#9797 Automate labeling PRs as community sourced
  .github/workflows/community-label.yml
Labels: cla:yes, Skip Changelog

#9802 ensure the upload name is unique
  .github/workflows/main.yml
Labels: cla:yes

#9773 Allow metrics in semantic layer filters
  .changes/unreleased/Features-20240322-103124.yaml
  core/setup.py
  tests/functional/metrics/fixtures.py
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_saved_query_parsing.py
Labels: user docs, cla:yes

#9803 update triggers to use issues for opening docs issues
  .github/workflows/docs-issue.yml
Labels: cla:yes, Skip Changelog

#9807 use issue context
  .github/workflows/docs-issue.yml
Labels: cla:yes, Skip Changelog

#9800 Update `pytest` examples for contributors
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#9805 fix team name
  .github/workflows/community-label.yml
Labels: cla:yes, Skip Changelog

#9642 Remove erroneously added `wildcard` method name
  .changes/unreleased/Under the Hood-20240223-092330.yaml
  core/dbt/graph/selector_methods.py
Labels: cla:yes

#9823 Fix info message for TestsConfigDeprecation
  core/dbt/events/types.py
Labels: cla:yes, Skip Changelog

#9825 Fix assorted source freshness edgecases so check is run or actionable information
  .changes/unreleased/Fixes-20240326-162100.yaml
  core/dbt/task/base.py
  core/dbt/task/freshness.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/conftest.py
  tests/unit/task/test_base.py
  tests/unit/test_contracts_graph_parsed.py
Labels: cla:yes

#9820 Include node_info in various Result events
  .changes/unreleased/Under the Hood-20240325-172059.yaml
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/task/printer.py
  core/dbt/task/runnable.py
  tests/functional/logging/test_logging.py
Labels: cla:yes

#9793 Fix #9608: Unit test path outputs
  .changes/unreleased/Fixes-20240326-003411.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/unit_tests.py
  core/dbt/task/printer.py
  core/dbt/task/test.py
  tests/functional/unit_testing/test_unit_testing.py
  tests/functional/unit_testing/test_ut_names.py
Labels: cla:yes

#9828 Fix Docker release process for `dbt-postgres`
  .changes/unreleased/Fixes-20240327-150013.yaml
  docker/Dockerfile
Labels: cla:yes

#9826 [Backport to 1.7.latest] Fix assorted source freshness edgecases so check is run or actionable information (#9825)
  .changes/unreleased/Fixes-20240326-162100.yaml
  core/dbt/task/base.py
  core/dbt/task/freshness.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/conftest.py
  tests/unit/task/test_base.py
  tests/unit/test_contracts_graph_parsed.py
Labels: cla:yes

#9837 [Tidy first] rename node, realnode to unique_id, node in selector_methods.py
  core/dbt/graph/selector_methods.py
Labels: cla:yes, Skip Changelog, tidy_first
