Repository dbt-labs/dbt-core, pull requests merged in 2024-12, with the labels that each got.

#11086 mashumaro < 3.15
  .changes/unreleased/Under the Hood-20241202-115626.yaml
  core/setup.py
Labels: cla:yes

#11096 Backport 11069 1.9.latest
  .changes/unreleased/Fixes-20241128-162936.yaml
  core/dbt/parser/manifest.py
Labels: cla:yes, Skip Changelog

#10990 Update core to support DSI 0.8.3
  .changes/unreleased/Dependencies-20241112-163815.yaml
  core/dbt/artifacts/resources/v1/metric.py
  core/dbt/artifacts/resources/v1/semantic_layer_components.py
  core/dbt/artifacts/resources/v1/semantic_model.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  core/setup.py
  schemas/dbt/manifest/v12.json
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metrics.py
  tests/functional/time_spines/fixtures.py
  tests/unit/contracts/graph/test_semantic_manifest.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes, artifact_minor_upgrade, community

#11099 Improve performance of select_children() and select_parents()
  .changes/unreleased/Under the Hood-20241205-143144.yaml
  core/dbt/graph/graph.py
Labels: cla:yes

#11100 Implement partial parsing for singular data tests configs in yaml files
  .changes/unreleased/Fixes-20241205-145307.yaml
  core/dbt/parser/partial.py
  core/dbt/parser/schemas.py
  tests/functional/data_test_patch/fixtures.py
  tests/functional/data_test_patch/test_singular_test_patch.py
Labels: cla:yes

#11072 Microbatch first last batch serial
  .changes/unreleased/Features-20241206-195308.yaml
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/task/test_run.py
  tests/unit/test_events.py
Labels: cla:yes

#11113 Fix erroneous additional batch execution
  .changes/unreleased/Fixes-20241209-133317.yaml
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes

#11115 Fix microbatch model `PartialSuccess` status to result in non-zero exit code
  .changes/unreleased/Fixes-20241209-150711.yaml
  core/dbt/task/runnable.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes

#10919 update adapter version messages
  .changes/unreleased/Fixes-20241025-104339.yaml
  core/dbt/version.py
  tests/unit/test_version.py
Labels: cla:yes, ready_for_review, community

#11082 Create a no-op exposure runner
  .changes/unreleased/Under the Hood-20241202-164715.yaml
  core/dbt/artifacts/schemas/results.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/types.py
  core/dbt/graph/selector.py
  core/dbt/runners/__init__.py
  core/dbt/runners/exposure_runner.py
  core/dbt/runners/no_op_runner.py
  core/dbt/runners/saved_query_runner.py
  core/dbt/task/build.py
  core/dbt/task/printer.py
  core/dbt/task/runnable.py
  tests/functional/adapter/concurrency/test_concurrency.py
  tests/functional/adapter/hooks/test_on_run_hooks.py
  tests/functional/defer_state/test_run_results_state.py
  tests/functional/exposures/test_exposures.py
  tests/functional/saved_queries/test_saved_query_build.py
  tests/unit/task/test_build.py
  tests/unit/test_events.py
Labels: cla:yes, artifacts, artifact_minor_upgrade

#11138 add allow additional property for Model and SourceDefinition
  core/dbt/artifacts/schemas/manifest/v12/manifest.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/test_artifacts.py
  tests/unit/contracts/graph/test_nodes.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes, Skip Changelog, artifact_minor_upgrade

#11145 Warn if `concurrent_batches` config is set to `True`, but the available adapter doesn't support it
  .changes/unreleased/Fixes-20241212-113611.yaml
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/manifest.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/parser/test_manifest.py
  tests/unit/test_events.py
Labels: cla:yes

#11152 Auto-response for bug reports during holiday break
  .github/workflows/auto-respond-bug-reports.yml
Labels: cla:yes

#11156 Fix yaml snapshot specification with data tests
  .changes/unreleased/Fixes-20241216-134645.yaml
  core/dbt/parser/schemas.py
  tests/functional/snapshots/fixtures.py
Labels: cla:yes

#11166 Fix for dbt_project.yml "tests" config resulting in incorrect state:modified
  .changes/unreleased/Fixes-20241218-112640.yaml
  core/dbt/config/project.py
  tests/functional/defer_state/test_unrendered_config.py
Labels: cla:yes

#10987 Add tags to SavedQueries
  .changes/unreleased/Features-20241216-095435.yaml
  core/dbt/artifacts/resources/v1/saved_query.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  schemas/dbt/catalog/v1.json
  schemas/dbt/manifest/v12.json
  schemas/dbt/run-results/v6.json
  schemas/dbt/sources/v3.json
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_configs.py
Labels: cla:yes, semantic, artifact_minor_upgrade, community

#11163 Custom SQL for get source maxLoadedAt
  .changes/unreleased/Features-20241217-171631.yaml
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_renderer.py
  core/dbt/parser/sources.py
  core/dbt/task/freshness.py
  core/setup.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/parser/test_parser.py
  tests/unit/parser/test_schema_renderer.py
Labels: cla:yes, artifact_minor_upgrade

#11137 Fix circular import
  .changes/unreleased/Fixes-20241211-132203.yaml
  core/dbt/cli/__init__.py
  core/dbt/config/profile.py
Labels: cla:yes, ready_for_review, community

#11173 Roadmap update (Dec 2024)
  docs/roadmap/2024-12-play-on.md
Labels: cla:yes

#11175 Revert "Fix circular import (#11137)"
  .changes/unreleased/Fixes-20241211-132203.yaml
  core/dbt/cli/__init__.py
  core/dbt/config/profile.py
Labels: cla:yes, Skip Changelog
