Repository dbt-labs/dbt-core, pull requests merged in 2024-02, with the labels that each got.

#9485 Move `SemanticModel` data artifacts to `dbt/artifacts`
  .changes/unreleased/Under the Hood-20240129-163800.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/v1/semantic_model.py
  core/dbt/artifacts/schemas/manifest/v12/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_models.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/semantic_models/test_semantic_model_configs.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
  tests/unit/test_semantic_models.py
Labels: cla:yes

#9494 Move `Exposure` data parts to `dbt/artifacts`
  .changes/unreleased/Under the Hood-20240130-161637.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/v1/exposure.py
  core/dbt/artifacts/schemas/manifest/v12/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/exposures/test_exposure_configs.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_contracts_graph_unparsed.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_manifest.py
Labels: cla:yes

#9503 Fix `compiled_code`, reimplement `sql` as wrapper
  .changes/unreleased/Fixes-20240201-124701.yaml
  core/dbt/context/providers.py
Labels: cla:yes

#9499 Integration Test Optimizations
  .changes/unreleased/Features-20240131-153535.yaml
  .changes/unreleased/Features-20240201-154956.yaml
  core/dbt/clients/jinja_static.py
  core/dbt/parser/macros.py
  core/dbt/plugins/manager.py
  core/dbt/tests/fixtures/project.py
  core/setup.py
Labels: cla:yes

#9489 Use new context invocation class to cache environment variables.
  .changes/unreleased/Features-20240202-112644.yaml
  core/dbt/cli/requires.py
  core/dbt/config/renderer.py
  core/dbt/context/base.py
  core/dbt/context/configured.py
  core/dbt/context/providers.py
  core/dbt/context/secret.py
  core/dbt/logger.py
  core/dbt/parser/partial.py
  core/dbt/task/runnable.py
  core/dbt/tests/util.py
  tests/unit/test_config.py
  tests/unit/test_graph_runnable_task.py
  tests/unit/test_partial_parsing.py
Labels: cla:yes

#9509 Begin using `Mergeable` supplied by `dbt-common`
  .changes/unreleased/Under the Hood-20240201-125416.yaml
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/contracts/util.py
Labels: cla:yes

#9480 Enable using the list command on unit tests
  .changes/unreleased/Features-20240129-114753.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/task/list.py
  core/dbt/task/test.py
  tests/functional/unit_testing/test_ut_list.py
Labels: cla:yes

#9479 [Backport 1.2.latest] Pin `pytest` in `dev-requirements.txt`
  .github/workflows/structured-logging-schema-check.yml
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#9529 Initialize invocation context before test fixture creation.
  .changes/unreleased/Fixes-20240206-161331.yaml
  core/dbt/tests/fixtures/project.py
Labels: cla:yes

#9527 Update artifacts left over from migrating dbt-postgres, dbt-common, and dbt-tests-adapter
  Makefile
  docker/Dockerfile
Labels: cla:yes, Skip Changelog

#9522 remove unnecesary fire_event_if_test
  core/dbt/parser/models.py
  tests/functional/experimental_parser/test_all_experimental_parser.py
Labels: cla:yes, Skip Changelog

#9539 Preserve model constraints when versioning models
  .changes/unreleased/Fixes-20240207-150223.yaml
  core/dbt/parser/schemas.py
  core/dbt/tests/__init__.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/configs/test_versioned_model_constraint.py
Labels: cla:yes

#9514 initial readme for dbt/artifacts
  core/dbt/artifacts/README.md
Labels: cla:yes, Skip Changelog

#9440 still register adapter when manifest is provided
  core/dbt/cli/requires.py
  tests/functional/dbt_runner/test_dbt_runner.py
Labels: cla:yes, Skip Changelog

#9258 Update README.md
  README.md
Labels: cla:yes, Skip Changelog

#9549 Fix: SemanticModel.same_model compares model attribute
  .changes/unreleased/Fixes-20240209-170146.yaml
  core/dbt/contracts/graph/nodes.py
  tests/functional/defer_state/fixtures.py
  tests/functional/defer_state/test_modified_state.py
  tests/unit/test_semantic_models.py
Labels: cla:yes

#9561 Anther Fix for Semantic model same content
  .changes/unreleased/Fixes-20240212-154728.yaml
  core/dbt/contracts/graph/nodes.py
  tests/unit/test_semantic_models.py
Labels: cla:yes

#9553 Fix #9385: Add a workflow to check if artifacts have changed
  .github/workflows/check-artifact-changes.yml
Labels: cla:yes, artifact_minor_upgrade

#9556 Set query headers when manifest is passed in to dbtRunner
  .changes/unreleased/Fixes-20240212-144733.yaml
  core/dbt/cli/requires.py
  tests/functional/dbt_runner/test_dbt_runner.py
Labels: cla:yes

#9559 Store node_info in GenericExceptionOnRun logging event
  .changes/unreleased/Fixes-20240212-165619.yaml
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/task/base.py
  core/dbt/task/freshness.py
  core/dbt/task/sql.py
Labels: cla:yes

#9569 [Backport 1.7.latest] Set query headers when manifest is passed in to dbtRunner
  .changes/unreleased/Fixes-20240212-165619.yaml
  core/dbt/cli/requires.py
  dev-requirements.txt
  tests/functional/dbt_runner/test_dbt_runner.py
Labels: cla:yes

#9568 [Backport 1.7.latest] Store node_info in GenericExceptionOnRun logging event
  core/dbt/events/types.proto
  core/dbt/events/types_pb2.py
  core/dbt/task/base.py
  core/dbt/task/sql.py
Labels: cla:yes, Skip Changelog

#9543 Move `SourceDefinition` to `dbt/artifacts`
  .changes/unreleased/Under the Hood-20240208-120620.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/types.py
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/artifacts/schemas/freshness/v3/freshness.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/common.py
  core/dbt/parser/sources.py
  tests/functional/sources/test_source_configs.py
  tests/unit/test_contracts_graph_compiled.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_contracts_graph_unparsed.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_providers.py
Labels: cla:yes, artifact_minor_upgrade

#9588 add cache to SavedQueryConfig
  .changes/unreleased/Features-20240215-145814.yaml
  core/dbt/artifacts/resources/v1/saved_query.py
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_configs.py
Labels: cla:yes, artifact_minor_upgrade

#9589 remove uses of Replaceable class
  .changes/unreleased/Under the Hood-20240216-104002.yaml
  core/dbt/artifacts/resources/base.py
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/docs.py
  core/dbt/artifacts/resources/v1/macro.py
  core/dbt/artifacts/resources/v1/owner.py
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/artifacts/schemas/catalog/v1/catalog.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/contracts/util.py
  core/dbt/parser/sources.py
  core/dbt/task/docs/generate.py
  tests/unit/test_contracts_graph_compiled.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/utils.py
Labels: cla:yes, artifact_minor_upgrade

#9592 add test for unit tests with a snapshot as a dependency
  tests/functional/unit_testing/test_ut_snapshot_dependency.py
  tests/functional/unit_testing/test_ut_sources.py
Labels: cla:yes, Skip Changelog

#9508 Fix filter parsing bug
  .changes/unreleased/Fixes-20240201-164407.yaml
  core/dbt/contracts/graph/unparsed.py
  tests/functional/metrics/fixtures.py
  tests/functional/metrics/test_metrics.py
  tests/functional/saved_queries/fixtures.py
  tests/functional/saved_queries/test_saved_query_parsing.py
Labels: cla:yes, ready_for_review, artifact_minor_upgrade

#9538 Move manifest nodes to dbt/artifacts
  .changes/unreleased/Under the Hood-20240207-122342.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/base.py
  core/dbt/artifacts/resources/types.py
  core/dbt/artifacts/resources/v1/analysis.py
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/config.py
  core/dbt/artifacts/resources/v1/docs.py
  core/dbt/artifacts/resources/v1/generic_test.py
  core/dbt/artifacts/resources/v1/hook.py
  core/dbt/artifacts/resources/v1/macro.py
  core/dbt/artifacts/resources/v1/model.py
  core/dbt/artifacts/resources/v1/seed.py
  core/dbt/artifacts/resources/v1/singular_test.py
  core/dbt/artifacts/resources/v1/snapshot.py
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/artifacts/resources/v1/sql_operation.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/parser/base.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  core/dbt/parser/unit_tests.py
  core/dbt/task/run.py
  tests/unit/test_contracts_graph_compiled.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_parser.py
Labels: cla:yes, artifact_minor_upgrade

#9631 Do not allow hook node_info to persist past hook run
  .changes/unreleased/Fixes-20240222-100958.yaml
  core/dbt/task/run.py
  core/setup.py
  tests/functional/dbt_runner/test_dbt_runner.py
Labels: cla:yes

#9628 flags & tracking from dbt/artifacts
  .changes/unreleased/Under the Hood-20240222-115245.yaml
  core/dbt/artifacts/schemas/manifest/v12/manifest.py
  core/dbt/config/runtime.py
  core/dbt/contracts/graph/manifest.py
  tests/unit/test_config.py
  tests/unit/test_manifest.py
Labels: cla:yes, artifact_minor_upgrade

#9638 Upgrade Jinja2 dependency version specification to address CVE-2024-22195
  .changes/unreleased/Security-20240222-152445.yaml
  core/setup.py
Labels: cla:yes, backport 1.5.latest, backport 1.6.latest, backport 1.7.latest

#9646 Fix #8948: Add target-path to retry
  .changes/unreleased/Fixes-20240223-162107.yaml
  core/dbt/cli/main.py
  tests/functional/retry/test_retry.py
Labels: cla:yes

#9640 remove ~= from dependency definitions
  core/setup.py
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#9650 Add method to infer primary key of model
  .changes/unreleased/Under the Hood-20240223-115021.yaml
  core/dbt/contracts/graph/nodes.py
  tests/unit/fixtures.py
  tests/unit/test_contracts_graph_compiled.py
  tests/unit/test_infer_primary_key.py
Labels: cla:yes

#9645 [Backport 1.7.latest] Do not allow hook node_info to persist past hook run
  .changes/unreleased/Fixes-20240222-100958.yaml
  core/dbt/events/contextvars.py
  core/dbt/task/run.py
  tests/functional/dbt_runner/test_dbt_runner.py
Labels: cla:yes

#9664 [Backport 1.7.latest] Add target-path to retry
  .changes/unreleased/Fixes-20240223-162107.yaml
  core/dbt/cli/main.py
  tests/functional/retry/test_retry.py
Labels: cla:yes

#9614 Paw/restrict to protobuf 4
  .changes/unreleased/Under the Hood-20240221-104518.yaml
  dev-requirements.txt
Labels: cla:yes

#9668 [Backport 1.6.latest] Upgrade Jinja2 dependency version specification to address CVE-2024-22195
  .changes/unreleased/Security-20240222-152445.yaml
  core/setup.py
Labels: cla:yes

#9651 move UnitTestDefinition, implement missing resource_class methods
  .changes/unreleased/Under the Hood-20240226-141038.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/v1/unit_test_definition.py
  core/dbt/artifacts/schemas/manifest/v12/manifest.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/graph/selector_methods.py
  core/dbt/parser/unit_tests.py
  tests/unit/test_unit_test_parser.py
Labels: cla:yes, artifact_minor_upgrade

#9670 [Backport 1.5.latest] Upgrade Jinja2 dependency version specification to address CVE-2024-22195
  .changes/unreleased/Security-20240222-152445.yaml
  core/setup.py
Labels: cla:yes

#9675 [Backport 1.6.latest] Restrict to protobuf 4
  .changes/unreleased/Under the Hood-20240221-104518.yaml
  dev-requirements.txt
Labels: cla:yes

#9673 [Backport 1.7.latest] Make dbt-core compatible with Python 3.12
  .changes/unreleased/Under the Hood-20240221-145058.yaml
  .github/workflows/main.yml
  core/dbt/task/test.py
  core/dbt/utils.py
  core/setup.py
  pytest.ini
  tests/unit/test_plugin_manager.py
Labels: cla:yes

#9676 [Backport 1.5.latest] Restrict to protobuf 4
  .changes/unreleased/Under the Hood-20240221-104518.yaml
  dev-requirements.txt
Labels: cla:yes

#9674 [Backport 1.7.latest] Restrict to protobuf 4
  .changes/unreleased/Under the Hood-20240221-104518.yaml
  dev-requirements.txt
Labels: cla:yes

#9544 Convert from WritableManifest -> Manifest to represent deferred manifest internally
  .changes/unreleased/Under the Hood-20240226-184258.yaml
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/schemas/manifest/v12/manifest.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/state.py
  core/dbt/graph/selector_methods.py
  core/dbt/task/clone.py
  core/dbt/task/runnable.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_manifest.py
Labels: cla:yes, artifact_minor_upgrade

#9690 bump dbt-common in setup.py
  .changes/unreleased/Dependencies-20240227-151115.yaml
  core/setup.py
Labels: cla:yes

#9691 Allow for dbt-adapters 1.0.0b1
  core/setup.py
Labels: cla:yes, Skip Changelog

#9704 swap var to make mypy happy
  core/dbt/parser/read_files.py
Labels: cla:yes, Skip Changelog

#9700 Throw ParsingError for invalid PK definition on constraints
  .changes/unreleased/Fixes-20240228-135928.yaml
  core/dbt/parser/schemas.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/configs/test_versioned_model_constraint.py
Labels: cla:yes

#9708 [Backport 1.5.latest] Restrict protobuf to 4.* versions (MANUAL)
  .changes/unreleased/Dependencies-20240222-102947.yaml
  core/setup.py
Labels: cla:yes
