Repository dbt-labs/dbt-core, pull requests merged in 2024-01, with the labels that each got.

#9326 move events only used by core to dbt/events
  .changes/unreleased/Under the Hood-20240103-145843.yaml
  core/dbt/cli/requires.py
  core/dbt/clients/git.py
  core/dbt/clients/registry.py
  core/dbt/common/events/types.proto
  core/dbt/common/events/types.py
  core/dbt/common/events/types_pb2.py
  core/dbt/common/helper_types.py
  core/dbt/compilation.py
  core/dbt/config/profile.py
  core/dbt/config/runtime.py
  core/dbt/config/utils.py
  core/dbt/context/base.py
  core/dbt/context/exceptions_jinja.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/semantic_manifest.py
  core/dbt/contracts/results.py
  core/dbt/contracts/state.py
  core/dbt/deps/base.py
  core/dbt/deps/git.py
  core/dbt/deps/local.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/graph/selector.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/read_files.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  core/dbt/task/base.py
  core/dbt/task/build.py
  core/dbt/task/clean.py
  core/dbt/task/compile.py
  core/dbt/task/debug.py
  core/dbt/task/deps.py
  core/dbt/task/freshness.py
  core/dbt/task/init.py
  core/dbt/task/list.py
  core/dbt/task/printer.py
  core/dbt/task/run.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  core/dbt/task/show.py
  core/dbt/task/snapshot.py
  core/dbt/task/sql.py
  core/dbt/task/test.py
  core/dbt/tracking.py
  tests/functional/logging/test_logging.py
  tests/unit/test_events.py
  tests/unit/test_functions.py
  tests/unit/test_helper_types.py
  tests/unit/test_proto_events.py
Labels: cla:yes

#9289 Move UserConfig to dbt_project.yml and rename to ProjectFlags
  .changes/unreleased/Features-20231218-195854.yaml
  core/dbt/adapters/contracts/connection.py
  core/dbt/cli/flags.py
  core/dbt/config/__init__.py
  core/dbt/config/profile.py
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/flags.py
  core/dbt/include/starter_project/dbt_project.yml
  core/dbt/tests/fixtures/project.py
  core/dbt/tracking.py
  core/dbt/utils.py
  tests/functional/basic/test_mixed_case_db.py
  tests/functional/basic/test_project.py
  tests/functional/configs/test_disabled_configs.py
  tests/functional/dependencies/test_local_dependency.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/fail_fast/test_fail_fast_run.py
  tests/functional/init/test_init.py
  tests/functional/metrics/test_metric_deferral.py
  tests/functional/run_operations/test_run_operations.py
  tests/unit/test_cli_flags.py
  tests/unit/test_config.py
  tests/unit/test_events.py
  tests/unit/test_flags.py
  tests/unit/test_graph_selection.py
Labels: user docs, cla:yes

#9333 Decouple core exceptions from common
  .changes/unreleased/Under the Hood-20240104-133249.yaml
  core/dbt/common/clients/_jinja_blocks.py
  core/dbt/common/clients/system.py
  core/dbt/common/contracts/config/base.py
  core/dbt/common/exceptions/__init__.py
  core/dbt/common/exceptions/connection.py
  core/dbt/common/exceptions/jinja.py
  core/dbt/common/exceptions/system.py
  core/dbt/common/utils/connection.py
  core/dbt/common/utils/dict.py
  core/dbt/deps/git.py
  core/dbt/exceptions.py
  core/dbt/task/debug.py
  tests/unit/common/test_system_client.py
  tests/unit/test_connection_retries.py
  tests/unit/test_core_dbt_utils.py
  tests/unit/test_registry_get_request_exception.py
Labels: cla:yes

#9338 Decouple warn error options from core and adapters
  .changes/unreleased/Under the Hood-20240104-165248.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/option_types.py
  core/dbt/common/helper_types.py
  core/dbt/events/__init__.py
  tests/unit/test_functions.py
  tests/unit/test_helper_types.py
Labels: cla:yes

#9335 generalize BaseConfig.update_from + call adapter factory methods in core
  .changes/unreleased/Under the Hood-20240104-135849.yaml
  core/dbt/common/contracts/config/base.py
  core/dbt/context/context_config.py
Labels: cla:yes

#9349 Update implementation-ticket.yml
  .github/ISSUE_TEMPLATE/implementation-ticket.yml
Labels: cla:yes, Skip Changelog

#9328 Fix full-refresh and vars for retry
  .changes/unreleased/Fixes-20231213-220449.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/contracts/state.py
  core/dbt/parser/manifest.py
  core/dbt/task/retry.py
  tests/functional/retry/test_retry.py
Labels: cla:yes

#9353 Fully remove legacy logger
  .changes/unreleased/Dependencies-20240109-120530.yaml
  core/dbt/README.md
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/contracts/results.py
  core/dbt/contracts/sql.py
  core/dbt/flags.py
  core/dbt/logger.py
  core/dbt/parser/manifest.py
  core/dbt/task/base.py
  core/dbt/task/printer.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  core/dbt/task/sql.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  core/dbt/tracking.py
  core/setup.py
  dev-requirements.txt
  tests/functional/list/test_list.py
  third-party-stubs/logbook/__init__.pyi
  third-party-stubs/logbook/__version__.pyi
  third-party-stubs/logbook/_fallback.pyi
  third-party-stubs/logbook/_termcolors.pyi
  third-party-stubs/logbook/base.pyi
  third-party-stubs/logbook/compat.pyi
  third-party-stubs/logbook/concurrency.pyi
  third-party-stubs/logbook/handlers.pyi
  third-party-stubs/logbook/helpers.pyi
  third-party-stubs/logbook/more.pyi
  third-party-stubs/logbook/notifiers.pyi
  third-party-stubs/logbook/queues.pyi
  third-party-stubs/logbook/ticketing.pyi
  third-party-stubs/logbook/utils.pyi
Labels: cla:yes

#9361 move cache exceptions to dbt/adapters
  .changes/unreleased/Under the Hood-20240110-161723.yaml
  core/dbt/adapters/cache.py
  core/dbt/adapters/exceptions/__init__.py
  core/dbt/adapters/exceptions/cache.py
  core/dbt/context/exceptions_jinja.py
Labels: cla:yes

#9040 Refactor deferral: always `merge_from_artifact` & support all commands
  .changes/unreleased/Under the Hood-20231108-163613.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/main.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/task/clone.py
  core/dbt/task/compile.py
  core/dbt/task/freshness.py
  core/dbt/task/list.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  tests/functional/dbt_runner/test_dbt_runner.py
  tests/functional/defer_state/test_defer_state.py
  tests/unit/test_manifest.py
Labels: cla:yes

#9391 Backport 9328 to 1.7.latest
  .changes/unreleased/Fixes-20231213-220449.yaml
  core/dbt/cli/flags.py
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/contracts/state.py
  core/dbt/parser/manifest.py
  core/dbt/task/retry.py
  tests/functional/retry/test_retry.py
Labels: cla:yes

#9398 pin dbt-common
  core/setup.py
Labels: cla:yes, Skip Changelog

#9396 Support longer unit test names + improve error handling in unit test construction
  .changes/unreleased/Fixes-20240115-165310.yaml
  core/dbt/context/providers.py
  core/dbt/parser/unit_tests.py
  core/dbt/task/test.py
  tests/adapter/dbt/tests/adapter/unit_testing/test_unit_testing.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_unit_testing.py
  tests/functional/unit_testing/test_ut_names.py
Labels: cla:yes

#9343 Ensure unit test models can depend on external nodes
  .changes/unreleased/Features-20240119-101335.yaml
  core/dbt/context/providers.py
  core/dbt/parser/unit_tests.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_unit_testing.py
Labels: cla:yes

#9412 Rename tests -> data_tests for model-level + versions
  .changes/unreleased/Fixes-20240119-215214.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schemas.py
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_config_deprecations.py
Labels: cla:yes

#9406 Align with order of unit test output when `actual` differs from `expected`
  .changes/unreleased/Features-20240118-135651.yaml
  core/dbt/task/test.py
Labels: cla:yes, ready_for_review

#9423 Refactor macro contexts.
  .changes/unreleased/Under the Hood-20240122-165446.yaml
  core/dbt/context/macros.py
  core/dbt/context/manifest.py
  core/dbt/contracts/graph/manifest.py
  tests/unit/test_context.py
Labels: cla:yes

#9427 add decorator
  .changes/unreleased/Under the Hood-20240123-114855.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#9366 Feature/source freshness hooks
  .changes/unreleased/Features-20231231-171205.yaml
  core/dbt/cli/flags.py
  core/dbt/contracts/project.py
  core/dbt/task/freshness.py
  tests/functional/sources/common_source_setup.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/test_cli_flags.py
  tests/unit/test_graph.py
Labels: user docs, cla:yes

#9428 Workflow Housekeeping
  .github/_README.md
  .github/workflows/bot-changelog.yml
  .github/workflows/changelog-existence.yml
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
  .github/workflows/test/.actrc
  .github/workflows/test/.gitignore
  .github/workflows/test/.secrets.EXAMPLE
  .github/workflows/test/inputs/release_docker.json
  .github/workflows/version-bump.yml
Labels: cla:yes, Skip Changelog

#9429 Simplify core release inputs
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#9443 fix retry as CLI
  .changes/unreleased/Fixes-20240124-142522.yaml
  core/dbt/cli/main.py
  core/dbt/task/retry.py
Labels: cla:yes

#9451 update contributing expectations for external PR reviews
  CONTRIBUTING.md
Labels: cla:yes, Skip Changelog

#9452 update dependencies
  core/setup.py
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#9316 OSS Standardization
  .changes/unreleased/Under the Hood-20240109-091856.yaml
  .github/ISSUE_TEMPLATE/implementation-ticket.yml
  CONTRIBUTING.md
  README.md
Labels: cla:yes

#9421 Enable unit testing versioned models
  .changes/unreleased/Features-20240122-145854.yaml
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/manifest.py
  core/dbt/parser/partial.py
  core/dbt/parser/unit_tests.py
  core/dbt/task/test.py
  tests/functional/unit_testing/fixtures.py
  tests/functional/unit_testing/test_unit_testing.py
  tests/functional/unit_testing/test_ut_versions.py
  tests/unit/test_unit_test_parser.py
Labels: cla:yes

#9460 Move `SavedQuery` data artifact to `dbt/artifacts`
  .changes/unreleased/Under the Hood-20240126-164038.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/base.py
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/saved_query.py
  core/dbt/artifacts/resources/v1/semantic_layer_components.py
  core/dbt/context/providers.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/node_args.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/saved_queries.py
  core/dbt/contracts/graph/semantic_models.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/common.py
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/manifest.py
  core/dbt/parser/models.py
  core/dbt/parser/schema_generic_tests.py
  core/dbt/parser/schema_yaml_readers.py
  core/dbt/plugins/manifest.py
  tests/functional/experimental_parser/test_all_experimental_parser.py
  tests/unit/test_contracts_graph_parsed.py
  tests/unit/test_graph_selector_methods.py
  tests/unit/test_manifest.py
  tests/unit/test_parser.py
  tests/unit/test_semantic_layer_nodes_satisfy_protocols.py
Labels: cla:yes

#9456 TestGenerateCatalogWithExternalNodes
  .changes/unreleased/Fixes-20240125-182243.yaml
  core/dbt/task/docs/generate.py
  tests/functional/docs/test_generate.py
Labels: cla:yes, backport 1.7.latest

#9465 Fix plurals in FoundStats message
  .changes/unreleased/Fixes-20240126-134234.yaml
  core/dbt/artifacts/resources/types.py
  core/dbt/compilation.py
  tests/functional/minimal_cli/test_minimal_cli.py
  tests/functional/schema_tests/test_schema_v2_tests.py
  tests/unit/test_node_types.py
Labels: cla:yes

#9454 Fix source seed selection docs generate
  .changes/unreleased/Fixes-20240125-155641.yaml
  core/dbt/task/docs/generate.py
  tests/functional/docs/test_generate.py
Labels: cla:yes

#9488 Manifest `upgrade_schema_version` runs upgrade script on all older versions
  .changes/unreleased/Fixes-20240130-124135.yaml
  core/dbt/artifacts/schemas/manifest/v12/manifest.py
  tests/functional/artifacts/data/state/v11/manifest.json
Labels: cla:yes

#9493 [Backport 1.7] Fix source seed selection docs generate (#9454)
  .changes/unreleased/Fixes-20240125-155641.yaml
  core/dbt/task/generate.py
  tests/functional/docs/test_generate.py
Labels: cla:yes

#9457 TestGenerateCatalogWithExternalNodes
  .changes/unreleased/Under the Hood-20240129-141543.yaml
  tests/functional/docs/test_generate.py
Labels: cla:yes

#9495 Fix Docker release to correctly publish `latest` and `1.x.latest` tags
  .github/actions/latest-wrangler/action.yml
  .github/actions/latest-wrangler/main.py
  .github/workflows/release-docker.yml
Labels: cla:yes

#9483 TestGenerateCatalogWithExternalNodes (#9456)
  .changes/unreleased/Fixes-20240125-182243.yaml
  core/dbt/context/providers.py
  core/dbt/task/generate.py
  tests/functional/docs/test_generate.py
Labels: cla:yes

#9162 Fix python model parsing from meder
  .changes/unreleased/Fixes-20231128-102111.yaml
  core/dbt/parser/models.py
  tests/unit/test_parser.py
Labels: user docs, cla:yes
