Repository dbt-labs/dbt-core, pull requests merged in 2025-03, with the labels that each got.

#11332 Rewrite execution of microbatch models to avoid blocking the main thread
  .changes/unreleased/Fixes-20250303-131440.yaml
  core/dbt/graph/thread_pool.py
  core/dbt/materializations/incremental/microbatch.py
  core/dbt/task/build.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/materializations/incremental/test_microbatch.py
  tests/unit/task/test_run.py
Labels: cla:yes

#11359 [Backport/1.9] ubuntu deprecation
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/actions/setup-postgres-linux/action.yml
  .github/actions/setup-postgres-linux/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
  test/setup_db.sh
Labels: cla:yes, Skip Changelog

#11357 [Backport/1.7] ubuntu deprecation
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/actions/setup-postgres-linux/action.yml
  .github/actions/setup-postgres-linux/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
  test/setup_db.sh
Labels: cla:yes, Skip Changelog

#11356 [Backport/1.6] ubuntu deprecation
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/actions/setup-postgres-linux/action.yml
  .github/actions/setup-postgres-linux/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
  test/setup_db.sh
Labels: cla:yes, Skip Changelog

#11361 [backport 1.5] handle ubuntu 20.04 deprecation (#11354)
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/actions/setup-postgres-linux/action.yml
  .github/actions/setup-postgres-linux/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
  test/setup_db.sh
Labels: cla:yes, Skip Changelog

#11360 [backport 1.4] handle ubuntu 20.04 deprecation (#11354)
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/actions/setup-postgres-linux/action.yml
  .github/actions/setup-postgres-linux/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
  test/setup_db.sh
Labels: cla:yes, Skip Changelog

#11349 Backport 11332 to 1.9.latest
  .changes/unreleased/Fixes-20250303-131440.yaml
  core/dbt/graph/thread_pool.py
  core/dbt/materializations/incremental/microbatch.py
  core/dbt/task/build.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/materializations/incremental/test_microbatch.py
  tests/unit/task/test_run.py
Labels: cla:yes

#11373 bump libpq-dev
  docker/Dockerfile
Labels: cla:yes, Skip Changelog

#11362 Fix parsing error for projects using the new YAML format for snapshots
  .changes/unreleased/Fixes-20250305-110257.yaml
  core/dbt/parser/partial.py
  tests/functional/snapshots/fixtures.py
  tests/functional/snapshots/test_basic_snapshot.py
  tests/unit/parser/test_partial.py
  tests/unit/utils/manifest.py
Labels: cla:yes, community

#11382 Remove `DBT_EXPERIMENTAL_SAMPLE_MODE` env var gating for sample mode
  core/dbt/context/providers.py
  core/dbt/task/run.py
  tests/functional/sample_mode/test_sample_mode.py
  tests/unit/context/test_providers.py
Labels: cla:yes, Skip Changelog

#11389 Macro Annotations and Inference
  .changes/unreleased/Features-20250314-143157.yaml
  core/dbt/contracts/project.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/macros.py
  core/dbt/parser/schemas.py
  tests/functional/macros/test_macro_annotations.py
  tests/unit/test_events.py
  tests/unit/test_macro_types.py
Labels: cla:yes

#11401 Add Support for Python 3.13
  .changes/unreleased/Features-20250319-153356.yaml
  .github/workflows/main.yml
  core/setup.py
  dev-requirements.txt
Labels: cla:yes

#11409 fix postgres github action using vibe coding
  .github/actions/setup-postgres-macos/action.yml
Labels: cla:yes

#11368 Add node_checksum to node_info on structured logs
  .changes/unreleased/Under the Hood-20250307-101758.yaml
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  tests/functional/logging/test_meta_logging.py
  tests/unit/events/test_types.py
Labels: cla:yes

#11419 Support artifact upload
  .changes/unreleased/Features-20250323-151625.yaml
  core/dbt/cli/artifact_upload.py
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/constants.py
  core/dbt/contracts/state.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/task/docs/generate.py
  core/dbt/task/freshness.py
  core/dbt/task/retry.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  core/dbt/tracking.py
  core/setup.py
  tests/unit/test_artifact_upload.py
  tests/unit/test_events.py
Labels: cla:yes

#11432 Add retry to macos postgres setup
  .github/actions/setup-postgres-macos/action.yml
  .github/actions/setup-postgres-macos/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  test/setup_db.sh
Labels: cla:yes, Skip Changelog

#11434 [Backport 1.5.latest] Add retry to macos postgres setup (#11432)
  .github/actions/setup-postgres-macos/action.yml
  .github/actions/setup-postgres-macos/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  test/setup_db.sh
Labels: cla:yes

#11435 [Backport 1.6.latest] Add retry to macos postgres setup (#11432)
  .github/actions/setup-postgres-macos/action.yml
  .github/actions/setup-postgres-macos/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  test/setup_db.sh
Labels: cla:yes

#11436 [Backport 1.7.latest] Add retry to macos postgres setup (#11432)
  .github/actions/setup-postgres-macos/action.yml
  .github/actions/setup-postgres-macos/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  test/setup_db.sh
Labels: cla:yes

#11437 [Backport 1.8.latest] Add retry to macos postgres setup (#11432)
  .github/actions/setup-postgres-macos/action.yml
  .github/actions/setup-postgres-macos/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  test/setup_db.sh
Labels: cla:yes

#11438 [Backport 1.9.latest] Add retry to macos postgres setup (#11432)
  .github/actions/setup-postgres-macos/action.yml
  .github/actions/setup-postgres-macos/setup_db.sh
  .github/workflows/main.yml
  .github/workflows/test-repeater.yml
  test/setup_db.sh
Labels: cla:yes

#11220 Functional test for hourly microbatch model
  core/dbt/context/providers.py
  core/dbt/materializations/incremental/microbatch.py
  tests/functional/microbatch/test_microbatch.py
  tests/unit/materializations/incremental/test_microbatch.py
Labels: cla:yes, Skip Changelog

#11445 [Tidy first] Update issue template to direct adapters issues -> dbt-adapters
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla:yes

#10726 Remove and correct outdated docs relating to include/ and include/global_project.
  ARCHITECTURE.md
  core/dbt/clients/README.md
  core/dbt/include/README.md
Labels: cla:yes, ready_for_review, community

#11447 [Backport 1.9.latest] Fixes dbt retry does not respect --threads (#10591)
  .changes/unreleased/Fixes-20240822-122132.yaml
  core/dbt/task/retry.py
  tests/functional/retry/fixtures.py
  tests/functional/retry/test_retry_threads.py
Labels: cla:yes
