Repository dbt-labs/dbt-core, pull requests merged in 2025-02, with the labels that each got.

#11247 Sample Mode Alpha
  .changes/unreleased/Features-20250202-140054.yaml
  core/dbt/artifacts/resources/types.py
  core/dbt/cli/main.py
  core/dbt/cli/option_types.py
  core/dbt/cli/params.py
  core/dbt/context/providers.py
  core/dbt/event_time/event_time.py
  core/dbt/event_time/sample_window.py
  core/dbt/task/run.py
  dev-requirements.txt
  tests/functional/sample_mode/test_sample_mode.py
  tests/unit/cli/test_option_types.py
  tests/unit/context/test_providers.py
  tests/unit/event_time/test_event_time.py
  tests/unit/event_time/test_sample_mode.py
Labels: cla:yes, artifact_minor_upgrade

#11260 Don't automatically run Artifact Schema Check on PRs
  .github/workflows/schema-check.yml
Labels: cla:yes

#11283 Revert "Add `doc_blocks` to manifest for nodes and columns (#11224)"
  .changes/unreleased/Features-20250122-170328.yaml
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/parser/manifest.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/docs/test_good_docs_blocks.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/contracts/graph/test_nodes.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes, Skip Changelog, artifact_minor_upgrade

#11284 Update ShowTaskDirect to correctly handle --limit -1
  .changes/unreleased/Fixes-20250207-131424.yaml
  core/dbt/task/show.py
  tests/functional/show/test_show.py
Labels: cla:yes, community

#11294 Round 2: Add doc_blocks to manifest for nodes and columns
  .changes/unreleased/Features-20250122-170328.yaml
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/parser/manifest.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/docs/test_doc_blocks_backcompat.py
  tests/functional/docs/test_good_docs_blocks.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/contracts/graph/test_nodes.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes

#11256 Require 2 CODEOWNER reviews for artifact changes
  .github/workflows/artifact-reviews.yml
Labels: cla:yes

#11303 Combine `--sample` and `--sample-window` into one CLI param
  .changes/unreleased/Features-20250212-155658.yaml
  core/dbt/cli/main.py
  core/dbt/cli/option_types.py
  core/dbt/cli/params.py
  core/dbt/context/providers.py
  core/dbt/task/run.py
  tests/functional/sample_mode/test_sample_mode.py
  tests/unit/cli/test_option_types.py
  tests/unit/context/test_providers.py
Labels: cla:yes

#11304 Ability to sample seeds
  .changes/unreleased/Features-20250212-173743.yaml
  core/dbt/context/providers.py
  tests/functional/sample_mode/test_sample_mode.py
  tests/unit/context/test_providers.py
Labels: cla:yes, sample_mode

#11307 Allow for running `sample mode` with `build` command
  .changes/unreleased/Features-20250213-182932.yaml
  core/dbt/cli/main.py
  tests/functional/sample_mode/test_sample_mode.py
Labels: cla:yes, sample_mode

#11311 Allow sampling from snapshots and of snapshots
  .changes/unreleased/Features-20250214-152957.yaml
  core/dbt/context/providers.py
  tests/functional/sample_mode/test_sample_mode.py
  tests/unit/context/test_providers.py
Labels: cla:yes, sample_mode

#11310 Fix #11275: `_get_doc_blocks` is crashing parsing if `.format` is called
  .changes/unreleased/Fixes-20250218-134745.yaml
  core/dbt/parser/manifest.py
  tests/functional/docs/test_doc_blocks_formatting.py
Labels: cla:yes

#11327 Update artifact triggers and concurrency rules
  .github/workflows/artifact-reviews.yml
Labels: cla:yes

#11308 Add secondary_profiles to `profile.py`
  .changes/unreleased/Under the Hood-20250214-123853.yaml
  core/dbt/config/profile.py
  core/dbt/config/runtime.py
  tests/unit/config/test_profile.py
Labels: cla:yes

#11330 add database to ModelNodeArgs in partial parsing test to better reflect prod use cases
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes, Skip Changelog
