Repository dbt-labs/dbt-core, pull requests merged in 2025-08, with the labels that each got.

#11879 Raise PropertyMovedToConfigDeprecation instead of CustomTopLevelKeyDeprecation when additional attribute is a valid config
  .changes/unreleased/Fixes-20250731-162142.yaml
  core/dbt/cli/params.py
  core/dbt/jsonschemas.py
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_deprecations.py
Labels: cla:yes

#11880 Remove duplicative PropertyMovedToConfigDeprecation source `freshness` config move
  .changes/unreleased/Fixes-20250805-104309.yaml
  core/dbt/parser/sources.py
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_deprecations.py
Labels: cla:yes

#11889 call adapter.add_catalog_integration during parse_manifest
  .changes/unreleased/Under the Hood-20250804-211346.yaml
  core/dbt/cli/requires.py
  core/dbt/parser/manifest.py
  core/dbt/task/retry.py
Labels: cla:yes, backport 1.10.latest

#11895 dont use default token
  .github/workflows/artifact-reviews.yml
Labels: cla:yes

#11887 Avoid redundant node patch removal during partial parsing
  .changes/unreleased/Fixes-20250804-074006.yaml
  core/dbt/parser/partial.py
Labels: cla:yes, community

#11911 flip require_generic_test_arguments_property behavior change flag
  .changes/unreleased/Features-20250811-150347.yaml
  core/dbt/contracts/project.py
  core/dbt/parser/generic_test_builders.py
  tests/functional/defer_state/fixtures.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/fixtures/happy_path_project/seeds/s.yml
  tests/functional/retry/fixtures.py
Labels: cla:yes

#11916 upgrade protobuf to 6.0
  .changes/unreleased/Dependencies-20250813-144832.yaml
  core/setup.py
  dev-requirements.txt
Labels: cla:yes

#11933 Bump dbt adapters minimum to 1.16.5
  .changes/unreleased/Dependencies-20250819-085714.yaml
  core/setup.py
Labels: cla:yes

#11957 Allow for the defining of basic SQL UDFs
  .changes/unreleased/Features-20250826-132700.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/types.py
  core/dbt/artifacts/resources/v1/function.py
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/contracts/project.py
  core/dbt/node_types.py
  core/dbt/parser/base.py
  core/dbt/parser/common.py
  core/dbt/parser/functions.py
  core/dbt/parser/manifest.py
  core/dbt/parser/read_files.py
  core/dbt/parser/schemas.py
  core/dbt/tests/fixtures/project.py
  tests/functional/functions/test_udfs.py
  tests/functional/list/test_commands.py
  tests/unit/config/test_project.py
  tests/unit/config/test_runtime.py
  tests/unit/test_node_types.py
  tests/unit/utils/project.py
Labels: cla:yes

#11859 fix: Properly quote event_time column names in sample mode filters
  .changes/unreleased/Fixes-20250725-112903.yaml
  core/dbt/context/providers.py
  tests/unit/context/test_providers.py
Labels: cla:yes, community

#11970 [BACKPORT 1.10.latest] Default parse-time nodes' raw_code property to "" (empty string) to comply with strict str type
  .changes/unreleased/Fixes-20250804-074254.yaml
  core/dbt/parser/base.py
Labels: cla:yes

#11968 Ability to list and select function nodes
  .changes/unreleased/Features-20250827-163400.yaml
  .changes/unreleased/Features-20250827-173103.yaml
  core/dbt/cli/params.py
  core/dbt/task/list.py
  tests/functional/fixtures/happy_path_project/functions/area_of_circle.sql
  tests/functional/fixtures/happy_path_project/functions/area_of_circle.yml
  tests/functional/list/test_commands.py
  tests/functional/list/test_list.py
Labels: cla:yes
