Repository dbt-labs/dbt-core, pull requests merged in 2025-04, with the labels that each got.

#11446 Fix microbatch model edge case of having only one batch (that failed) but counting as success
  .changes/unreleased/Fixes-20250328-170142.yaml
  core/dbt/task/run.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes

#11162 Parse `catalogs.yml`
  .changes/unreleased/Under the Hood-20250321-155026.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/v1/catalog.py
  core/dbt/cli/main.py
  core/dbt/cli/requires.py
  core/dbt/config/catalogs.py
  core/dbt/constants.py
  tests/functional/catalogs/test_catalogs_parsing.py
Labels: cla:yes, artifact_minor_upgrade

#11430 Update `dir` to look
  .changes/unreleased/Fixes-20250326-194259.yaml
  core/dbt/task/init.py
Labels: cla:yes, community

#11451 Stop dismissing workflow runs
  .github/workflows/artifact-reviews.yml
Labels: cla:yes

#11449 better track of artifacts to upload, more retry
  core/dbt/cli/requires.py
  core/dbt/parser/manifest.py
  core/dbt/task/docs/generate.py
  core/dbt/task/run.py
  core/dbt/task/runnable.py
  core/dbt/utils/__init__.py
  core/dbt/utils/artifact_upload.py
  core/dbt/utils/utils.py
  tests/unit/test_artifact_upload.py
Labels: cla:yes, Skip Changelog

#11456 Remove homebrew services from workflow
  test/setup_db.sh
Labels: cla:yes, Skip Changelog

#11466 General Deprecation Warning Improvements
  .changes/unreleased/Features-20250403-174659.yaml
  core/dbt/cli/main.py
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/clients/registry.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  tests/functional/conftest.py
  tests/functional/deprecations/test_config_deprecations.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/macros/test_macro_annotations.py
  tests/functional/materializations/test_custom_materialization.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/clients/test_registry.py
  tests/unit/test_deprecations.py
  tests/unit/test_events.py
Labels: cla:yes

#9839 [#9791] Fix datetime.datetime.utcnow() is deprecated as of Python 3.12
  .changes/unreleased/Fixes-20240329-223653.yaml
  core/dbt/artifacts/schemas/base.py
  core/dbt/artifacts/schemas/results.py
  core/dbt/artifacts/schemas/run/v5/run.py
  core/dbt/contracts/graph/node_args.py
  core/dbt/contracts/sql.py
  core/dbt/parser/manifest.py
  core/dbt/task/base.py
  core/dbt/task/docs/generate.py
  core/dbt/task/run.py
  core/dbt/task/run_operation.py
  core/dbt/task/runnable.py
  core/dbt/task/sql.py
  core/dbt/tests/fixtures/project.py
  core/dbt/tests/util.py
  core/dbt/utils/utils.py
  tests/functional/adapter/basic/test_docs_generate.py
  tests/functional/adapter/utils/test_current_timestamp.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/artifacts/test_run_execution_result.py
  tests/functional/configs/test_configs.py
  tests/functional/source_overrides/test_simple_source_override.py
  tests/functional/sources/test_source_fresher_state.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/artifacts/test_run_execution_result.py
  tests/unit/contracts/graph/test_manifest.py
Labels: cla:yes, ready_for_review, artifact_minor_upgrade, community

#11481 Fix artifact review checks hangs
  .github/workflows/artifact-reviews.yml
Labels: cla:yes

#11483 Behavior flag to handle all warnings with warn_error logic
  .changes/unreleased/Features-20250410-111023.yaml
  core/dbt/cli/requires.py
  core/dbt/contracts/project.py
  tests/functional/configs/test_warn_error_options.py
Labels: cla:yes

#11488 Add package 'name' to lock file
  .changes/unreleased/Under the Hood-20250411-021610.yaml
  core/dbt/contracts/project.py
  core/dbt/task/deps.py
  tests/functional/dependencies/test_dependency_options.py
  tests/functional/dependencies/test_simple_dependency.py
Labels: cla:yes

#11501 Install `pre-commit` in Docker container for running tests
  .changes/unreleased/Fixes-20250414-082916.yaml
  Dockerfile.test
  Makefile
Labels: cla:yes

#11475 fix: dead link in `ARCHITECTURE.md`
  ARCHITECTURE.md
Labels: cla:yes, community

#11505 Begin basic jsonschema validations of dbt_project.yml
  .changes/unreleased/Features-20250414-171209.yaml
  core/MANIFEST.in
  core/dbt/cli/requires.py
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/include/jsonschemas/__init__.py
  core/dbt/include/jsonschemas/project/0.0.85.json
  core/dbt/jsonschemas.py
  core/dbt/tests/fixtures/project.py
  dev-requirements.txt
  tests/functional/test_project.py
  tests/unit/config/test_project.py
  tests/unit/test_events.py
Labels: cla:yes, Skip Changelog

#11514 Add Deprecation Warnings for Unexpected Jinja Blocks
  .changes/unreleased/Features-20250416-144427.yaml
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/base.py
  core/dbt/parser/macros.py
  core/dbt/parser/search.py
  tests/unit/test_events.py
Labels: cla:yes

#11517 Add `UnexpectedJinjaBlockDeprecationSummary` and add file context to `UnexpectedJinjaBlockDeprecation`
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/base.py
  core/dbt/parser/macros.py
  core/dbt/parser/search.py
  tests/unit/test_events.py
Labels: cla:yes, Skip Changelog

#11518 Deprecate Custom Top-Level Keys
  .changes/unreleased/Features-20250417-001347.yaml
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/include/jsonschemas/resources/0.0.85.json
  core/dbt/jsonschemas.py
  tests/unit/test_events.py
Labels: cla:yes

#11510 Add Check for Duplicate YAML Keys
  .changes/unreleased/Features-20250415-133751.yaml
  core/dbt/clients/checked_load.py
  core/dbt/clients/yaml_helper.py
  core/dbt/config/project.py
  core/dbt/config/selectors.py
  core/dbt/config/utils.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/read_files.py
  core/dbt/parser/schemas.py
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/clients/test_yaml_helper.py
  tests/unit/test_events.py
Labels: cla:yes

#11508 Revert "Install `pre-commit` in Docker container for running tests"
  .changes/unreleased/Fixes-20250414-082916.yaml
  Dockerfile.test
  Makefile
Labels: cla:yes, Skip Changelog

#11499 Add pre-commit installation to Docker container for testing compatibility
  .changes/unreleased/Fixes-20250414-170457.yaml
Labels: cla:yes, artifact_minor_upgrade, community

#11474 add link to yaml tips
  core/dbt/context/README.md
Labels: cla:yes, community

#11522 Deprecate having custom keys in config blocks
  .changes/unreleased/Features-20250417-114915.yaml
  core/dbt/config/selectors.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/include/jsonschemas/resources/0.0.85.json
  core/dbt/jsonschemas.py
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/test_events.py
Labels: cla:yes

#11526 Begin emitting deprecation events for custom properties found in objects
  .changes/unreleased/Features-20250418-104210.yaml
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/include/jsonschemas/resources/0.0.85.json
  core/dbt/jsonschemas.py
  core/dbt/parser/schemas.py
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/parser/test_parser.py
  tests/unit/test_events.py
Labels: cla:yes

#11529 fix trigger for artifact review check
  .github/workflows/artifact-reviews.yml
Labels: cla:yes

#11531 Fix duplicate error when multiple macros in one file with macro patches
  .changes/unreleased/Fixes-20250422-122835.yaml
  core/dbt/parser/partial.py
  tests/functional/partial_parsing/fixtures.py
  tests/functional/partial_parsing/test_partial_parsing.py
Labels: cla:yes

#11540 One single DeprecationsSummary event to rule them all
  .changes/unreleased/Features-20250424-153327.yaml
  core/dbt/cli/requires.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/test_events.py
Labels: cla:yes

#11541 Update jsonschemas to versions 0.0.110
  core/dbt/include/jsonschemas/project/0.0.110.json
  core/dbt/include/jsonschemas/resources/0.0.110.json
  core/dbt/jsonschemas.py
Labels: cla:yes, Skip Changelog

#11544 Initial slate of deprecations for 1.10
  .changes/unreleased/Features-20250414-171209.yaml
  .changes/unreleased/Features-20250415-133751.yaml
  .changes/unreleased/Features-20250416-144427.yaml
  .changes/unreleased/Features-20250416-151711.yaml
  .changes/unreleased/Features-20250417-001347.yaml
  .changes/unreleased/Features-20250417-114915.yaml
  .changes/unreleased/Features-20250418-104210.yaml
  .changes/unreleased/Features-20250424-153327.yaml
  core/MANIFEST.in
  core/dbt/cli/requires.py
  core/dbt/clients/checked_load.py
  core/dbt/clients/yaml_helper.py
  core/dbt/config/project.py
  core/dbt/config/runtime.py
  core/dbt/config/selectors.py
  core/dbt/config/utils.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/include/jsonschemas/__init__.py
  core/dbt/include/jsonschemas/project/0.0.110.json
  core/dbt/include/jsonschemas/project/0.0.85.json
  core/dbt/include/jsonschemas/resources/0.0.110.json
  core/dbt/include/jsonschemas/resources/0.0.85.json
  core/dbt/jsonschemas.py
  core/dbt/parser/base.py
  core/dbt/parser/macros.py
  core/dbt/parser/read_files.py
  core/dbt/parser/schemas.py
  core/dbt/parser/search.py
  core/dbt/tests/fixtures/project.py
  core/setup.py
  dev-requirements.txt
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/retry/test_retry.py
  tests/functional/test_project.py
  tests/unit/clients/test_yaml_helper.py
  tests/unit/config/test_project.py
  tests/unit/parser/test_parser.py
  tests/unit/test_events.py
Labels: cla:yes

#11547 Fix functional deprecation tests so they don't break on windows
  tests/functional/deprecations/test_deprecations.py
Labels: cla:yes, Skip Changelog

#11551 Pin setuptools to 79.0.1
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#11552 Pin setuptools to 79.0.1
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#11525 Fix seed path if project directory name changes
  .changes/unreleased/Fixes-20250428-141528.yaml
  core/dbt/parser/unit_tests.py
Labels: cla:yes

#11545 Install `pre-commit` in Docker container for running tests
  .changes/unreleased/Fixes-20250430-084512.yaml
  Dockerfile.test
  Makefile
Labels: cla:yes

#11555 stop directly using the output
  .github/workflows/artifact-reviews.yml
Labels: cla:yes
