Repository dbt-labs/dbt-core, pull requests merged in 2025-07, with the labels that each got.

#11636 Source Override Deprecation
  .changes/unreleased/Features-20250701-164957.yaml
  core/dbt/deprecations.py
  core/dbt/events/types.py
  core/dbt/parser/schemas.py
  core/setup.py
  tests/functional/source_overrides/test_simple_source_override.py
  tests/unit/parser/test_parser.py
  tests/unit/test_events.py
Labels: cla:yes

#11787 Update contributing guide for comment resolution requirement
  CONTRIBUTING.md
Labels: cla:yes, community

#11793 update ModelParamUsageDeprecation message
  core/dbt/events/types.py
Labels: cla:yes, Skip Changelog, backport 1.10.latest

#11808 Upgrade to DSI 0.9.0 for more robust saved query support
  .changes/unreleased/Dependencies-20250709-132213.yaml
  core/dbt/artifacts/resources/v1/semantic_layer_components.py
  core/setup.py
  tests/functional/saved_queries/fixtures.py
Labels: cla:yes, artifact_minor_upgrade, community

#11795 Create and protect dbt engine environment variable namespace via prefix `DBT_ENGINE`
  .changes/unreleased/Features-20250703-175341.yaml
  core/dbt/cli/params.py
  core/dbt/cli/requires.py
  core/dbt/deprecations.py
  core/dbt/env_vars.py
  core/dbt/events/types.py
  core/setup.py
  tests/functional/cli/test_requires.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/test_env_vars.py
  tests/unit/test_events.py
Labels: cla:yes

#11815 Make `GenericJSONSchemaValidationDeprecation` a "preview" deprecation
  .changes/unreleased/Fixes-20250710-170148.yaml
  core/dbt/deprecations.py
  core/dbt/events/types.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/test_project.py
  tests/unit/config/test_project.py
Labels: cla:yes

#11824 add merge_group event
  .github/workflows/check-artifact-changes.yml
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes

#11823 skip type checking deprecation_date on the basis of jsonschemas
  core/dbt/jsonschemas.py
  tests/functional/deprecations/test_deprecations.py
Labels: cla:yes, Skip Changelog

#11821 Some additional SL JSONSchema improvements/fixes
  .changes/unreleased/Fixes-20250714-125000.yaml
  core/dbt/include/jsonschemas/project/0.0.110.json
  core/dbt/include/jsonschemas/resources/latest.json
  tests/functional/fixtures/happy_path_project/models/m.yml
  tests/functional/list/test_list.py
Labels: cla:yes

#11840 accept generic test args under 'args'
  .changes/unreleased/Features-20250721-173100.yaml
  core/dbt/contracts/project.py
  core/dbt/deprecations.py
  core/dbt/events/types.py
  core/dbt/include/jsonschemas/resources/latest.json
  core/dbt/parser/generic_test_builders.py
  core/setup.py
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/fixtures.py
  tests/unit/parser/test_parser.py
  tests/unit/test_events.py
Labels: cla:yes, strictness

#11734 deprecate modules.itertools usage
  .changes/unreleased/Features-20250728-115443.yaml
  core/dbt/context/base.py
  core/dbt/deprecations.py
  core/dbt/events/types.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/test_events.py
Labels: cla:yes

#11872 add argument values to ArgumentsPropertyInGenericTestDeprecation message
  core/dbt/events/types.py
  core/dbt/parser/generic_test_builders.py
Labels: cla:yes, Skip Changelog
