Repository dbt-labs/dbt-core, pull requests merged in 2025-01, with the labels that each got.

#11188 Move initialization of keyword_args up
  core/dbt/graph/selector_methods.py
Labels: cla:yes, Skip Changelog

#11184 fix: partial parsing - reparse downstream nodes when adding versioning
  .changes/unreleased/Fixes-20250102-140543.yaml
  core/dbt/parser/partial.py
  tests/functional/partial_parsing/test_versioned_models.py
  tests/unit/parser/test_partial.py
Labels: cla:yes, community

#11170 add model freshness for adaptive job
  .changes/unreleased/Features-20241218-170729.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/v1/model.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/parser/test_parser.py
Labels: cla:yes, artifact_minor_upgrade

#11190 Meta config for dimensions, measures, and entities
  .changes/unreleased/Features-20250106-132829.yaml
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/semantic_models/fixtures.py
  tests/functional/semantic_models/test_semantic_model_configs.py
Labels: cla:yes, semantic, artifact_minor_upgrade, community

#11195 Create `LogNodeResult` event
  .changes/unreleased/Under the Hood-20250107-205838.yaml
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  tests/unit/events/test_types.py
  tests/unit/test_events.py
Labels: cla:yes

#11196 Always emit warning when microbatch models lack any filtered input node
  .changes/unreleased/Fixes-20250107-173719.yaml
  core/dbt/parser/manifest.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes

#11193 Fix exception type of run operation macro not found
  .changes/unreleased/Under the Hood-20250107-123955.yaml
  core/dbt/task/run_operation.py
  tests/functional/run_operations/test_run_operations.py
Labels: cla:yes

#11187 Fix microbatch dbt list --output JSON
  .changes/unreleased/Fixes-20250109-123309.yaml
  core/dbt/task/list.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes, community, backport 1.9.latest

#11205 Re-cast definition of unique_key in SnapshotConfig
  core/dbt/artifacts/resources/v1/snapshot.py
Labels: cla:yes, Skip Changelog, artifact_minor_upgrade

#11207 Fix error counts for exposures
  .changes/unreleased/Under the Hood-20250110-202057.yaml
  core/dbt/task/printer.py
  core/dbt/task/runnable.py
  tests/unit/test_events.py
Labels: cla:yes

#11208 Fix generic test not null and unique custom configs
  .changes/unreleased/Fixes-20250110-155824.yaml
  core/dbt/parser/generic_test_builders.py
  core/dbt/parser/schema_generic_tests.py
  tests/functional/partial_parsing/test_pp_vars.py
  tests/functional/schema_tests/fixtures.py
  tests/functional/schema_tests/test_custom_test_config.py
Labels: cla:yes

#11203 [Backport] Fix microbatch dbt list --output JSON (#11187)
  .changes/unreleased/Fixes-20250109-123309.yaml
  core/dbt/task/list.py
  tests/functional/microbatch/test_microbatch.py
Labels: cla:yes

#11218 Misc fixes for group info in logging
  .changes/unreleased/Under the Hood-20250117-152215.yaml
  core/dbt/artifacts/resources/v1/owner.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/task/base.py
  core/dbt/task/runnable.py
  core/dbt/task/seed.py
  core/dbt/task/snapshot.py
  core/dbt/task/test.py
  tests/functional/logging/test_logging.py
Labels: cla:yes, artifact_minor_upgrade

#11234 ADAP-1183: Use the new location for dbt-postgres
  ARCHITECTURE.md
  dev-requirements.txt
  docker/README.md
Labels: cla:yes, Skip Changelog

#11224 Add `doc_blocks` to manifest for nodes and columns
  .changes/unreleased/Features-20250122-170328.yaml
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/parser/manifest.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/docs/test_good_docs_blocks.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/contracts/graph/test_nodes.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes, artifact_minor_upgrade

#11246 [Backport 1.8.latest] ADAP-1135: Point to the `dbt-adapters` subdirectory for tests post-monorepo migration
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#11253 loosen validation for freshness
  .changes/unreleased/Fixes-20250128-135509.yaml
  core/dbt/artifacts/resources/v1/model.py
  schemas/dbt/manifest/v12.json
Labels: cla:yes, artifact_minor_upgrade

#11259 post-hoc addition of discussion to roadmap
  docs/roadmap/2024-12-play-on.md
Labels: cla:yes, Skip Changelog
