Repository dbt-labs/dbt-core, pull requests merged in 2025-09, with the labels that each got.

#11979 Restore record functional tests
  tests/functional/record/record.py
  tests/functional/record/test_record.py
Labels: cla:yes, Skip Changelog

#11942 Support `quoting.snowflake_ignore_case`
  .changes/unreleased/Features-20250821-092532.yaml
  core/dbt/contracts/project.py
  tests/unit/config/test_project.py
Labels: cla:yes, community

#12002 Add catalogs.yml parsing to parse, test, and snapshot
  .changes/unreleased/Features-20250910-144554.yaml
  core/dbt/cli/main.py
Labels: cla:yes

#12018 Fix legacy time spine deprecation warning logic
  .changes/unreleased/Fixes-20250915-152227.yaml
  core/dbt/contracts/graph/semantic_manifest.py
  tests/functional/time_spines/test_time_spines.py
  tests/unit/contracts/graph/test_semantic_manifest.py
  tests/unit/utils/manifest.py
Labels: cla:yes, community

#12027 Support configuring model.config.freshness.build_after.update_on without period or count
  .changes/unreleased/Features-20250917-164941.yaml
  core/dbt/artifacts/resources/v1/model.py
  tests/functional/model_config/test_freshness_config.py
Labels: cla:yes, artifact_minor_upgrade

#12052 fix matrix for windows CI
  .github/workflows/main.yml
  tests/functional/defer_state/test_modified_state_schema_evolution.py
Labels: cla:yes

#12031 Add a new macro `function()` to the jinja context for using functions
  .changes/unreleased/Features-20250918-165821.yaml
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/artifacts/schemas/manifest/v12/manifest.py
  core/dbt/compilation.py
  core/dbt/context/providers.py
  core/dbt/contracts/files.py
  core/dbt/contracts/graph/manifest.py
  core/dbt/graph/selector.py
  core/dbt/graph/selector_methods.py
  core/dbt/node_types.py
  core/dbt/parser/functions.py
  core/dbt/parser/manifest.py
  core/dbt/parser/schemas.py
  core/dbt/task/list.py
  core/dbt/task/runnable.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/defer_state/data/manifest.json
  tests/functional/functions/test_udfs.py
  tests/unit/context/test_context.py
  tests/unit/contracts/graph/test_manifest.py
  tests/unit/contracts/graph/test_nodes.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes, artifacts

#12057 Add `type` property to function nodes
  .changes/unreleased/Features-20250926-140315.yaml
  core/dbt/artifacts/resources/types.py
  core/dbt/artifacts/resources/v1/function.py
  core/dbt/contracts/graph/nodes.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/schemas.py
  schemas/dbt/manifest/v12.json
  tests/functional/functions/test_udafs.py
  tests/functional/functions/test_udfs.py
Labels: cla:yes, artifact_minor_upgrade

#12055 Fix schema file patch collection
  .changes/unreleased/Fixes-20250925-212728.yaml
  core/dbt/parser/partial.py
  tests/functional/partial_parsing/test_pp_schema_file_order.py
Labels: cla:yes
