Repository dbt-labs/dbt-core, pull requests merged in 2025-05, with the labels that each got.

#11579 Gate jsonschema validations behind private environment variable
  core/dbt/jsonschemas.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/test_project.py
  tests/unit/config/test_project.py
Labels: cla:yes, Skip Changelog

#11580 Fix jsonschema validation that fires `CustomKeyInConfigDeprecation`
  .changes/unreleased/Fixes-20250502-131822.yaml
  core/dbt/jsonschemas.py
  tests/functional/deprecations/fixtures.py
  tests/functional/deprecations/test_deprecations.py
Labels: cla:yes

#11574 Make codecov informational-only
  codecov.yml
Labels: cla:yes

#11575 stop code checkout
  .github/workflows/artifact-reviews.yml
Labels: cla:yes

#11591 1.6.latest - fix test failures
  .github/workflows/main.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#11592 1.5.latest - fix test failures
  .github/workflows/main.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#11593 1.4.latest - fix test failures
  .github/workflows/main.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
Labels: cla:yes, Skip Changelog

#11596 fix query comment tests
  tests/unit/config/test_project.py
Labels: cla:yes

#11601 [Backport 1.8.latest] fix query comment tests
  tests/unit/config/test_project.py
Labels: cla:yes

#11589 Fix #11428: Add tags and meta config to exposures
  .changes/unreleased/Fixes-20250508-142542.yaml
  core/dbt/artifacts/resources/v1/exposure.py
  core/dbt/parser/schema_yaml_readers.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/exposures/fixtures.py
  tests/functional/exposures/test_exposure_configs.py
  tests/unit/contracts/graph/test_nodes_parsed.py
Labels: cla:yes, artifact_minor_upgrade

#11605 fix command test
  tests/functional/list/test_commands.py
Labels: cla:yes

#11595 replace all runner names on main
  .github/_README.md
  .github/actions/latest-wrangler/README.md
  .github/actions/latest-wrangler/examples/example_workflow.yml
  .github/workflows/artifact-reviews.yml
  .github/workflows/auto-respond-bug-reports.yml
  .github/workflows/backport.yml
  .github/workflows/bot-changelog.yml
  .github/workflows/check-artifact-changes.yml
  .github/workflows/main.yml
  .github/workflows/model_performance.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  .github/workflows/schema-check.yml
  .github/workflows/structured-logging-schema-check.yml
  .github/workflows/test-repeater.yml
Labels: cla:yes

#11611 Flip behavior flag `source-freshness-run-proejct-hooks` to true
  .changes/unreleased/Breaking Changes-20250512-150436.yaml
  core/dbt/contracts/project.py
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes

#11613 do not have DbtProject unit tests rely on default QueryCommment settings
  tests/unit/config/test_project.py
  tests/unit/utils/project.py
Labels: cla:yes, Skip Changelog

#11616 Fixup changelog that I typod
  .changes/unreleased/Breaking Changes-20250512-150436.yaml
Labels: cla:yes, Skip Changelog

#11621 deprecate --output/-o usage in dbt source freshness
  .changes/unreleased/Features-20250514-115328.yaml
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/task/freshness.py
  tests/functional/deprecations/test_deprecations.py
  tests/unit/test_events.py
Labels: cla:yes

#11598 Allow for deprecation warning previews
  .changes/unreleased/Under the Hood-20250508-162148.yaml
  core/dbt/deprecations.py
  tests/unit/test_deprecations.py
Labels: cla:yes

#11594 Initial happy path testing of jsonschema validations
  core/dbt/include/jsonschemas/resources/latest.json
  core/dbt/jsonschemas.py
  tests/functional/deprecations/test_deprecations.py
  tests/functional/fixtures/happy_path_project/models/model_with_lots_of_schema_configs.sql
  tests/functional/fixtures/happy_path_project/models/schema.yml
  tests/functional/list/test_list.py
Labels: cla:yes, Skip Changelog

#11624 Fix typo in changelog
  .changes/unreleased/Features-20250415-133751.yaml
Labels: cla:yes

#11626 `normalize` expected file path of functional test to ensure windows testing doesn't break
  tests/functional/list/test_list.py
Labels: cla:yes, Skip Changelog

#11631 add exposure to happy path project
  tests/functional/fixtures/happy_path_project/models/e.yml
  tests/functional/list/test_list.py
Labels: cla:yes, Skip Changelog

#11629 move pin of libpq-dev
  docker/Dockerfile
Labels: cla:yes, Skip Changelog

#11640 bump dbt-common
  .changes/unreleased/Under the Hood-20250519-111033.yaml
  core/setup.py
Labels: cla:yes

#11630 add more seed configs to happy_path_project
  core/dbt/deprecations.py
  core/dbt/include/jsonschemas/resources/latest.json
  tests/functional/artifacts/data/state/v1/manifest.json
  tests/functional/fixtures/happy_path_project/macros/expression_is_true.sql
  tests/functional/fixtures/happy_path_project/seeds/s.yml
  tests/functional/list/test_list.py
Labels: cla:yes, Skip Changelog

#11628 Fix #11506: Add freshness config to sources
  .changes/unreleased/Fixes-20250515-145857.yaml
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/deprecations.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/dbt/events/types.py
  core/dbt/parser/sources.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/test_events.py
Labels: cla:yes, artifact_minor_upgrade, proto update

#11608 move protos into external dependency
  .changes/unreleased/Under the Hood-20250520-101040.yaml
  .pre-commit-config.yaml
  Makefile
  core/dbt/events/README.md
  core/dbt/events/base_types.py
  core/dbt/events/core_types.proto
  core/dbt/events/core_types_pb2.py
  core/setup.py
  tests/unit/events/test_types.py
Labels: cla:yes

#11643 Revert "bump dbt-common (#11640)"
  .changes/unreleased/Under the Hood-20250519-111033.yaml
  core/setup.py
Labels: cla:yes, Skip Changelog

#11645 Flip behavior flag to disallow spaces in resource names
  .changes/unreleased/Breaking Changes-20250520-131830.yaml
  core/dbt/contracts/project.py
  tests/functional/manifest_validations/test_check_for_spaces_in_model_names.py
Labels: cla:yes

#11632 Add analyses properties.yml to happy path fixture
  core/dbt/include/jsonschemas/resources/latest.json
  tests/functional/fixtures/happy_path_project/analyses/a.yml
  tests/functional/list/test_list.py
Labels: user docs, cla:yes, Skip Changelog

#11620 use saner default setting of QueryComment.append in project fixture
  tests/unit/config/test_project.py
  tests/unit/utils/project.py
Labels: cla:yes, Skip Changelog

#11648 update analyses configs + happy path fixture
  core/dbt/include/jsonschemas/resources/latest.json
  tests/functional/fixtures/happy_path_project/analyses/a.yml
Labels: cla:yes, Skip Changelog

#11644 Fix #11506: Add freshness config to models
  .changes/unreleased/Fixes-20250520-170808.yaml
  core/dbt/artifacts/resources/v1/model.py
  core/dbt/parser/schemas.py
  core/dbt/parser/sources.py
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/unit/parser/test_parser.py
Labels: cla:yes, artifact_minor_upgrade

#11656 happy path seeds: no tags/meta as column properties
  core/dbt/include/jsonschemas/resources/latest.json
  tests/functional/fixtures/happy_path_project/seeds/s.yml
  tests/functional/list/test_list.py
Labels: cla:yes, Skip Changelog

#11649 Support config.meta and description on groups + add to happy path testing
  .changes/unreleased/Features-20250522-160050.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/v1/group.py
  core/dbt/contracts/graph/model_config.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/include/jsonschemas/resources/latest.json
  core/dbt/parser/schema_yaml_readers.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/fixtures/happy_path_project/analyses/a.yml
  tests/functional/fixtures/happy_path_project/models/g.yml
  tests/functional/fixtures/happy_path_project/models/schema.yml
  tests/functional/fixtures/happy_path_project/seeds/s.yml
  tests/functional/list/test_list.py
Labels: cla:yes, artifact_minor_upgrade

#11668 update latest.json with metrics objects
  core/dbt/include/jsonschemas/resources/latest.json
Labels: Skip Changelog

#11673 no type-related deprecations yet, allow additional properties on colu…
  core/dbt/include/jsonschemas/resources/latest.json
  core/dbt/jsonschemas.py
Labels: cla:yes, Skip Changelog

#11675 Update latest jsonschema for schema files to have 'warn_unsupported' property
  core/dbt/include/jsonschemas/resources/latest.json
Labels: Skip Changelog

#11674 Add singular data tests, generic data tests, and unit tests to happy path fixture
  tests/functional/fixtures/happy_path_project/models/model_to_unit_test.sql
  tests/functional/fixtures/happy_path_project/models/schema.yml
  tests/functional/fixtures/happy_path_project/models/unit_tests.yml
  tests/functional/fixtures/happy_path_project/tests/fixtures/test_incremental_fixture.csv
  tests/functional/fixtures/happy_path_project/tests/generic/my_generic_test.sql
  tests/functional/fixtures/happy_path_project/tests/schema.yml
  tests/functional/fixtures/happy_path_project/tests/t.sql
  tests/functional/list/test_list.py
Labels: cla:yes, Skip Changelog

#11682 update jsonschemas + dont skip happy path deprecation test
  core/dbt/include/jsonschemas/resources/latest.json
Labels: cla:yes, Skip Changelog

#11683 Fix #11506: Add freshness config to sources (#11628)
  .changes/unreleased/Fixes-20250515-145857.yaml
  core/dbt/artifacts/resources/v1/source_definition.py
  core/dbt/parser/sources.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/list/test_list.py
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_source_freshness.py
Labels: cla:yes, artifact_minor_upgrade

#11684 Backport 11671 to 1.9.latest
  .changes/unreleased/Features-20250526-112259.yaml
  core/dbt/artifacts/resources/__init__.py
  core/dbt/artifacts/resources/v1/components.py
  core/dbt/contracts/graph/unparsed.py
  core/dbt/parser/common.py
  schemas/dbt/manifest/v12.json
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/docs/test_good_docs_blocks.py
  tests/functional/fixtures/happy_path_project/models/schema.yml
  tests/functional/list/test_list.py
  tests/unit/contracts/graph/test_nodes_parsed.py
  tests/unit/contracts/graph/test_unparsed.py
Labels: cla:yes, artifact_minor_upgrade

#11689 Don't warn for `metricflow_time_spine` with non-day grain
  .changes/unreleased/Fixes-20250528-092055.yaml
  core/dbt/contracts/graph/semantic_manifest.py
Labels: cla:yes, community

#11692 Fix weird formatting on code snippet for may 2025 roadmap post
  docs/roadmap/2025-05-new-engine-same-language.md
Labels: cla:yes

#11695 Add file_format as CatalogWriteIntegrationConfig
  .changes/unreleased/Features-20250529-085311.yaml
  core/dbt/artifacts/resources/v1/catalog.py
Labels: cla:yes, artifact_minor_upgrade

#11698 Fix null handling of source freshness and dbt_project vs schema spec precedence
  .changes/unreleased/Fixes-20250530-005804.yaml
  core/dbt/parser/sources.py
  tests/functional/sources/fixtures.py
  tests/functional/sources/test_source_freshness.py
  tests/unit/parser/test_sources.py
Labels: cla:yes, backport 1.9.latest
